### ISSUE TITLE
No Info and background posters

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#10]
After latest update i noticed that Background poster, Trailer and Movie/TV Series info is missing when enter into detail pages. It need 30 seconds, up to 1 minute to load it both. 
But sometime Background poster is loaded when enter detail page and only Movie/tv series info is missing and need all that time i said before to show up.. 
This issue wasn't present before until now.

In latest case also Seasons / Episodes it self (along with all the info) were missing for that period of time
![222](https://cloud.githubusercontent.com/assets/7681671/11017355/ad55e45a-859c-11e5-9778-8f6726758e94.PNG)

And i some cases everything is missing ( Background Poster, Movie info,)

![1111111](https://cloud.githubusercontent.com/assets/7681671/11017385/5449ddfc-859d-11e5-841d-965fda70304a.PNG)

No info, no Trailer button

![333](https://cloud.githubusercontent.com/assets/7681671/11017424/c5207904-859e-11e5-9dd7-fccd4980f1b3.PNG)

**Comment by Ivshti** [comment]
That doesn't have anything to do with the update, it has to do with unoptimized queries. Working on that ATM :)

**Comment by Draxler** [comment]
My bad. I just start Stremio and it updated so i thought ...  :)

**Comment by Ivshti** [comment]
Thank for for reporting it anyway!

I'm rolling out updates today which should solve these issues for the future
