### ISSUE TITLE
Usa tv

### ISSUE THREAD

**Issue by msc173** [Stremio/stremio-bugs#1000]
When I open up the usa tv app on stremio and choose a station it loads for a bit, and then tells me the stream failed. It has been going on since Saturday.

**Expected behavior**
When I open a channel, the stream to show what the channel is currently playing.

**Desktop (please complete the following information):**
 I am using the samsung tv app on my samsung tv. I have also tried it on my android phone app.

**Smartphone (please complete the following information):**
 Samsung s90c tv
Samsung galaxy 24 ultra.

**Comment by TRtomasz** [comment]
Stremio does not control third party add-ons this is not a stremio issue
