### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by ShakedGold** [Stremio/stremio-bugs#1001]
**Describe the bug**
Whenever setting the external player to vlc on stremio web on ios, vlc says "Playback failed" even when copying the stream's url and inserting to vlc, it still says playback failed, the url works on other platforms so perhaps its not a stremio issue

**To Reproduce**
1. Go to stremio web
2. Click on settings
3. Scroll down to Advanced
4. Select vlc as the external player
5. play any stream
6. See the "Playback failed" error

**Expected behavior**
PLayback should work instead of failing

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/352fdcb7-8efa-482b-acf7-0c6af8ecc030)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 18.0.1
 - Browser safari
 - Version 5.1.7 

**Additional context**
Tested in outplayer and it does seem to work

**Comment by TRtomasz** [comment]
Closing as this is not stremio issue
