### ISSUE TITLE
Libvlc downsamples from 5.1 much better than ExoPlayer

### ISSUE THREAD

**Issue by NineKain** [Stremio/stremio-bugs#1002]
**Describe the bug**
Libvlc sounds much better when dowsamples 5.1 to 2.0 compared to ExoPlayer, where it is much quieter and hollow

**To Reproduce**
1. Put on any 5.1 movie/show on a stereo TV
2. Test Exo Player, change to libvlc and compare
3. Liblvc should sound louder and richer

**Expected behavior**
Both players should sound the same.

**TV (please complete the following information):**
 - Device: Xiaomi Mi Tv Stick
 - OS:Android TV
 - Version 1.6.13

**Additional context**
I have an older ~2017 Samsung 1080p Stereo TV plugged in via HDMI

**Comment by jaruba** [comment]
while you may be correct, this is out of our control, if you consider that this is an exoplayer issue, then an issue should be created at the exoplayer github repository
