### ISSUE TITLE
Failed load subtitles

### ISSUE THREAD

**Issue by krisdebock** [Stremio/stremio-bugs#1006]
when i want to synchronize opensubtitles v3plus with my samsung tv stremio application then a message appears failed to load subtitles. and on my laptop this addon works perfect. how can i make them work perfect on my tv? my laptop and tv app of stremio are synchronized with each other

**Comment by TRtomasz** [comment]
We cant controll 3rd party addon which is opensubtitles v3.

**Comment by krisdebock** [comment]
Its working on my laptop version 1.6.13 perfectly,only i cant synchronise on my tv version..
