### ISSUE TITLE
Hangs for few seconds and than continues

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#101]
OSX El Capitan 10.11.6 (15G31)
Stremio 3.6.6

MacBook Pro (Retina, 15-inch, Late 2013)
16 GB 1600 MHz DDR3
2.3 GHz Intel Core i7
NVIDIA GeForce GT 750M 2048 MB

It happens almost on every movie.
It Stopped for few seconds and then it continues the playback.
The subtitles continue to play fine just the movie hangs. 
 It is not a buffer issue as it happens even when the entire movie is buffered.

Let me know how should I troubleshoot.

**Comment by Ivshti** [comment]
How often does this happen?

Can you try with an official add-on, for example the content you'd find in Discover->Channels, and see if it happens there?

**Comment by krasi-georgiev** [comment]
Ok I will try

It happens every 20-30min but randomly. Sometimes even every 5-10min

It happens with any torrent source - EzTv, Joan Carlos, Rarbg

Even if it doesn't happen with an official add-on is there any easy way to troubleshoot the issue with the torrents?

**Comment by Ivshti** [comment]
My first suggestion would be to try to use a VPN, sometimes protocols like bittorrent get restricted by ISPs

also in case that's not the issue, it could be that the router is not very fast, as stremio is a bit more aggressive on the networking than other apps, because of the streaming

**Comment by krasi-georgiev** [comment]
now with your new QT version there is no issue
