### ISSUE TITLE
Can't install addons with long URL because of the UI bug

### ISSUE THREAD

**Issue by vanchaxy** [Stremio/stremio-bugs#1013]
**Describe the bug**
The addon install window in the web version is not scrollable, so can't click install with a long addons URL.

**To Reproduce**
1. Go to https://web.stremio.com/
2. Click on "add addon"
3. Paste a long URL

**Expected behavior**
The install button is visible.

**Screenshots**
![image](https://github.com/user-attachments/assets/599d5adc-97d1-4053-8b63-09caadce0381)

**Comment by kKaskak** [comment]
https://github.com/Stremio/stremio-web/pull/727
