### ISSUE TITLE
addons on web version of stremio wont load

### ISSUE THREAD

**Issue by kmjsmith** [Stremio/stremio-bugs#1016]
hi when ever i try and load a movie or tv show on the web version of stremio from my external url of stremio.kmjsmith763.net no addons will load such as comet or torrento does anyone else experence this thw whole point of me getting comet was to provide a media server that could stream movies and tv with premium links from anywhere without the need of giving a vpn to people

**Comment by TRtomasz** [comment]
Sorry from your message it is basically not possible to understand what is the issue. Please provided steps that will allow us to reproduce the issue.

**Comment by kmjsmith** [comment]
Oh I just figured it out it's because I wasn't logged into my account.

**Comment by kmjsmith** [comment]
Hi.  So I now get an error named failed to fetch. Tried different browsers ect. [
![Screenshot_20241129-171745](https://github.com/user-attachments/assets/b096e599-db46-4789-9c7f-68794e6d4cc1)
