### ISSUE TITLE
Sremio requests streams for TV series without including season and episode

### ISSUE THREAD

**Issue by vanchaxy** [Stremio/stremio-bugs#1017]
**Describe the bug**
Sremio requests streams for TV series without including season and episode. It's reproducible in the web version for some series, but it's also very common for users with "HabaneroTV" user-agent.

**To Reproduce**
1. Go to https://web.stremio.com/#/detail/series/tt1818588. 
2. Observe the request for stream without season and episode "/stream/series/tt1818588.json".

**Expected behavior**
No stream request before selecting an episode.

This behavior is very common for "habaneroTV" user-agent users even for series that work normally in the web version. (e.g. tt9813792)

![image](https://github.com/user-attachments/assets/3a2e6627-eee4-45ce-a3e1-f3751ae087aa)

upd. The full user-agent is "HabaneroTV/2411221001 CFNetwork/1568.200.51 Darwin/24.1.0" and it looks like Apple TV.

**Comment by vanchaxy** [comment]
@TRtomasz There are steps to reproduce described in the issue.

**Comment by TRtomasz** [comment]
if series do not have any episodes we will treat is as a movie and try to fetch without season/episode number
