### ISSUE TITLE
Ongoing crash and requires hard restart

### ISSUE THREAD

**Issue by B-Rawrrr** [Stremio/stremio-bugs#1018]
**Describe the bug**
App is unstable and requires ongoing exit close and open

**To Reproduce**
Application crashes and requires hard restart. It feels like it requires a bug fix and also performance improve due to the new or updated ONE UI from Samsung recent update.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem

**TV (please complete the following information):**
 - Device: Samsung OLED S90C
 - OS: Tizen
 - Version: 1.3

**Additional context**

**Comment by TRtomasz** [comment]
I'm closing that one, as it does not provide any details about reproducing issue, it is not possible to fix something like that.
New app update is ready and is pending samsung approval
