### ISSUE TITLE
Google TV Streamer - HDR10+ issue

### ISSUE THREAD

**Issue by briankinane** [Stremio/stremio-bugs#1019]
I am having an issue with Stremio playing files in HDR10+. Samsung TVs do not support Dolby Vision so HDR10+ is the only option for dynamic HDR metadata. The Nvidia Shield doesn't support HDR10+ so I purchased the new Google TV Streamer.

If you play a DV/HDR10+ file in Stremio using the integrated ExoPlayer, it falls back to HDR10 (but not HDR10+). If you click open in external player for the exact same file it can be played in HDR10+ in Kodi (You just have to disable Dolby Vision under Dynamic metadata formats in Kodi video settings).

This way, Kodi only attempts HDR10+ for dynamic metadata (which works), and then falls back to HDR10.

Bearing this in mind, it looks like this issue only happens when Dolby Vision is attempted first as the Dynamic metadata format. The Google TV device does not attempt a second dynamic metadata format, it just defaults back to HDR10.

As other users have pointed out, if a file has only HDR10+ metadata and no Dolby Vision metadata the file plays perfectly in Stremio with the integrated ExoPlayer in HDR10+.

This is an issue on both the "Google Chromecast with Google TV" and the new "Google TV Streamer". 

If there was any way the Stremio Devs could implement a feature similar to Kodis player settings where we could select which dynamic metadata format we want to use I think it would be amazing and would help so many users with Google devices and Samsung TVs.

The link below describes how they were able to implement the solution to allow the user to choose their desired HDR format.

xbmc/xbmc#24584

Thanks for all the work ye do! It does not go unnoticed! The app is amazing.

**Comment by TRtomasz** [comment]
This it outside of scope of bugs stremio can fix, we use exoplayer and vlc player. If you want yo u can propose this solution to them.
