### ISSUE TITLE
Can't add another word at the beginning of search box

### ISSUE THREAD

**Issue by pabloab** [Stremio/stremio-bugs#102]
Let's say you wan't to search _john cassavetes_. You write _cassavetes_ and then want to refine the search adding the word at te begging (it doesn't mother OR logic operator doesn't care of the order) of the search box. After you type the first letter the cursor jump to the end:

![image](https://cloud.githubusercontent.com/assets/657836/24875587/f6c3b364-1dfe-11e7-8027-46610a0a047c.png)

**Comment by Ivshti** [comment]
we fixed that in 4.0 alpha/beta, it will be deployed in a few days to everyone running it
