### ISSUE TITLE
Trakt scrobble not working well

### ISSUE THREAD

**Issue by Aerozolic** [Stremio/stremio-bugs#1020]
When watching something trakt shows the progress correctly of what I'm watching. But when I finish a movie or an episode it doesn't get "watched" mark in trakt. At the same time in Stremio the tick mark is shown.

**To Reproduce**
1. Watch something and finish it in Stremio
2. It doesn't show as watched in trakt

**Expected behavior**
Watched content should show as watched in trakt.

**Desktop (please complete the following information):**
 - macOS 12.7.6
 - Safari
 - 17.6

**Comment by TRtomasz** [comment]
Trakt marks when something is watched in 70% stremio marks when something is watched in 90%

**Comment by TRtomasz** [comment]
i misunderstood your message, anway it is duplicate there are already few issues reporting issues with trakt integration
