### ISSUE TITLE
Subtitles not working in web client when returned with stream

### ISSUE THREAD

**Issue by vanchaxy** [Stremio/stremio-bugs#1022]
**Describe the bug**
Subtitles not working in the web client when returned with stream (`subtitles` key in the /stream/series/imdb:s:e.json endpoint).

**To Reproduce**
1. Use an addon that sends subtitles with streams.
2. Open series

**Expected behavior**
subtitles present in the subtitles list

**Screenshots**
It works fine on the desktop client, the problem is only with https://web.stremio.com/.

web (subtitles not present):
<img width="968" alt="image" src="https://github.com/user-attachments/assets/f5b1025b-12da-4785-8080-bdea1d45a1d6">
desktop (subtitles present):
<img width="517" alt="image" src="https://github.com/user-attachments/assets/5d9588b7-d833-44d4-9dcc-30a887f4e40c">

**Comment by TRtomasz** [comment]
Does it still not work when you send correct language code?

**Comment by vanchaxy** [comment]
@TRtomasz Yes, sending the correct language code still does not work. I tried "pol" as lang.
