### ISSUE TITLE
Samsung Tizen app

### ISSUE THREAD

**Issue by rja120** [Stremio/stremio-bugs#1023]
On some Videos the audio won't play it has no sound I have tried all the sound settings on the TV but no luck

Looks like it been a while since Tizen update do you have a Beta I could install using USB stick

**Comment by rja120** [comment]
It works with Emby and Jellyfin same file

**Comment by Dennis-NL** [comment]
Yes but Jellyfind transcodes the audio if its not supported. Stremio does not and is run locally

**Comment by rja120** [comment]
I see, Is that why web.stremio has no sound.  But the desktop windows doe's
