### ISSUE TITLE
Custom streaming server for Tizen

### ISSUE THREAD

**Issue by edde746** [Stremio/stremio-bugs#1026]
It seems that the Tizen app currently does not support settings a custom streaming server, that would be a great feature to have (and should be fairly easy to implement).

**Comment by TRtomasz** [comment]
not a bug

**Comment by edde746** [comment]
@TRtomasz
Yeah. Is there a more appropriate place to make feature suggestions?

**Comment by TRtomasz** [comment]
stremio-features and please use the template
