### ISSUE TITLE
Descriptions and Trailers are always in English language (AndroidTV)

### ISSUE THREAD

**Issue by sjuk** [Stremio/stremio-bugs#1029]
**Describe the bug**
When browsing all titles, descriptions and trailers are always shown in English language only.

**To Reproduce**
1. Browse around
2. Click on 'any title'
3. Show trailer

**Expected behavior**
The preferred language, that has already been configured in the settings, should be used whenever available.
When the preferred language is not available then the second preferred language should be used.
When none of the two preferred languages is available the app should fall back to English.
Regarding trailers the user should have the option to choose (before playing the clip) between his two preferred languages or to fall back to English.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**TV (please complete the following information):**
 - Device: Philips 65OLED806
 - OS: Android TV
 - Version 11

**Additional context**
N/A

**Comment by TRtomasz** [comment]
thats not a bug

**Comment by sjuk** [comment]
@TRtomasz 
Is it expected that titles, descriptions and trailers are in Englisch language only?

It may not expected from end user perspektive.

Maybe it's a missing feature. Is it possible to requests this Feature? And If yes, how?

**Comment by TRtomasz** [comment]
Stremio-features is for features
Trailers in users languages are not possible there simply is not realiable api for that
Descriptions it is possible but there is no point in opening such issues as it already exists

**Comment by sjuk** [comment]
What exactly already exists and where?

**Comment by TRtomasz** [comment]
Such issue already exists in the streamio-features repository

**Comment by sjuk** [comment]
I didn't find it in the streamio-features repository.
Can you please relate this issue to the feature request? thanks

**Comment by sjuk** [comment]
No of the feature requests gets even near to this issue.

**Comment by sjuk** [comment]
[stremio-features > 1076](https://github.com/Stremio/stremio-features/issues/1076)
