### ISSUE TITLE
[Bug]: Can't add content 

### ISSUE THREAD

**Issue by spanfan1** [Stremio/stremio-bugs#1037]
### Stremio Platform

Desktop App (Windows)

### Describe the bug

I'm want to add content from my NAS but can;t add anything. I click on " Import Movies and Shows you have on your hard disk" but just get a pop up saying Local Addon is not enabled even though in Settings Enable the local files addon is on and green and I have restarted several times. How can I add the files from my NAS?

![Stremio](https://github.com/user-attachments/assets/7087655b-a26c-473e-b908-054c7a80a991)

### To Reproduce

Go to Profile on top right of screen
Click on  Import Movies and Shows you have on your hard disk
pop appears saygin Local files not enabled even thogh they are

### Expected behavior

Something to let me choose which files to add

**Comment by TRtomasz** [comment]
You can't import manually, it automatically detects files on disks that windows indexed

**Comment by spanfan1** [comment]
I have folders on the NAS which are shared and appear in Windows file manger but Stremio doesn't see them

**Comment by TRtomasz** [comment]
Your disks has to be indexed by windows indexer for files to be detected

**Comment by spanfan1** [comment]
The folders have all got the "Allow files on this drive to have contents indexed in addition to properties" box ticked. What else so I need to do?

**Comment by spanfan1** [comment]
I've also gone to the Modify Indexing Option in Control Panel  but the NAS folders don't show  (only my PC drives) even though they are  shared and have drive letters in Windows File Manager
