### ISSUE TITLE
[Bug]: community subs addons not working

### ISSUE THREAD

**Issue by Danygh95** [Stremio/stremio-bugs#1039]
### Stremio Platform

Android Mobile App

### Describe the bug

All community subtitles addons don't work. Example: for "Subscene subtitles by dexter21767" addon i recieve this error: error loading subtitles stremio fetch timeout

The official addon OpenSubtitles V3 is working, bun I need a language that is not on this addon.

Any solutions?

App version: 1.6.13
Same issue on stremio for android TV

### To Reproduce

1. Uninstall official OpenSubtitles v3
2. Install any community subtitle addon

### Expected behavior

I should be able to pick a subtitle from the installed addon

**Comment by TRtomasz** [comment]
we cant help with issues regarding 3rd paty addons

**Comment by Danygh95** [comment]
> we cant help with issues regarding 3rd paty addons

Ok. Sorry for the incovenience
