### ISSUE TITLE
App colors = Stremio 3.6.6

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#104]
Could you please give us nice colors for Stremio 3.6.6 as you use for Stremio 4.0 alpha/beta?
(no need for transperent function system which couse you problems - at least this is how i understand you, why color changes , when i ask why color changes from older Stremio versions to recent Stremio versions).
Anyway,, is it posible for you to give us this nice sleek colors for Stremio 3.6.6?

1.) Something like this ''finished version''

![stremio colors 01](https://cloud.githubusercontent.com/assets/7681671/24999493/f523dec6-203d-11e7-9d08-477d091eb706.PNG)

2.) In this screenshot i only pointed out Header color changes because in ''finshed version' isn't that obvious color change i made =i switched colors between Search box and the rest of header.

![stremio colors 02](https://cloud.githubusercontent.com/assets/7681671/25000398/7442b5ee-2041-11e7-8381-81d9a055f4f3.PNG)

Regards

**Comment by Ivshti** [comment]
I can see what you mean. Usually, 3.x is designed with window transparency in mind, and it looks much, much better when it's enabled. Unfortunately, transparency doesn't work on Linux and it's purposefully disabled on Windows 7.

At the moment 100% of our development effort is focused on pushing out 4.x, so we don't have time to tweak 3.x. Also, our build system for 3.x has been abandoned for some time and would take additional development effort to get it back up in working order. So I suggest that you wait for 4.x, sorry for that :( But the good news is that it's very close to release state - a few weeks away :)

**Comment by Draxler** [comment]
i really like 3.6.x versions (no isues) / 4.0 version have (don't have) some things that really botherd me.

i hope your new 4.0.x version would come without OS top bar. I hope top header would stand on it's own (as 3.6.x versions have) without having OS bar on top of it. Also didn't see guest login in 4.0 .. 

![stremio board 4 0 beta](https://cloud.githubusercontent.com/assets/7681671/25006955/140ee652-205f-11e7-891c-3d407d5bacbb.png)
