### ISSUE TITLE
[Bug]: stremio-desktop for linux does not respond to MPRIS signals

### ISSUE THREAD

**Issue by KiaraGrouwstra** [Stremio/stremio-bugs#1040]
### Stremio Platform

Desktop App (Linux)

### Describe the bug

stremio-desktop for linux seems not to respond to MPRIS signals as associated with media player related buttons on the keyboard

### To Reproduce

1. press play/pause button on keyboard

### Expected behavior

stremio should pause/play

### Desktop (if applicable)

Stremio 4.4.168 on linux (NixOS 24.11)

**Comment by TRtomasz** [comment]
This is not a bug, just a missing feature. I will close that one as we have similar issues opened in stremio-features and stremio-shell repositories. Feel free to provide PR to the shell if you want to have this implemented.
