### ISSUE TITLE
[Bug]: auto play next episode

### ISSUE THREAD

**Issue by Jarvis636** [Stremio/stremio-bugs#1046]
### Stremio Platform

Desktop App (Windows)

### Describe the bug

Stremio 5 is awesome I love it but the only issue I'm experiencing is the auto play next episode it doesn't skip to the next episode it closes off instead.

### To Reproduce

Stremio 5 is awesome I love it but the only issue I'm experiencing is the auto play next episode it doesn't skip to the next episode it closes off instead.

### Expected behavior

Auto play to the next episode 

### Desktop (if applicable)

Stremio 5

**Comment by kKaskak** [comment]
closed in favor of the new issue, please do not repeat the same issue more than once
