### ISSUE TITLE
Win10x64 showing white window in app if app was opened from start screen (beta 4)

### ISSUE THREAD

**Issue by SaintGerasim** [Stremio/stremio-bugs#105]
https://www.screencast.com/t/u9R64XNDE

**Comment by Ivshti** [comment]
Thanks for reporting this.

Few notes:

1. Is it a version downloaded recently? The last installer is alpha.46 
2. Can you give us information on your GPU and general setup (do you have 2 GPUs - separate integrated graphics and dedicated?), GPU drivers, exact Windows 10 version
3. Try adding "QT_OPENGL" environment variable set to "desktop" and see if this behaviour would be replicated
