### ISSUE TITLE
[Bug]: External subtitles error 

### ISSUE THREAD

**Issue by robertbruce76** [Stremio/stremio-bugs#1052]
### Stremio Platform

Desktop App (Windows)

### Describe the bug

I downloaded version 5 of Stremio, but, unlike versione 4.4, if i drag and drop external subtitles, they don't work. There is written "Unsupported file", with every video and subtitles.

### To Reproduce

Go to video
Drag and drop external subtitles, forma srt
Error shown "Unsupported file"

### Expected behavior

With Stremio, version 4.4, if i drag and drop external srt subtitles on videos, they are shown correctly

### Desktop (if applicable)

Windows 11 app

**Comment by TRtomasz** [comment]
this is not a bug, this feature is not supported at the moment in 5.0

**Comment by robertbruce76** [comment]
Thank you

**Comment by TRtomasz** [comment]
@robertbruce76  it will be soon added to the app
