### ISSUE TITLE
Cant get Full Screen on Windows 10 after Creators Update

### ISSUE THREAD

**Issue by ferrazrafael** [Stremio/stremio-bugs#106]
After updating my Windows 10 64 bits machine, Stremio stopped been able to get to full screen. I think is related to this new Creators Update. Using Stremio 3.6.6

**Comment by Ivshti** [comment]
Yes, it is. Please try our 4.0 beta: http://www.strem.io/four

**Comment by yanazevedo** [comment]
I keep getting this error message when I try to install the 4.0, am I suposed to uninstall the 3.6.6 first? 
![2017-04-25 1](https://cloud.githubusercontent.com/assets/28025664/25410094/3e60b6c0-29eb-11e7-9a81-87cfd40e32b9.png)
