### ISSUE TITLE
Can't find Chromecast

### ISSUE THREAD

**Issue by devojeff** [Stremio/stremio-bugs#107]
My Stremio just doesn't show my Chromecast (all movies/series), i have Windows 10, i can see my Chromecast at other apps like Popcorn and Google Chrome, i can even cast Stremio on Chromecast using Stremio Android App and already tried:
Reinstall Stremio
. --development
Disable firewall
Change DNS

**Comment by Ivshti** [comment]
Are you using a VPN?

**Comment by devojeff** [comment]
No VPN

**Comment by devojeff** [comment]
No VPN

**Comment by NeySlim** [comment]
Same problem for me.

**Comment by MatrixOfDeath** [comment]
Same for me, same network, from google chrome google chromecast works fine !

**Comment by jeroen7s** [comment]
also doesn't work a lot of the time, stuck at a grey screen with a chromecast logo, killing stremio and stoping the stream from "google home" app on android(it will still see an active stream), and then restarting stremio usually works

**Comment by TRtomasz** [comment]
Should be fixed, as we improved chromecast discovery recently.
