### ISSUE TITLE
Chromecast audio problem

### ISSUE THREAD

**Issue by lucaspessoapereira** [Stremio/stremio-bugs#108]
hey,

i'm trying to cast stremio to chromecast 2 and i've got the video and the subtitles but not the audio. it seems that it's happening only with the stremio app.

thanks.

**Comment by Ivshti** [comment]
Is it happening with all sources? Can you try some from Discover -> Channels or Discover -> TV

**Comment by assafmo** [comment]
Same issue for me with Android and desktop Linux, Chromecast 3.
Local files on desktop Linux works fine
