### ISSUE TITLE
Casting to chromecast doesn't work

### ISSUE THREAD

**Issue by aviled** [Stremio/stremio-bugs#109]
Hey guys, 
First of all thanks for a great app!

I have the latest stable stremio app installed on my mac and I'm having an issue with casting to chromecast v2.

The TV shows the movie loading for a while and eventually stops.
This happens consistently.

When running the app in dev mode I can see the following error:

```
[8401:0422/214550:ERROR:CONSOLE(0)] "Not allowed to load local resource: file:///Applications/Stremio.app/Contents/Resources/app.asar/index.html", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@201276/&can_dock=&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)
```

Any idea?

Thanks,
Aviram

**Comment by Ivshti** [comment]
Can you please try the following and report the results:

1. Try something from Discover -> Channels
2. If you have firewalls/VPNs, try disabling them

**Comment by aviled** [comment]
Thanks Ivshti for your reply.
I don't have any VPN or firewall enabled.
Interesting, playing from "Channels" *works* on Chromecast.

Does it helps you understand the Chromecast issue when playing movies?

**Comment by aviled** [comment]
Hey Ivo, any news regarding this issue?
Is there anything I can try to fix this issue?

**Comment by msrowley** [comment]
I am having the exact same problem too. Maybe a firmware upgrade to chromecast broke the functionality??

**Comment by aviled** [comment]
Works in stremio 4 beta version

**Comment by mabusdogma** [comment]
I have the same problem with the 4 beta and with the 3.6.5 on windows, I can't cast to my Samsung Smart TV

**Comment by nikosfil23** [comment]
Hello,

I have the same issue. i can't cast to chromcast. it seems loading and when it is going to start it stops and take me back to the series page

**Comment by experienceetc** [comment]
Same here. Interestingly, Chromecast goes black but a new window opens onto Netflix's page for the tv series corresponding to the file I dropped in Stremio..

**Comment by cfontes** [comment]
@experienceetc My problem was solved after I updated to Ubuntu 17.10, now it works perfectly.

**Comment by MilanStojanovski** [comment]
I Still have this issue on Stremio 4.4.25

**Comment by dzg** [comment]
Has this ever worked?

**Comment by rafaeldev** [comment]
Any update about this?

**Comment by Ivshti** [comment]
We can't do anything about this issue, because no one here has provided all the details, such as what Chromecast they're using, OS and Stremio version.

In our tests, chromecast works in all of our official builds (Windows, macOS). We test it every few weeks, both with an official Chromecast device and with embedded chromecast on a few TVs.

To get help with this issue, please provide all the possible details.

**Comment by mabusdogma** [comment]
At the end I've got the perfect solution:

I sold the old device and now I've got a new xiaomi smart TV with android
OS, so I installed stremio directly on the TV.

Isn't it great?
