### ISSUE TITLE
Don't prevent computer from sleeping when not playing

### ISSUE THREAD

**Issue by vmasto** [Stremio/stremio-bugs#111]
Hello,

The app currently prevents the system from sleeping any time it's open. This should only be happening if a video is playing and the app is at the foreground.

This happens on MacOS, latest Sierra version, with the latest Stremio version.

**Comment by Ivshti** [comment]
Will check it out - but when you say "current", do you mean 4.0 or 3.x?

**Comment by vmasto** [comment]
Sorry I mean 3.6.7, I wasn't aware there's a 4.0 version. I thought it would upgrade automatically on the latest.

**Comment by Ivshti** [comment]
solved now
