### ISSUE TITLE
Stremio 4 stuck on loading screen

### ISSUE THREAD

**Issue by Vinno97** [Stremio/stremio-bugs#112]
Hi, 

I have the latest beta because Stremio told me it would fix incompatibilities with the Windows Creators Update. It worked fine for some time, but now I cannot launch it anymore. 
Every time I launch it, it's stuck on the loading screen with the flashing logo. 

I cannot find anything weird, so I will just provide the data that I can give:

- No disk activity
- No network activity
- 0.5-1.5% CPU
- stable 28.4 MB RAM
- HDD spun up when I started it the first time.

![image](https://cloud.githubusercontent.com/assets/17764599/25913412/e76c8174-35ba-11e7-8da5-da2ddfb6cb55.png)

**Comment by Ivshti** [comment]
Thanks for reporting this - we identified the cause and pushed a fix. It should be live in around 6 minutes, that's how long it takes for the caches to expire for app.strem.io

**Comment by Vinno97** [comment]
Wow. I am very impressed by your response time. I will check it out immediately

**Comment by lhunardaien** [comment]
im still having this issue, any updates ?

**Comment by Vinno97** [comment]
I don't think you're experiencing the same issue. After @Ivshti  patched it, I never experienced it again. 

Also, I actually should've closed this issue months ago. Perhaps open a new issue and report exactly what you are experiencing?

**Comment by Ivshti** [comment]
thanks for the update @Vinno97
