### ISSUE TITLE
4.0 beta 10 getting only sound with subtitles

### ISSUE THREAD

**Issue by pocesar** [Stremio/stremio-bugs#113]
No matter which type of streaming service used, it always show a black screen, with sound and subtitles.

**Comment by Ivshti** [comment]
Can you please provide details about your operating system & PC?

**Comment by pocesar** [comment]
- Windows 10 64bits Creators Update
- nVidia GTX 970 (latest drivers)
- Core 2 Quad Q9550
- 8Gb RAM

**Comment by Ivshti** [comment]
@pocesar can you check if this is fixed now?

**Comment by pocesar** [comment]
@Ivshti yes, it's fixed, thanks!
