### ISSUE TITLE
Subtitles casting to a chromecast 2 not working

### ISSUE THREAD

**Issue by jokssimon** [Stremio/stremio-bugs#116]
Subtitles casting to a chromecast 2 from android app (on a op3 phone) aren´t working, it´s only something that happends to me or is it a known issue? I´ve tried on 2 different phones and is the same, i can see the subtitles if i play the video directly on the android phone, but when i try to cast it, they just doesn´t appear at all.

Thx so much for the incredible work on this app!

**Comment by thiagohsp** [comment]
Im having the same problem! Since 2 weeks ago.

**Comment by jokssimon** [comment]
Yeah, It was same timing for me, about 2-3 weeks ago.. I've tried several things and nothing worked

**Comment by alisonsm92** [comment]
For me too, since 2 weeks ago the subtitles aren´t working on Chromecast.

**Comment by jokssimon** [comment]
Nobody can help us?

**Comment by lielran** [comment]
Same as here

**Comment by podrivo** [comment]
Having the same problem here. Tried on an android and desktop.
