### ISSUE TITLE
Hebrew subtitles punctuation is in the wrong side.

### ISSUE THREAD

**Issue by gusovi** [Stremio/stremio-bugs#117]
Testing in v3.7.6 as well as in v4.0.0 beta 16; testing all different subtitle options.
Hebrew will display nicely throughout the Stemio UI, as well as having displayed in the right direction while displaying subtitles. The only issue is that punctuation appear not in the right place, for example:

STEMIO SUBTITLES:
"חפה מפשע ,אבל אם תתקרבו." 
THE CORRECT DISPLAY:
",חפה מפשע. אבל אם תתקרבו"

(For your convenience, the same text, in English:
**note that when in English the subtitles appear perfectly; English translation is for your convenience only. 

STEMIO SUBTITLES:
".Innocent, But get closer though"
THE CORRECT DISPLAY:
"Innocent. But get closer though,")

**Comment by Ivshti** [comment]
@NikolaBorislavovHristov maybe we can implement whatever we implemented for android?

**Comment by gusovi** [comment]
Note that the issue exists also on v0.30.7 on android.

**Comment by TRtomasz** [comment]
@gusovi  can you confirm that it is fixed on android and pc app?

**Comment by gusovi** [comment]
The issue is NOT fixed for PC
it is ok only for android
