### ISSUE TITLE
Failed to scroll in Android TV

### ISSUE THREAD

**Issue by lielran** [Stremio/stremio-bugs#118]
It seems that I can scroll on Android TV(left or right).
also, I couldn't get to the subtitles menu while playing the movie.

**Comment by jeroen7s** [comment]
i have different issues on AndroidTV
can get to the subtitle menu fine, but sibtitles only apear partly and get cut-off, untill i pause and play, then it works for a while and half a minute later they get cut off again, like it's only allowed to show them  in a small box
scrolling through seems to only work while playing, while paused there's no way to access the timeline
