### ISSUE TITLE
Right click on a title (to see if the episode has the watched status) takes a awfull long time to load

### ISSUE THREAD

**Issue by ursie** [Stremio/stremio-bugs#119]
Most of the times within the stremio client it takes literally minutes to see the right click context menu (see attached screenshot)

![image](https://user-images.githubusercontent.com/25615774/28376674-057be64c-6cab-11e7-80c5-b1454edd0cdf.png)

I forgot to mention that I am running on a mac

**Comment by Ivshti** [comment]
can't reproduce. can you test with www.strem.io ?

**Comment by ursie** [comment]
You are right. With the BETA build I can't reproduce this.
