### ISSUE TITLE
Clicking TV (casting) just returns to details screen

### ISSUE THREAD

**Issue by haroldma-zz** [Stremio/stremio-bugs#12]
Chromecast works fine but casting to my smart tv doesn't.

**Comment by Ivshti** [comment]
This is related to a number of casting issues with DLNA, AppleTV and Chromecast that need to be fixed

**Comment by luiseduardobrito** [comment]
+1

**Comment by Ivshti** [comment]
Cross referencing https://mail.google.com/mail/u/0/#inbox/152043a0756e363e

**Comment by TRtomasz** [comment]
Closing. Stremio 3 is not longer maintained.
