### ISSUE TITLE
Preventing screen locking - 4.0 beta 

### ISSUE THREAD

**Issue by leonardoRC** [Stremio/stremio-bugs#121]
Preventing screen locking when playing full screen videos (on linux)
 And if the desktop environment somehow affects this then I am using Gnome 3.

**Comment by Ivshti** [comment]
We're looking into this, thanks for reporting

This may be related: https://github.com/mpv-player/mpv/issues/4763

**Comment by TRtomasz** [comment]
@leonardoRC  can you confitm that it is fixed now?

**Comment by ales-tsurko** [comment]
I have this problem too. Stremio v4.4.120.
