### ISSUE TITLE
Stremio 4 player freezes when 'hardware-accelerated decoding' is enabled

### ISSUE THREAD

**Issue by CoderOffka** [Stremio/stremio-bugs#123]
Stremio 4 player freezes (lags/10fps) when 'hardware-accelerated decoding' is enabled. If it's disabled no lags, no freezes, stable and high fps.

**Comment by Ivshti** [comment]
Which operating system?

**Comment by CoderOffka** [comment]
Windows 7 pro

**Comment by zayexo** [comment]
are you talking about hardware acceleration on vlc? otherwise how do you turn off/on hardware acceleration on stremio?

**Comment by Ivshti** [comment]
By my last memory, we made it so it's disabled on windows by default.

Was it?

**Comment by CoderOffka** [comment]
No.... Stremio 4 beta 26.... Enabled on windows by default. And stremio doesn't save settings after the restart

**Comment by CoderOffka** [comment]
For ex.: I uncheck the 'hardware-accelerated decoding'... Restart stremio.... 'hardware-accelerated decoding' checked again...

**Comment by yusufjee** [comment]
Same here on MAC. I disable hardware accelerated decoding and it enables itself when i start stremio again. Very annoying.
