### ISSUE TITLE
stremio.desktop does not pass validation

### ISSUE THREAD

**Issue by probonopd** [Stremio/stremio-bugs#124]
```
stremio.desktop: error: value "4.0.0-alpha.22" for key "Version" in group "Desktop Entry" is not a known version

stremio.desktop: warning: value "./" for key "Path" in group "Desktop Entry" does not look like an absolute path
```

Solution:
* Remove `Version=4.0.0-alpha.22` entirely or put `1.0` there (this key is __not__ meant for the version of Stremio according to the [spec](https://standards.freedesktop.org/desktop-entry-spec/latest/))
* Remove `Path=./` entirely

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266465992#L537-L540

**Comment by Ivshti** [comment]
Ok, thanks for that, we'll fix it

**Comment by Ivshti** [comment]
Just made the edits that you suggested.

How do you validate the desktop files? xdg-* ?

**Comment by probonopd** [comment]
I am using the `desktop-file-validate` command line tool.

**Comment by probonopd** [comment]
Please let me know once a release containing the fix is available for download, so that I can include it in the AppImageHub central directory of available AppImages. Thanks!
