### ISSUE TITLE
Stremio 4 beta 26 doesn't save settings after the restart

### ISSUE THREAD

**Issue by CoderOffka** [Stremio/stremio-bugs#125]
Stremio 4 beta 26 doesn't save settings after the restart.

**Comment by Ivshti** [comment]
Which operating system? I can't reproduce on OSX and on Arch Linux

**Comment by Ivshti** [comment]
Second edit: the reason it was happening for me was that I had another streaming server started.

Is it possible that you had stremio 3.x started too?

**Comment by CoderOffka** [comment]
@Ivshti 
Windows 7
For ex.: I uncheck the 'hardware-accelerated decoding'... Restart stremio.... 'hardware-accelerated decoding' is checked again...
