### ISSUE TITLE
[Desktop] [Streamio 4.0.0 Beta 26] - Subtitles loose sync when using chrome cast 

### ISSUE THREAD

**Issue by filipelouro** [Stremio/stremio-bugs#126]

**Comment by CSRodulfo** [comment]
Not only in Chromecast, casting by TV (in my case LG) streaming to TV without subtitles everything ok, but i try subtitiles in spanish said "incompatible file"

**Comment by Ivshti** [comment]
can you control the sync with G and H?

**Comment by Acme908** [comment]
With me too
I stopped using Stremio because of this.

Plz fix it

**Comment by thelinuxlich** [comment]
This is a horrible bug :(

**Comment by ArthurLDS** [comment]
This happens in Xbox One too
