### ISSUE TITLE
[Android] Chromescast series stream without audio

### ISSUE THREAD

**Issue by pedrogalv** [Stremio/stremio-bugs#127]
Some series (actually, most of them) when streamed to chromecast doesn't have any audio.

Bug only happens for Series. 
I'm using Juan Carlos Torrents2, doesn't matter the quality.

Using Stremio Beta current version on Google Play. Only happen on APK version, the desktop stream is fine.

**Comment by BlueSialia** [comment]
Same thing is happening to me except I do have sound when the quality of the series is 480p or SD (but I guess SD is probably 480).

With movies I just watched Wonder Woman at 1080p with no issues, for example.

**Comment by ekkash** [comment]
I'm experience the same issue, although as mentioned, it works fine for 720p or below and it's occurring for movies only.

Let me know if there's anyway I can assist on helping you resolve this.

**Comment by kiklop74** [comment]
It can also be a case where audio stream uses codec unsupported by Chromecast.

**Comment by jsf15** [comment]
I'm having the exactly same problem here, please solve this

**Comment by BlueSialia** [comment]
Could you link the original issue? I can't find it among the current 39 open issues.

**Comment by assafmo** [comment]
Same issues for me, Android and desktop Linux, Chromecast 3
