### ISSUE TITLE
Email Change on facebook creates a new account.

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#128]
I am using facebook to login and after changing the email Stremio created a new account so doesn't keep any of my saved series/movies etc.

Should use the facebook ID rather than email when implementing the facebook login :)

In the meanwhile could  you please update my email account from ..... to .... so that when I login with facebook I have my old collection.

**Comment by Ivshti** [comment]
That's a very good catch, thank you! We also have the ID, but for compatibility reasons we used the email.

We'll update your account right now.

**Comment by krasi-georgiev** [comment]
all good now , thanks , I have edited my comment to remove my emails.

Congrats on the QT rewrite, It performs much better than electron so far!
