### ISSUE TITLE
Can't set the property "watched" on a epsiode

### ISSUE THREAD

**Issue by ursie** [Stremio/stremio-bugs#129]
I have installed the latest beta (4.0.0 beta.31) and I can't set the "watched" property anymore on a individual episode of a serie. Is this a know bug ?

I run stream.io on my mac

**Comment by Ivshti** [comment]
It's an oversight, we'll fix it. There will be a new UI for that, though, as the context menu there is removed

**Comment by ursie** [comment]
I have installed now the official 4.0.0 Gold release. But still the "watched" context menu option is not there. Is that correct ?

**Comment by Ivshti** [comment]
the reason for this was identified and fixed, should be ok now
