### ISSUE TITLE
Drag on Drop feature for Subtitles doesn't work (always)

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#13]
Win OS

- In some cases when Drag and Drop subtitles into Stremio player (when video play) nothing hapens, there is no subtitles.

- I think it would be much better if SUB feature would be visible (fixed) at all time (even if there is no subs avaiable for some movie|Tv series) because when SUB featue isn't visible then Subs it self doesn't work at all when drag and droped. I also think Custom Subs feature should be available on SUB menu it self, (Drag and Drop subs should be secondary way how to add subs). 

- Also a lot of times SUB option doesn't show on the player when subs are avaible and user need to completley turned movie off and then play that same movie again for SUB option to actualy reapear. That's why i think SUB option should be visible (fixed) at all times on Stremio player.

- The main reason why Subs doens't always work when Drag and Drop is becuase of this SUB Feature isn't visible (fixed) at all time on Player. When This feature isn't visible then also Drag and Drop doesn't work, which means Subs Ffeature is completley turned off and it couldn't be used at that time. You need to make this SUB feature visible (working) at all times if you want for subs to work at all times.  

Here are screenhots about Subs feature not reparing:

![1a](https://cloud.githubusercontent.com/assets/7681671/11145507/62d85aa2-8a06-11e5-807e-5e6f7638fec1.PNG)

![2b](https://cloud.githubusercontent.com/assets/7681671/11145511/6cbc380e-8a06-11e5-886e-650e0ada24c3.PNG)

**Comment by Ivshti** [comment]
Which cases though? 

This works only with srt files

**Comment by Draxler** [comment]
I use only srt files. 
Can you read more closely my Issue report?. I explaineid that this Drag and Drop issue couse another issue you having with Subs feature on Stremio.

- **1st. issue** : SUB option (SUB menu) doesn't show always on Stremio when it should (subs are available). User must exit movie or tv serie completley and then go back and start movie or TV Serie again for SUB option (SUB Menu) to actualy apear on a player. This issue happenes at random, you can't point it out which video does that.

- **2nd. issue** : This 2nd issue is connected with 1st. issue. Why? Because, Whenever 1st issue happens, when there's no SUB option (SUB Menu) available on Player then this 2nd isssue happenes.

2nd issue is this; Drag and Drop subs (srt) doesn't work. when we having 1st issue. 
Drag and Drop subs only works when we doesn't have 1st issue , which means, when SUB option (SUB Menu) is present on player then Drag and Drop subs works.

1st. issue doesn't jast mede SUB option/SUBmenu unavailable on player but it kills Subs option alltogether when this happens. Not working Drag and Drop subs, when 1st issue is present, is proof to that.

You need to fix 1st issue so 2nd issue won't happend. 
Imo SUB menu should be always present on player, no metther if Stremio find any subs or not for a video. This issue would continue to happens if Stremio won't make Sub option available everytime when it won't found subs in time or won't find it at all. and user would again need to do workarounds just to made subs available.

https://cloud.githubusercontent.com/assets/7681671/11145507/62d85aa2-8a06-11e5-807e-5e6f7638fec1.PNG

https://cloud.githubusercontent.com/assets/7681671/11145511/6cbc380e-8a06-11e5-886e-650e0ada24c3.PNG

**Comment by Ivshti** [comment]
"2nd issue is this; Drag and Drop subs (srt) doesn't work only when we having 1st issue. "

Thank you. I know what the problem is, will solve it

**Comment by Ivshti** [comment]
I am also against showing SUB all the time, simply because I cannot think of where to put the custom subs button without cluttering the UI ;) I know this is kind of stupid, but we'll figure something out

**Comment by Draxler** [comment]
Where to put Custon Subtitles Button? well that's eazy;

![9999999](https://cloud.githubusercontent.com/assets/7681671/11165419/7b066fde-8b0e-11e5-9133-278cf99e7d8c.PNG)

to return to my issue report with 2 defferent (connected) issues;
I would like to know if both issues are solwed , i mean if  1st. issue is also fixed? 
Would be SUB option from now on always available on player (when subs are available), so user doesn't have to turned movie off and then restarted movie again for SUB option to show up with all vaiable subtitles?




Are you solwed both issues? What i mean is, if 1st issue i also solwed?

**Comment by Ivshti** [comment]
@Draxler solved the issue with subs not working when icon is shown, not sure if it's released, I think it is. If not, then tomorrow.
