### ISSUE TITLE
The app is getting closed after a certain interval of time.

### ISSUE THREAD

**Issue by Pronoy999** [Stremio/stremio-bugs#130]
I am on windows 10 creator's update and the app is getting closed after a certain interval of time while watching movies.

**Comment by Ivshti** [comment]
Hello,

Does it get closed without warning or interaction? Just disappers? does some stremio.exe process still stay active (you can check in the Task Manager)

**Comment by Pronoy999** [comment]
I was watching Spider Man home coming movie and after every 7-10 minutes the app was getting closed. No the process is getting closed too. There are no warnings or anything else.  I have to restart the app again.
