### ISSUE TITLE
Huge application window on 3200*1800 screen stremio4 beta linux

### ISSUE THREAD

**Issue by jeroen7s** [Stremio/stremio-bugs#131]
everything is blown out of proportion in a way that half the application is not even completely on screen, and i' can't resize it to be any smaller, only bigger
this issue is using the Linux AppImage for Stremio4, currently beta29, but was also an issue in beta 25 and beta 21

**Comment by Ivshti** [comment]
Which distro?

I usually solve that by launching it with "QT_SCALE_FACTOR=0.6 ...path to appimage.."

**Comment by jeroen7s** [comment]
it is manjaro with Gnome, tried your fix and it seems to work

**Comment by microstudi** [comment]
Happens in Ubntu 16.04 as well. The fix works, thanks!

**Comment by gapplef** [comment]
Same here on both Ubuntu 17.04 and 17.10 with 13'' 1080P screen, and the fix given by @Ivshti works.
Couldn't this be fixed in the application?

**Comment by jeroen7s** [comment]
for reference, my display is 13 inch as well

**Comment by gapplef** [comment]
The fix works in terminal, but not work when putting the command in the Desktop Entry file.
It report error at launch. So, how to fix this problem in Desktop Entry file?

**Comment by microstudi** [comment]
You should use the `env` command:
in my .desktop file I have:
`Exec=env QT_SCALE_FACTOR=0.6 /home/ivan/bin/Stremio+4.0.0-beta.29.appimage`

**Comment by gapplef** [comment]
Thanks a lot @microstudi

**Comment by Ivshti** [comment]
fixed in https://github.com/Stremio/stremio-shell/commit/6a74d5c574ef656479763497acf10cf4b9a042aa
