### ISSUE TITLE
Keeping reminder me to upgrade.

### ISSUE THREAD

**Issue by gapplef** [Stremio/stremio-bugs#133]
Stremio 4.0 beta on Ubuntu 17.10
I download the latest "Stremio+4.0.0.appimage" for Linux from the official site. But it keeping reminder me that "New version is available! Upgrade to the latest Stremio version. Re-launch now!".
p.s. how to find the version of Stremio.

**Comment by Ivshti** [comment]
Thanks for reporting this, we are looking into it.

**Comment by Ivshti** [comment]
We found it, it seems the linux build is slightly weird - it includes a server build that doesn't have the same hash as in the version descriptor

we identified the reason for the error and we will fix it

**Comment by gapplef** [comment]
Thanks for your quick responds! Nice work!

**Comment by Ivshti** [comment]
Should be OK now - please try it

Should upgrade you ONCE and not any more.

As already said, the weird thing in our Linux builds is that you will have to launch the newly downloaded version from your home directory to avoid being upgraded again

**Comment by gapplef** [comment]
The issue was fixed now. Appreciate your work!
