### ISSUE TITLE
[failed] New version is available! Upgrade to the latest Stremio version. Re-launch now!

### ISSUE THREAD

**Issue by smaimon** [Stremio/stremio-bugs#134]
1. - I see the banner ![image](https://user-images.githubusercontent.com/9210668/32948268-f711c1a0-cb9e-11e7-8ce7-59e9d8d4237d.png)
2. - Then I click on Re-launch now! 
3. - The link open my default browser on this Failed autoupdate link http://www.stremio.com/?fromFailedAutoupdate=true

**Comment by Ivshti** [comment]
we are currently experiencing downtime of the auto-update server.

The auto-updater does that as a backup procedure in case it cannot check for a new version.

Both separate issues, but they lead to this. Will be resolved soon
