### ISSUE TITLE
Stremio 4 Beta - Touchpad scroll won't work

### ISSUE THREAD

**Issue by I-NOZex** [Stremio/stremio-bugs#135]
Unfortunelly I can't migrate to version 4, because the scroll with touchpad won't work on my computer
My computer is a **Asus x550ld**, all updated ( drivers and such), runing legitimous Windows 10 Pro Fall Creators Update.
The touchpad scroll works fine everywhere else.
I had some similar issues with touchpad scroll not working properly in Electron apps (I've not tested with my personal computer refered before, but is also a Asus,  ASUS P2440UQ, running the same windows version, and I have issues with Visual Studio Code, wich is also a Electron app, it could be related...)
Thanks!

**Comment by Ivshti** [comment]
4.x is not an electron app, it's a qt app

3.x is an electron app

When you say you can't migrate to 4, do you mean to say it works on 3.x?

**Comment by I-NOZex** [comment]
Ouch, I've forgotten that...
Yes I'm still using 3.x because everything works as expected.
In version 4.x is where I have this issue
