### ISSUE TITLE
Drag and drop subtitles sometimes not working on version 4

### ISSUE THREAD

**Issue by wptd** [Stremio/stremio-bugs#138]
Im trying the following file to stream, and stremio adds a subtitle when I add a subtitle draggind and dropping, and the subtitle is listed on sub menu, but I cant select the subtitle.

Trying with this stream

magnet:?xt=urn:btih:a470d85445bba6ffb127c7bdeae3a106d936581d&dn=Blade+Runner+2049.720p.WEB-DL.H264.AC3-EVO&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969

**Comment by TRtomasz** [comment]
That magnet link is no longer working. If you have some other file to check please let us know
