### ISSUE TITLE
FilmOn addon is broken = Not one Channel have Stream

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#14]
When enter Stremio **Tvs** section = **FilmOn addon** ; not one Channel have working Stream, in fact every channel have this message; **No stream available** when enter into their detail page.
You can choose whatever **Genre** and picked whatever Channel, everywhere is the same.

![1a](https://cloud.githubusercontent.com/assets/7681671/11183090/0712603e-8c70-11e5-8eaf-0020fc1986bd.PNG)

![2a](https://cloud.githubusercontent.com/assets/7681671/11183042/bc76b106-8c6f-11e5-92c8-04fdec1800f3.PNG)

**Comment by Ivshti** [comment]
Just discovered this myself

working to fix it

**Comment by Draxler** [comment]
After i reported this, channels start to work again. But unfourtnely, i see again that channels doesn't work. This time Play button is there instead of a messsage **No stream available** as it was last time, (this is the only deffrence).

**Comment by Ivshti** [comment]
how about now?

**Comment by Draxler** [comment]
Still not working. :(

**Comment by Ivshti** [comment]
That's weird, it's working for me
can you try with a fresh account?

**Comment by Draxler** [comment]
I completeley uninstalled Stremio and delete all leftovers and then install Stremio again. I loged in with guest account (the only one i used) and Not one channel is working. Not only that, after you click on Play button on channels detail page you can't exit this channell afterwards. When you click on exit button (x=close button) app minimized it self instead of exit channel detail page. so you have 2 isuess:

1st.) Not working channels

2nd.) Can't exit channel detail page after click on Play button

**Comment by Ivshti** [comment]
Found the issue @Draxler 
we are doing a release to fix it

**Comment by Draxler** [comment]
:+1:

**Comment by Ivshti** [comment]
@Draxler can you check with the latest update

**Comment by Draxler** [comment]
iT's WoRkiNg ... :-)
