### ISSUE TITLE
No way to return to board after watch multiple episodes

### ISSUE THREAD

**Issue by cosmoscalibur** [Stremio/stremio-bugs#142]
When you explore and watch episodes, there is no way to return to the board in one step. Using `Back` option is backward in history (through each episode that you see).  

Stremio 4.0.3 Beta
Server 4.1.29
Shell 4.4.0

**Comment by Ivshti** [comment]
We're aware of this and working on a resolution, thanks for reporting

**Comment by Ivshti** [comment]
navigation is fixed now
