### ISSUE TITLE
linux - single instance broken in  4  beta.

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#143]
#45  
Sigle instance  broken in the 4 beta. 

running the appimage starts a new instance everytime which makes it unusable when opening magnet or torrent files as each click starts a new instance of stremio and it returns the - "can't fetch" error

I was on the appimage irc channel and seems that the single instance needs to be enforced form the binary or the QT QtSingleApplication

I manged to extract the content of the appimage and when running stremio form there it works as expected.

**Comment by krasi-georgiev** [comment]
'sudo mount -o loop -o offset=97112 ./Stremio+4.0.2.appimage /tmp/stremio'

can be used as a workaround

**Comment by Ivshti** [comment]
Yeah, that makes sense

Thanks for letting us know.

Is there a way to make the appimage behave in a way friendly to the single instance application?

the alternative would be to provide deb/rpm/AUR packages directly

**Comment by krasi-georgiev** [comment]
I am sure the appimage can be made a sinlg einstance only , but I didn't even know about appimages before yesterday so don't have the 'know how'

**Comment by krasi-georgiev** [comment]
this is low priority so closing for now.
