### ISSUE TITLE
[updated with new info] Subtitles Not Working At Android TV (version 0.40.1)

### ISSUE THREAD

**Issue by nioxys** [Stremio/stremio-bugs#144]
Recently i installed the stremio app from the website and its not working like it should. The subtitles don't load, or sometimes loads the first line of the subtitle file and stays on the screen for the rest of the video. I already reinstalled and it keeps the same.
The subtitles on the previous version works well but i'm not able to select the language with the remote control, in version (0.40.1) the UI lets me select the subtitles language with the remote control but the subtitles don't work. i'm using a Xiaomi Mi box with android tv.

**Comment by NikolaBorislavovHristov** [comment]
Please provide a screanshot. 
Did you install stremio on the mi box or you just cast a video to the TV, because it is not clear?

**Comment by nioxys** [comment]
I've installed stremio version 0.40.1 on the Mi Box with android tv.
This issue happens in all the streams i've try to play.
The subtitles don't load, or sometimes loads only the first line and stays on the screen for the rest of the video. 
In the previews version of stremio this issue don't happen, but in that version i'm note able to select, with the remote controlo, the correct language of the subtitles.
In this new version i can control everything with the remote control but the subtitles don't work.

**Comment by nioxys** [comment]
So, i've installed stremio version 0.40.1 on my Android tablet and the subtitles work fine.
Conclusion, this issue only happens on my Android TV device. 
Any idea on what can cause this issue on Android TV version and not on the "normal" version?

**Comment by nioxys** [comment]
I've installed the version 0.42.3 and now everything works fine.
Thanks.
