### ISSUE TITLE
Stremio(ubuntu) crashes after couple of second

### ISSUE THREAD

**Issue by ivanmrchk** [Stremio/stremio-bugs#145]
Never had this before, but whenever I run app image most of the time error reads the following
`js: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
js: TypeError: Failed to fetch
js: TypeError: Failed to fetch
js: TypeError: Failed to fetch
QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault (core dumped)
`

I'm running ubuntu 14.04

**Comment by mozgbrasil** [comment]
--
Description:	Ubuntu 18.04.1 LTS
--
marcio@marcio-Aspire-5542:~$ ./Stremio+4.4.10.appimage
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 0, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar  7 03:52:26 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.10-1~trusty3.1
[cplayer] 
[cplayer] Configuration: ./waf -v configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --disable-cplayer --enable-libmpv-shared
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date cdda debug-build dlopen drm dvbin dvdnav dvdread enca encoding fchmod fnmatch gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler shm sse4-intrinsics standard-gl subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '-'
[cplayer] Set property: vo="opengl-cb" -> 1
[cplayer] Set property: opengl-hwdec-interop="auto" -> -3
[cplayer] Set property: cache-default=15000 -> 1
[cplayer] Set property: cache-backbuffer=15000 -> 1
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?winControls=true&loginFlow=desktop
qml: Stremio Shell version: 4.4.10
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: checking for new version
[3524:3554:0901/212020.461700:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/marcio/.pki/nssdb): libsoftokn3.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
[3524:3554:0901/212020.461829:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -5925
[opengl-cb] GL_VERSION='3.0 Mesa 18.0.5'
[opengl-cb] Detected desktop OpenGL 3.0.
[opengl-cb] GL_VENDOR='X.Org'
[opengl-cb] GL_RENDERER='AMD RS880 (DRM 2.50.0 / 4.15.0-33-generic, LLVM 6.0.0)'
[opengl-cb] GL_SHADING_LANGUAGE_VERSION='1.30'
[opengl-cb] Loaded extension GL_ARB_sync.
[opengl-cb] Loaded extension GL_ARB_timer_query.
[opengl-cb] Loaded extension GL_ARB_debug_output.
[opengl-cb] 16 bit texture depth: 16.
[opengl-cb] Reported display depth: R=8, G=8, B=8
[opengl-cb] Testing FBO format 0x805b
[opengl-cb] Create FBO: 16x16 (16x16)
[opengl-cb] Using FBO format 0x805b.
[opengl-cb] No advanced processing required. Enabling dumb mode.
[3524:3554:0901/212020.461839:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0
#0 0x7f74953ed3ae <unknown>
#1 0x7f74953fd4b7 <unknown>
#2 0x7f7495bce68d <unknown>
#3 0x7f7495bceba0 <unknown>
#4 0x7f7495afdc75 <unknown>
#5 0x7f74959ea8a7 <unknown>
#6 0x7f74959b6b67 <unknown>
#7 0x7f7494b3652a <unknown>
#8 0x7f7494b37a46 <unknown>
#9 0x7f7494b39bce <unknown>
#10 0x7f7494d19207 <unknown>
#11 0x7f749503b21f <unknown>
#12 0x7f74954615a3 <unknown>
#13 0x7f7495406b90 <unknown>
#14 0x7f749540899d <unknown>
#15 0x7f7495409896 <unknown>
#16 0x7f749540a210 <unknown>
#17 0x7f7495405f92 <unknown>
#18 0x7f74954219d8 <unknown>
#19 0x7f7494d4e1f5 <unknown>
#20 0x7f7494d4e62b <unknown>
#21 0x7f74954395f6 <unknown>
#22 0x7f74954358ad <unknown>
#23 0x7f748deaf6db start_thread
#24 0x7f749206b88f clone

QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
Falha de segmentação (imagem do núcleo gravada)
marcio@marcio-Aspire-5542:~$ 
--

**Comment by TRtomasz** [comment]
Hi, you can find new deb package here. https://www.reddit.com/r/Stremio/comments/9pjcrk/new_deb_package_for_linux_systems/
