### ISSUE TITLE
Linux - fedora 27 - playback doesn't prevent screen lock

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#146]
I would expect that a playback , full screen or not would prevent screen blanking.
Screen is locking in full screen as well as not full screen.

VLC works fine so it shouldn't be a bug with fedora, but some keep alive signal that Stremio needs to enable.

**Comment by Ivshti** [comment]
Known issue, will be resolved with one of the next stremio updates

**Comment by krasi-georgiev** [comment]
if this is a known issue closing the issue
