### ISSUE TITLE
Stremio 4 Beta-Ubuntu 17.10- doesn't get the user keyboard ?

### ISSUE THREAD

**Issue by nidhal1920** [Stremio/stremio-bugs#148]
Typing in any text field of the application is done with QWERTY layout even if the user keyboard layout is AZERTY .

Running : **Stremio+4.0.2.appimage** 
`localectl status`
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_BE.UTF-8
                  LC_TIME=de_BE.UTF-8
                  LC_MONETARY=de_BE.UTF-8
                  LC_PAPER=de_BE.UTF-8
                  LC_NAME=de_BE.UTF-8
                  LC_ADDRESS=de_BE.UTF-8
                  LC_TELEPHONE=de_BE.UTF-8
                  LC_MEASUREMENT=de_BE.UTF-8
                  LC_IDENTIFICATION=de_BE.UTF-8
       VC Keymap: n/a
      X11 Layout: fr
       X11 Model: pc105

and 
`lsb_release -a
`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by Ivshti** [comment]
Interesting

Perhaps this is due to the fact stremio runs in an AppImage.

What you can try to do is copy stremio from the appimage dir (/tmp/Stremio.SOMETHING) and run it from the normal dir by directly starting the executable

**Comment by nidhal1920** [comment]
Hi @Ivshti 
For the result described above I have run it @ /home/xxx/Download

**Comment by TRtomasz** [comment]
Can you confirm that is fixed now?
