### ISSUE TITLE
No Status Icons on GNOME  / Elementary OS - Please add an exit control on application

### ISSUE THREAD

**Issue by alex285** [Stremio/stremio-bugs#149]
On some Linux Desktops including GNOME and Elementary OS (Pantheon Desktop) Stremio's Systrem Tray Icon doesn't work, and thus we cannot close Stremio, without using a terminal

In Ubuntu's case, GNOME is patched with an extension to use [KDE Status Notifier Indicators](https://github.com/Ubuntu/gnome-shell-extension-appindicator), so that solves the problem there, but not on Elementary OS, or Linux distros that use GNOME without this extension, like Fedora

**Comment by TRtomasz** [comment]
I'm closing this issue. If it is still not working in the latest stremio 4 please let us know

**Comment by megatux** [comment]
What was the solution to this issue? I just downloaded latest 4.x versino and still don't see a "Close" menu action. I'm also on ElementaryOS, where the Systrem Tray Icon was removed.
