### ISSUE TITLE
Design/UI Bug: Translucent backgrounds allow me to see previous screen

### ISSUE THREAD

**Issue by kodaxx** [Stremio/stremio-bugs#15]
For example: When I click on Board it says, "Your Board is empty"...but when I click on Library it says, "Your Library is empty". The problem is that UNDERNEATH "Your Library is empty" I can still see "Your Board is empty" very lightly and then with the next screen it just stacks on top and on and on. On Windows 10 by the way.

**Comment by Ivshti** [comment]
Probably related to https://github.com/atom/atom/issues/4924 or some other unrelated issue. It's unfortunate, and I can offer you to start stremio with --disable-transparency flag if this breaks the UX
