### ISSUE TITLE
Desktop addon not working on android app

### ISSUE THREAD

**Issue by ThanosDi** [Stremio/stremio-bugs#151]
I'm trying to make this https://github.com/ThanosDi/piratebay-stremio-addon work on Android beta app too but without any success.

Any ideas what is wrong?

**Comment by Ivshti** [comment]
Tagging @NikolaBorislavovHristov, our mobile dev

So far we discovered that for the mobile app all addons should be referenced with `/stremio/v1` at the end because of a stupid check

we will correct that in the future

For now, can you check if the add-on works with the suffix

**Comment by Ivshti** [comment]
Tagging @NikolaBorislavovHristov, our mobile dev

So far we discovered that for the mobile app all addons should be referenced with `/stremio/v1` at the end because of a stupid check

we will correct that in the future

For now, can you check if the add-on works with the suffix

**Comment by ThanosDi** [comment]
Yip that was it, I had to append `/stremio/v1` to the endpoint url. now it is working properly to android too.
Thank you for your fast reply and help.
