### ISSUE TITLE
arm appimage for Rpi 3 , raspberry pi ?

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#152]
Hi @Ivshti would you compile an arm  appimage for Rpi3 ?

 quad-core ARM Cortex-A53

**Comment by hessel** [comment]
@krasi-georgiev Do you have success on RPI3?

**Comment by krasi-georgiev** [comment]
nope , but I think it shouldn't be a problem as long as @Ivshti finds some time to compile it for that CPU

The maintenance overhead is another thing, but I guess it is at least worth a try.

**Comment by ans-4175** [comment]
Any updates here, guys?
