### ISSUE TITLE
Stremio 4.0.17 fails to start in Debian Buster

### ISSUE THREAD

**Issue by vejeta** [Stremio/stremio-bugs#156]
Latest stremio fails to start in Debian Buster.

Relevant message is this:

:ERROR:service_manager.cc(539)] Instance: content_packaged_services attempting to register an instance for a process it created for target: content_browser without the service_manager{client_process} capability class.

This is the complete log:

 >/Stremio+4.0.17.appimage                                                                                                     1s 1ms
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 0, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar  7 03:52:26 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.10-1~trusty3.1
[cplayer] 
[cplayer] Configuration: ./waf -v configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --disable-cplayer --enable-libmpv-shared
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date cdda debug-build dlopen drm dvbin dvdnav dvdread enca encoding fchmod fnmatch gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler shm sse4-intrinsics standard-gl subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '-'
[cplayer] Set property: vo="opengl-cb" -> 1
[cplayer] Set property: opengl-hwdec-interop="auto" -> -3
[cplayer] Set property: cache-default=15000 -> 1
[cplayer] Set property: cache-backbuffer=15000 -> 1
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
[2834:2872:0716/140941.623683:ERROR:service_manager.cc(539)] Instance: content_packaged_services attempting to register an instance for a process it created for target: content_browser without the service_manager{client_process} capability class.
Received signal 11 SEGV_MAPERR 000000000010
#0 0x7fe0b56327e6 <unknown>
#1 0x7fe0b425d10a <unknown>
#2 0x7fe0b5632b5c <unknown>
#3 0x7fe0b1275f50 <unknown>
#4 0x7fe0b2675682 QShortcutMap::addShortcut()
#5 0x7fe084b3f41f <unknown>
#6 0x7fe084b5e91a <unknown>
#7 0x7fe0b2187de2 <unknown>
#8 0x7fe0b218544c QQmlPropertyPrivate::write()
#9 0x7fe0b2205cf4 QQmlBinding::slowWrite()
#10 0x7fe0b22070f8 <unknown>
#11 0x7fe0b22081ae <unknown>
#12 0x7fe0b2204c93 QQmlBinding::update()
#13 0x7fe0b22119fb QQmlObjectCreator::finalize()
#14 0x7fe0b218929e QQmlComponentPrivate::complete()
#15 0x7fe0b21893b7 QQmlComponentPrivate::completeCreate()
#16 0x7fe0b2189192 QQmlComponent::create()
#17 0x7fe0b2209d93 QQmlApplicationEnginePrivate::finishLoad()
#18 0x7fe0b2209ffe QQmlApplicationEnginePrivate::startLoad()
#19 0x7fe0b220a03d QQmlApplicationEngine::load()
#20 0x00000040de98 main
#21 0x7fe0b0932a87 __libc_start_main
#22 0x00000040e1e7 <unknown>
  r8: 00007fe084b3f0f0  r9: 0000000000000007 r10: 0000000000001f8a r11: 00007fe0b2675650
 r12: 00000000025e25f0 r13: 00007fffdd3f6630 r14: 0000000000000000 r15: 0000000000000001
  di: 0000000002309758  si: 00000000025e2638  bp: 00007fe084b3f0f0  bx: 00007fffdd3f66a0
  dx: 00000000025e2638  ax: 0000000000000000  cx: 0000000000000001  sp: 00007fffdd3f6620
  ip: 00007fe0b2675682 efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000010
[end of stack trace]
Calling _exit(1). Core file will not be generated.

**Comment by Ivshti** [comment]
If you're up for it, you can try to compile this repo: https://github.com/stremio/stremio-shell

Upon running the `./stremio` binary, stremio should start up as usual. Except it won't start the streaming server, for this you need to have NodeJS installed and `server.js`, `stremio.asar` in your working dir, for which you need to do:

```
wget https://dl.strem.io/four/v4.0.17/server.js && wget https://dl.strem.io/four/v4.0.17/stremio.asar
```

After this, it should work.

The issue with AppImages is that they often conflict with existing libs on the system, so this happens..

**Comment by vejeta** [comment]
Thanks @Ivshti for the quick reply!,

For documentation purposes I describe what I did:

Installed qtcreator and and qt5-make
``
sudo apt-get install qtcreator
sudo apt-get install qtcreator
``

When doing:

( cd deps/qBreakpad/handler ; qmake ; make )
qmake
make

I get

``
In file included from ../third_party/breakpad/src/client/linux/crash_generation/crash_generation_client.cc:39:0:
../third_party/breakpad/src/common/linux/ignore_ret.h:38:34: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 #define IGNORE_RET(x) do { if (x); } while (0)
                                  ^
../third_party/breakpad/src/client/linux/crash_generation/crash_generation_client.cc:84:5: note: in expansion of macro ‘IGNORE_RET’
     IGNORE_RET(HANDLE_EINTR(sys_read(fds[0], &b, 1)));
     ^~~~~~~~~~
g++ -c -pipe -O2 -fPIC -std=gnu++11 -D_REENTRANT -Wall -W -DCALIPER -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../third_party/breakpad/src -I../../qBreakpad -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I_build -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o _build/obj/thread_info.o ../third_party/breakpad/src/client/linux/dump_writer_common/thread_info.cc
g++ -c -pipe -O2 -fPIC -std=gnu++11 -D_REENTRANT -Wall -W -DCALIPER -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../third_party/breakpad/src -I../../qBreakpad -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I_build -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o _build/obj/ucontext_reader.o ../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc: In static member function ‘static uintptr_t google_breakpad::UContextReader::GetStackPointer(const google_breakpad::ucontext*)’:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:92:12: error: invalid use of incomplete type ‘const struct google_breakpad::ucontext’
   return uc->uc_mcontext.gregs[REG_RSP];
            ^~
In file included from ../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:30:0:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.h:44:49: note: forward declaration of ‘struct google_breakpad::ucontext’
   static uintptr_t GetStackPointer(const struct ucontext* uc);
                                                 ^~~~~~~~
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc: In static member function ‘static uintptr_t google_breakpad::UContextReader::GetInstructionPointer(const google_breakpad::ucontext*)’:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:96:12: error: invalid use of incomplete type ‘const struct google_breakpad::ucontext’
   return uc->uc_mcontext.gregs[REG_RIP];
            ^~
In file included from ../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:30:0:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.h:44:49: note: forward declaration of ‘struct google_breakpad::ucontext’
   static uintptr_t GetStackPointer(const struct ucontext* uc);
                                                 ^~~~~~~~
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc: In static member function ‘static void google_breakpad::UContextReader::FillCPUContext(google_breakpad::RawContextCPU*, const google_breakpad::ucontext*, const _libc_fpstate*)’:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:101:26: error: invalid use of incomplete type ‘const struct google_breakpad::ucontext’
   const greg_t* regs = uc->uc_mcontext.gregs;
                          ^~
In file included from ../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.cc:30:0:
../third_party/breakpad/src/client/linux/dump_writer_common/ucontext_reader.h:44:49: note: forward declaration of ‘struct google_breakpad::ucontext’
   static uintptr_t GetStackPointer(const struct ucontext* uc);
                                                 ^~~~~~~~
Makefile:535: recipe for target '_build/obj/ucontext_reader.o' failed
make[1]: *** [_build/obj/ucontext_reader.o] Error 1
make[1]: Leaving directory '/home/mendezr/development/stremio-shell/deps/qBreakpad/handler'
Makefile:46: recipe for target 'sub-handler-make_first-ordered' failed
make: *** [sub-handler-make_first-ordered] Error 2
``

Does it need to get compiled with an specific compile/version besides gcc?

**Comment by Ivshti** [comment]
hmm, what's your gcc/qt version? you need qt5 and a relatively new gcc

**Comment by vejeta** [comment]
The error seems related to different glibc versions, one featuring ucontext, and others ucontext_t

https://github.com/google/breakpad/commit/bddcc58860f522a0d4cbaa7e9d04058caee0db9d

**Comment by vejeta** [comment]
@Ivshti:

I have created a Pull Request with instructions on how to compile it for Debian:
https://github.com/Stremio/stremio-shell/pull/40

**Comment by vejeta** [comment]
This error was specific of the libraries versions used in Debian, incompatible with the ones needed by the AppImage release.

There is a work ongoing to have a Debian package, so, deleting this issue.
https://github.com/Stremio/stremio-shell/tree/debian
