### ISSUE TITLE
Pressing either the ... or the play button produces an error

### ISSUE THREAD

**Issue by asolvang** [Stremio/stremio-bugs#157]
Pressing the ... or the play button on new episodes on the board produces the error message "No information about this" inside a new window. No other information shows up in the new window except the normal back button. 

This is Streamio v4.0.30, server 4.1.30 and Shell 4.4.7
Only tested on Windows 10 Home

**Comment by Ivshti** [comment]
fixed in v4.0.32, 

the update should propagate around in a few hours, if you restart your app now you might get it

let us know if it works for you!
