### ISSUE TITLE
Fails to load on ubuntu 18

### ISSUE THREAD

**Issue by dimikz** [Stremio/stremio-bugs#159]
./Stremio+4.4.10.appimage 
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 0, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar  7 03:52:26 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.10-1~trusty3.1
[cplayer] 
[cplayer] Configuration: ./waf -v configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --disable-cplayer --enable-libmpv-shared
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date cdda debug-build dlopen drm dvbin dvdnav dvdread enca encoding fchmod fnmatch gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler shm sse4-intrinsics standard-gl subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '-'
[cplayer] Set property: vo="opengl-cb" -> 1
[cplayer] Set property: opengl-hwdec-interop="auto" -> -3
[cplayer] Set property: cache-default=15000 -> 1
[cplayer] Set property: cache-backbuffer=15000 -> 1
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?winControls=true&loginFlow=desktop
qml: Stremio Shell version: 4.4.10
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: checking for new version
[10005:10034:0830/213951.148926:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/dimi/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[10005:10034:0830/213951.149093:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -5925
[opengl-cb] GL_VERSION='3.0 Mesa 18.0.5'
[opengl-cb] Detected desktop OpenGL 3.0.
[opengl-cb] GL_VENDOR='Intel Open Source Technology Center'
[opengl-cb] GL_RENDERER='Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) '
[opengl-cb] GL_SHADING_LANGUAGE_VERSION='1.30'
[opengl-cb] Loaded extension GL_ARB_sync.
[opengl-cb] Loaded extension GL_ARB_timer_query.
[opengl-cb] Loaded extension GL_ARB_debug_output.
[opengl-cb] 16 bit texture depth: 16.
[opengl-cb] Reported display depth: R=8, G=8, B=8
[opengl-cb] Testing FBO format 0x805b
[opengl-cb] Create FBO: 16x16 (16x16)
[opengl-cb] Using FBO format 0x805b.
[opengl-cb] No advanced processing required. Enabling dumb mode.
[10005:10034:0830/213951.149110:FATAL:nss_util.cc(203)] nss_error=-5925, os_error=0
#0 0x7f92626983ae <unknown>
#1 0x7f92626a84b7 <unknown>
#2 0x7f9262e7968d <unknown>
#3 0x7f9262e79ba0 <unknown>
#4 0x7f9262da8c75 <unknown>
#5 0x7f9262c958a7 <unknown>
#6 0x7f9262c61b67 <unknown>
#7 0x7f9261de152a <unknown>
#8 0x7f9261de2a46 <unknown>
#9 0x7f9261de4bce <unknown>
#10 0x7f9261fc4207 <unknown>
#11 0x7f92622e621f <unknown>
#12 0x7f926270c5a3 <unknown>
#13 0x7f92626b1b90 <unknown>
#14 0x7f92626b399d <unknown>
#15 0x7f92626b4896 <unknown>
#16 0x7f92626b5210 <unknown>
#17 0x7f92626b0f92 <unknown>
#18 0x7f92626cc9d8 <unknown>
#19 0x7f9261ff91f5 <unknown>
#20 0x7f9261ff962b <unknown>
#21 0x7f92626e45f6 <unknown>
#22 0x7f92626e08ad <unknown>
#23 0x7f925b1526db start_thread
#24 0x7f925f30e88f clone

QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
QSocketNotifier: Invalid socket 11 and type 'Read', disabling...
Segmentation fault (core dumped)

**Comment by vzamanillo** [comment]
Exactly the same for me.

**Comment by Ivshti** [comment]
can you guys try starting with `LD_PRELOAD=/usr/lib/libnss3.so` ?

**Comment by Ivshti** [comment]
alternatively just building http://github.com/stremio/stremio-shell and starting it would work!

**Comment by lelongg** [comment]
Same for me but works with LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so

**Comment by mozgbrasil** [comment]
Thank you, working

![captura de tela de 2018-09-01 21-45-51](https://user-images.githubusercontent.com/17202780/44951072-6e7ab980-ae30-11e8-9c1a-47dee0df366a.png)

**Comment by vitorhugods** [comment]
`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so` did the trick for me.

Thanks =)

**Comment by arijr** [comment]
work for me too. tks =)

**Comment by dimikz** [comment]
+1 Works! Thanks

**Comment by vzamanillo** [comment]
My solution on Ubuntu 18.04, added to desktop file

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Stremio - All You Can Watch
Icon=stremio
Exec=env LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so /home/me/stremio.appimage
StartupNotify=false
StartupWMClass=Stremio
X-BAMFGenerated=true
```

**Comment by benjamimgois** [comment]
Nice ! it worked for me too. The package should be updated. Thanks to all

**Comment by benjamimgois** [comment]
If you are running a 4K display you need to scale the interface with the command
env QT_SCALE_FACTOR=2.5

in the end desktop file should be:

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Stremio - All You Can Watch
Icon=stremio
Exec=env LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so env QT_SCALE_FACTOR=2.5 /home/$USER/Stremio+4.4.10.appimage
StartupNotify=false
StartupWMClass=Stremio
X-BAMFGenerated=true

**Comment by Cris70** [comment]
On openSUSE Tumbleweed the correct command is this:
`LD_PRELOAD=/usr/lib64/libnss3.so /opt/strem.io/Stremio+4.4.10.appimage`
HTH
Cris

**Comment by MarkRijckenberg** [comment]
Same issue on Debian 9.5 (stretch)
Error occurred even with libnss3 Debian package already installed.
Following workaround worked for me too:
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so ./Stremio4.4.10.appimage

**Comment by bilelmoussaoui** [comment]
You guys should try the flatpak package which works out of the box without having to do anything manually ;) https://github.com/bilelmoussaoui/stremio-flatpak

**Comment by endersonmenezes** [comment]
> My solution on Ubuntu 18.04, added to desktop file
> 
> ```
> [Desktop Entry]
> Encoding=UTF-8
> Version=1.0
> Type=Application
> Name=Stremio - All You Can Watch
> Icon=stremio
> Exec=env LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so /home/me/stremio.appimage
> StartupNotify=false
> StartupWMClass=Stremio
> X-BAMFGenerated=true
> ```

This work for me in Ubuntu 18.04 <3
Thx ;)

**Comment by AkKrock** [comment]
Desktop file is a solution. Thanks for sharing.  
Whatnare your suggestions for closing? Could not kill via GUI menubar or window x.

**Comment by gc12345678** [comment]
hi ! thx you all for the LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libnss3.so ./Stremio4.4.10.appimage solution , its working for me on le ubuntu 18.04 , but i need to do it manually each time. i understood that modifying the desktop file is a solution but Im not sure about how can i do this ? and where and how to fine this file to modify it ... please help !

**Comment by Hrrrx** [comment]
thanks, solved it for me too

**Comment by danilocandido** [comment]
To work on Ubuntu 20.04, I've downloaded  http://archive.ubuntu.com/ubuntu/pool/universe/x/x264/libx264-152_0.152.2854+gite9a5903-2_amd64.deb and after install every thing worked

**Comment by sotmir** [comment]
Thanks @danilocandido for your advice, this worked for me in kali linux 2020.4.
