### ISSUE TITLE
Caching location always defaults to D: even if i change it to c: even after update

### ISSUE THREAD

**Issue by Roxra** [Stremio/stremio-bugs#16]
Still broken apparently. I am using windows 10 btw

**Comment by Yinchie** [comment]
Very frustrating issue. Hopefully, this gets fixed soon.
Apparently it keeps defaulting back to the installation drive, in my case C:

**Comment by franzbischoff** [comment]
I have the opposite problem. It always defaults do C: but I want D: ...

Lets switch computers? :)

**Comment by ForSite** [comment]
Years... The same BUG.... change temp to F and after time, back to C, my SSD.

**Comment by TRtomasz** [comment]
If this still happens in stremio 4 let us know so we will reopen it then.
