### ISSUE TITLE
nss_error=-8023 - Opensuse Tumbleweed

### ISSUE THREAD

**Issue by leonardotessaroalves** [Stremio/stremio-bugs#165]
dev@linux-xqeu:/opt/Stremio> ./Stremio+4.4.10.appimage
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 600, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar  7 03:52:26 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.10-1~trusty3.1
[cplayer] 
[cplayer] Configuration: ./waf -v configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --disable-cplayer --enable-libmpv-shared
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date cdda debug-build dlopen drm dvbin dvdnav dvdread enca encoding fchmod fnmatch gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler shm sse4-intrinsics standard-gl subprocess termios tv tv-v4l2 uchardet vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '-'
[cplayer] Set property: vo="opengl-cb" -> 1
[cplayer] Set property: opengl-hwdec-interop="auto" -> -3
[cplayer] Set property: cache-default=15000 -> 1
[cplayer] Set property: cache-backbuffer=15000 -> 1
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?winControls=true&loginFlow=desktop
qml: Stremio Shell version: 4.4.10
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: checking for new version
[2570:2598:1022/204443.252186:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/dev/.pki/nssdb): NSS error code: -8023
[2570:2598:1022/204443.252266:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -8023
[opengl-cb] GL_VERSION='4.6.0 NVIDIA 390.87'
[opengl-cb] Detected desktop OpenGL 4.6.
[opengl-cb] GL_VENDOR='NVIDIA Corporation'
[opengl-cb] GL_RENDERER='GeForce GTX 960/PCIe/SSE2'
[opengl-cb] GL_SHADING_LANGUAGE_VERSION='4.60 NVIDIA'
[opengl-cb] Loaded extension GL_NV_vdpau_interop.
[opengl-cb] 16 bit texture depth: 16.
[opengl-cb] Reported display depth: R=8, G=8, B=8
[opengl-cb] Testing FBO format 0x805b
[opengl-cb] Create FBO: 16x16 (16x16)
[opengl-cb] Using FBO format 0x805b.
[opengl-cb] No advanced processing required. Enabling dumb mode.
[2570:2598:1022/204443.252276:FATAL:nss_util.cc(203)] nss_error=-8023, os_error=0
#0 0x7fc2111673ae <unknown>
#1 0x7fc2111774b7 <unknown>
#2 0x7fc21194868d <unknown>
#3 0x7fc211948ba0 <unknown>
#4 0x7fc211877c75 <unknown>
#5 0x7fc2117648a7 <unknown>
#6 0x7fc211730b67 <unknown>
#7 0x7fc2108b052a <unknown>
#8 0x7fc2108b1a46 <unknown>
#9 0x7fc2108b3bce <unknown>
#10 0x7fc210a93207 <unknown>
#11 0x7fc210db521f <unknown>
#12 0x7fc2111db5a3 <unknown>
#13 0x7fc211180b90 <unknown>
#14 0x7fc21118299d <unknown>
#15 0x7fc211183896 <unknown>
#16 0x7fc211184210 <unknown>
#17 0x7fc21117ff92 <unknown>
#18 0x7fc21119b9d8 <unknown>
#19 0x7fc210ac81f5 <unknown>
#20 0x7fc210ac862b <unknown>
#21 0x7fc2111b35f6 <unknown>
#22 0x7fc2111af8ad <unknown>
#23 0x7fc20a04b554 start_thread
#24 0x7fc20e1e0ccf __GI___clone

QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
QObject::~QObject: Timers cannot be stopped from another thread
Falha de segmentação (imagem do núcleo gravada)

**Comment by TRtomasz** [comment]
Please check deb package which you can find here https://www.reddit.com/r/Stremio/comments/9pjcrk/new_deb_package_for_linux_systems/
