### ISSUE TITLE
Investigate using Flatpak as a distribution package

### ISSUE THREAD

**Issue by bilelmoussaoui** [Stremio/stremio-bugs#167]
Using deb/rpm packages on 2018/2019 is the old school way. Flatpak offers a great way to install the app pretty easily, you ship the right dependencies versions to make sure your app will work no matter which distro the user uses. 

I have already created a Flatpak package based on the appimage package. https://github.com/bilelmoussaoui/stremio-flatpak
I can work on improving it and help to make sure the Linux users experience is much better.

Thanks!

**Comment by probonopd** [comment]
>  Using deb/rpm packages on 2018/2019 is the old school way.

There is also an [AppImage](https://appimage.org/), which is the new school way ;-)

**Comment by bilelmoussaoui** [comment]
I know about AppImage. I'm here to ask for Flatpak support.

**Comment by probonopd** [comment]
Hi @TRtomasz I'd be interested to learn which problems AppImage does not solve for you. Feel free to tell us over at https://github.com/AppImage/AppImageKit/issues/. Thanks.

**Comment by bilelmoussaoui** [comment]
The flatpak package doesn't have any issues as far I can tell, have been using it for a while for now.

**Comment by Rouvenster** [comment]
I followed your step-by-step readme file, but still couldn't build it :-(

`ruben@Ruben-Kubuntu:~$ cd ./stremio-flatpak`

`ruben@Ruben-Kubuntu:~/stremio-flatpak$ flatpak-builder --install stremio com.stremio.Stremio.yml`
                            
`Can't parse 'com.stremio.Stremio.yml': <data>:1:6: Parse error: unexpected identifier app-id', expected value`

Any ideas ? Thanks

**Comment by bilelmoussaoui** [comment]
You must be using an old flatpak-builder version that doesn't support YAML files. You can either try to upgrade flatpak-builder or use it from Flathub. Can you open an issue about this so I can update the Readme with how to build it using Flatpak Builder from Flathub? Otherwise you can use GNOME Builder, open the repo you have cloned and click on Run, you can export the artifact (installable flatpak file) from there if you wish.

**Comment by Rouvenster** [comment]
> Otherwise you can use GNOME Builder

Nah I am totally new on this Flatpak thing and wanted to try it out. 
By the way : `ruben@Ruben-Kubuntu:~$ flatpak --version`

`Flatpak 1.0.1`

Is it an old version ?
Thanks for your quick answer

**Comment by bilelmoussaoui** [comment]
What I would like is the version number of flatpak-builder and not flatpak

**Comment by Rouvenster** [comment]
flatpak-builder 0.10.9

**Comment by bilelmoussaoui** [comment]
I'm having `flatpak-builder 1.0.1` the yaml support was added in `0.10.10`. You should upgrade flatpak-builder first.

**Comment by anassahmed** [comment]
@bilelmoussaoui This is a Flatpak package that runs the AppImage package! :joy:

**Comment by bilelmoussaoui** [comment]
@anassahmed because Stremio guys don't ship any tarballs. Was forced to extract the AppImage to get the app files.

**Comment by anassahmed** [comment]
@bilelmoussaoui The problem is that you ship an old version of Stremio because you depend on the AppImage package.

Can you use the new dep/rpm packages instead?!

**Comment by TRtomasz** [comment]
HI, please check this out https://github.com/Stremio/stremio-shell/issues/109

**Comment by TRtomasz** [comment]
https://flathub.org/apps/details/com.stremio.Stremio
