### ISSUE TITLE
UI/UX: Add cast button in all screens

### ISSUE THREAD

**Issue by sudevschiz** [Stremio/stremio-bugs#169]
As of now, cast button is only available in the main page. User has to connect to the TV before searching for any media. 

Would be great if I start with the search right away and then while I am about to play, I can click the cast button from Top Right. 

YouTube, Netflix - majority of the On demand video services do it this way. Saw it lacking only in Stremio.

Platform : Android 9
Device : OnePlus 6

**Comment by TRtomasz** [comment]
It is not available in latest stremio version.
