### ISSUE TITLE
Stremio black screen on android tv

### ISSUE THREAD

**Issue by dhiman33** [Stremio/stremio-bugs#175]
On android TV only audio and subtitles get loaded .. a black screen or green stripes come in place of video. Even the "Introduction to stremio" tutorial plays only the audio. My device is Xiomi mi tv 4a

**Comment by Ivshti** [comment]
@core1024 @NikolaBorislavovHristov can you check this?

**Comment by dhiman33** [comment]
> @dhiman33 which 4a is it? 32 inches or bigger one? Also how do you open "introduction to Stremio" video? In the app or on some webpage?

@TRtomasz it is the 32 inch variant. Have installed stremio from aptoide tv (version 1.1.1) ... within stremio the introductory video has the name "Stremio-All you can watch- getting started with stremio" ... which when I ran, only the audio played with a black screen... afterwards I have installed some plugins and tried to play contents from piratebay and other addons but for all the cases no video is being shown...it's either a solid black screen or some green stripes

**Comment by dhiman33** [comment]
@TRtomasz I am trying to open all the videos within app only, as I could not find a way to run the contents/videos with an external player/on webpage.

**Comment by TRtomasz** [comment]
@dhiman33 can you install Vimeo or YouTube add-on and  try to play a video from one of these add-ons?

**Comment by dhiman33** [comment]
tried the app version 1.1.4(beta) as well .. same issue on my tv

**Comment by NikolaBorislavovHristov** [comment]
can you try installing **vlc 3.0.6** then play some movie in external player (VLC icon in the top right corner of the player screen)

**Comment by dhiman33** [comment]
@NikolaBorislavovHristov I have vlc 3.0.96 and mxplayer installed ... have tried switching to these players and the video plays! however, I don't see a setting to permanently switch to an external player to play all the content.. is it there somewhere?

**Comment by dhiman33** [comment]
currently I have set the external player as mxplayer ("always" setting) and when I open a video ... I pause it and select the vlc icon to play the movie as a workaround .. would love to get an actual fix though :)

**Comment by dhiman33** [comment]
update... issue persists on stremio version 1.2.0 ... am still following this. Hope developers would also follow.

**Comment by Ivshti** [comment]
We're following this, but for now we're not really sure why this happens. Will keep you updated.

**Comment by maaAnandsheela** [comment]
i can confirm this last working version on this tv is 0.45.1 of stremio. I am having the same issue black screen but audio plays but works fine with vlc as external player

**Comment by TRtomasz** [comment]
Try to change hardware decoding setting in the settings menu

**Comment by TRtomasz** [comment]
@maaAnandsheela  do you also have Xiaomi Mi tv? Which version?

**Comment by maaAnandsheela** [comment]
Yeah I have Mi tv and turning off haedware decoding worked. Thanks.

**Comment by serenaofficial13** [comment]
Hi I have a problem in stremio... There's a screen blackout on 
The Vampire Diaries Season 1 Complete s01 HEVC DD51 Bluury this file but the audio is playing plz help 😢

**Comment by maaAnandsheela** [comment]
Hi @serenaofficial13 .Turning hardware decoding off in settings worked for me.

**Comment by assafmo** [comment]
Turning hardware decoding off in settings of stremio worked for me as well. :rocket:
