### ISSUE TITLE
Drag and drop .torrent file not working

### ISSUE THREAD

**Issue by Aj404K** [Stremio/stremio-bugs#179]
every time I drag and drop a .torrent link/File into stremio it gives me an error on the top left stating :           
`ERR_OPENING_MEDIA`
`Invalid file`

for me, drag and drop is a really great feature but I don't know why it is not working anymore.

![Screenshot (11)](https://user-images.githubusercontent.com/48709514/54587089-4b82b200-49dc-11e9-80fb-a881b0527988.png)

Windows 8.1(64x)
Stremio 4.4.24

**Comment by TRtomasz** [comment]
@Aj404K  Please update stremio to the latest version :-) also could you tell us what is the name of that torrent file?

**Comment by Ivshti** [comment]
Also, is it working with other torrent files?

**Comment by Aj404K** [comment]
@TRtomasz Thank you for your reply. Yes, I even updated it. It is v 4.4.25. They are movies from website called ( 1337x. to) I mean not even a single file is working on it.

**Comment by Aj404K** [comment]
@lvshti No, it is not working on any other file. I mean utorrent is working properly. Whereas if I try to run it on stremio it shows me 'invalid file' error

**Comment by TRtomasz** [comment]
Hi @Aj404K  do you use some vpn service? If not please try one that you can test for free and then check whether you can open torrent files in stremio.
