### ISSUE TITLE
Back/Close button doesn't work 

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#18]
Win OS / Stremio 3.3.4 /

When go to TV Channels section and picked one of FilmOn (not working atm) channel and click play, it shows only cover or screenshot from this channel and that's it. And when i try to exit whatever channel after i click play , app only minimize it self. You can't exit this chanell after this. I got to completley exit stremio which means to turn Stremio off and then start it again if i wan't to use Stremio.

look at screenshot:

![x not working](https://cloud.githubusercontent.com/assets/7681671/11457536/b83e1d86-96ab-11e5-8d60-dde5574429f4.jpg)

Back icon/button where it should be :

![23e456](https://cloud.githubusercontent.com/assets/7681671/11457616/d72ade3a-96ad-11e5-9be6-3ad6875b2fd3.PNG)

**Comment by Ivshti** [comment]
@Draxler can you check now, with the 3.4.1 update?

**Comment by Draxler** [comment]
now it works. this can be closed now. 

btw, Back button would better never the less.. :smile:
