### ISSUE TITLE
strings cutting off on Android app

### ISSUE THREAD

**Issue by wieltar** [Stremio/stremio-bugs#180]
The titles of movies, episodes, categories, casts etc are all cut off to some degree on the Android app on my OnePlus 6 on Android 9

Movies randomly have 1 word missing from the title or when it is 1 word long there isn't a title at all, this is either at the beginning or the end of the string. The same goes for the titles of episodes

Categories are missing the last letter, for example adventure becomes adventur. Casts are either last name only or first name only.

The issue has been around for a really long time and I am surprised nobody has noticed it, I redownload several times and it is slowly driving me insane.

The issue persists on the beta and the "live" version

Maybe an API data fetching/formatting issue?

**Comment by TRtomasz** [comment]
Please provide screenshots

**Comment by wieltar** [comment]
Sorry, pictures are posted here:

http://imgur.com/a/dLec2Ms

**Comment by TRtomasz** [comment]
I don't think this is a bug. Titles are too long to fit labels. That's why posters are displayed also. 
@NikolaBorislavovHristov  Do you think we could change behavior of labels so for long titles text will be moving?

**Comment by wieltar** [comment]
Maybe some lables could be changed in size or made longer/spaced dynamically in a container? Because the genres no matter how long they are, are always cut one letter short and some longer cast names are displayed fully but then other ones that are shorter for some reason are still cut off.

But I don't know the code/API that is used so I wouldn't know what is possible

**Comment by TRtomasz** [comment]
@wieltar have you changed font in the system settings?

**Comment by wieltar** [comment]
@TRtomasz no I have left it at the default size and font

**Comment by wieltar** [comment]
@TRtomasz I just sized it down to the lowest setting I could and it makes some difference with the actors but not with the genres or the episode titles, some are still blank (presumably because they're too long then) etc.

**Comment by TRtomasz** [comment]
Ok, good we have some lead now
