### ISSUE TITLE
Catalog entries not requested when there is no scrollbar

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-bugs#183]
When browsing a catalog in full screen next catalog entries are not requested when there's no scrollbar. If you resize the app to have a scrollbar then the next entries are requested. 
Using windows app Stremio 4.4.25 UI 4.4.47
![](https://media.giphy.com/media/Tf3PGCqEhLWjYd8Ya8/giphy.gif)

**Comment by TRtomasz** [comment]
Hi thanks for your report. We will track it internally for now.
