### ISSUE TITLE
Stremio prevents linux systems from shutdown

### ISSUE THREAD

**Issue by krasi-georgiev** [Stremio/stremio-bugs#185]
Every time when trying to shutdown or logout a linux computer (tried on fedora and ubunut) I get a message - Stremio is preventing the shutdown.

using
https://dl.strem.io/linux/v4.4.25/stremio_4.4.25-1_amd64.deb

**Comment by krasi-georgiev** [comment]
ping to the maintainers.

**Comment by krasi-georgiev** [comment]
ping

**Comment by Ivshti** [comment]
@core1024 any ideas?

also i'll move this issue to https://github.com/stremio/stremio-shell

**Comment by gmelodie** [comment]
@Ivshti Any updates on this? I wasn't able to find this issue on https://github.com/stremio/stremio-shell

**Comment by Ivshti** [comment]
@gmelodie it may be fixed after https://github.com/Stremio/stremio-shell/pull/173 was merged

any chance you can build from source and check?

**Comment by gmelodie** [comment]
@Ivshti sure, could you point me to what exactly I should build? Kinda confused with `stremio-shell`, `stremio-core` etc.

**Comment by Ivshti** [comment]
@gmelodie stremio-shell is the desktop app repo
