### ISSUE TITLE
Cannot install RPM on Fedora 30: nothing provides libQt5Quick.so.5(Qt_5.11.3_PRIVATE_API)(64bit)

### ISSUE THREAD

**Issue by greg0ire** [Stremio/stremio-bugs#188]
Here is my failed attempt at installing stremio on Fedora 30:

```
sudo dnf install /tmp/stremio-4.4.52-1.fc29.x86_64.rpm
Last metadata expiration check: 0:00:54 ago on Tue 21 May 2019 07:55:13 PM CEST.
Error: 
 Problem: conflicting requests
  - nothing provides libQt5Quick.so.5(Qt_5.11.3_PRIVATE_API)(64bit) needed by stremio-4.4.52-1.fc29.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

Maybe that's to be expected given the file ends with `fc29`?

However, that lib seems to be on my system:

```
locate libQt5Quick.so
/usr/lib64/libQt5Quick.so.5
/usr/lib64/libQt5Quick.so.5.11
/usr/lib64/libQt5Quick.so.5.11.3
```
Not sure why it isn't detected…

**Comment by SadWii** [comment]
Same issue, tried to reinstall libraries, no luck.

**Comment by TRtomasz** [comment]
@greg0ire  @SadWii  please check this comment https://github.com/Stremio/stremio-shell/issues/87#issuecomment-495189279

**Comment by greg0ire** [comment]
Thanks but I managed to make popcorntime work again on my machine in the meantime, and this script requires building Stremio rather than merely installing a pre-built package, so I guess I won't retry stremio unless it's super easy to install (with an RPM package, for instance). And since you guys are planning to drop support for Fedora, this is starting to look unlikely…

**Comment by sheepdestroyer** [comment]
Fedora user, same pb on fedora 30 ; if you guys are indeed planning on dropping fedora support, would you consider providing a flatpack?

**Comment by the-cave-dweller** [comment]
same problem here
