### ISSUE TITLE
Cant change progress while streaming to TV

### ISSUE THREAD

**Issue by joaomcarlos** [Stremio/stremio-bugs#191]
Hi,

When pressing somewhere other than the start on the progress bar I can view the content on that timestamp in my computer but I cant while streaming to the TV.

I even tried stop streaming, push it forward, then start streaming again and all it does is restart at the beginning.

Is there a way around this problem? Perhaps something to install on my TV?

Thanks

**Comment by Ivshti** [comment]
Are you streaming directly to the TV or through Chromecast?

Streaming to TVs directly is deprecated and won't supported anymore: https://blog.stremio.com/dropping-dlna-upnp-support/

**Comment by danieltr3s** [comment]
I'm casting through Chromecast (from windows PC) and I have the same issue.
Changing progress while casting makes the playback to go back to zero on the PC although you can see that the chromecast buffered to the right position but kept the frame freezed in that position (no playback) while the progress of the playback on the PC shows as it started from 00:00:00. The only to get the video to play again while casting is to manually move the cursor back to the begining.

**Comment by TRtomasz** [comment]
Closing, as this seems to be working now.
