### ISSUE TITLE
Trakt won't successfully authenticate

### ISSUE THREAD

**Issue by fredsalesjr** [Stremio/stremio-bugs#192]
On Windows 10 using Stremio 4.4.77, Trakt won't successfully authenticate to sync watched movies/TV shows. 
![stremio_Kk1eg42WjU](https://user-images.githubusercontent.com/15468834/63308996-78a8f880-c2cb-11e9-81e9-8c5913341b64.png)

**Comment by TRtomasz** [comment]
Try to authenticated 2nd time. Second try should be successful

**Comment by fredsalesjr** [comment]
Trying to authenticate a 2nd appears to work, but it does not sync watched movies or shows with Trakt.

![stremio_cuVFY4mYQM](https://user-images.githubusercontent.com/15468834/63375679-9f663e00-c362-11e9-95f2-6c86e061ef21.png)
![stremio_feUWDG37xR](https://user-images.githubusercontent.com/15468834/63375689-a2f9c500-c362-11e9-8843-1fa52ade0c21.png)
![chrome_UMKXBTvxIF](https://user-images.githubusercontent.com/15468834/63375745-bad14900-c362-11e9-8e6c-286c18b0dca8.png)

**Comment by Evilways** [comment]
same as Fred, any idea for fix?

**Comment by TRtomasz** [comment]
Hi,
Recently we have fixed a lot of issues regarding trakt synchronization, it should be working fine now. Please let us know if you still have problems with it, so i can reopen this issue then.

**Comment by michalss** [comment]
same trak does not work :(
