### ISSUE TITLE
Cannot login to stremio in linux

### ISSUE THREAD

**Issue by m49761** [Stremio/stremio-bugs#194]
OS - Linux Mint 19.2
Installation from stremio_4.4.52-1_amd64.deb

Upon login it shows error text asking to agree to terms and conditions but there isnt an option to do so
Please find attached screenshot
![Screenshot from 2019-09-12 01-43-21](https://user-images.githubusercontent.com/12169631/64731948-c21de980-d4ff-11e9-9749-53feec248afb.png)

**Comment by Ivshti** [comment]
should be fixed now, thanks for reporting
