### ISSUE TITLE
Streaming service cannot GET /

### ISSUE THREAD

**Issue by stoyanov7** [Stremio/stremio-bugs#196]
![image](https://user-images.githubusercontent.com/23521228/67405646-b8d37280-f5bd-11e9-9814-60ff416a8bd4.png)

When I try to open this URL it get me this error: `Cannot GET /`
Used browsers: Firefox v.71.0b3, Chrome v.77.0.3865.120

**Comment by gunzordonblat** [comment]
Cannot find an answer to this myself. Something to do with file placement for the Stremio server though.... Thought it would be easy to fix, but it's not proved to be for me. I live in hope that someone knows and will answer in "the christmas spirit" :+1 : )

**Comment by TRtomasz** [comment]
thats not an error everything is fine.
