### ISSUE TITLE
Dutch subtitle issue

### ISSUE THREAD

**Issue by XwhitewidowX** [Stremio/stremio-bugs#197]
Dutch subtitles are not loading automatically when starting a movie/show.

**Comment by XwhitewidowX** [comment]
Sorry if i didn’t explain it correctly, but they’re not even loading automatically if the dutch subtitles are available.

**Comment by TRtomasz** [comment]
@XwhitewidowX i belive this error happens in Android application?

**Comment by XwhitewidowX** [comment]
Tried it on windows to confirm and it works normally, so it should be an error within the android application.

**Comment by XwhitewidowX** [comment]
This issue has been fixed. Tested on my Nvidia Shield TV 2017.

**Comment by TRtomasz** [comment]
Yes, indeed it was. Sorry i totally forgot about letting you know after deploying new version. Thanks for keeping track!
