### ISSUE TITLE
Volume not working on Android 10

### ISSUE THREAD

**Issue by DiogoSilva48** [Stremio/stremio-bugs#198]
On Android 10 Pixel Experience my device volume doesn't change Stremio's volume, just stays the same volume all the time even if my volume is at 0 and it's quite loud. Wasn't happening on Android Pie and isn't happening with any other app.

**Comment by TRtomasz** [comment]
Hi, stremio doesn't have any additional volume controler. It uses system volume setting. Does it happen only while playing a video? Or maybe when you change volume outside the player it also isn't noticed by player?

**Comment by DiogoSilva48** [comment]
Hi, it only happens while using the Stremio video player, if I use external player doesn't happen, it's weird. It's like Stremio it's ignoring system volume and using it's own, I tried a lot of other apps and it's only happening on Stremio.

**Comment by TRtomasz** [comment]
Couldn't reproduce this on on Pixel 3a with latest Android. But this chould be related to the fact you are using some custom rom.

**Comment by DiogoSilva48** [comment]
Yes, you're right, anyway I bought a new phone and I don't have this problem anymore, sorry for the trouble, thanks for the answer.
