### ISSUE TITLE
Navigation with arrow keys issues in version 1.2.11

### ISSUE THREAD

**Issue by Kageblakely** [Stremio/stremio-bugs#199]
Hi

I had been using Stremio version 1.2.11 on the Android TV without any major issues.

I installed veersion 1.2.16 to try it out. It also works but it seems that a feature to use the "arrow keys" with it (without a mouse or touchscreen) got disabled.

While I'm watching a video, I was used to pause it and use the "up arrow key" to go to the upper menu and change the settings like the subtitles. Now with version 1.2.16 I can no longer access the upper menu with the arrow keys. I have no way to access it without a mouse or touchscreen.

Is someone else experincing this? or there is some other way to access the upper menu with only the keys (remember that Android TV has touchscreen or mouse).

Thanks

**Comment by NikolaBorislavovHristov** [comment]
Hi @Kageblakely 
Thanks for the report.
I will check this and get back to you as soon as possible.

**Comment by Greggaz** [comment]
I'm also having this issue!

**Comment by huatken** [comment]
Same issue carried to the latest 1.2.19 version. The arrow movement goes to some hidden stops. I find pressing the arrow keys randomly somehow makes it reappear. It's getting annoying. Please can someone help in fixing this?

**Comment by Greggaz** [comment]
Some additional info for the Devs as I'm having the same issue as the OP:

I'm currently running a Nvidia Shield
Currently running version 8.0
(32.5.205.75)
Model number: P2897
Version: 9
Patch levels: 5th July 2019

**Comment by lisoki** [comment]
Hi

Today I tried version 1.2.21 and seems that the problem was fixed.
I tried it on my Android TV, and now, when I'm looking at the video, I can pause and move to the subtitles with the arrow keys and return to the video after that.

Thanks
