### ISSUE TITLE
Larger movie files turned app off after few minutes

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#2]
Win OS 

Larger movie files culldn't be played on STREM.IO , it stop playing and turned STREMIO comletley off after few minutes of playing. I watched a movie with size of 18GB and it streams perfectley but after few minutes Stremio turned off it self completley. I think it could have something to do with PCs cache (folder). When app rich the limit it clears the cache (at least this is what i think of when this happened). I had Stremio cache set on maximum but i think PC folder have size limits or something. Maybe Temp folder doesn't have cache size limits. But that again, issue could be something completley defferent. The fact is Stremio have issues with larger files. I try every cache setting on Stremio and it didn't work, after few minutes of playing Stremio turned off it self.. Btw. i used Magnet link to get this movie. Connection was realy good, so this issue have nothing to do with net speed or something like that.

**Comment by TRtomasz** [comment]
Closing this. Stremio 3 is no longer supported.
