### ISSUE TITLE
Issues with disappearing movies

### ISSUE THREAD

**Issue by nightcorereality** [Stremio/stremio-bugs#20]
I am experiencing issues with stremio, where movies that I watch are gone from the Discover list, i do not know how to access the movies and some movies that i didnt watch are no where to be found, such as Fantastic 4, i saw it in my discover then it disappeared and i couldn't find it when i searched. This also means that the search bar needs to be improved becauuse the new movies does not come up when searched. Also when i reinstall the program, a lot of the new movies such as ant man disappears and i cant find them no matter what. Please fix this ASAP

**Comment by Ivshti** [comment]
What about using the Search? movies in Discover are determined on what's trending, and it's probably updated in your case.

If you really want to always see a movie you should add it to your library

**Comment by nightcorereality** [comment]
Unfortunately, the new movies can not be searched up i cant find the new
movies

**Comment by Ivshti** [comment]
You're right - we're looking into it

**Comment by Draxler** [comment]
Here are another 2 titles which were present on Stremio before but now both are gone;
TV serie > LOST < is gone completley and can't be found. 
Also last x-files movie gone from Stremio completly ;  
The X Files: I Want to Believe (2008)

**Comment by nightcorereality** [comment]
the thing is, on some movies, such as antman, if u watch it once, u dont
have it in ur discovery or search bar anymore. And if the library is
cleared all the movies are unable to be found, same thing goes for scorch
trials and fantastic 4s.

**Comment by Ivshti** [comment]
@nightcorereality I found the cause of the issue, it was using an obsolete property for counting popularity of movies / series.

In about 2 hours (after all caches flush) the issue should be completely resolved

Thanks for helping!

Please report if there are more issues like that

**Comment by nightcorereality** [comment]
ok thank you so much. Glad that i helped.
