### ISSUE TITLE
Dutch subtitle issue

### ISSUE THREAD

**Issue by XwhitewidowX** [Stremio/stremio-bugs#200]
Dutch subtitles are not loading automatically when starting a movie/show. They do work if i choose a dutch subtitle manually. This issue has been the case with every stremio version i installed in the past (on android). I did set dutch subtitles as a default in settings.

Tried it on windows recently and it seems to work fine there, so the issue is within the android application.

**Comment by TRtomasz** [comment]
Closing it as you have already created identical issue

**Comment by XwhitewidowX** [comment]
Yes, but you closed it while it should be open.
