### ISSUE TITLE
Some youtube channels return Invalid HTTP status code

### ISSUE THREAD

**Issue by BeatLink** [Stremio/stremio-bugs#201]
Certain youtube channels such as PolyMatter, Ordinary Things and LICHTENSTEIN will return the following message when trying to load: 

Removing and adding the channels from my library, reinstalling stremio including clearing the configuration files from the user folder, as well as reinstalling the addon, does not resolve the issue

Error Fetching Item Data
Invalid HTTP status code

Other channels will work fine however. 
Im running Stremio 4.4.52 deb on Linux mint 19.2. The youtube addon is the official one, version 1.30.5

**Comment by BeatLink** [comment]
Any updates on this?

**Comment by Ivshti** [comment]
which country are you trying to access the channels from?

Did you try a VPN to another country?

**Comment by BeatLink** [comment]
Im from Jamaica. Not using VPNs currently. They normally work for me on youtube itself and in other applications

**Comment by TRtomasz** [comment]
@Ivshti  it is related to this https://github.com/Stremio/stremio-channels/issues/4

**Comment by BeatLink** [comment]
Are there any updates on this? I dont have access to a VPN to test this

**Comment by maxoku** [comment]
I have the same problem. Is there a way to fix it?

**Comment by krapgras** [comment]
Seems to be same issue as #285

**Comment by maxoku** [comment]
> Seems to be same issue as #285

Maybe, but my issue was for the movies and tv series though.

**Comment by mghadam** [comment]
I have same issue accessing [YummyGastronomy](https://www.youtube.com/c/YummyGastronomy) youtube channel

![image](https://user-images.githubusercontent.com/10244293/184605759-40b41475-5528-4d1f-8383-46e52ea6424d.png)

This is while some other channels such as [TwinkieMan](https://www.youtube.com/c/TwinkieMan) work fine

![image](https://user-images.githubusercontent.com/10244293/184606068-6d32d0ec-8b23-4f98-a088-7ac591978804.png)
