### ISSUE TITLE
The video still stalls even after it has buffered all of it.

### ISSUE THREAD

**Issue by NitishNaineni** [Stremio/stremio-bugs#204]
Generally when i watch i leave video running when i get busy in between watching the video so that it buffers and get back to it later.
but i have had this weird issue where stremio has buffered all of the video but still stalls and never resumes again till i close and re-stream the video. 

Please do tell if i can do something to avoid this problem.

**Comment by TRtomasz** [comment]
Hi is it windows, macos or linux? Also how do you know that movie is fully buffered? Please also explain what do you mean it stalls? Please send screenshots if possible.

**Comment by TRtomasz** [comment]
Closing the issue due to lack of response.
