### ISSUE TITLE
Struck on initialization screen

### ISSUE THREAD

**Issue by CrashxZ** [Stremio/stremio-bugs#205]
Stremio loads up fine the first time, but it gets stuck on the initialization screen with the stremio logo blinking after a restart/shutdown.

Uninstalling and Reinstalling fixes the problem.

**Comment by CrashxZ** [comment]
![image](https://user-images.githubusercontent.com/17525982/70546164-56e8bf80-1ba1-11ea-92da-653b19c1758a.png)

**Comment by TRtomasz** [comment]
Hi, can you tell us when does it start to happen? Does it happen like every day or after some time?

**Comment by CrashxZ** [comment]
Hi,
It usually happens once a day.
Can you show me where the container initializes the angular app? It may be a problem only in my system.

**Comment by TRtomasz** [comment]
@CrashxZ  You can try to run app with `--remote-debugging-port=<port_number>` and then open chrome dev tools on `localhost:<port_number>` to debug this

**Comment by CrashxZ** [comment]
I will try to come up with what's causing the problem.

**Comment by CrashxZ** [comment]
I figured it out, it was an issue with the nvidia drivers , an update fixed it. 
Thank you !
