### ISSUE TITLE
On android 10 pause

### ISSUE THREAD

**Issue by hvalee** [Stremio/stremio-bugs#206]
Issue:
Player not stopping on application onPause.

Solution:
Override activity onPause and pause the player loop

On samsung A50, android 10

**Comment by TRtomasz** [comment]
It's not a bug, Perhaps you are talking about background player feature that can be used to play podcasts or music in the background, simply pause video before going back to other screen.

**Comment by hvalee** [comment]
And why not id streams so only keep running in background when its a
podcast or music?

A quinta, 2/01/2020, 10:49, Tomasz <notifications@github.com> escreveu:
