### ISSUE TITLE
No QUIT menu action in app

### ISSUE THREAD

**Issue by megatux** [Stremio/stremio-bugs#207]
I was unable to find a visual QUIT action for the app. I only found it from the desktop notification area, but lot of Linux Desktop Environments deprecated these app menus a long time ago. Also, other window managers like I3 don't support it out-of-the-box.

**Comment by megatux** [comment]
Nice to see the related Quit function implemented. What about the UI now?
I hate to have to go to the console to kill the processes manually.

**Comment by Zeioth** [comment]
I don't mean to be a jerk, but how does it take 6 months to add an 'exit' button? This should be critical.

**Comment by Ivshti** [comment]
Sorry, the reason this is so long is because it needed to be implemented in github.com/stremio/stremio-shell: https://github.com/Stremio/stremio-shell/commit/da49bfdd0c5aae94f1cd9cc31091fa74d19b8d89 and then rolled out as a full build

our cycle for full build releases (that replace the shell) is quite slow cause we rarely need to update the shell - we make 2-3 shell releases per year and we wait until enough people run them to enable UI features that depend on them

as for priorities - we don't get that many requests for this so it's low prio

**Comment by megatux** [comment]
Thanks for the explanation, it's good to see it is almost implemented. Will ping you late in January otherwise :grinning:

**Comment by Zeioth** [comment]
Ping

**Comment by TRtomasz** [comment]
Quit option has been added and is available from settings
![image](https://user-images.githubusercontent.com/40594253/109868594-b8da8c80-7c5f-11eb-9c03-9c8328fdd34c.png)

**Comment by megatux** [comment]
IMHO, this is terrible UX! Could we reopen and talk about this?

**Comment by Ivshti** [comment]
Not sure what you're refering to specifically, but there are very valid reasons why the app stays in the background - for example, series notifications, autoupdater, scanning local files (if enabled). This works fine with the tray on Mac/Windows, and it's not worth it for us to make special cases for Linux considering less than 1% of our user base is using it.

**Comment by megatux** [comment]
> Not sure what you're refering to specifically
I'm saying that the Quit action is a common action and unrelated to the Settings panel. Not very discoverable in there.
A good place could be in as the last option in the main dropdown menu: 
![2021-03-19-123640_418x652_scrot](https://user-images.githubusercontent.com/850020/111805562-e8200900-88af-11eb-93fb-92100f9a21a1.png)

BTW, how do you get the OS stats? are you tracking it or is a guess? 1% for Linux seems low.

**Comment by Ivshti** [comment]
Stats are retrieved through network traffic to core addons, and are very reliable. Despite many of our team being linux users including myself, we cannot afford to spend a lot of time on it given the low percentage of our user base that uses it.

Having Quit there would be nice, we'll consider it

**Comment by Zeioth** [comment]
+1, anyone would expect it to be there. Thank you for implementing this feature.

**Comment by piregg** [comment]
Please please please move this to the main menu. This has been driving me crazy for months and I only just came across this thread searching for a solution. It works now that I know where it is but I honestly would never have thought to look there.

**Comment by TRtomasz** [comment]
@piregg  we have no plans to move the button but if you select this option in the settings 
![image](https://user-images.githubusercontent.com/40594253/227148940-fddf4e09-90f3-4f1a-8c3a-2b824d530027.png)
Stremio will close when you click X window button.

**Comment by piregg** [comment]
@TRtomasz I'm using stremio in Linux, full screen, with a keyboard/controller. I'm not sure this option is available? If it was, would it help me?
