### ISSUE TITLE
No Streams available

### ISSUE THREAD

**Issue by Draxler** [Stremio/stremio-bugs#21]
Win OS / Stremio 3.4.1

After last update there are a lot of movie titles wich doesn't have available streams anymore. These movies was available before on Stremio. Also these movies are available on all major trackers and have all good health (lot of seeders). These are not some  forgotten movie titles, they are popular movies..

Here are some of these movies;

![1a](https://cloud.githubusercontent.com/assets/7681671/11549484/bcdf80e2-9966-11e5-8d52-fc3af01fe5c6.PNG)

![1b](https://cloud.githubusercontent.com/assets/7681671/11549493/ca47ed5a-9966-11e5-819e-ca18ead2d94e.PNG)

![1c](https://cloud.githubusercontent.com/assets/7681671/11549497/d5326272-9966-11e5-9949-d2edbd58c199.PNG)

![1d](https://cloud.githubusercontent.com/assets/7681671/11549505/debda2ac-9966-11e5-8e61-84fa48a2c1d1.PNG)

![1e](https://cloud.githubusercontent.com/assets/7681671/11549513/eb1771c2-9966-11e5-9e6b-c8e03510acfb.PNG)

![1f](https://cloud.githubusercontent.com/assets/7681671/11549521/fa0d3540-9966-11e5-804b-c14f02eda67b.PNG)

**Comment by vipconsult** [comment]
same here, This is major problem

**Comment by Ivshti** [comment]
As Stremio does not provide these movies directly, but through the add-ons system, I'm closing this

**Comment by vipconsult** [comment]
no way to add more trackers ? It was much better few releases before so something must have changes since than. 50% of all series I am trying to watch lately show no streams available where most big torrent trackers have quite a few seeders.

**Comment by Ivshti** [comment]
Of course there is, anyone can build add-ons. The documentation is not ideal at the moment, but I'm working on it (https://github.com/Ivshti/stremio-addons)

**Comment by JCB9090** [comment]
@vipconsult https://github.com/JCB9090/juan-carlos-torrents-2 submit issues here
