### ISSUE TITLE
Stuttering on 1080p, please advise.

### ISSUE THREAD

**Issue by imurreflection** [Stremio/stremio-bugs#213]
Hello friends, I really need your help. Initially, on my TV, Stremio streams play in a very tiny screen on the extreme left top of the player and absolutely nothing can be seen though subtitles played in full screen.  I was suggested to turn off hardware acceleration and it started working. However, it works fine only on 720p, whenever I click on any 1080p or higher resolution, link plays but there is lot of stuttering. The same link plays fine on any external player like Archos or MX. Please advise what should I do to get 1080p link working without stuttering. Could you also please let me know which native video player is used by Stremio. I am using the latest version 1.2.21. Thanks in advance. I love Stremio and this great community.

**Comment by Ivshti** [comment]
We use libvlc internally which isn't perfect but gets the job done


Some questions that might help us:
* Which version of android is the TV running?
* can you try Play in external player with VLC and let us know whether it works
* same, but with MPV
* try another 1080p stream (different encoding); the issue could be specific to a particular encoding, e.g. HEVC

**Comment by TRtomasz** [comment]
Please also tell us what TV you have

**Comment by imurreflection** [comment]
Thank you for responding and I apologize for not being specific earlier. Here are the answers.

1) Android version is 8
2) I tried VLC and it does not have any stuttering issue. 
3) MPV player also works fine
4) I tried different 1080p Streams from all movie addons using VLC and MPV player and none of them has this issue.

5) TRtomasz bro - TV is MITV 4 55 inches 4k

Please let me know if you need further information.

**Comment by imurreflection** [comment]
Can I please have an update?

**Comment by TRtomasz** [comment]
Can you update your TV to Android TV 9?

**Comment by imurreflection** [comment]
No Mate....This TV will never get updated to Android 9

**Comment by imurreflection** [comment]
Is there any update to this?

**Comment by imurreflection** [comment]
Hey please release the updated verion of Stremio with updated libvlc. May be that will resolve the issue

**Comment by imurreflection** [comment]
Thank you so much bro

**Comment by imurreflection** [comment]
Hi, may I know when can we expect the new version for Android with updated libvlc.

**Comment by Ivshti** [comment]
Within a few weeks, as we're working on finishing touches related to the addon system. @TRtomasz perhaps we can post a link to an early build here so that @imurreflection can test?

**Comment by TRtomasz** [comment]
@imurreflection  can you tell us on what device you want to test it? So, we can give you link the proper app version.

**Comment by imurreflection** [comment]
I am on MITV 4 55inch and current version 1.2.22 works fine on it except the problem as mentioned. Kindly send me the test version here and I will let you know if it works without stuttering on 1080p. Many thanks and regards.

**Comment by imurreflection** [comment]
Hi @TRtomasz, can you please provide me the test version?

**Comment by TRtomasz** [comment]
@imurreflection  sure, you can download it from here https://slack-files.com/T08Q9N48G-F016XU37VL5-d111e569b0

**Comment by imurreflection** [comment]
Dear ivshti and TRtomasz.

Thank you so much for providing the test version. Please find my observation"s as below

1) There is still stuttering issue and new version has no impact on the prolonged issue.
2) File size is 161 mb which takes time to load as most of the Android TV has less RAM and mine is not an exception. I guess this is because of test build and we need to wait for beta or final version
3) In previous version namely 1.2.22, the app can be fully navigated without the use of external mouse but this test version has some limitations like selecting external player, subtitles etc

I know since this is a test version, it may have bugs but one thing which is missing is "Subtitle Positioning.' It's an earnest request to ivshti and TRtomasz bro to please include this in final version. I know since my TV is on android version 8 and it will never get updated to android 9, the stuttering issue may never get resolved and I will have to resort to 720p but still, it's okay as long as we have "Subtitles Positioning' feature and that app is not relying on external mouse for any feature/s.

Please let me know if you need more information.

Warm regards.

**Comment by TRtomasz** [comment]
Hi,
I found that your tv has an arm processor so here is version that is dedicated to your TV
https://slack-files.com/T08Q9N48G-F0171PC1CHH-988c3bde66 it is smaller, around 42 MB
Also please check now if turning off hardware decoding helps for movies other than 720p

**Comment by Ivshti** [comment]
Regarding subtitle positioning, would up/down only satisfy your needs?

**Comment by imurreflection** [comment]
Definitely yes, if it goes down the video and doesn't overlap.

**Comment by imurreflection** [comment]
- @TRtomasz Bro, unfortunately, this version is not compatible with my TV. I uninstalled the previous version and tried to install this version but it simply says "'App not installed." On further digging, I found the processor info on their official site and took a screenshot. Please see if this can be helpful. Also, kindly let me know if I can get the link to base test version link with all test builds and I can manually install to see which one is working.

**Comment by imurreflection** [comment]
> Hi,
> I found that your tv has an arm processor so here is version that is dedicated to your TV
> https://slack-files.com/T08Q9N48G-F0171PC1CHH-988c3bde66 it is smaller, around 42 MB
> Also please check now if turning off hardware decoding helps for movies other than 720p
> Also please try playing something with hardware decoding now maybe it is fixed in this VLC version

@TRtomasz Bro, unfortunately, this version is not compatible with my TV. I uninstalled the previous version and tried to install this version but it simply says "'App not installed." On further digging, I found the processor info on their official site and took a screenshot. Please see if this can be helpful. Also, kindly let me know if I can get the link to base test version link with all test builds and I can manually install to see which one is working.
![Pinfo](https://user-images.githubusercontent.com/30263396/87404098-5141d500-c5db-11ea-9d48-743f3c7b454f.jpg)

**Comment by imurreflection** [comment]
Hi TRtomasz mate, can you please provide the test build based on my reply please.

**Comment by TRtomasz** [comment]
@imurreflection  sorry for the delay we have discovered another issue, once we have new build ready i will send you a link to it.

**Comment by imurreflection** [comment]
No worries bro. I will wait for your response.

**Comment by imurreflection** [comment]
Hi TRtomasz bro, is there any update to this? Please let me know.

**Comment by TRtomasz** [comment]
Hi, @imurreflection  sorry for the delay here is the updated version https://slack-files.com/T08Q9N48G-F017TE4TN4D-e525371996

**Comment by imurreflection** [comment]
Hi TRtomasz bro. Thank you so much for the updated version. Unfortunately, it didn't have any desired effect as stuttering is still there. After enabling Hardware Acceleration, there is no picture though can see subtitles and stuttering continues once the same is disabled. I guess, this is the limitation with my TV as it cannot be upgraded to Android 9. I have no further request and I really thank you and Ivshti bro for trying to help the lost cause.
Dear Ivshti bro, just one request to please including subtitles positioning on final release so that o can enjoy this wonderful application on my official android tv box running Android 9.

Once again, I thank you both for your efforts. Warm regards.

**Comment by imurreflection** [comment]
Dear Ivshti mate. It appears that final version has been released. However, it was disappointing to see that subtitles positioning feature was not provided. May I request you to let me know if this feature is even possible or not. No disregard but I have been requesting for this feature for almost a year now. Please let me know if this is possible or not and I will never trouble you. Regards.

**Comment by Ivshti** [comment]
It's possible - we're looking into it, please be patient.

**Comment by imurreflection** [comment]
Thank you sir. I can see light at the end of tunnel. Please keep me posted.

**Comment by namanyayg** [comment]
Exact same TV and exact same issue. No stuttering for 720p but low framerate for 1080p. @imurreflection what are you using now to enjoy 1080p media? Would you recommend an alternative media player?

**Comment by imurreflection** [comment]
I m using KM9 Pro and I updated it to Android 10. No stuttering issues there but subtitles positioning is my concern now. The box has 4 gb ram and 32 gb rom.

**Comment by imurreflection** [comment]
Dear Ivshti, is there any update to this request?

**Comment by Ivshti** [comment]
@nklhrstv and @TRtomasz can answer that, I think we're working on it

**Comment by imurreflection** [comment]
Okay mate..I will ask again after a month.

**Comment by nklhrstv** [comment]
In the next version of the android app, you will be able to configure subtitles vertical position.

**Comment by imurreflection** [comment]
Thank you for this update. I shall wait for the new version.

**Comment by imurreflection** [comment]
Hi @nklhrstv, do we have any test build I can check and report back. Alternatively,can you let me know when can we expect new version with this feature please?

**Comment by nklhrstv** [comment]
@imurreflection I guess i will have one by the end of the day.

**Comment by imurreflection** [comment]
Thanks Mate. May I request you to please provide the same once you have it.

**Comment by nklhrstv** [comment]
its ready for testing. pm me

**Comment by imurreflection** [comment]
Hi...am here now..please provide

**Comment by imurreflection** [comment]
Dear nklhrstv mate. Please provide the test version here or on my email imurreflection@gmail.com. I don't know how to PM you here in GitHub.

**Comment by imurreflection** [comment]
Dear TRtomasz bro. Can you please provide me this  test build as it seems that nklhrstv mate is occupied.

**Comment by nklhrstv** [comment]
@imurreflection ive send you a test build

**Comment by imurreflection** [comment]
Hi @nklhrstv ..Thank you so much for this and it works absolutely fine and both size and vertical placements are doing wonders. Unfortunately, this version crashes both on my android TV box running Android version 7.1 and on my MITV 55 inch running Android 7.1. Can you please provide me test build for these respective platforms?

**Comment by imurreflection** [comment]
@nklhrstv Just for your information, this is the corresponding version shared by @TRtomasz bro
https://slack-files.com/T08Q9N48G-F017TE4TN4D-e525371996

**Comment by imurreflection** [comment]
Dear @nklhrstv. Thank you so much for TV compatible version. This is working just fine and with inclusion of this feature, this now makes Stremio as one stop shop for my viewing needs.

I would also like to extend my sincere gratitude to dear @ivshti @TRtomasz  bro for extending their complete support and patience throughout this long journey which finally ends happily. Friends, I really appreciate your constant support on this.

Warm regards,
Sanjeev

**Comment by nklhrstv** [comment]
@imurreflection I'm glad we helped you
