### ISSUE TITLE
Stremio full my disk

### ISSUE THREAD

**Issue by skarmiglione** [Stremio/stremio-bugs#215]
Hello, i am using linux mint and i am giving to / a partition with 120gb it get full when i am looking a serie but the app dont mention it, then all the system get stucked because of that, normally this partition have about 60gb but if i see 2 seanson from a serie it get full, maybe can be a good idea if you put a message when it is getting full and a button to erase the oldest videos in the /tmp ?

sometimes i forget this happen, and i end about to format my operating system, then i remember it should be stremio fault, later of an hour(i dont use it all the days to know always that happen then i forget it).

**Comment by TRtomasz** [comment]
Hi,
What are you caching settings? Can you send us a picture? Cache should be cleared once it  reaches maximum size.

**Comment by TRtomasz** [comment]
Due to lack of response i'm closing this ticket for now
