### ISSUE TITLE
Stremio 4.4 stuck after loading screen (won't start)

### ISSUE THREAD

**Issue by Franklyn-S** [Stremio/stremio-bugs#217]
Stremio 4.4 stuck after loading screen on ubuntu 18.04.4

![image](https://user-images.githubusercontent.com/28740153/75623592-391c6c80-5b8a-11ea-8671-56232dcb9da4.png)

**Comment by TRtomasz** [comment]
Most common reason for such behavior is an issue with graphic card drivers. Start Stremio in terminal and plase paste here output.

**Comment by TRtomasz** [comment]
Closing due to lack of response. Feel free to open it whenever you will have needed data.
