### ISSUE TITLE
Stremio on Amazon Fire TV Stick

### ISSUE THREAD

**Issue by KylePr0** [Stremio/stremio-bugs#218]
Hey

I use Stremio on Amazon Fire TV Stick, please could you add a way for us to dismiss a movie/tv show from the continue to watch list because we can't press on the three dots to get the menu to pop up to dismiss it.

How you guys can solve this:

You could simply add functionality to long press it to get the options up or enable us to press the three lines on our fire tv stick remote to bring it up.

Thank you!

P.S

I love what you guys have created.

**Comment by TRtomasz** [comment]
Firestick uses Android TV os. As our app has never been designed to work on Android TV OS some user interface elements might not work out of the box. To dismiss element from continue watching you can sideload mouse app and use it to click three dots, then menu will be displayed and you will be able to remove element from the list
