### ISSUE TITLE
Subtitles timing sync on Chromecast is reversed

### ISSUE THREAD

**Issue by assafmo** [Stremio/stremio-bugs#219]
In the desktop up and in the android mobile app, while watch a video locally timing subtitles works great (`G` and `H`), but when casting (Chromecast 3) it's reversed. Pressing `H` takes the subtitles back by 0.25sec instead of ahead. Respectively pressing `G` takes the subtitles ahead by 0.25sec instead of taking it back.

**Comment by TRtomasz** [comment]
Hi,
Thanks for your report. I was able to reproduce this error when casting from PC.

**Comment by assafmo** [comment]
Cool, waiting for the fix :heart_eyes:

**Comment by TRtomasz** [comment]
Hi,
This should be fixed now. If it is not please let us know and i will reopen issue.

**Comment by assafmo** [comment]
Thanks, will do!
