### ISSUE TITLE
Stremio Bug

### ISSUE THREAD

**Issue by isaacirlanda** [Stremio/stremio-bugs#22]
Hello Stemio

I got a Win7 Sp1 , country: Brazil

Since 3.3.1 update ( ever since I download the program) 
I'm unable to login, the login doesn't do anything 
Facebook login brings my profile pic and login button but it won't login
Guest Login doesn't work also, when singing up when trying to sign up with bugs with login thread

Hope you guys fix this

**Comment by isaacirlanda** [comment]
It seems like the Register / Login code is conflicting , up is bugging the other

**Comment by Ivshti** [comment]
most likely explanation is that cloudflare is blocking you
it shouldn't have anything to do with the version. You can download a previous version by http://www.strem.io/StremioVERSION.exe e.g. http://www.strem.io/Stremio3.3.0.exe to check, but it shouldn't

As to how to solve it - let's first confirm the issue. what kind of errors are you getting? if anything at all?

**Comment by isaacirlanda** [comment]
Hey Ivshti

Well I will be posting the screenshots since it will be easier to explain
I can't login with facebook, login after I put the e-mail it bugs with the register form , register bugs with the login form

Lets start, As soon as I open it (normal)
http://prntscr.com/9anhf3

Login with e-mail/pass , it bugged after putting the 6th letter on the password
(Might not be a bug but the facebook login goes missing)
http://prntscr.com/9ani2n

Register, when putting the email and password it goes into the login form
http://prntscr.com/9aniog

Guest login doesn't conect

How can I fix the sloudflare problem? my hosts file is fine, everything else is working fine on the pc and internet

**Comment by Ivshti** [comment]
The first one is not a bug, since as soon as you start using the forms FB login disappears

Can you launch Stremio with ". --development" arguments and see if any errors appear in the console?

For windows, that is:
%LOCALAPPDATA%\Programs\LNV\Stremio\Stremio.exe . --development
IN the cmd

**Comment by isaacirlanda** [comment]
http://prntscr.com/9atwe1 Console
http://prntscr.com/9atx1s  Cmd

Btw thanks for trying to fix this issue

-GET file:///C:/Users/Wagner/AppData/Local/Programs/LNV/Stremio/resources/app.asar/node_modules/stremio-translations/pt_BR.json net::ERR_FILE_NOT_FOUND
-POST http://stremio.torplay.net:6969/stremio/v1 net::ERR_CONNECTION_TIMED_OUT
-TypeError: Failed to fetch(…) "http://stremio.torplay.net:6969"

**Comment by Ivshti** [comment]
@isaacirlanda try this:

wget http://api9.strem.io

What is the result?

**Comment by isaacirlanda** [comment]
http://prntscr.com/9b2pla
-Uncaught SyntaxError: Unexpected identifier(…)

First error seams it can't find a Portuguese Translation
Other one with the torrent files
Other conection timeout and can't conect to the server

**Comment by Ivshti** [comment]
@isaacirlanda the unexpected identifier error worries me. Can you click on the arrow on it's left to see the stack trace? Also on the three dots?

As for the torplay errors - ignore those, this add-on is only available in certain ISPs in India.
The translation errors are also more or less normal, as for the ENOENTS on torrents.

Also, give me a result of ``wget http://api9.strem.io`` - or simply open http://api9.strem.io in your browser and report if it redirects you to the stremio website. Also open http://api9.strem.io/addons5 and report if it gives a JSON file or some error.

**Comment by isaacirlanda** [comment]
Today I tried to login [Email-Password] I got this huge error: http://prntscr.com/9baqkx It might mean something to you so just sending it anyways,

http://api9.strem.io - Redicted fine to the stremio website - http://prntscr.com/9bar8p
http://api9.strem.io/addons5 - This was the result -  http://prntscr.com/9barh8
All the tabs from the errors = http://prntscr.com/9bas0i

I just realised you are replying very fast , if wanted give me your e-mail or some info so I can teamview and you can support me in this matter a lot faster

**Comment by Ivshti** [comment]
Yes, let's talk about TeamViewer or something - write at ivo@strem.io
Also, this error is very helpful!

**Comment by isaacirlanda** [comment]
Sent

**Comment by Ivshti** [comment]
@isaacirlanda can you try this -> www.strem.io/Stremio3.4.3.exe

Even if it doesn't work, it will be much easier to debug the logging/registration process because requests will be logged in the dev tools.

**Comment by isaacirlanda** [comment]
Going to try it now and edit when I get the results

**Comment by isaacirlanda** [comment]
@Ivshti It's now working fine, logged in with facebook account, program is in portguese

Everything seems to be working fine will edit if there's a bug but seems like you fixed it !
Thanks for all the support give, hope the best !

**Comment by Ivshti** [comment]
@isaacirlanda that's great news!

So indeed, the issue was getting blocked by cloudflare, and it could have happened to many other issues.

The fix was giving them normal user-agent headers and having all requests being done through chromium's AJAX system rather than node.js's http

**Comment by jirkabaron** [comment]
Hi guys. I've just downloaded version 3.4.3, I also live in Brazil. I'm on windows 7 and can neither sign up nor get in as a guest. The login button redirects me to the sign-up screen but when I put in an email and a password and click on the sign up button, it doesn't do anything. The same thing with the guest login button. Nothing happens. Is there any way how to get in? I'm going to try to download an older version through the link you had posted here...

**Comment by jirkabaron** [comment]
Seems like a simple restart did the trick. Sorry about "spamming" here!

**Comment by Hellboy913** [comment]
Reopening this issue again. Having the same problem. Works completely fine with a VPN.

Output of wget http://api9.strem.io

> --2021-12-02 14:55:03--  http://api9.strem.io/
Resolving api9.strem.io (api9.strem.io)... 104.16.205.72, 104.16.206.72, 2606:4700::6810:ce48, ...
Connecting to api9.strem.io (api9.strem.io)|104.16.205.72|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-12-02 14:55:09 ERROR 403: Forbidden.
