### ISSUE TITLE
No audio on chromecast from Android

### ISSUE THREAD

**Issue by Suxsem** [Stremio/stremio-bugs#222]
Hello, I want to report a bug regarding casting series from android to chromecast.

The problem seems to affect only 720p and 1080p torrents casted to chromecast.

Video and subtitles are ok but no audio is transmitted to chromecast.

You can reproduce it by casting "greys.anatomy.s16e02.720p.hdtv.x264-metcon[tgx]" from an Android device to a chromecast 3.

I tried from two smartphones, one huawei and one xiaomi.

This is the only real problem affecting this awesome project!

**Comment by Suxsem** [comment]
Any news guys?

**Comment by TRtomasz** [comment]
You should use different source in such case. Chromecast supports only small subset of formats/codecs so if video has different sound format it will not work on chromecast.

**Comment by Suxsem** [comment]
> You should use different source in such case. Chromecast supports only small subset of formats/codecs so if video has different sound format it will not work on chromecast.

Hello TRtomasz,
if I cast the very same source to my chromecast from Stremio installed on my Windows 10 PC the audio works correctly, so it must be a problem related to the Android version of Stremio.

I think it's related to this recent reddit post: https://www.reddit.com/r/Stremio/comments/eq01lq/no_audio_or_video_while_chromecasting_from/

but the problem is still there...

**Comment by Ivshti** [comment]
It is an issue only on Android and we're aware on it and in the process of refactoring to fix it - unfortunately, we cannot provide an exact timeline of when it will be fixed.

It's not straight forward because it requires a full rework of the way chromecasting works, because we need to incorporate ffmpeg transcoding/transmuxing. Previously we wanted to avoid this feature altogether cause it might drain the battery of weaker phones.

**Comment by Suxsem** [comment]
I fully understand, maybe you could add a switch in preferences to enable or disable transcoding.
Thank you for your hard work! Until then I will continue using my PC to cast :)

**Comment by assafmo** [comment]
This is also a problem for me. Also on Linux.
Let me know if I can help somehow. :pray:

**Comment by nielsbaele** [comment]
Had the same problem.
After some try and error i found the add-on PBD+ 
It's uses an MP4 format.
So they Chromecast can use the sound.

**Comment by assafmo** [comment]
PBD+? Can't find it...

**Comment by ismardz** [comment]
You can "fix" it opening vlc as an external app and cast to chromecast from there

**Comment by TRtomasz** [comment]
Should be fixed in release 1.4.4 of the android app
