### ISSUE TITLE
Request: add "hide" to video-items offered to us

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Stremio/stremio-bugs#223]
Sometimes video items that can be watched are actually fake.
Please add an option to hide them manually, when we notice they are fake, so that later we could see only the rest.

**Comment by AndroidDeveloperLB** [comment]
@Ivshti I mean that if you search for some movie, and you get some results, and you choose one, you see this instead of the movie:

![image](https://user-images.githubusercontent.com/5357526/80385532-d5bf6a00-88ae-11ea-80fa-b05f7b3d2676.png)

**Comment by Ivshti** [comment]
can't you just uninstall the addon that provides this source?

**Comment by AndroidDeveloperLB** [comment]
Sure I can, but sometimes it does provide the correct ones.
Also, it can be useful in case we see a movie with a similar name (example is a movie that got to be created in multiple years).
If you want, you can even have "report" instead, to help others know about this.

**Comment by jaruba** [comment]
what if you report them and the addon fixes the streams later on?

**Comment by AndroidDeveloperLB** [comment]
Isn't there an ID for each item? The ID will be reported as one that doesn't match the one of the current movie. 

You could have multiple options for reporting:
1. Report as fake
2. Report as incorrect movie
3. Cancel previous report/s.

Maybe even one of "report as very low quality."

When reporting, you could put the item at the bottom of the list. The more reports, the closer the item will be to the bottom. You can also add a counter of reports.

**Comment by Ivshti** [comment]
there is a report button in the bottom right of the player for each stream, if the addon has provided a contact email

**Comment by AndroidDeveloperLB** [comment]
I don't see it.
Look at the screenshot I've shown you. It's not there either.
The request is to have it for all items. .
Original request wasn't about reporting. 

My request is some form of action to be able to ignore those, as I've tried them already. It can be completely local to the current installation. You can put a mark on it if you wish, or put it at the bottom of the list, under a title "ignored", or something similar.

The report function is optional, to help other users.

**Comment by jaruba** [comment]
you don't see it because it's shown only if the addon has provided a contact email

**Comment by jaruba** [comment]
i think you're still not considering some things with your request.

there were addons that had streams that work in only one country, if you did not have an ip from that country, then the streams wouldn't work. this was clearly stated in the addon's description, yet users still continued to ask why it does not work

such preferential treatment of some streams over others, might create more issues then it fixes in the long run

**Comment by AndroidDeveloperLB** [comment]
OK, can you please consider adding a way to do it for each item.
Again, I'm not talking about reporting. I'm talking about any way to prevent myself from trying to open it again, as it's not the right one for me.

**Comment by jaruba** [comment]
well we take all requests into consideration, so i can promise you that much, the complexity and general benefit of such a feature is questionable for now though, so what i can't promise is that it will actually be added

**Comment by AndroidDeveloperLB** [comment]
Is there any workaround you know of for this?
I mean other than reporting that doesn't seem to exist, and removal of the addon that shows those?

**Comment by jaruba** [comment]
a workaround to filter or give preferential treatment to one stream or another? i'm afraid not

**Comment by AndroidDeveloperLB** [comment]
Streams? preferential ? Maybe I wasn't clear. I mean those:

![image](https://user-images.githubusercontent.com/5357526/80400239-30fb5780-88c3-11ea-8262-aa2d2b3d25a5.png)

I mean that when I notice one of them is wrong, I could mark with something that I will know not to try it again.

**Comment by AndroidDeveloperLB** [comment]
Closed because added?

**Comment by TRtomasz** [comment]
Closing because it is not a Stremio bug and as stated by @jaruba 
> the complexity and general benefit of such a feature is questionable for now though, so what i can't promise is that it will actually be added

**Comment by AndroidDeveloperLB** [comment]
It's not a bug. It's a feature request.

Why do you need traffic to decide if something is a good idea or not?
:(

**Comment by Ivshti** [comment]
It could be a good idea, it just creates complexities under the hood that we don't want to tackle across multiple platforms

**Comment by AndroidDeveloperLB** [comment]
Oh ok. Could you at least add sorting by what was watched/semi-watched , vs those that weren't?

**Comment by Ivshti** [comment]
Unfortunately for privacy and legal reasons we don't and can't collect this data

**Comment by AndroidDeveloperLB** [comment]
@Ivshti But it's already this way. It shows the progress for each of the items.
So what I suggest now about sorting is to sort it by the progress.

**Comment by Ivshti** [comment]
Ah, you mean sorting by how many times *you* watched it or *all users* watched it?

If it's the first one, then it's possible.

**Comment by AndroidDeveloperLB** [comment]
Not how many times you watched. This isn't even shown.
The progress.
When you choose a TV show episode (or a movie), there are items shown on the side, for you to choose the source.
If you choose one, it starts playing. If you stop playing, and go back to the same screen, you see the progress of how much you've watched from this source.
