### ISSUE TITLE
external hebrew subtitles don't work

### ISSUE THREAD

**Issue by preachify** [Stremio/stremio-bugs#224]
When using external hebrew subtitles via "drag&drop" the subtitles don't show up at all, yet they are recongnized and the srt filename is displayed when dropping them.

I've tested with multiple hebrew SRT's and none of them worked, external english subtitles worked just fine. so i suppose this issue has something related to language (?)

thank you very much.

**Comment by jaruba** [comment]
I just tried it myself, I downloaded a hebrew subtitle from Open Subtitles, dragged and dropped it in the player.

<img width="476" alt="Screen Shot 2020-04-27 at 19 46 45" src="https://user-images.githubusercontent.com/1777923/80398302-12479180-88c0-11ea-9be2-109635c2c769.png">

**Comment by jaruba** [comment]
Maybe you're dragging and dropping unsupported files? Like `.sub` or `.zip`? Or maybe the subtitles you are trying to drop are simply broken?

But dropping hebrew subtitles definitely works.. as you can see in the screenshot.

**Comment by preachify** [comment]
thats weird, problem is probably on my side. i have been dragging and dropping srt's, just now i have tested with joker(2019) and and the tv show westworld and none of them worked.
maybe try to send me the url of that srt that worked for you and i will test on my end.
if that doesnt work i will try a reinstall.
thank you for your help.

**Comment by preachify** [comment]
I've tested it with a different computer, on the tv show 'Black Sails' season 4 and still no luck :(
will update once i discover something new.

**Comment by jaruba** [comment]
[archive.zip](https://github.com/Stremio/stremio-bugs/files/4541611/ad.astra.2019.heb.1cd.8004145.zip)
this is the one i tried, can you send me one that you tried so i can test that on my side too?

**Comment by preachify** [comment]
this one for an example: https://www.opensubtitles.org/en/subtitles/7373697/westworld-the-original-he
but basically every one i tried didn't work.

**Comment by preachify** [comment]
yep, the subtitles that you sent work for me too.

**Comment by jaruba** [comment]
and the one that you sent me doesn't work for me.. the first thing i noticed is that it is not properly encoded, look at the difference between them in text editors:
<img width="452" alt="Screen Shot 2020-04-27 at 22 27 09" src="https://user-images.githubusercontent.com/1777923/80412381-75dcb980-88d6-11ea-8602-cd880cbed681.png">

**Comment by preachify** [comment]
yes this might be it, i've opened the srt with notepad++ and they look good(both the one you sent me and the bad one)
maybe notepad++ can read it and stremio cannot therefore subs not showing up.
![subs](https://user-images.githubusercontent.com/47429812/80412998-627e1e00-88d7-11ea-9cdd-1b307b744914.png)
![subs2](https://user-images.githubusercontent.com/47429812/80413017-6ad65900-88d7-11ea-8f61-5d8080b51a44.png)

**Comment by preachify** [comment]
actually this seems like it could be just a problem with an unknown language, Windows Notepad could also open this SRT file properly.
![subs3](https://user-images.githubusercontent.com/47429812/80413354-0798f680-88d8-11ea-810b-8ed6e19f9e0f.png)

**Comment by jaruba** [comment]
maybe you are using windows in hebrew? which converts to the presumed encodings automatically?

**Comment by preachify** [comment]
i used to have my windows main language set to hebrew but now my main is english.
i still use hebrew and english inputs so it makes sense i can read them properly.

**Comment by jaruba** [comment]
i converted the subtitle file u sent manually from `IOS 8859-8` to `UTF-8` and it works in Stremio

**Comment by jaruba** [comment]
i did this by using:
```
iconv -f iso-8859-8 -t utf-8 < old.srt > new.srt
```
in OSX in the terminal

**Comment by preachify** [comment]
yes, this pretty much solves the problem for me, tried it for myself and it worked like a charm.
By the way Notepad++ has a built in feature to convert to UTF-8 so it's even more easy!
it's located at Notepad++ : Encoding<Convert to UTF-8 .
thank you so much for your help! This issue can be closed.

**Comment by jaruba** [comment]
You were correct to create an issue for this, I looked into it closer and it seems that internally we detect the file as having `ISO-8859-8-I` encoding, while the charset converter only supports `ISO-8859-8`.

This seems to be a very isolated case that can happen only for `ISO-8859-8`, I will work on fixing this.

**Comment by preachify** [comment]
thank you very much for your kind support!
