### ISSUE TITLE
Request: add own subtitle

### ISSUE THREAD

**Issue by samuelpetroline** [Stremio/stremio-bugs#227]
Hello,

I've been wondering if there is any way to manually add a subtitle? Sometimes it seems possible and sometimes it doesn't. 

If there was always an option it would be really helpful.

Thanks in advance

**Comment by Ivshti** [comment]
There's always an option - you just drag and drop the file over Stremio
Feel free to reopen if you can describe cases in which it doesn't work

**Comment by samuelpetroline** [comment]
Oh, I see. It wasn't obvious to me.

Thanks :)
