### ISSUE TITLE
Trakt.tv scrobbling does not work when manually marking a show as watched from library

### ISSUE THREAD

**Issue by chronos000** [Stremio/stremio-bugs#229]
I have Stremio connected to trakt.tv. Scrobbling works correctly after watching a movie or a TV show. After watching it normally, the information is scrobbled to trakt.tv and the show gets marked as watched with the current time.

However, if I mark any show as watched using the mouse pointer, and the context menu (for example, in "My Library" section, and right clinking in any show, and then selecting "mark as watched"), then the show is not scrobbled to trakt.tv.

The expected behavior should be to scrobble it with the current time.

This issue is closely related to the fact that Stremio is not "downloading" the list of watched shows and movies from trakt.tv, and only shows a tick (for watched episodes) for movies and episodes watched with installed Stremio. This would make possible a very nice feature, which is to [hide watched movies](https://github.com/Stremio/stremio-features/issues/96).

I am using Stremio for Linux:
```
Stremio	4.4.106
Web UI	4.4.112
Server	4.90
```

**Comment by TRtomasz** [comment]
Hi,
That's not a bug, there is no such feature in stremio. Trakt synchronization works only when user actually plays something in the app
