### ISSUE TITLE
I have 2 DLNA devices on the network, Stremio picks one of them at random

### ISSUE THREAD

**Issue by sabbour** [Stremio/stremio-bugs#23]
I have 2 DLNA devices on the network, Stremio picks one of them at random and still goes back to the movie screen when clicking on the button.

**Comment by Ivshti** [comment]
Which version? Is it above 3.4.1?

**Comment by sabbour** [comment]
When upgraded to 3.4.3, it can't see any of them anymore

**Comment by Ivshti** [comment]
@sabbour what kind of devices are they?

**Comment by gleisonfelipe** [comment]
did you solve the issue? @sabbour
