### ISSUE TITLE
Foreign subtitles in VLC

### ISSUE THREAD

**Issue by fadoaglauss** [Stremio/stremio-bugs#230]
This [Reddit post](https://www.reddit.com/r/Stremio/comments/gyezu3/foreign_subtitles_in_vlc/) describes problems related to foreign languages' subtitles on external players (Android only?). Seems to be related to #197. I can confirm this bug occurs on Android TV (mi box 4k), Amazon FireStick, and Mobile Android for brazialian portuguese subtitles.
Interestingly english subtitles works.

**Comment by TRtomasz** [comment]
I don't really think that is a bug. Subtitles are provided by addons in this case opensubtitles addon which is not present in VLC. Probably english subtitles are embedded subtitles and thats why it is possible to load them while playing in the vlc.
