### ISSUE TITLE
 Problems with "Doctor Who" subtitles in stremio

### ISSUE THREAD

**Issue by Seiyaofc** [Stremio/stremio-bugs#231]
I'm having problems starting with season 7, episode 6 of "doctor who" in "the rings of akhaten". From episode 6 the subtitles are related to the last episode, for example, if I am watching episode 6 the subtitles are showing those from episode 5. If I am watching episode 7 the subtitles are from episode 6 ... What I do? Does anyone else have this problem?

**Comment by TRtomasz** [comment]
Subtitles are provided by opensubtitles, so issue is on their side and there is nothing we can do about this. As a workaround you can download subtitles and drag and drop them to the stremio
