### ISSUE TITLE
No audio on Linux (Ubuntu) for the latest version (4.4.116)

### ISSUE THREAD

**Issue by devserkan** [Stremio/stremio-bugs#232]
**Describe the bug**
Upgraded from an old version to the latest, which is 4.4.116. There is no sound right now.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**
There wasn't any problem with the old version. After upgrading to the latest this happened. Somehow, I found an old package (4.4.10) and installed, the sound came back. I started the latest version from terminal but as far as I can see there wasn't any error. If there is anything that we can use for debugging please let me know.

**Comment by TRtomasz** [comment]
Hi, we know about this issue, You can install app from flatpack package that is also available on our webpage, we have checked and when app is installed from flatpack sound is working.

**Comment by devserkan** [comment]
Hello. 

Sorry if there is an existing issue but I couldn't find it. Well, I can confirm it works if it is installed from flatpack. But, I prefer .deb packages since installing and using flatpack is a little bit annoying right now :) At least,  it installs org.kde.Platform (do I need it? if yes why I do not need it with .deb package) and does not create desktop files for the user. I had to copy it to the proper place in order to run it from Activities.

Nevertheless, thank you for pointing me to the flatpack. I can use it like that till the deb package fixed.

**Comment by TRtomasz** [comment]
Updated deb package is now available on our website. Sound should be working now.
