### ISSUE TITLE
Stremio does not load subtitles

### ISSUE THREAD

**Issue by mrcanelas** [Stremio/stremio-bugs#233]
Hello, we are creating an addem for stremio for a Brazilian anime site, but there are some episodes that Stremio does not load the subtitle, we use SoftSub in the encode, follow the link of an episode that did not load the subtitle.

This didn't work: [https://drive.google.com/file/d/1_GAqQmkl-qT_MTx9n0JrvcTyDAktwkGD/view?usp=sharing](https://drive.google.com/file/d/1_GAqQmkl-qT_MTx9n0JrvcTyDAktwkGD/view?usp=sharing) 
Screenshots: [https://drive.google.com/file/d/1lFdCOyn3rAltNfirghyBGUWVCc3qkOTZ/view?usp=sharing](https://drive.google.com/file/d/1lFdCOyn3rAltNfirghyBGUWVCc3qkOTZ/view?usp=sharing) 

This worked: [https://drive.google.com/file/d/1jUuVZKbxCSgqlqJHECrlecx4PYprE8tz/view?usp=sharing](https://drive.google.com/file/d/1jUuVZKbxCSgqlqJHECrlecx4PYprE8tz/view?usp=sharing)
Screenshots: [https://drive.google.com/file/d/14BGM1bzREi__QZwbgf3i22y0qgSN7F4b/view?usp=sharing](https://drive.google.com/file/d/14BGM1bzREi__QZwbgf3i22y0qgSN7F4b/view?usp=sharing)

**Comment by TRtomasz** [comment]
In the first file lang and track description are undefined. Not sure if such case should be handled.

**Comment by jaruba** [comment]
@TRtomasz in such cases, video players usually just name them Track 1, Track 2, etc.

**Comment by mrcanelas** [comment]
> @TRtomasz nesses casos, os players de vídeo geralmente os denominam Faixa 1, Faixa 2, etc.

Exactly, on all other video players it works well, I think the ideal would be to name track 1 and track 2 like all other players, if this is not possible our addon will be unviable, as we will have to encode our entire database .

**Comment by fidelix** [comment]
Hi @Ivshti , any reason why you closed the issue?
Too complicated? out of scope?

**Comment by Ivshti** [comment]
I didn't close it directly - the issue was referenced in a bug fix that I merged, so it got closed automatically. I'll open it until you test it and confirm it's fixed

**Comment by TRtomasz** [comment]
Hi @mrcanelas 
We have deployed UI with fixed issue on our staging environment. 
In order to use it you will need to start stremio from command line with additional `--staging` parameter
Please tell me what operating system are you using? So i can tell you where is Stremio installed on your system.

**Comment by mrcanelas** [comment]
Hello @TRtomasz I'm using Stremio 4.4.116 on Windows 10.

**Comment by TRtomasz** [comment]
@mrcanelas 
On windows stremio is installed in `%localappdata%\Programs\LNV\stremio-4`
so you should be able to start Stremio using this command `%localappdata%\Programs\LNV\Stremio-4\stremio.exe --staging`
this will Start stremio with staging UI, subtitles tracks should be working now fine for both files.

**Comment by mrcanelas** [comment]
@TRtomasz 
It is working perfectly now, thank you very much for the quick solution of the problem.

**Comment by TRtomasz** [comment]
That is great, thanks for checking this :)

**Comment by fidelix** [comment]
Hi, when is this expected to show up on Android?

Cheers,

**Comment by Kunaal-parikh** [comment]
@TRtomasz  i use a android phone and the subtitles are not at all coming but when i see a episode in russian the subtitles option is available ( where you change the speed and all) but when i see that particular episode in English the subtitles are not working
