### ISSUE TITLE
Stremio doesnt start on desktop[Ubuntu]

### ISSUE THREAD

**Issue by esercankutay** [Stremio/stremio-bugs#235]
Nothing happens when its launched from gnome menu. If i launch it from the terminal here is the error im given.

> stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory

I expect it to lauch without me needing to solve some dependency problem.

![Screenshot from 2020-07-02 18-51-30](https://user-images.githubusercontent.com/29177826/86383877-f1703380-bc96-11ea-8cdb-f52ba61cef18.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [Firefox 77.0.1]
 - Version [4.4]

**Comment by TRtomasz** [comment]
That's how deb packages are working, they don't install anything automatically you need to install needed dependencies by yourself. You can do this using this command `apt-get install --fix-missing`

**Comment by chronos000** [comment]
@TRtomasz 
the latest libx264 version available in the official Ubuntu repos is 
```
libx264-155/eoan,now 2:0.155.2917+git0a84d98-2 amd64 [installed,automatic]
  x264 video coding library
```
But the latest stremio stable build asks specifically for libx264-152, which is not available.

If I manually download and install version libx264-152, stremio works again. Perhaps stremio should be looking for libx264-152 _or greater_

**Comment by marcelodive** [comment]
Download and install this:
http://archive.ubuntu.com/ubuntu/pool/universe/x/x264/libx264-152_0.152.2854+gite9a5903-2_amd64.deb
