### ISSUE TITLE
Continue watching

### ISSUE THREAD

**Issue by BobtheChipmunk** [Stremio/stremio-bugs#237]
Using Firestick I am unable to access the 3 dot menu on a movie on the continue watching list 

**To Reproduce**
1. Go to Board.
2. Highlight a movie on the continue watching list
3. Click the additional menu button on the firestick remote
4. Nothing happens

**Comment by baytree20** [comment]
Same problem on 2019 Nvidia Shield TV, can see but cant access the 3 dots on "Continue Watching" list to remove them as its getting cluttered with stuff with only minutes left id I leave before the very end. Would also be nice if you could had the option of turning off the whole "Continue Watching" part of the hme screen or maybe selecting what you would like on the home screen from an options menu.

**Comment by TRtomasz** [comment]
Fixed in 1.4 now this menu is displayed on long click/long press
