### ISSUE TITLE
Slow or no response to keyboard/mouse

### ISSUE THREAD

**Issue by LostBrit** [Stremio/stremio-bugs#239]
Stremio sometime responds very slowly to keystrokes or mouse clicks while playing video. Once it does respond it will then often lock up to all input. Meanwhile the video continues to play, but there is no control of the application. The PC (Win10, i3, 8GB) is still responsive to keyboard / mouse while this happens.

The only way to restore Stremio responsiveness is to restart the app.

**Comment by LostBrit** [comment]
This just happened again at the end of a show. So as video playback stopped, Stremio continued to display the last frame. It would not responded to mouse clicks or keyboard. However moving the mouse pointer does show the progress bar which is displaying a point half way through the video playback. I have seen this before when it locks up, as if the interface locked up some time ago, stopped updating, and you don't realise it until you come to the end of video playback or try keyboard/mouse input.

**Comment by TRtomasz** [comment]
Please tell us for which exact stream does it happen, you can make  a screenshot, so we can try to reproduce it on our end.

**Comment by LostBrit** [comment]
Torrentio has had an issue a couple of times. I have been using TPB+ a lot lately and have had no issues with that in the last couple of weeks.
