### ISSUE TITLE
UX: Android Chromecast button only in homepage

### ISSUE THREAD

**Issue by oxmanroman** [Stremio/stremio-bugs#240]
**Describe the bug**
When in Android application, the only way to cast Stremio to the Chromecast is when being on the home page.

**Why this is a problem**
1. Let's say you forget to cast when entering the app
2. Look for the movie you want to see
3. Select your streaming option
4. Wait for it to load
5. And just now you realize you did not cast the app, and you need to return all the way back to the home page

**Expected behavior**
For the cast button to appear in every step

**Screenshots**
![Screenshot_20200724-212229_Stremio_2](https://user-images.githubusercontent.com/5060694/88423515-8ed10a00-cdf4-11ea-9356-57587c500df3.jpg)
![Screenshot_20200724-212235_Stremio](https://user-images.githubusercontent.com/5060694/88423519-90023700-cdf4-11ea-9c4a-030c53990734.jpg)
![Screenshot_20200724-212247_Stremio](https://user-images.githubusercontent.com/5060694/88423500-8bd61980-cdf4-11ea-9267-c846f8db13a4.jpg)
![Screenshot_20200724-212342_Stremio](https://user-images.githubusercontent.com/5060694/88423510-8e387380-cdf4-11ea-97bb-061bd33140be.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android
 - Version 10

**Comment by oxmanroman** [comment]
I would pretty much like to fix this issue myself, could you please guide me to where this issue should be fixed? Thanks!

**Comment by Ivshti** [comment]
AFAK This is mandated by the Chromecast SDK use guide. @nklhrstv can you confirm?

**Comment by nklhrstv** [comment]
This is a design issue that we must fix in some of the next releases. That button should appear on home, detail and player screens.

**Comment by oxmanroman** [comment]
@nklhrstv I could try to fix it send a PR, could you let me know which repo would be the correct one?

**Comment by nklhrstv** [comment]
The source code of the android app is not yet open source.

**Comment by nklhrstv** [comment]
Chromecast button was added to the player screen in the 1.3.0 version.
