### ISSUE TITLE
Stremio- 4.4(Beta) on Windows 10 1909 x64 version has "initShellComm is not defined" error

### ISSUE THREAD

**Issue by thamizharasan** [Stremio/stremio-bugs#241]
These are the troubles I'm facing right now:
- Stremio on launch/relaunch/reinstall gets stuck on the CAPTCHA page with an error notification saying "Error applying ShellJS, please consider re-installing from https://www.stremio.com"
- Unable to login via Facebook on the website (this issue started right after the captcha error)

To give an idea of the present situation, I have tried re-installing the application multiple times. I have updated Windows 10 including all the optional updates to the latest version. I do not understand why the app would suddenly throw an error. Please resolve it.

**Comment by TRtomasz** [comment]
Looks like cloudflare is blocking access to our webpage for you. It is possible in some cases(like a lot of weird traffic comming from your IP/ISP). I would recommend using a VPN in such situations.
