### ISSUE TITLE
Filter By Year does not show the current year

### ISSUE THREAD

**Issue by thiagodp** [Stremio/stremio-bugs#242]
**Describe the bug**
Filter By Year does not show `2020`. It shows from `2005` to `2019`.

**To Reproduce**
1. Click `Discover`
2. Select `By Year`

**Expected behavior**
Show the current year (`2020`) as well as past years.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome?
 - Version 106 and 116

**Comment by TRtomasz** [comment]
Hi,
Do you use a guest account?

**Comment by thiagodp** [comment]
Hi @TRtomasz , yes I do.

**Comment by TRtomasz** [comment]
@thiagodp  then, this is fine. current year is visible only for logged users.

**Comment by thiagodp** [comment]
How so? This isn't a bug, but a _feature_? 😳

**Comment by TRtomasz** [comment]
Features are limited for guest users. In order to have all Stremio features you should create an account
