### ISSUE TITLE
stremio: error while loading shared libraries: libx264.so.152:

### ISSUE THREAD

**Issue by jay763190097** [Stremio/stremio-bugs#243]
```
jay@jay-PC:/$ stremio %U
stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory
```
```bash
jay@jay-PC:/$ find /usr/lib -name libx264*
/usr/lib/x86_64-linux-gnu/vlc/plugins/codec/libx26410b_plugin.so
/usr/lib/x86_64-linux-gnu/vlc/plugins/codec/libx264_plugin.so
/usr/lib/x86_64-linux-gnu/libx264.so.155
/usr/lib/i386-linux-gnu/i686/sse2/libx264.so.155
/usr/lib/i386-linux-gnu/libx264.so.155
```
It seems my ffmpeg's version is newer than it depends on.

**Comment by TRtomasz** [comment]
Hi,
You need to install this version https://packages.ubuntu.com/bionic/libx264-152 as it is one being required.

**Comment by cossio** [comment]
@TRtomasz Why is this issue closed? I think Stremio installer should automatically install the required libraries.

**Comment by lucaszanella** [comment]
On ubuntu 20.04 there's no libx264-152, only 155, so I guess it cannot be installed on 20.04

**Comment by cossio** [comment]
@TRtomasz reopen?

**Comment by marcelodive** [comment]
Download and install this:
http://archive.ubuntu.com/ubuntu/pool/universe/x/x264/libx264-152_0.152.2854+gite9a5903-2_amd64.deb

**Comment by cossio** [comment]
> Download and install this:
> http://archive.ubuntu.com/ubuntu/pool/universe/x/x264/libx264-152_0.152.2854+gite9a5903-2_amd64.deb

Maybe the stremio installer can take care of this automatically.

**Comment by lucaszanella** [comment]
Wouldn't it be better to launch a completely contained image in snapcraft? I was helping someone to install this. For me I'd ok with the .deb but I was helping someone who just came from Windows and she would like to install things by one click. This was the only app that I had to make her use the terminal to install properly. Even to find the problem she had to start through terminal. I'd like her experience to be just as windows: click to install, click to open.

**Comment by cristianvasquez** [comment]
I want to try stremio, but this error appears after installing in linux.

Are there any alternatives?

**Comment by Ivshti** [comment]
There's a flatpak available on the website, try that: stremio.com/downloads

**Comment by emiliopedrollo** [comment]
This should be reopened.

I cannot properly setup firewall/vpn rules to an app running behind `bwrap` as this flatpak does.

**Comment by ibster1st123** [comment]
> This should be reopened.
> 
> I cannot properly setup firewall/vpn rules to an app running behind `bwrap` as this flatpak does.

Here Is My Solution : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> Wouldn't it be better to launch a completely contained image in snapcraft? I was helping someone to install this. For me I'd ok with the .deb but I was helping someone who just came from Windows and she would like to install things by one click. This was the only app that I had to make her use the terminal to install properly. Even to find the problem she had to start through terminal. I'd like her experience to be just as windows: click to install, click to open.

Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> On ubuntu 20.04 there's no libx264-152, only 155, so I guess it cannot be installed on 20.04

Yes It Can, here Is My Solution : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> @TRtomasz Why is this issue closed? I think Stremio installer should automatically install the required libraries.

Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> ```
> jay@jay-PC:/$ stremio %U
> stremio: error while loading shared libraries: libx264.so.152: cannot open shared object file: No such file or directory
> ```
> 
> ```shell
> jay@jay-PC:/$ find /usr/lib -name libx264*
> /usr/lib/x86_64-linux-gnu/vlc/plugins/codec/libx26410b_plugin.so
> /usr/lib/x86_64-linux-gnu/vlc/plugins/codec/libx264_plugin.so
> /usr/lib/x86_64-linux-gnu/libx264.so.155
> /usr/lib/i386-linux-gnu/i686/sse2/libx264.so.155
> /usr/lib/i386-linux-gnu/libx264.so.155
> ```
> 
> It seems my ffmpeg's version is newer than it depends on.

Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> @TRtomasz Why is this issue closed? I think Stremio installer should automatically install the required libraries.

Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
> I want to try stremio, but this error appears after installing in linux.
> 
> Are there any alternatives?

Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by ibster1st123** [comment]
Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

**Comment by emiliopedrollo** [comment]
> Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=1exPPXCFWVM

That's not a solution. That's a workaround. And if you had read my comment you would know why this does NOT fixes it for me.

Now stop spamming at Github.

**Comment by ibster1st123** [comment]
> > Here Is How To Fix This 100% working : https://www.youtube.com/watch?v=
> 
> That's not a solution. That's a workaround. And if you had read my comment you would know why this does NOT fixes it for me.
> 
> Now stop spamming at Github.

I Will Do What i Want, Shut Up!..
