### ISSUE TITLE
MacOS Catalina Mouse Volume Behaviour

### ISSUE THREAD

**Issue by emog** [Stremio/stremio-bugs#244]
**Describe the bug**
When scroll the magic mouse up the volume decreases and when scroll down the volume increases.

**To Reproduce**
1. Open some movie to watch
2. Scroll Up with your mouse or your touchpad
3. See that the volume goes down

**Expected behaviour**
It should use the native behaviour of the macOS. (User can change macOS settings to use different scroll direction: Preferences->Mouse->Scroll direction)

**Desktop:**
 - OS: macOS Catalina 10.15.6 (19G2021)
 - Browser: WebUI 4.4.117 (can't see which browser is used)

**Comment by Ivshti** [comment]
Actually this is intended as the scroll corresponds to volume on all operating systems. What do you think the expected behavior should be - perhaps if you find this unintuitive, we can add an option.

**Comment by emog** [comment]
The volume up in macOS (default behaviour) is when you scroll up on your mouse the volume increases and when scroll down it's decreasing. In Stremio it's the opposite way. I should be honest that Youtube uses the same approach like you but there is a horizontal slider instead of vertical like in Stremio that's why it's more noticeable in Stremio.

**Comment by emog** [comment]
Open VLC player on macOS (with default scroll direction: Natural) and scroll up - the volume will be increased and when you scroll down the volume will be decreased. This is what I expect.

**Comment by TRtomasz** [comment]
@emog  i'v just tested on my Mac, i have scroll direction set to Naturall. Scroll down is moving two fingers on touchpad up and scroll up is moving two fingers on touchpad down. I'v tested in both stremio app and youtube web app. In both volume works in the same way on scroll down volume is decreasing on scroll up it is increasing.
