### ISSUE TITLE
Playback error for some URLs on Windows since Stremio server 4.10.0

### ISSUE THREAD

**Issue by doingodswork** [Stremio/stremio-bugs#247]
**Describe the bug**

Some URLs can't be played back on Windows since Stremio server `4.10.0`, despite working in VLC and MPV directly, as well as in Stremio on other operating systems.

The URLs that don't work were from AllDebrid, but it could *potentially* affect others as well.

**To Reproduce**

1. Go to the "Magnets" page on AllDebrid: https://alldebrid.com/magnets/
2. Paste a magnet URL of a legally streamable (public domain) movie, like "Night of the Living Dead" from 1968: `magnet:?xt=urn:btih:50B7DAFB7137CBECF045F78E8EFBE4AC1A90D139&dn=Night+of+the+Living+Dead+%281968%29+%5BBluRay%5D+%5B720p%5D+%5BYTS%5D+%5BYIFY%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce`
3. Scroll down to the finished downloads and click on the "uptobox.com" link. There are two but only the first one is for the mp4 file. Click on the link that actually goes to "alldebrid.com/service/?url=https://uptobox.com/...".
4. On the new page, which is the main page of AllDebrid, the uptobox.com link should already be pasted in the large input field. Select the radio button "Text only links" and click on "Generate my links!"
5. A yellow box below should show the URL to the MP4 file. Copy it into the clipboard.
6. Open Stremio and paste the video URL into the search box at the top.
7. Most video URLs, also from RealDebrid, play fine now. **On Windows 10 with Stremio server 4.10.0 you get a playback error.**

**Expected behavior**

The video plays fine with Stremio server 4.9.0 and on other operating systems and I expected Stremio server 4.10.0 on Windows 10 to be able to play back the file as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/60071482/94346054-5d5e0000-002a-11eb-8485-a88b8b8ea2ad.png)

![image](https://user-images.githubusercontent.com/60071482/94346025-2ab40780-002a-11eb-8dd5-b1a8b4f77846.png)

**Desktop (please complete the following information):**

- OS: Windows 10 (2004)
- Version: Stremio 4.4.116, with server 4.10.0 (see screenshot of the version section of the settings above)

**Additional context**

- It worked on Linux Mint 20 XFCE, where the official Stremio deb package was installed plus the fix from [here](https://www.reddit.com/r/Stremio/comments/hmwe9g/error_while_running_stremio/fx9glj3/?utm_source=reddit&utm_medium=web2x&context=3). The Stremio server version here is 4.10.0 as well, so it's not that the Linux packages are behind and only working because of that.
- As mentioned above, using the exact same link in VLC ("Media"->"Open Network Stream") or MPV works fine

**Comment by doingodswork** [comment]
Thanks for the PR that attempts to fix this! But I can still reproduce the issue with:
- Stremio 4.4.120
- Web UI 4.4.122
- Server 4.11.0

Was the fix already part of a release or is it just not released yet?

Cc @shteryana

**Comment by woxie** [comment]
Why was this closed? Unfortunately, this issue hasn't been fixed yet. @shteryana

**Comment by TRtomasz** [comment]
Sorry about that, github closed it automatically when PR was merged, we will be releasing new version soon with this fix included.
