### ISSUE TITLE
Video streams don't start on Android

### ISSUE THREAD

**Issue by aagha** [Stremio/stremio-bugs#248]
**Describe the bug**
Whenever I try to play any video stream, the movie/show loading screen appears and then I'm taken back to the movie/show screen. On another Android phone, everything works just fine.

I'm using the Torrentio add on, but this happens with non-torrentio links as well.

**To Reproduce**
Search for a show.
Click on a torrent stream
Watch the loading page come up
It goes back to the show page

**Expected behavior**
Search for a show.
Click on a torrent stream
Watch the loading page come up
Show starts

**Smartphone (please complete the following information):**
 - Device: 1+ 7
 - OS: Android 10
 - Browser Chrome

**Comment by nklhrstv** [comment]
Is the show you try to play already part of your library?
Which is the app version?
Can you reproduce the bug with a movie?

**Comment by aagha** [comment]
Issue resolved. The account was connecting to Real Debrid and that account had expired.
