### ISSUE TITLE
cannot close stremio on latest osx 10.11.1

### ISSUE THREAD

**Issue by vipconsult** [Stremio/stremio-bugs#25]
See the video
http://screencast.com/t/nyQtw56JQ
this is stremio 3.4.4

**Comment by Ivshti** [comment]
Looks like a JS exception going on somewhere for me

Can you do that:
Start stremio
```
/Applications/Stremio.app/Contents/MacOS/Electron . --development
```

Focus the development tools and try to close the app. see what errors appear and screenshot/screencast them

thanks

**Comment by vipconsult** [comment]
seems to work after the latest update so closing this for now.
