### ISSUE TITLE
Manjaro xfce4

### ISSUE THREAD

**Issue by noisecode3** [Stremio/stremio-bugs#251]
**Describe the bug**
When I resize the windows stremio sometimes crash. and If I don't run stremio from command line it will lag. like 1 second freezes. This Is on Manjaro xfce4 

**To Reproduce**
Resize windows in Xfce on Manjaro and try with or without executing from terminal 

**Expected behavior**
not to crash and not to lag

**Comment by TRtomasz** [comment]
Hi,
Please tell us 1. What stremio version do you have installed 2. What manjaro version do you have installed, on their webpage latest one available is 20.1.2 3. How did you install stremio?

Cheers

**Comment by martinbangens** [comment]
its stremio 4.4.107-1 in AUR, its fully upgraded Manjaro xfce installed a week ago.

**Comment by TRtomasz** [comment]
Please update it to the latest version https://aur.archlinux.org/packages/stremio-beta

**Comment by martinbangens** [comment]
The lag problem seems to be gone in stremio-beta. Need some more time to test resizes the windows, but seems to be gone too. :D

**Comment by martinbangens** [comment]
ahh the lag is still there, but not as long lags as before. its annoying when I start to notice it. could it be my laptop have NVIDIA optimus? but other applications work fine. I use the bbswitch method and it makes no difference if I use intel of nvidia. also I use 5.9.1-1-rt19-MANJARO kernel.
`$ lspci 
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-LM (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d4)
00:1c.1 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 (rev d4)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d4)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d4)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation QM87 Express LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK106GLM [Quadro K2100M] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK106 HDMI Audio Controller (rev a1)
02:00.0 SD Host controller: O2 Micro, Inc. SD/MMC Card Reader Controller (rev 01)
03:00.0 Network controller: Intel Corporation Wireless 7260 (rev 83)
`

**Comment by martinbangens** [comment]
And now it also crashed when I minimized the window
