### ISSUE TITLE
Stermio stuck on logo in android app

### ISSUE THREAD

**Issue by Zeshan17** [Stremio/stremio-bugs#252]
When i launch the app it just stuck on the logo for a very long time. I reinstalled it like 20 times now and still doesn't work. I also cleared data and cache. And yes, the app is updated and on the latest version

**Comment by TRtomasz** [comment]
Please go to your router settings and try to reconfigure it so it use only ipv4 and then check

**Comment by Zeshan17** [comment]
> Please go to your router settings and try to reconfigure it so it use only ipv4 and then check

DIdn't work.

**Comment by Zeshan17** [comment]
I tried it on 3 phones, different models still didn't work. There something broken in the app. I live in the philippines.

**Comment by Zeshan17** [comment]
Okay, it did work by rooting my device and turning it off there manually.
