### ISSUE TITLE
Meta videos without released info not sorted into seasons

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-bugs#254]
Sometimes Cinemeta's metadatas' do not have `released=null` info, thus videos are not sorted into seasons/episodes.
I think it would be good to have a fallback sorting in case `released=null`.

Some examples: `tt0198254`, `tt0120926`

**Comment by Ivshti** [comment]
@jaruba did you have a chance to check this out?

**Comment by jaruba** [comment]
we are already looking into it, this is the same issue as this one: https://github.com/Stremio/stremio-addon-sdk/issues/146

and this bug is also blocking this change: https://github.com/Stremio/stremio-addon-sdk/issues/148

**Comment by TRtomasz** [comment]
looks like related item has been completed so i will close this one
