### ISSUE TITLE
High CPU usage while playing

### ISSUE THREAD

**Issue by wonbinbk** [Stremio/stremio-bugs#256]
I found that when I played videos using Stremio internal player, it requires much higher CPU usage compared with when I play using VLC.
Is it a known issue?

**Comment by TRtomasz** [comment]
It is not possible to compare CPU utilization for two different applications, especially since stremio does not use VLC but it uses MPV player.  Due to complicated multi layer architecutre it is normal that Stremio in total use more CPU power than VLC
