### ISSUE TITLE
Video not working in Android TV

### ISSUE THREAD

**Issue by ProStrike-hub** [Stremio/stremio-bugs#258]
Hi,

I’m trying to watch Tenet in Stremio on my TCL Android TV. 
Audio’s coming out but not the video. I disabled the hardware decoding. Video came but freezes right after. 
I then tried to cast to VLC, instead of Stremio’s player, it’s working perfectly fine on VLC but I cannot play backward/forward the movie. Thus, cannot move from where I stopped last time. Each time I’m trying to move VLC displays a message “can’t seem the file”...

**Comment by vsv1302** [comment]
I have the same problem and I don’t want to use vcl because there aren’t any subtitle tracks available when you use it

**Comment by vsv1302** [comment]
Yes, I sideload the latest version by downloading the app from Stremio’s website because the app doesn’t show in Google Play Store

**Comment by StarYes6** [comment]
I have the same problem with my TCL android TV.

I can't play FHD and 4k videos , only some hd videos works !!

**Comment by adrianlungu** [comment]
Are you, by any chance, trying to play HEVC/x265 videos ?

**Comment by TRtomasz** [comment]
Should be fixed in 1.4.20 release
