### ISSUE TITLE
Disable Calendar

### ISSUE THREAD

**Issue by webmutation** [Stremio/stremio-bugs#259]
Issue. In Vikings season 6. All episodes have been released, but on Windows Streamio version they do not show up. 

Problem is on windows version. 

To fix i had to move pc clock 2 months forward... as only 2 episodes are listed on next... would be nice to disable calendar and just show all episodes. 

Minor annoyance but had to change clock settings to workaround. 

Would be better if it behaved the same as on Android where the list is just tagged with upcoming but shows all episodes. 

![Screenshot_20210117-190836_Stremio](https://user-images.githubusercontent.com/761367/104851806-764f3180-58f7-11eb-9df3-b1de0c6dbedd.jpg)

**Comment by TRtomasz** [comment]
That was not really a bug in stremio, we can't change upcoming episodes dates. And they were according to the canadian release
https://en.wikipedia.org/wiki/Vikings_(season_6)
