### ISSUE TITLE
Requires root access to run properly

### ISSUE THREAD

**Issue by mehdid** [Stremio/stremio-bugs#26]
Running stremio as a normal user results in the following error:

Stremio3.4.3.linux % ./Stremio.sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get path
    at Error (native)
    at Object.<anonymous> (/home/mehdi/Downloads/Stremio3.4.3.linux/resources/atom.asar/browser/lib/init.js:113:41)
    at Object.<anonymous> (/home/mehdi/Downloads/Stremio3.4.3.linux/resources/atom.asar/browser/lib/init.js:125:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3

The program doesn't stop, but doesn't show any window nor makes any visible progress. Running the same as root (aka, sudo ./Stremio.sh) makes Stremio work properly.

**Comment by Ivshti** [comment]
That's weird, but it seems like an Electron issue. I'll investigate

**Comment by mehdid** [comment]
$HOME is properly set. I am using Debian (testing).

**Comment by mehdid** [comment]
Sorry. Didn't want to close the issue...

**Comment by mehdid** [comment]
Oh, just noticed that Stremio works perfectly fine as a normal user as long as we define XDG_CONFIG_HOME. So, the following works:
XDG_CONFIG_HOME=$HOME ./Stremio-runtime

Would it be possible to add that to Stremio.sh in case XDG_CONFIG_HOME is not defined?

**Comment by Ivshti** [comment]
It is possible, but first we should decide if this is an Electron issue, or a Debian issue. 

Obviously Electron expects XDG_CONFIG_HOME to be defined, which is a bit weird, considering that we have HOME.

**Comment by mehdid** [comment]
I am also not sure why it works as root, since XDG_CONFIG_HOME is not defined for root too.

**Comment by Ivshti** [comment]
Because it can write to some path it shouldn't write to?

For example /.stremio or /.electron?

**Comment by mehdid** [comment]
No, created files/directories are under /root/.config and /root/.cache. There is no .electron though.

**Comment by mehdid** [comment]
XDG_CONFIG_HOME is pretty standard but not defined everywhere (not on all distributions). But I can live with a "wontfix, define XDG_CONFIG_HOME". So, your call.

**Comment by Ivshti** [comment]
I considered investigating the issue deeper with Electron, but instead I'm just going to put a

```
if [ ! "$XDG_CONFIG_HOME" ]; then
   export XDG_CONFIG_HOME=$HOME
fi
```
in Stremio.sh

**Comment by mehdid** [comment]
If you put that in Stremio.sh, that would be perfect :)

**Comment by Ivshti** [comment]
I did, it will be out for the next release

**Comment by mehdid** [comment]
Perfect. Thank you!

**Comment by mehdid** [comment]
Just a last note, the variable should be set XDG_CONFIG_HOME=$HOME/.config

**Comment by Ivshti** [comment]
Good observation, fixing
