### ISSUE TITLE
Meta videos with streams not opened on Android

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-bugs#260]
When meta's videos already have a stream object defined on Android it does not start playing the stream for that video, but opens up addons' streams section. On desktop (Linux and win) when selecting the video it starts playing the stream from the video object.

**Comment by TRtomasz** [comment]
Hi, can you please give example of such addon/video so we can check it?

**Comment by TheBeastLT** [comment]
It's for Torrentio configured with RD/AD. With that configuration there's a catalog for files added to debrid service.
But I guess it should be possible to replicate this with some sample addon returning http streams inside video object?

**Comment by jaruba** [comment]
I created a demo addon so we can look into it:
https://1fe84bc728af-test-video-object.baby-beamup.club/manifest.json

@TheBeastLT please check it to approve that the addon responses are the same as in your situation

**Comment by TheBeastLT** [comment]
@jaruba looks about right. Just in my case the type is 'other' and stream entries don't have title, just url property. Not sure if that has any impact.
