### ISSUE TITLE
Trakt Integration Not Working in Android

### ISSUE THREAD

**Issue by kooolarpan** [Stremio/stremio-bugs#262]
**Describe the bug**
After watching an episode of a TV Series/Movie in Stremio, it is not synced with the Trakt.

**Expected behavior**
Trakt should know that I have watched the episode / movie and mark it as watched.

**Smartphone**
 - Device: Xiaomi Redmi Note 8
 - OS: MIUI 12

**Comment by TRtomasz** [comment]
Do you have latest android app version 1.3.5 installed? Also is this account connected with trakt?

**Comment by kooolarpan** [comment]
> Do you have latest android app version 1.3.5 installed? Also is this account connected with trakt?

Yes, I do have the latest Stremio installed. And it is connected with Trakt too. Trakt only shows What I am currently watching as follows.

**Comment by TRtomasz** [comment]
You must watch over 80% of an video for trakt to know this. In case you wtach something very short where credits are longer than 20% of the video time, you might have closed player to early.

**Comment by kooolarpan** [comment]
> You must watch over 80% of an video for trakt to know this. In case you wtach something very short where credits are longer than 20% of the video time, you might have closed player to early.

I have watched the episode all the way through but it didn't count.  It didn't add the series/movies in the history too. Only currently watched works.

**Comment by TRtomasz** [comment]
i'v just checked and it works fine. Please try doing the following in PC app click "Log out from trakt" and then log in to trakt, maybe your token has expired.

**Comment by kooolarpan** [comment]
> i'v just checked and it works fine. Please try doing the following in PC app click "Log out from trakt" and then log in to trakt, maybe your token has expired.

Ok will try that. But, if my token has expired then it wouldn't send response to Trakt about What I am currently watching. Can you please clarify?

**Comment by kooolarpan** [comment]
Yeah. After re-authorizing from the Stremio PC, it is working now. Thanks :)
