### ISSUE TITLE
Video stuttering in 1080p

### ISSUE THREAD

**Issue by FiReLoRd44** [Stremio/stremio-bugs#264]
The video is stuttering in 1080p, what should I do to remove that stuttering? I am using stremio on windows 10.

**Comment by pa-friederich** [comment]
Hi,
I am also experiencing stuttering with Stremio. I am using Stremio  on macOS Big Sur. This is completely unrelated to internet connection or source availability. Either with a lot of seeds or completely buffered, a video will stutter continuously without any logical reason.

**Comment by TRtomasz** [comment]
Please try turning on hardware accelerated decoding in the settings and then check :)

**Comment by FiReLoRd44** [comment]
I have turned on hardware accelerated decoding in the settings

**Comment by pa-friederich** [comment]
Same for me, the stutter, even less frequent is still present. I can confirm that this is the case when the video is completely cached.

**Comment by TRtomasz** [comment]
Is it a full hd video or maybe 4k video?

**Comment by pa-friederich** [comment]
A full HD video

**Comment by TRtomasz** [comment]
Please try using our latest update, maybe now issue will be fixed.
