### ISSUE TITLE
Subtitle delay is not working on firestick

### ISSUE THREAD

**Issue by FernandoGarcia** [Stremio/stremio-bugs#265]
Hi!

I'm facing a problem with subtitle delay on firestick. The time adjust does nothing.

I was using version 1.3.4 and now I have 1.3.5 from APK mirror and the problem is the same.

On windows version it works perfectly.

Best regards.

**Comment by jaruba** [comment]
Hi, can you ensure that you are using external subtitles (from addons) and not embedded subs (from the video) when this happens?

The difference between them should be clear in the subtitle selection screen, if it is not, a screenshot / photo of this screen would also help.

**Comment by FernandoGarcia** [comment]
Hi!

I have sure the subtitles are from external source. 

In subtitle window sometimes there's many subtitles options and the problem happens with any.

Best regards.

**Comment by jaruba** [comment]
What Android TV version are you running? And what Fire Stick? (device version, and is it the 4K device or not?)

**Comment by jaruba** [comment]
Thank you for the detailed information, we will do our best to attempt to reproduce and find a solution to your issue.

**Comment by nando182** [comment]
Hi, I do have the same issue and my stremio is the lasted one, 1.4.4, running on fite stick 4k

**Comment by nando182** [comment]
@jaruba , any news?

**Comment by jaruba** [comment]
@nando182 the issue that was initially posted has been fixed a long time ago, it should not be present in v1.4.4 or v1.4.5

are you sure that you still have this issue? can you confirm that your issues are with external subtitles? can you give us some steps to reproduce your current subtitle issues?

**Comment by nando182** [comment]
Hi @jaruba, I did a new test today and it has been fixed on V 1.4.5.

Thank you!

**Comment by jaruba** [comment]
@nando182 glad to hear it
