### ISSUE TITLE
DeprecationWarning:

### ISSUE THREAD

**Issue by natecoy42967** [Stremio/stremio-bugs#266]
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:11112) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
C:\Users\natec\AppData\Local\Programs\LNV\Stremio-4\node.exe[11112]: c:\ws\src\util-inl.h:408: Assertion `(ret) != (nullptr)' failed.
 1: 00AA717F
(node:6992) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
C:\Users\natec\AppData\Local\Programs\LNV\Stremio-4\node.exe[6992]: c:\ws\src\util-inl.h:408: Assertion `(ret) != (nullptr)' failed.
 1: 00AA717F
(node:3096) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by TRtomasz** [comment]
Hi, this issue should be fixed now, could you confirm?
