### ISSUE TITLE
desktop version 4.4.120 Windows 10 - jumping forward during serie/movie (arrow keys)

### ISSUE THREAD

**Issue by dratiom** [Stremio/stremio-bugs#267]
When launching a serie/movie & jumping forward a couple of times (settings are set on + 10 sec and -10 sec) somtimes it doesn't jump forward, but backwards for 15 to 20 sec. This doesn't happens always but is quite annoying when fast forwarding for specific parts.

**To Reproduce**
1. Launch stremio + select movie/serie + fast forward  a couple of times (doesn't happen always)  untill it jumps back

**Expected behavior**
No jumping back when fast forwarding.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.4.120

**Comment by TRtomasz** [comment]
Hi, did you wait for movie to load or you were trying to seek before it event started loading?

**Comment by AlanVek** [comment]
I had the same issue. I think it has something to do with the progress bar not updating properly when it's hidden. So when you hit the arrow keys, it jumps to +-10 seconds relative to the out-of-date time point. If you make the progress bar visible, wait for it to update to the current time point and then tap the arrow keys, it works fine. It's a bit annoying, though.

**Comment by TRtomasz** [comment]
@AlanVek Progress bar is like that on purpose. Huge performance benefit. 
Also i can't reproduce issue you are talking about, if you can record a video to see it would be helpfulf

**Comment by dratiom** [comment]
Hi, the movie was still loading but in both cases (fully loaded/ongoing) you sometimes get this problem. Video is also difficult to track it because you will to know how the plot of the movie goes (to be able to identify the repeat part).

Can i put a trace on the app/code while i"m watching a movie. I can send that afterwards?

**Comment by AlanVek** [comment]
https://vimeo.com/519628080 Here's an example of the behavior. After the progress bar disappeared, I waited for about 15 seconds and at 0:22 I hit forward. As you can see, it only forwarded 10 seconds relative to the time when the progress bar disappeared, so it actually went back about 5 seconds. Sorry for the spoilers, by the way.

**Comment by jaruba** [comment]
A hotfix for seeking has just been released, it will become available to all users within one hour. You will need to restart Stremio after 1 hour and update from the green notification on the bottom of the User Interface, after which seeking should show as expected.

Please reopen the issue if u still have issues eith seeking after the next update.
