### ISSUE TITLE
Titles removing themselves from library

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#268]
**Describe the bug**
Sometimes a tv series are removing themselves from the library just by watching them. It happened 3 times already for me that after watching a couple of episodes I'm going back and can't see them the library anymore. I needed to add them again. Fortunately it remembered all data about it like which episodes were watched and I can continue watching. It doesn't do that every time though.

**To Reproduce**
1. Open a TV series from your library
2. Watch a couple of episodes
3. Go back
4. See it's not in the library anymore

**Expected behavior**
It should still be in the library, cuz I haven't click to remove it. Especially I couldn't do that while watching.

**Desktop (please complete the following information):**
 - OS: Windows 8.1 64bit
 - Browser [e.g. chrome, safari] Desktop App
 - Version [e.g. 22] I guess the newest one

**Comment by maxoku** [comment]
Today it happened again with two TV series. I opened an episode and allow it to be buffered. After going back they weren't in my library anymore. I needed to access them from the board and add them again.

**Comment by TRtomasz** [comment]
Hi, does it happen only when opening series from library? Do you have to watch couple episodes or one is enough or maybe it is happening even when you exit in the middle of a episode?

**Comment by maxoku** [comment]
Opening one episode seems to be enough. I don't have to watch it whole it seems, like I said I only buffered them and then after going back they were removed from library. With one tv series it happened after I watched the whole season 1 and it switched to a special episode, I went back (cuz I wanted to watch season 2) and I saw button to add the series instead of to remove (like when it's added to library). So I guess it's like random, hard to tell when it'll happen.

**Comment by TRtomasz** [comment]
Hi,
We could not reproduce this issue, also looks like for some reason you are the only one affected.
Last thing youca can try is to delete content of this folder `%localappdata%\Smart Code ltd\Stremio`

**Comment by mindtrapper** [comment]
This happens to me too in one of my PCs (my main one). Doesn't happen in another pc I tried or on Android.

Tried uninstalling and reinstalling but still the same. Very weird.

**Comment by ItsRogueRen** [comment]
I see this happen as well. I'll have an anime I'm watching and I'll go to watch the new episode this week, and it's suddenly not on my library anymore. This happens on several shows for seemingly no reason, even if it's been in my library for months
