### ISSUE TITLE
New episode notifications work wrong

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#270]
**Describe the bug**
Sometimes new episode notifications work wrong. Some series that has that option disabled show new episode and those that have it enabled don't. In some cases it works properly. Looks like it works randomly.

**Expected behavior**
That those series that has this option enabled always would show new episodes and those with option disabled would never show it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 8.1
 - Browser [e.g. chrome, safari] Desktop app
 - Version [e.g. 22] 4.4.120

**Comment by maxoku** [comment]
I wasn't notified about a new episode again after almost a week I just accidentally found out. I usually can get from the calendar that something new is up, but this tv show for some reason doesn't have a cover so it's not showed on the calendar, though it is on the list.

For last week I seem to not get any new notifications for new episodes. Was the functionality turned completely off or something?

**Comment by Ivshti** [comment]
@maxoku thanks for reporting this, we're working on it!

**Comment by TRtomasz** [comment]
Hi @maxoku  can you confirm please that you have new notifications now?

**Comment by maxoku** [comment]
Yeah, I suddenly got all old notifications that I haven't got from last 2 weeks and new ones from the yesterday as well. Thanks for restoring them.

**Comment by TRtomasz** [comment]
Great! thanks for confirming!

**Comment by maxoku** [comment]
Notifications returned, but they still work wrongly. E.g. I had new episodes for 2 tv series today, but I have notification only for 1 of them. I just noticed looking at calendar. Fortunately latest update fixed the cover problem with that series, so I was able to notice it.
It would be nice if the whole problem would be solved, not only one part.
So please reopen the issue until it will be fixed completely.

**Comment by maxoku** [comment]
Yesterday my notifications came late after 2 pm. Today I have only one new episode and still after 5 pm I haven't got notification from it.
@Ivshti @TRtomasz so reopen the issue please and fix those problems. You only restored not having any notifications that happened later, but they still work wrong.

**Comment by TRtomasz** [comment]
I reopen for now as we are observing notifications now. Although you have remember that notifications will not be immediate it might take some time for them to show up.

**Comment by maxoku** [comment]
I don't need them to show up immediately, but waiting few hours for them is not expected behaviour. I've seen new episodes in the morning yesterday, but notifications for them came out after 2 am. All 4 notifications appeared at the same time yesterday, so it looks like notifications are set to just appear at specific time.
It's almost 8 pm and the notification for today just appeared. That is very late, too long to appear.

**Comment by maxoku** [comment]
Two of my tv series had new episodes today.
First when appeared took a short time to get notification. So that one worked as supposed.
The second one got new episode little later, but notification appeared about 6 hours after that. It was about 10-11 pm, so that's rather a long waiting.

**Comment by maxoku** [comment]
Yesterday's notification came today, about 20 hours after the episode appeared. That's very late.

**Comment by maxoku** [comment]
Today in the evening I've got notifications from last three day. And even despite I've already watched them before they were still marked as new episodes.

**Comment by jaruba** [comment]
@maxoku thank you for keeping us updated with your experience, we are actively trying to improve the new episodes notifications.

**Comment by maxoku** [comment]
I had 3 new episodes on Monday, for 2 of them I've got notifications. Looking at calendar for the 3rd one I would got it today if I already haven't watched it. I just was observing the cover in the calendar to go half transparent and it happened today.

Yesterday's notification came at time, which is surprising cuz usually this one was comming very late. Though the cover in the library didn't get the new episode tag. A lot of series that have notifications turned off still get this tag though.

Two new episodes for today still haven't got their notifications while it's 11 pm already.

**Comment by maxoku** [comment]
Notifications work the same. It's random to get them on time or delayed. Some notifications won't appear after I watch the episode earlier, but some do. Unfortunately calendar stopped showing some tv series and it's hard to determine if there are new episodes for them if the notification won't appear. Though I'm getting notifications from them, but mostly delayed.

Another problem is that if there are multiple episodes released at the same time I get e.g. notifications for the last 3 episodes. It would be better if I've got only one notification for the first episode.

**Comment by maxoku** [comment]
So notification comes once in about 2 weeks and showing even already watched episodes, so nothing's changed.

**Comment by jaruba** [comment]
@maxoku 

different team members tried fixing this issue many times and it just didn't work, we also upgraded the server twice. so we'll start the process of rewriting the notification service in a different programming language.

thank you for keeping us updated on ur experience, it means a lot and keeps us focused on solving it!

**Comment by maxoku** [comment]
Oki, thanks for letting me know. I hope it'll work, I'll be waiting for updates.

**Comment by maxoku** [comment]
I've got notifications today from last week updates. Interesting is that from a pack of 5 new episodes that were released together only the first one was in notifications. So I guess it's a progress. Unfortunately all notifications were about already watched episodes.

**Comment by M4dKiwi** [comment]
Notifications have been few & far between now for months, they are now non existent (windoze 10) , 
I cleared my notifications on new years day & have yet to see a single notification - 
strange because 'Book of Boba Fett' has had its third episode allready (as well as many new episodes to other series IK used to get notified for) , such a shame as the original notification system was perfect (even if a day late)

**Comment by Light7654** [comment]
Yes I also didn't get notification even I subscribed to my windows calander

**Comment by M4dKiwi** [comment]
Before I saw this report I posted this issue, sadly it was closed without explanation ,I hope it hasnt become like popcorn time
(disbanded by creators no longer interested ). It was 1 of the best features so I dont get why it stopped working,
I'm sure it could be solved if we knew why its challanging - it is open source isn't it?

**Comment by jaruba** [comment]
> I hope it hasnt become like popcorn time (disbanded by creators no longer interested ).

please calm down, nobody abandoned / disbanded anything

> It was 1 of the best features so I dont get why it stopped working

influx of users

> I'm sure it could be solved if we knew why its challanging

it definitely can be solved, but it is a very complex task

> it is open source isn't it?

notifications are handled by our servers, the server side code is not open source

**Comment by jaruba** [comment]
new episode notifs should start showing again soon, they will still (generally) show later than expected though

**Comment by M4dKiwi** [comment]
Woohoo! , thank you (after having cleared my notifications & having no updates for a while)
good to see a bunch of notifications working today, thank you for resolving / working on this.
Stremio (& its contributors) Rocks!

**Comment by jaruba** [comment]
@maxoku hi, are you still having issues with receiving notifications?

**Comment by maxoku** [comment]
@jaruba Notifications still seems to work the same, having lately them once a week or something.

**Comment by M4dKiwi** [comment]
Seems alot better now, thanks for the behind the scenes work - occasionally I can beat the notifications as there seems to be a slight delay but the main thing is they (links) are still fresh when the notification arrives within 24hrs ,
I wonder if an add on may make all the difference as to which library torrent database's to also check for updates but that would be a bonus ,Im glad to have Stremio working the way it used to again :)

**Comment by jaruba** [comment]
@maxoku users have started reporting that their notifications are coming in properly now, if you are sure that they are still coming in late for you, could you email me (my email is public on my github profile) the email address you used for ur Stremio account? that way we can check if there is an issue specific to ur account

**Comment by maxoku** [comment]
I didn't have any notifications for 3 weeks and they all just appeared today.

**Comment by TRtomasz** [comment]
I think we can close this issue, my notifications are working fine and we have no users reporting issues with notifications. In case this repeats please create  a new issue.
