### ISSUE TITLE
[Windows] [cinemeta/opensubtitles] No subtitles

### ISSUE THREAD

**Issue by m0rpheas** [Stremio/stremio-bugs#271]
**Describe the bug**
No subtitles. My settings: UI language: Greek, default subtitles language: Greek. Latest version of Stremio on Windows 10 and official Opensubtitles add-on. I see there have been some recent changes in the stremio-opensubtitles add-on repo, maybe this is related to the error? So far I only experience it when selecting stuff from cinemeta catalog, TMDb catalogs work fine.

**To Reproduce**
1. On Windows, select any item from the official catalog (Cinemeta)
2. Hit play (content source is irrelevant)
3. Subtitle button does not appear in the player, no subtitles are displayed/loaded.

**Expected behavior**
Opensubtitles should return results, button should appear. An example movie you could try this on is Joker (2019). Select it from the default (cinemeta) catalog first to see the bug. Then try TMDB catalog (add-on). Use the same source file for playback. In my setup, UI language was Greek and subtitle language was set to Greek too.
You'll see that when selecting the exact same item from eg. TMDB catalog and picking the exact same source file to be played, subtitles work just fine. Must be an ID issue, and OS-specific.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: latest public

**Comment by m0rpheas** [comment]
Hereby reporting that the bug does not occur on Android. It is on the desktop client.

**Comment by jaruba** [comment]
@m0rpheas this should be fixed with yesterday's update, please confirm that subtitles are working as expected for you now
