### ISSUE TITLE
Windows - Subtitles addon not loaded (example)

### ISSUE THREAD

**Issue by dratiom** [Stremio/stremio-bugs#272]
Hi,

When launching a movie normally there is always at the bottom right a subtitles icon on which a user can click. In some cases when loading a movie, this isn't visible & hence no subtitles are downloaded/visible.

In the past even if there aren't any subtitles available you would still see this icon.

OS: Windows 10

![image](https://user-images.githubusercontent.com/80009250/111205723-d563b680-85c7-11eb-84a1-9855225edcd2.png)

Example of a video to show:

https://user-images.githubusercontent.com/80009250/111206194-5e7aed80-85c8-11eb-89c1-29ee33b4c2b4.mp4

**Comment by TRtomasz** [comment]
Please check if you have subtitles addon installed in the addons settings.

**Comment by victorgveloso** [comment]
Please check if a movie from TMDB catalog works. It seems to be an issue with Cinemeta and IMDB's ID.

Btw, this is a duplicated issue. Please consider contributing to the discussion at #271

**Comment by TRtomasz** [comment]
Hi, this should be fixed now, could you confirm?

**Comment by dratiom** [comment]
yup is solved, thx
