### ISSUE TITLE
Add support for 2021 in the Discover tab

### ISSUE THREAD

**Issue by yannickboy15** [Stremio/stremio-bugs#274]
**Describe the bug**
As the title says, right now there are movies and series made in 2021. When filtering by year, only 2020 is shown. 2021 should be added to those.

**To Reproduce**
1. Go to Discover
2. Click on Movies
3. Click on By Year
4. 2021 missing from the list

**Expected behavior**
A list including 2021.

**Comment by Ivshti** [comment]
Currently this is a known issue related to the updating of addons. If you're using Stremio anonymously without an account, the Cinemeta addon cannot be updated

@TRtomasz are you aware of any workarounds?

**Comment by yannickboy15** [comment]
@Ivshti 

I saw this old tutorial about using the addon:
https://github.com/Stremio/stremio-addons/blob/master/docs/tutorial/using-cinemeta.md

I assume it's being included into the UI, if we intercept the element they use to display those years, couldn't we manually add it in? I assume the query looks into all movies containing a 2021. I assume it should then be a matter of UI tweaking in order to make it work.

If it checks in their backend against 2021, then we indeed have no way to adjust this. Who made Cinemeta and is it eventually open source, so we can fork or make a PR to it?

**Comment by Ivshti** [comment]
It doesn't work like this.

What happens is that Stremio caches the manifest of the addon locally for the account. This is how the manifest looks like: https://v3-cinemeta.strem.io/manifest.json - you'd notice it includes 2021, but stremio has already cached the old one for you.

There are a few solutions that you can do: either make an account, or clear all data/cache.

But will probably work on ways to resolve it on our end too.

**Comment by yannickboy15** [comment]
I see, I've got an account but that seems to not update it then either. I assume uninstalling/reinstalling will do the trick? But that way we then found a bug in triggering an update in cache.

**Comment by yannickboy15** [comment]
Confirmed, seems to be fixed now!

**Comment by TRtomasz** [comment]
That is great! thank you for your help :)
