### ISSUE TITLE
stremio subtitle bug

### ISSUE THREAD

**Issue by ReaLJohnBaker** [Stremio/stremio-bugs#275]
All media players i've tried show the subtitles normally but not stremio, see linked comparison carefully below:

http://www.framecompare.com/screenshotcomparison/KGYWLNNX

as you see the subtitles are too high & small, ALL DEFAULT SETTINGS

OS: Windows 10

**Comment by TRtomasz** [comment]
Thats not a bug it is matter of preferences.
