### ISSUE TITLE
Subtitles error

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#277]
**Describe the bug**
Almost every time I load a video I'm getting an error about loading subtitles. They're annoying and appears regardless if subtitles are loaded or not.

**To Reproduce**
1. Load a video
2. See an error

**Expected behavior**
I would like to not see any error. Mostly is a false alarm and even if subtitles are not loaded then I can see it myself that icon is missing, so I don't need an annoying error. Not mentioning that mostly don't use any subtitles. Let the error show maybe if I try to use subtitles that aren't loaded or something. It doesn't make sense to have an error if I don't use any subs at the moment.

**Screenshots**
![strem sub](https://user-images.githubusercontent.com/17256400/113217293-03aaec80-927e-11eb-9ac6-ddd207f845e8.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
![stremio ver](https://user-images.githubusercontent.com/17256400/113217349-1ae9da00-927e-11eb-9548-36e9326cad3c.jpg)

**Comment by TRtomasz** [comment]
Hi, this usually happens when you have multiple subtitles addons installed and one of them fails to respond in correct way. If you remove this faulty addon the warning will be gone.

**Comment by maxoku** [comment]
Strange, I see only one subtitle addon, the official OpenSubtitles. I thought about it the first time I saw this error and remove other subtitles addons. The error was still on.

**Comment by maxoku** [comment]
Still getting the annoying error while not having any subtitles addon besides the default one. The official one can't be removed or turned off. I need subs only on Japanese anime, so I wouldn't mind to have it just turned off to not annoy me with a false error. Unfortunately it can't be, so I don't know what else I can do to stop it.

**Comment by TRtomasz** [comment]
Hi, i still think it is one of your addons, could you please try to use a new account or guest account with addons only required to play this show + opensubtitles addon installed?

**Comment by maxoku** [comment]
I don't know how to do this. Nevertheless I just disabled OpenSubtitles and still got the error. After disabling there were only embeded subs on some videos. I guess that the link provider might have a problem with fully loading own subs. If that's the case then this addon can't be disabled, cuz I wouldn't be able to watch anything, so it wouldn't make sense. And I doubt it's the problem with addon itself. There will always be a problem with connection. The best solution is to just disable useless error messages.

**Comment by TRtomasz** [comment]
Could you tell us what you dont know how to do? Simply log in to the app with different account or as a guest user. Then add addon that provides streams for the content which cause the error and simply try to play it. Guest option is available after you click "Sign up wti email"
![image](https://user-images.githubusercontent.com/40594253/115571313-ca7efe80-a2b6-11eb-9cab-26951f886312.png)

**Comment by maxoku** [comment]
Oki in guest it played without any error after installing everything that I had in my profile. Seems I had an outdated addon that after uninstalling I couldn't find anymore on the list. Though that addon wasn't a subtitles addon, only providing links. If it affected subtitles it should state that. There is no subtitles category in the addon list, so if it's not stated in description no one would know that it affects subtitles.

This problem was solved, but it can easily appear again. So I suggest to make two improvements to prevent this.
First that addons should be marked if they affect subtitles. So if anyone would get such error they could isolate faulty addons.
The second that outdated addons should be mark as well to know that they might not be supported anymore, so can produce errors like this one.

Thanks anyway.

**Comment by maxoku** [comment]
Suddenly the error started to show again when I didn't install any new addon. I decided to remove one addon that gives links, I suspected and that helped. Even after reinstalling it the error haven't shown up again. Maybe it was outdated, but still have the same version.
Nevertheless I just wonder how an addon that gives links can affect subtitles while I'm watching video from a link that was provided by another addon? That just doesn't make any sense.

**Comment by TRtomasz** [comment]
Can you please tell us which addon was it so we can verify this? Also we will add addon name to the error message in the next release so in the future it will be easier to debug.

**Comment by maxoku** [comment]
The first addon I don't remember anymore, the second addon was MyAnimeStrem+. I was watching anime at the moment, so I thought that addon might be responsible. I looked for addons in other category, cuz I guess subtitles addons fall to that category.

**Comment by TRtomasz** [comment]
With latest update, now we display the title of the addon that is failing, so if you still see this error now you will know which addon should be removed.
