### ISSUE TITLE
Series catalog doesn't show

### ISSUE THREAD

**Issue by Jaba87** [Stremio/stremio-bugs#279]
Hi,
I used to have an option in "Discover" for Movies and Serieses.
for about a month or two i can only see the movies catalog, with no series option

**Desktop information:**
 - OS: WIN10 home
 - Browser: chrome,
 - Version 4 beta

![000](https://user-images.githubusercontent.com/81981535/113599204-f5c2e600-9646-11eb-9d77-0dd866a759b7.JPG)

**Comment by Ivshti** [comment]
@jaruba that's an interesting case, we should check it

**Comment by jaruba** [comment]
@Jaba87 Please go to the Settings page and take a screenshot of the versions shown in the bottom left corner of the Stremio window.

**Comment by Jaba87** [comment]
![000](https://user-images.githubusercontent.com/81981535/113609703-cf0bac00-9654-11eb-8559-c1a9f46ed400.JPG)

**Comment by jaruba** [comment]
@Jaba87 are you logged in to a Stremio account? if so, log out and restart the app, and check if you can see the catalogs

**Comment by TRtomasz** [comment]
@Jaba87  could you give us a list of all addons that you have installed? could be in form of screenshot

**Comment by Jaba87** [comment]
that's a lot, it counts only movies and series add-ons, almost most of them

**Comment by jaruba** [comment]
@Jaba87 Tomek encountered the same issue for a different user and it got fixed by uninstalling a broken addon. This might be the issue in ur case as well.

**Comment by Jaba87** [comment]
i've been uninstalling them all and it worked! 
i've installed a few add-ons to check if one of them was the problematic one but everything looks fine now.
thanks!
