### ISSUE TITLE
Data Export not working (Error on dataExport) on Web/Desktop app.

### ISSUE THREAD

**Issue by frykauf** [Stremio/stremio-bugs#280]
Data export doesn't work (shows Error on dataExport) in both Stremio website and in Desktop app (btw. I'm on macOS).

**Comment by jaruba** [comment]
@frykauf 

Hi, this seems to be happening to some Stremio accounts only. Luckily, I also got this error with my own account as we tested it today, so we will look into fixing it.

Thank you for reporting it!

**Comment by TRtomasz** [comment]
seems to be fixed
