### ISSUE TITLE
Subtitle default language scrollbar can't be dragged in desktop app

### ISSUE THREAD

**Issue by Araxeus** [Stremio/stremio-bugs#281]
**Describe the bug**
When going to settings - player - Default Subtitle Language
the dropdown menu is long and has a scrollbar.
Said scrollbar can't actually be clicked and dragged.
(mouse scrollwheel / arrowkeys still works)

**To Reproduce**
1. Go to Settings
2. Click on Player
3. Open "Default Subtitle Language" dropdown menu
4. Try to click & drag the scrollbar

**Expected behavior**
Scrollbar can be clicked and dragged

**Actual behavior**
Scrollbar color change when clicked but can't be dragged

**Screenshots**
 <details>
  <summary> Click to view Screenshot of said menu-</summary>
  
![21-04-2021 17 33 38](https://user-images.githubusercontent.com/78568641/115571985-2aca6c00-a2c8-11eb-9c54-0a0f93796d37.png)
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [19042]

**Additional context**
This is probably unrelated, but loading a video never automatically loads the subtitle for me
(unless I already set the subtitle for that specific video, and then its saved)

This is especially annoying when the next episode is automatically played but I need to get up, go to my pc to set the subs again..
I always need to manually set it to English (even tho as you can see in my settings its set to English)

I should note that I'm only using the plugin that was automatically installed - OpenSubtitles
Am I missing something here? or is that also a bug?

**Comment by jaruba** [comment]
I have tested and can confirm the bug, thank you for reporting it!

**Comment by Araxeus** [comment]
thanks for looking into it.

any info about the automatic subtitle loading?
is the player actually supposed to auto load subtitles in the selected language or is my client somehow bugged?

**Comment by jaruba** [comment]
It should definitely automatically select the subtitle language.

**Comment by TRtomasz** [comment]
It will not work with embedded subtitles though

**Comment by TRtomasz** [comment]
I will close this issue, as this is low impact and it turned out we can't fix it with a simple change.
