### ISSUE TITLE
Streaming server has thrown an error

### ISSUE THREAD

**Issue by vperpl** [Stremio/stremio-bugs#282]
**Describe the bug**
Used to work, now it doesn't.

Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:19532) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
C:\Users\Xan\AppData\Local\Programs\LNV\Stremio-4\server.js:42979
  throw err;
  ^

Error: Text data outside of root node.
Line: 4
Column: 17
Char:

**Comment by laNuez** [comment]
Any news to this? Im getting the DeprecationWarning every 2 minutes and when i press ok the stream stops working and i have to restart it
