### ISSUE TITLE
Can't add to library if can't fetch the data

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#285]
**Describe the bug**
Some movies or series (and youtube channels) are blank after opening them. There's an error fetching item data. Sometimes it shows links though. Problem here is I can't add it to the library anymore. I could do that some time ago, but after one of updates I can't anymore. I get it that I can't do much with a movie or tv series if it can't fetch data, but it could be fixed in the future, but then I might forget about this movie or tv series. So I would like to save to the library now and e.g. get notified in the future when tv series will be aired.

**To Reproduce**
1. Find a movie, tv series or youtube channel (that has a fetching data error)
2. Open it
3. See an error on fetching data
4. Button to add it to the library vanishes immediately.

**Expected behavior**
Button should stay so I could add it to library despite of the error.

**Screenshots**
![stremio error fetch](https://user-images.githubusercontent.com/17256400/117047428-27949e80-ad12-11eb-9c50-a3ce093223db.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 8.1
![stremio ver2](https://user-images.githubusercontent.com/17256400/117047389-1cda0980-ad12-11eb-8a24-ea1c247c8890.jpg)

**Comment by krapgras** [comment]
I have this same bug. Mainly on youtube channels. But i have a feeling this is more linked to the youtube plugin rather then stremio itself.

**Comment by maxoku** [comment]
> I have this same bug. Mainly on youtube channels. But i have a feeling this is more linked to the youtube plugin rather then stremio itself.

I don't think so if it happens also to movies and tv series.

**Comment by TRtomasz** [comment]
This simply means stremio does not have data about particular video/movie/series or youtube channel.

**Comment by maxoku** [comment]
Hawkeye tv series and I see something like that:
![image](https://user-images.githubusercontent.com/17256400/143324925-ee9e984c-5488-4b90-94de-e6ecb56056eb.png)
There are 2 episodes already.
Well at some point it works it seems, but I can't add it to the library, so every time I have to search for it to watch.
Even if there is no data it would be nice to add it to the library for future when that would be added.

**Comment by maxoku** [comment]
Hawkeye added properly now, thanks.

**Comment by TRtomasz** [comment]
This is added now 
![image](https://user-images.githubusercontent.com/40594253/166889022-ad3d31ab-c65d-4c68-8d77-5498a002bc0f.png)
