### ISSUE TITLE
Bug: Search results scroll back to top after interacting with results

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#286]
**Describe the bug**
Search results don't maintain scrolled position after interacting with results.

**To Reproduce**
1.Search for a series
2.Scroll down
3.Click on a search result
4.Press the back button
5.You will find that the search results have gone back to the top of the page.

**Expected behavior**
The expected behavior would be that the search scroll position is maintained and is not reset to the top of the page

**Desktop (please complete the following information):**
 - Windows 10 home
 - Stremio 4.4.137
 - WebUI 4.4.137
 - Server 4.16.0

**Comment by TRtomasz** [comment]
Hi, looks like this is fixed in the latest stremio version - 4.4.142

**Comment by rp1231** [comment]
Hi, 
I can confirm that it has been fixed.
Thanks
