### ISSUE TITLE
Too big subtitles and cant adjust size of it while casting to TV Stick

### ISSUE THREAD

**Issue by tolgayavuz** [Stremio/stremio-bugs#287]
Hi there,

When I cast a movie from my android phone to my Mi TV Stick, subtitles are too big almost cover half of the screen and adjusting the size from both stremio settings and tv settings won't effect.

**Comment by TRtomasz** [comment]
Please use the template when reporting an issue

**Comment by tolgayavuz** [comment]
**Describe the bug**
When I cast a movie from my android phone to my Mi TV Stick, subtitles are too big almost cover half of the screen and adjusting the size from both stremio settings and tv settings won't effect.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to any movie/video from any source doesn't matter.
2. Click on chromecast icon.
3. Select a subtitle and turn subtitles on.
4. Try to change size of subtitle in subtitle settings.
5. See the adjust size is not works and subtitle size are almost half of screen.

**Expected behavior**
I would except when I adjust the size of subtitle in my stremio app in my smartphone it changes the size of chromecast too.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Version: Stremio Android 1.3.6

**Additional context**
Also changing color/background color of subtitle is not working too.

**Comment by TRtomasz** [comment]
Hi,
Please tell us if this still happens with latest 1.4.4 release?

**Comment by tolgayavuz** [comment]
> 
> 
> Hi,
> Please tell us if this still happens with latest 1.4.4 release?

Hi,

Problem seems fixed with a normal size subtitle. Can we adjust subtitle size from phone or we have to adjust size from tv-stick settings?
I tried to change size from stremio (in phone) while video playing but seems like nothing happens.

**Comment by TRtomasz** [comment]
Closing this issue as we have released new app version just for android TV.
