### ISSUE TITLE
Can't play with MPV on Linux.

### ISSUE THREAD

**Issue by rizzini** [Stremio/stremio-bugs#289]
I'm trying to watch movies on MPV, but an error shows up. Inside Stremio, works just fine.

The log suggests I don't have whatever permissions at `/opt/stremio/`. Already tried to recursively give it full permissions (777 or -rwxrwxrwx), just for testing, nothing changed.

OS: Arch Linux
Kernel: 5.10.33-152-tkg-upds
MPV: 0.33.1-dirty
Stremio: 4.4.135. Same hapens on 4.4.137(beta).
Web UI: 4.4.137
Server: 4.15.0

![image](https://user-images.githubusercontent.com/1186150/117661714-19f97180-b175-11eb-895e-0c10d2120c89.png)

```Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:218173) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:343
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (node:fs:583:3)
    at Object.writeFileSync (node:fs:2144:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:133661:36)
    at IncomingMessage.emit (node:events:377:35)
    at IncomingMessage.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
```

**Comment by TRtomasz** [comment]
I can confirm, the same thing happens on ubuntu 20.4 as a workaround, if you dont need subtitles, you can just turn them off.
@core1024  any idea why this is happening?
