### ISSUE TITLE
DLNA to TVs doesn't work when additional network adapters

### ISSUE THREAD

**Issue by MeirionHughes** [Stremio/stremio-bugs#29]
DLNA works perfect in popcorn time (push to tv), but unfortunately doesn't work for me in stremio. I do get the "TV" option show up, but when I click it nothing happens. In popcorn-time, it should spur the TV into playing the content.

**Comment by Ivshti** [comment]
First try doing it again but disable subtitles first from the SUB menu. Most likely that's the issue.

Then try reproducing the error when running stremio with --development flag:

```
%LOCALAPPDATA\Prorams\LNV\Stremio\Stremio.exe . --development
```

For Mac:
```
/Applications/Stremio.app/Contents/MacOS/Electron . --development
```

click on TV and then see what error you get

**Comment by MeirionHughes** [comment]
```
[7244:0103/131458:INFO:CONSOLE(2)] "Player using backend: BRAVIA KDL-42W829B", s
ource: file:///C:/Users/####/AppData/Local/Programs/LNV/Stremio/resources/app
.asar/blob.js (2)
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
[7608:0103/131458:ERROR:v8_value_converter.cc(156)] Unexpected value type: 5
```

that's with subtitles off and the subtitles plugin disabled.

**Comment by Ivshti** [comment]
```
[8912:0103/132003:INFO:CONSOLE(3)] "Error: Action SetAVTransportURI failed (716)
", source: file:///C:/Users/#/AppData/Local/Programs/LNV/Stremio/resources
/app.asar/blob.js (3)
```
that's the key one
I don't know what it means, I'll research

**Comment by MeirionHughes** [comment]
just to be clear though; popcorn time had two options

![](http://i.imgur.com/kvrbAfM.png)

Only the top one ever worked for me.

**Comment by MeirionHughes** [comment]
Okay, figured it out. The problem is with stremio picking the wrong network adapter when making a URI to send to the TV. 

* If I disable every adapter, except WIFI, the option to stream to TV is present and works. 
* If I enable "TAP-Windows Adapter V9" adapter (OpenVPN), the option to stream is present but doesn't work. 
* If I enable an OpenVPN connection, the option to stream to TV is NOT present. 

It seems there is a need to specify a specific network adapter, either through the UI or config.

**Comment by Ivshti** [comment]
Seems useful.

Still, the subtitles problem might exist

Can you dlna with subs?

**Comment by MeirionHughes** [comment]
with only Wifi adapter: the video plays, but no subtitles are shown. 

if I enable the openvpn adapter and connect to vpn, it is no longer able to stream to TV.

**Comment by Ivshti** [comment]
we're pushing subtitles fixes with the next update

as for the openvpn adapter, I don't know what exactly we can do. I have to research

**Comment by MeirionHughes** [comment]
Well, as mentioned popcorn time could only stream to the TV (when using the VPN) with one of two options: 

Shown here as the first option:
![](http://i.imgur.com/kvrbAfM.png)

Presumably that code is available somewhere?

**Comment by Ivshti** [comment]
Closest thing I can find is the butter project, which supposedly inherited their codebase.

However, I cannot think of anything particularly different between the way things are done. Maybe it's something related to binding to IPs  / ports.

As soon as possible, we'll be releasing the casting part of our code into an open source module, this may help identify the issue.

**Comment by MeirionHughes** [comment]
Turns out the top symbol is the DLNA symbol, while the bottom symbol is for "Chromecast"
