### ISSUE TITLE
Subtitles Freezing

### ISSUE THREAD

**Issue by Lerrey23** [Stremio/stremio-bugs#290]
**Describe the bug**
Hi there, i am expierecing a bug with subtitles. This started 1 month ago. Subtitles with every addon on every movie lags and freezes for seconds. It stays on 1 line for a lot longer and the next line appears only for a milisecond, Making me uncapable of reading and understanding the subs of the movie/TV show.
Is there a fix that i could have?
This happens on my Xiaomi mí box and firestick Full HD.

**To Reproduce**
1. Go to 'any movie/ TV show'
2. Click on 'any addon'
3. Also, this happens with every subtitle addon

**Expected behavior**
I would like to have subtitles with no freezes and lags. 

 - OS: [Fire os 5.2.7.8]
 - Version 1.3.5

**Additional context**
This Is the only problem that the app has. Playback is perfect and Ui too. It would be very nice if you would provide me a Solution please. Thanks a lot.

**Comment by Lerrey23** [comment]
Ok but this didn't use to happen before, so i dont know why it's happening. Thanks a lot for the info.

**Comment by TRtomasz** [comment]
Hi, this should be fixed in the latet stremio for android version 1.4.4
