### ISSUE TITLE
(android) loading loop

### ISSUE THREAD

**Issue by stem2580** [Stremio/stremio-bugs#292]
**Describe the bug**
using the anonymous login option everything is 100% working
but when i logged in it opened but it's loading forever
**To Reproduce**

1. open the app
2. login
3. See error

**Expected behavior**
i expect that it should finish loading & show the recommended movies, tv shows & normal stuff

**Screenshots**
![image](https://user-images.githubusercontent.com/37732484/118612019-49cbf900-b7b5-11eb-84be-a3e9b5d5852e.png)

**Desktop (please complete the following information):**
 - OS: chrome os v90 using "android 9 x86" container
 - Browser: chrome
 - Version 1.3.6

**Additional context**
no

**Comment by TRtomasz** [comment]
Hello,
Chrome os is not currently tested and supported by us so sadly we have no means to debug this issue.
