### ISSUE TITLE
Subtitles size reset when selecting embedded subtitles on Android

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-bugs#293]
**Describe the bug**
When opening subtitles menu for videos with embedded subtitles on Android before any of the subtitles addons respond, the subtitles size settings reset to size 8 (or 0 sometimes). Also afterwards if no susbtiles addons have yet responded, but embedded subtitles were selected and the subtitles menu was exited, then after any of the subtitles addons responds, stremio still selects external subtitles without checking if embedded ones were selected, thus you have 2 overlapping subtitles playing.

**To Reproduce**
1. Open a stream with embedded subtitles
2. Click on subtitles menu before any of the subtitle addons respond.
3. Exit the stream
4. Open the same video with embedded subtitles
5. Size settings should have changed to 8

**Expected behavior**
If embedded subtitles are selected it should not reset the size settings and should not try to load external subtitles.

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by jaruba** [comment]
This is a valid bug, thank you for reporting it.
