### ISSUE TITLE
@TRtomasz  i use a android phone and the subtitles are not at all coming but when i see a episode in russian the subtitles option is available ( where you change the speed and all) but when i see that particular episode in English the subtitles are not working

### ISSUE THREAD

**Issue by Kunaal-parikh** [Stremio/stremio-bugs#294]
@TRtomasz  i use a android phone and the subtitles are not at all coming but when i see a episode in russian the subtitles option is available ( where you change the speed and all) but when i see that particular episode in English the subtitles are not working

_Originally posted by @Kunaal-parikh in https://github.com/Stremio/stremio-bugs/issues/233#issuecomment-841076236_

**Comment by TRtomasz** [comment]
Please use template when reporting an issue 
![image](https://user-images.githubusercontent.com/40594253/119658428-09a7ee80-be25-11eb-9103-2cdd63972021.png)
Also please remeber that stremio does not control available subtitles, they are provided by addons. In this case opensubtitles addon. So it is possible that for video you tried to watch there simple are no subtitles.
