### ISSUE TITLE
Stremio on Amazon stick 4k often crashes, or loses audio if skipping or rewinding video

### ISSUE THREAD

**Issue by wonbinbk** [Stremio/stremio-bugs#298]
Like the title said, I install the official apk on the website to Amazon stick. Most of the time Stremio runs fine and I am happy with it. Just a few bugs like said above. I don't know how to get a log out so you can debug or know more about the problem.

**Comment by TRtomasz** [comment]
Please try out our latest release, you can download it from our webpage. Please let us know if it still happens.

**Comment by aSapien** [comment]
Same issue here, Stremio ARM 1.5.5
