### ISSUE TITLE
Some tv series vanished from calendar

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#299]
**Describe the bug**
Few weeks ago some tv series just stopped being displayed in the calendar like they weren't in library, but they are. I can even get notifications from them (but mostly delayed), but they're not in calendar at all. Not only cover thumbnail is missing from the calendar, but also those tv series are not displayed on the list on the right as well.

**To Reproduce**
1. Open tv series from library
2. See new episodes and their date
3. Go to Calendar
4. See that those tv series are not in the calendar for those days or anywhere else

**Expected behavior**
All tv series that are in the library (especially those with turned on notifications) should be displayed in the calendar.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 8.1
![stremio ver](https://user-images.githubusercontent.com/17256400/121784265-5294cc80-cbb3-11eb-9dd4-b578f42e69c2.jpg)

**Comment by TRtomasz** [comment]
Calendar is limited to 50 entries as far i remember, so if you have more series in the library then some of them will not be displayed in the callendar

**Comment by maxoku** [comment]
@TRtomasz what means 50 entries? 50 tv series or 50 episodes? There's 54 episodes on the list, so I guess it's tv series.

And 50 include all tv series that are in the library or only those which have updates? Cuz it wouldn't make sense if inactive tv series would prevent active ones to appear on the calendar making it practically blank. And it's not that I suddenly significantly increased number of tv series in the library that some had to vanish.

I have as I counted 120 tv series in the library, but only about 8 have updates and I watch regularly now, about 2 that had one day updates, plus few that are updating, but I have notifications turned off, cuz I don't watch them at the moment. Is this too much? It's not that month ago numbers were much different though.

If on calendar is too much entries wouldn't make sense that tv series with updates got priority and be displayed instead of those with turned off notifications? Cuz I still see on calendar those tv series I don't watch at the moment and don't see those that I watch.

Besides I don't really see calendar would be overwhelmed while 9 days are still empty, 6 have only one entry, 6 two entries and 8 with 3 entries. There's still a lot of space to display episodes.

**Comment by TRtomasz** [comment]
@maxoku  50 entries from library

**Comment by maxoku** [comment]
@TRtomasz So it's random which tv series appear in calendar regardless of how many would be in the calendar?
And I still don't understand 50 entries from library are tv series or episodes?

If it's tv series then I have only about 10 in calendar. If it's episodes then there are 54 in current month. But even removing one tv series from library that results in removal of 17 episodes packed in 4 days doesn't help and nothing more appears in the calendar.

Nevertheless a month ago everything was okay. Were you modifying the calendar lately? As I see it right now it's more in order than before which reminds me my feature request about prioritizing in cover's order. But at the same time some series just vanished from it.

Just check it out, cuz I don't think it should work like this, cuz it wouldn't really make any sense while before it didn't have any problems to display more entries in the calendar.

**Comment by TRtomasz** [comment]
Hi
1 entry is one whole series, so you have only 10 series in the library added at the moment? Please tell me for which exact series you don't see calendar entries?

**Comment by maxoku** [comment]
@TRtomasz No, I have 120 tv series in the library, I said I have 10 that I see in the calendar this month, in all months I see 16.

So if there's limit to 50 then it's not reached. Unless it puts empty tv series that has no updates then it might reach the limit, but then it doesn't seem to work like suppose to, cuz those that are updating should get prioritised, otherwise the whole calendar might be empty if wrong entries were entered to the calendar.

The tv series that is running now and now showing in the calendar is "Superman & Lois" that updates every Wednesday lately. I wouldn't even know it's updating again if I didn't get a notification, which unfortunately was few days delayed like all next ones.

**Comment by TRtomasz** [comment]
Ok i checked and limit is 80. But it does not matter if they currently have any entries in the calendar or not just 80 elements from your library. @jaruba  should we increase this limit?

**Comment by jaruba** [comment]
@TRtomasz yes, I think we should increase it, doubling it to 160 should be enough for now imo.

**Comment by maxoku** [comment]
That would be nice.
Though it I think that maybe excluding some series manually from appearing in the calendar would be nice to put in the future. And generally view which ones are loaded to the calendar would be good too. Some kind of control over which series would appear in the calendar and which not if it works that way. Should I make a feature request?

**Comment by TRtomasz** [comment]
@maxoku  we bumped value to 120 series

**Comment by maxoku** [comment]
@TRtomasz Great thanks, but wasn't that suppose to be 160? I have 128 series now. Nevertheless I don't see any problems at the moment, but as the library will grow the problem might return.
And how about an option to just exclude some tv series from the calendar that it won't block other ones that suppose to be there?

**Comment by jaruba** [comment]
@maxoku i chose to increase it by less so we can monitor the impact on our infrastructure

**Comment by maxoku** [comment]
@jaruba Okay, that makes sense. Thanks for answering.
What do you think about my idea though? Excluding tv series from calendar like from notifications would also help. Would you consider adding it from here or should I make a feature request?

**Comment by TRtomasz** [comment]
Excluding items from notifications/calendar would require at the moment a lot of work. As there are other more important things to implement at the moment i will close this issue. @maxoku  please create feature request.

**Comment by HuzzyN** [comment]
You should add an option in the library or calendar to choose which show to keep track of in the calendar as some shows are added to the library to go back to rewatch, this would separate add to library button to add to the calendar or it would still do it by default.
