### ISSUE TITLE
Can't register or log in as a guest

### ISSUE THREAD

**Issue by birimbecas** [Stremio/stremio-bugs#30]
When i try to log in as a guest nothing happens
When i press the register button after filling in my email and password, also nothing happens, before it was saying connection error.
And when i log in with facebook it redirects me to the strem.io site and says Your Facebook login is complete, please return to Stremio. and when i return to stremio nothing happens.

I am using windows 10
stremio 3.4.5  -  says connection error
stremio 3.4.3  -  says nothing
country Portugal

Thanks in advance

**Comment by Ivshti** [comment]
any chance you're running bitdefender?

**Comment by birimbecas** [comment]
Never even heard of that

**Comment by Ivshti** [comment]
Actually, 2 hours ago there may have been some downtime. Can you try again?

**Comment by birimbecas** [comment]
I'm still getting the connection error when i try to register

**Comment by Ivshti** [comment]
What happens when you open http://api9.strem.io in your browser ?

**Comment by birimbecas** [comment]
The first one redirects me to strem.io website
The second one shows this
![capturar](https://cloud.githubusercontent.com/assets/6265631/12242821/1c757566-b893-11e5-9d9d-1a0e6d9f14c0.PNG)

**Comment by Ivshti** [comment]
That's the expected behaviour. 
Did you try disabling mcafee and/or a firewall?

**Comment by birimbecas** [comment]
No, I will try that

**Comment by birimbecas** [comment]
Tried disabling both and still getting the connection error when registering and facebook login still doesnt work

**Comment by Ivshti** [comment]
so the login server is online, you can even connect to it in your browser, but something prevents stremio from connecting
try  opening stremio with stremio.exe . --development and seeing the log

**Comment by birimbecas** [comment]
Tried opening it like you said and this is what shows up in cmd
![capturar](https://cloud.githubusercontent.com/assets/6265631/12262627/ec396c48-b920-11e5-87ff-33467f505432.PNG)

**Comment by Ivshti** [comment]
There has to be a dot before "--development", as I've specified

That will open a new window with the debug log

**Comment by birimbecas** [comment]
Ops missed that.
Here it is
![capturar](https://cloud.githubusercontent.com/assets/6265631/12263673/15ed1366-b929-11e5-9518-ff9f0eaa0e57.PNG)
![capturar1](https://cloud.githubusercontent.com/assets/6265631/12263674/15ef1e4a-b929-11e5-9834-0bdcc85f85fb.PNG)

**Comment by Ivshti** [comment]
Wow! It can't connect to anything - neither the website, nor the add-ons, nor the log-in server.
With a ERR_PROXY_CONNECTION_FAILED

No idea what that means for now, but keep in mind all those things are connected through cloudflare. It could be blocking you for some reason

i'm trying to think of a reason/solution

**Comment by birimbecas** [comment]
Well i hope you can find out what it is because i don't really understand most of these things
Thanks again for looking into this

**Comment by birimbecas** [comment]
It works now!
I tried to to launch it once again and it said a new version was out and would be installed next time i launched stremio, and when i launched it again i was able to login with facebook.

**Comment by Ivshti** [comment]
We've changed nothing.

Issues like this are usually due to the cloudflare's infrastructure.

With threats of world-wide ddos attacks against some websites, they may have tweaked security settings and that may have blocked some users

just my theory

**Comment by birimbecas** [comment]
Well since it's working i guess i can close this thread.
thanks again for your help
