### ISSUE TITLE
DeprecationWarning Buffer() - Application Error

### ISSUE THREAD

**Issue by JasonSD24** [Stremio/stremio-bugs#301]
Hi team,

Hope you are doing great. 

Since a few days ago I am receiving the following error message when I try to see any serie or movie:

_Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:11696) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)_

I re-installed Streamio several times, but I still receive the same error.

**Screenshots**
![image](https://user-images.githubusercontent.com/12404111/124403927-e4e14980-dcf5-11eb-8c26-dda7b17d8ad2.png)
![image](https://user-images.githubusercontent.com/12404111/124403936-f0347500-dcf5-11eb-890d-a42815627f1f.png)

**Desktop:**
 - OS: Windows 10 
 - Version 21H1
- Stremio version: 4.4.137

Please let me know if you need any additional information from my side.

thank you in advance for your help!

Best regards,

JasonSD24

**Comment by JasonSD24** [comment]
Just to let you know, I just downloaded the latest Stremio version 4.4.141. I will test it and inform if it fixes the issue or not.

**Comment by JourneyOver** [comment]
Have been running into the same behavior myself. Have tried uninstalling and reinstalling stremio multiple times and the issue still comes up.

**Comment by g4ngelo** [comment]
Same issue here. Uninstalling / re-installing does nothing, issue remains.

**Comment by mgood7123** [comment]
me too on macbook

**Comment by SandeMC** [comment]
Keeps happening to me randomly every 20-40 minutes. Even when I'm not watching anything.

**Comment by ItsDrike** [comment]
I'm also having this issue, I'm running from Arch Linux and the window shows up every few seconds. This also prevents me from even watching anything at all, with some weird errors showing up:

![image](https://user-images.githubusercontent.com/20902250/167216857-4ed5e86e-1398-42e3-adfe-2617d0279cc8.png)

I've tried both restarting and reinstalling streamio, but neither have helped.

This seems like something fairly easy to fix, as it's just a naming change in Node.js and you should simply be able to use the suggested Buffer.alloc, any reason why this wasn't fixed already?

**Comment by JasonSD24** [comment]
Hi guys,

For all who reported this issue after me, just FYI, I reinstalled Windows in my PC, because I needed to do it for other reason, when I installed Stremio on the fresh Windows installation I don't receive the error. 

Since I did the resintallation at late January, I just got the error message like 4-5 times, and I use Stremio almost every day, and when that happened closing and opening Stremio worked for me.

**Comment by aviven** [comment]
This is never getting fixed is it?

**Comment by R4ygen** [comment]
> This is never getting fixed is it?

Apparently not.
Got the same error today with the last version

**Comment by Sotiris-k** [comment]
I've been getting the same error quite a lot lately too on PC

**Comment by bt4ibwem8** [comment]
I get this error also in the newest 4.4.165 version of Windows desktop app. Do developers know what causes this error?

**Comment by TRtomasz** [comment]
Will close this issue as this is not related to any specific issue. This is just a warning that is being displayed, but true reason why server is crashing is somehow hidden, each case should be checked separately
