### ISSUE TITLE
Stremio stuck on loading screen then turns off

### ISSUE THREAD

**Issue by Raffe-Telis** [Stremio/stremio-bugs#302]
Hello there,

I try to launch Stremio but it just gets stuck on the loading screen and then goes off.

![image](https://user-images.githubusercontent.com/87081455/124778847-33325a80-df39-11eb-8e1f-0f4ffc80b5a2.png)

 - OS: Windows 10
 - Browser Chrome

**Comment by Slowly-Grokking** [comment]
I'm having the same issue.

[libmpv_render] Loading hwdec driver 'd3d11-egl'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-egl'
[libmpv_render] Loading hwdec driver 'd3d11va'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-dxgi'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-dxinterop'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'cuda-nvdec'
[libmpv_render/cuda-nvdec] need OpenGL >= 2.1 or OpenGL-ES >= 3.0
[libmpv_render/cuda-nvdec] CUDA hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.
Segmentation fault

**Comment by TRtomasz** [comment]
Hi @Raffe-Telis 
Please check if you can log in using web app which is available here http://app.strem.io/shell-v4.4/#/
