### ISSUE TITLE
Automatically use embedded subtitles if available 

### ISSUE THREAD

**Issue by JediRhymeTrix** [Stremio/stremio-bugs#306]
Right now, Stremio prioritizes external subtitles always. Ideally, it should prioritize embedded subtitles if the video contains them. 

Also, there needs to be an option to temporarily disable subtitles only for the current video l, either by making the subtitles toggle in the player act only on the current video or by giving an option to select "None" as a subtitle.

**Comment by TRtomasz** [comment]
Done in 4.4.144 :)

**Comment by JediRhymeTrix** [comment]
Hey, sorry to comment on a closed issue, but I just wanted to know if this has been implemented in the android build as well, since I don't see it in the 1.4.13 version.

**Comment by TRtomasz** [comment]
No, this has been implemented only in Pc version of app

**Comment by Dennis-NL** [comment]
Can this be changed somewhere? It uses the embedded subtitles even if its in the wrong language
