### ISSUE TITLE
Drag on Drop for torrent files stopped working.

### ISSUE THREAD

**Issue by Braiio** [Stremio/stremio-bugs#310]
**Describe the bug**
Drag and drop is no longer working, related problem can be seen in screenshots section.

**To Reproduce**
1. Open stremio
2. Find whatever torrent 
3. Drag it to the app

**Expected behavior**
Most normal drag and drop to watch a series. 

**Screenshots**
![image](https://user-images.githubusercontent.com/57599309/126624045-146c6a57-4124-4d78-8344-63e5d58a7432.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit, version 21H1
 - Browser Chrome (but irrelevant, I'm a desktop user)
 - Version 4.4.142

**Additional context**
https://github.com/Stremio/stremio-bugs/issues/179 - seems like the related issue, could it be because of the version?
Playing anything else from within the app, works fine.

**Comment by jaruba** [comment]
@Braiio We've been unable to reproduce your issue, it works fine in our tests.. Is it possible for you to give us more information? Where are the torrent files coming from? Are they from some private tracker? Did drag & drop ever work for you in the past with other versions?

**Comment by Braiio** [comment]
Sorry for the delay in the answer, I have found an old installation of 4.4.120 and this one works fine, allows me to do the drag and drop, the newer version mentioned above, doesn't
