### ISSUE TITLE
Hardware Acceleration makes image washed out on Nvidia.

### ISSUE THREAD

**Issue by SandeMC** [Stremio/stremio-bugs#311]
For some reason, using Hardware Acceleration causes washing out when used. The solution to that was enabling Full Dynamic Range for color settings in Nvidia Control Panel, but that causes issues with other applications which specifically were made for Limited colors. My GPU is GTX 1650, my friend, who has the same issue, used 1660ti and a 2060 on different rigs. I'm not sure if it's a problem for all GPU's, so i specified mine. We're using latest Windows, driver and Stremio updates.

Hardware Acceleration off:
![image](https://user-images.githubusercontent.com/70141395/128007780-2c314518-9b5d-43e1-8830-b97c4d314b43.png)
Hardware Acceleration on:
![image](https://user-images.githubusercontent.com/70141395/128007822-9d596c15-faca-43fb-82f9-f7e2936db9f7.png)
Hardware Acceleration on and manually set full dynamic range for colors:
![image](https://user-images.githubusercontent.com/70141395/128007903-dbf938aa-03b0-4447-897c-a8ca277858f2.png)

Again, setting full dynamic range for all time is not an option. Some apps manually set to use Limited.
![image](https://user-images.githubusercontent.com/70141395/128008345-4d16e0a0-c4f8-497f-b159-06684f84a491.png)
![image](https://user-images.githubusercontent.com/70141395/128008477-77fcba42-8ac1-437e-b633-a833a3d7dcfa.png)
(for second, it wasn't visible on a screenshot)

**Comment by SandeMC** [comment]
![image](https://user-images.githubusercontent.com/70141395/128008659-75bee848-877a-449b-91da-d113ecca44b5.png)
Here's where you enable full range. I'm not sure how it would translate to english, but it would be
Color settings for video content -> NVIDIA Settings -> Additional -> Dynamic Range

**Comment by TRtomasz** [comment]
Hi,
Do you have HDR turned on in your display settings?

**Comment by SandeMC** [comment]
No. Nor my display, nor my friend's display, support HDR.

**Comment by TRtomasz** [comment]
Please try go to the settings -> Player and enable "Launch player in a separate window" and check if with this option colors are still washed out

**Comment by SandeMC** [comment]
Yes. The issue stays.

вт, 3 авг. 2021 г., 17:43 Tomasz ***@***.***>:

**Comment by TRtomasz** [comment]
So there is nothing we can do about this as this is caused by MPV which we use as a player in Stremio, Maybe updating it will help but i can't give any eta when it will happen or if it will fix the issue

**Comment by SandeMC** [comment]
Got it.

вт, 3 авг. 2021 г., 20:48 Tomasz ***@***.***>:

**Comment by TRtomasz** [comment]
Under the gear icon you might find options like downloading video or playing in the external player, like vlc, so you might use these options to mitigate the issue.
