### ISSUE TITLE
Can you support subtitles in other formats?

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#312]
At present, it seems that stremio can only use subtitles in .srt format. However, many animation or TV dramas and some movies use subtitles in .ass format, which can support more special effects.

**Comment by TRtomasz** [comment]
At the moment Stremio does not support ASS subtitles formats. If you want to use them with drag&drop feature you might try using one of the online converters that switch ass subtitles to srt subtitles.

**Comment by XeiDaMoKa** [comment]
> At the moment Stremio does not support ASS subtitles formats. If you want to use them with drag&drop feature you might try using one of the online converters that switch ass subtitles to srt subtitles.

We would want the .ass in the first place , you can choose fonts , colors , sizes , positions etc , i asked gpt to create me a script that converts srt to my favorite .ass setup , i dont use stremio since 2019 because stremio refuses to allow customization on subtitles on android
