### ISSUE TITLE
Mi box S back button and Stremio

### ISSUE THREAD

**Issue by apr0vleptos** [Stremio/stremio-bugs#313]
I am using stremio on mi box S. When watching a series , and change the episode from inside the stremio player (3 horizontal bars top right corner), the back button on the bluetooth controller stops working only for stremio. restarting the app fixes it temporarily.

**Comment by TRtomasz** [comment]
Hi,
Could you please tell us which stremio version you have installed?

**Comment by apr0vleptos** [comment]
I am using stremio version 1.4.4.

**Comment by apr0vleptos** [comment]
I recreated the bug on my mobile phone. Seems that the "go back" gesture is disabled when switching episode from the 3 bar button in the player.

**Comment by TRtomasz** [comment]
Closing issue, there is new TV app. If this issue is still present there please let us know
