### ISSUE TITLE
Mi 11x/Poco F3 lag/stutter on 480p videos

### ISSUE THREAD

**Issue by sprtkd** [Stremio/stremio-bugs#315]
**Describe the bug**
480p old videos stutter on Mi11x. Suspect something with Xiaomi super resolution. Gets fixed if I turn off hardware acceleration.
720p/1080p/4k works great.

**Smartphone (please complete the following information):**
 - Device: Mi 11x
 - OS: Android 11, Miui 12.5.2
 - Version 1.4.4

**Comment by TRtomasz** [comment]
Hi,
If issue is caused by some Xiaomi feature there is nothing we can do about this, sorry.

**Comment by sprtkd** [comment]
Request to add quick toggle to turn on/off hardware acceleration in player.

**Comment by sprtkd** [comment]
Found out, after minimising the app once a 480p video starts playing, the issue goes away.
