### ISSUE TITLE
Drag the mouse under the url on Configurations>Streaming>Streaming server url. Program Crashes.

### ISSUE THREAD

**Issue by amzero** [Stremio/stremio-bugs#316]
You are logged. Go in Configurations>Streaming>Streaming server Url , drag the mouse under the url, the program crashes. 

**Expected behavior**
Copy automatically the url to your copy area without bug or crash. and if possible, a message saying that the link was copied.

I can't get a printscreen. during a crash, the printscreen seems do not work.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version Stremio 4.4.142

**Comment by TRtomasz** [comment]
Hi,
Do you mean something like on this video?
Yes, it looks like app crashes then but there is copy button which you can use to copy the text. 
https://user-images.githubusercontent.com/40594253/130574539-f1462ce6-37e8-4bcb-9d5d-11b505e1b884.mp4

**Comment by amzero** [comment]
Yes. Exactly this.
I already knew about the copy button, but to drag the mouse under the link and the program crashes is really a bug. 

How do you recorded the video?
