### ISSUE TITLE
streaming server is not available

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#318]
Recently, when I open the software, I always can't play the video. This error is displayed. I think it's my network problem, but the problem still hasn't been solved after I reset the network.

**Comment by shanyan-wcx** [comment]
I use Windows11 22000.168

**Comment by TRtomasz** [comment]
Hi,
Something on your PC is blocking access to local streaming server. It could be either a vpn, a firewall, an antivirus or a proxy. We do not have any means to troubleshoot this remotely so you have to find it by yoursellf.

**Comment by shanyan-wcx** [comment]
I didn't use any vpn, firewall, antivirus or proxy
