### ISSUE TITLE
Black screen on HEVC codec

### ISSUE THREAD

**Issue by apr0vleptos** [Stremio/stremio-bugs#319]
**Describe the bug**
When streaming a movie encoded as HEVC (h.265) there is black screen, but audio and subtitles play correctly.  With hardware acceleration off, the playback freezes completely.

**To Reproduce**
1. Stream any hevc movie
2. Black screen

**Smartphone (please complete the following information):**
 - Device: TV Box H96 MAX RK3318 4G Ram
 - OS: Android 9 and Android 10 (upgraded)
 - Browser: Chrome
 - Version: 1.4.5

**Additional context**
When playing on external media player , for example vlc, mx player and others, everything is smooth and plays correctly.

**Comment by TRtomasz** [comment]
Hello,
Please reofrmat your issue with the template that was displayed when you started to create it.
https://github.com/Stremio/stremio-bugs/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by adrianlungu** [comment]
I also have the same issue, but then again, never did manage to get Stremio to work with HEVC. 

Works just fine in VLC, but then other functions don't work like `Autoplay next episode`.

**Comment by TRtomasz** [comment]
should be fixed in the latest release 1.4.20
