### ISSUE TITLE
Hebrew subtitles are not displayed RTL

### ISSUE THREAD

**Issue by bsphere** [Stremio/stremio-bugs#32]
When choosing Hebrew subtitles, they are not displayed RTL,
the text is correct, but it is aligned to the left instead of to the right, it causes punctuation marks to be on the wrong side, and if the text contains an English word, everything is messed up.

**Comment by Ivshti** [comment]
I just fixed this - It will be out with the next release in a few days, so I'm closing this

**Comment by AlonHmdt** [comment]
This bug still exists.
