### ISSUE TITLE
Stremio subtitles doesn't download in fire stick 4k 

### ISSUE THREAD

**Issue by sbaus** [Stremio/stremio-bugs#321]
Hi,
I am using the latest version of Stremio 1.4.5, The subtitles don't load most of the time, and the subtitles list is blank. when this happens,I have to clear the cache, force stop and then lounch the application again, when i do so the subtitels load normally. 
I didnt face this problem in the previous versions. Please let me know what to do. 
i have this issue only with my firestick, my Mac and Andrio phone versions work fine.

**Comment by TRtomasz** [comment]
Hi, please tell us if there is any error message when subtitles dont load?
