### ISSUE TITLE
Error installing addons

### ISSUE THREAD

**Issue by FinixFighter** [Stremio/stremio-bugs#322]
Hi! I'm having a problem for a few weeks: I can't install any addon anymore. When I go to the addons page and I try to install one, I get the error message:"ADDON_PUSH_FAILED" right after the "Addon installed" message (as you can see in the photo).
![Screenshot at 2021-09-09 08-47-51](https://user-images.githubusercontent.com/19877271/132636925-39c733e2-a2fd-4449-8eca-be436d57a840.png)
I launched Stremio via the terminal to see what happens, it seems a problem with CORS:

`js: Access to fetch at 'https://9546dcbb7c1c-stremio-fmovies.baby-beamup.club/catalog/movie/top.json' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Here is the complete terminal output: https://ufile.io/06yd3ac7

**Comment by TRtomasz** [comment]
Yes, there is addon limit, Looks like you have reached it.

**Comment by FinixFighter** [comment]
> Yes, there is addon limit, Looks like you have reached it.

Ok, but why does this limit exist?
