### ISSUE TITLE
Episode history / Continue Watching bug

### ISSUE THREAD

**Issue by apr0vleptos** [Stremio/stremio-bugs#324]
**Describe the bug**
On many of the series i am watching , the episode tracker of stremio is bugged. Lets say i am on episode 12. Not only is episode 12 marked as currently watching (purple color around it) , but other episodes as well , even from other seasons of the show. Why does this happen? Also stremio used to auto start the movie on the stream i was watching when clicking a movie from "Continue watching" list. Now it always opens the stream selection for that movie for some strange reason.

**Screenshots**
![Screenshot_2021-09-24-03-02-16-943_com stremio one](https://user-images.githubusercontent.com/4735340/134599223-94895994-f783-4121-8910-db2623bd4959.jpg)

**Smartphone:**

 - Device: xiaomi poco x3
 - OS: android 11
 - Browser firefox
 - Version 1.4.5

**Tv Box:**
 - Device: a95x f4
 - OS: android 10
 - Browser chrome
 - Version 1.4.5

**Comment by TRtomasz** [comment]
Hi, thanks for your report, we will check this out

**Comment by TRtomasz** [comment]
Hi, this should be fixed in latest version 1.4.13
