### ISSUE TITLE
Subtitles hidden by the timeline

### ISSUE THREAD

**Issue by Macka323** [Stremio/stremio-bugs#325]
**Describe the bug**
Subtitles hidden by the timeline

**To Reproduce**
1. Open any video/stream with subtitles
2. move your mouse

**Expected behavior**
the subtitles too go over the timeline , and be able to move them freely

**Screenshots**
![image](https://user-images.githubusercontent.com/75259519/139553691-021500a4-982f-4199-a0d7-d5b2b27c04b5.png)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser: chrome
 - Version ![image](https://user-images.githubusercontent.com/75259519/139553728-3edc3590-71ed-420f-bd80-526072832afe.png)

**Additional context**
/

**Comment by TRtomasz** [comment]
Hello, this issue should be fixed in the next release

**Comment by TRtomasz** [comment]
It is Fixed now 4.4.144
