### ISSUE TITLE
BubbleUPnP - Cannot play: no http stream found

### ISSUE THREAD

**Issue by bacevs** [Stremio/stremio-bugs#326]
**Describe the bug**
Cannot open/play Real Debrid links through external player bubbleupnp. Always errors with "Cannot play: no http stream found".
Syncler does not have this issue.

**To Reproduce**
Configure torrentio addon with a Real debrid API key. Install addon.
In options make sure "Always start video in external player" is selected. 
Search for a "title" and click play on a real debrid link. It will ask to open in a external player, select Bubbleupnp. After a while it will say "Cannot play: no http stream found"

**Expected behavior**
It should be able to play the stream, like Syncler does. 

**Smartphone (please complete the following information):**
 - Device: Pixel 4XL
 - OS: Android 11

**Comment by AlekssZeltins** [comment]
I have exactly the same problem. And I just can't figure out how to get it to work.

**Comment by TRtomasz** [comment]
I really don't think we can solve issues that external application has.

**Comment by AlekssZeltins** [comment]
> I really don't think we can solve issues that external application has.

I checked that Bubbleupnp works with VLC as external, but VLC is simply terrible for casting videos as most of the time it even does not find the device to cast to. 

What exactly is Changing when I am using Debrid service, because Bubbleupnp Works when using Stremio Without Debrid service.

**Comment by tkalfaoglu** [comment]
I'm getting this error when I start a youtube video from newpipe and share it to bubblepnp to playback on an Google home (w screen) device .

**Comment by druscoe** [comment]
I receive the same error as @tkalfaoglu

> I'm getting this error when I start a youtube video from newpipe and share it to bubblepnp to playback on an Google home (w screen) device .

Except I'm using kodi for the sink. Sometimes this will work, in fact I can get a good few days/weeks off things working flawlessly. Randomly the connection appears to fail. Each and every subsequent YouTube link I share with bubble upnp then displays the error message `Cannot play: no http stream found`. 

Sometimes a reboot of many things (router, kodi, bubble upnp app) will solve the issue. Other times restarting these things will not solve the issue and the error continue to be displayed. 

My intuition is saying this is a bubble app issue although I cannot be certain. Are there any logs which can be analysed?
