### ISSUE TITLE
Navigation issues - Stremio 1.4.5 FireOS

### ISSUE THREAD

**Issue by CallMeVorex** [Stremio/stremio-bugs#328]
When hovering over a film on Stremio 1.4.5 on FireOS, then moving upwards to the hamburger menu button, and selecting it, when moving downwards it doesn’t register that the sidebar is open and ghosts behind it, you have to navigate left twice then down to access the sidebar
(Me pointing out bugs will hopefully help with future updates I don’t mean for them to be annoying)

**Comment by TRtomasz** [comment]
Closing, this issue as we have new stremio version for android TV.
