### ISSUE TITLE
Why not use ExoPlayer or just (Video) Player as default for android

### ISSUE THREAD

**Issue by krishne35** [Stremio/stremio-bugs#333]
The default player of stremio is good for light files but fails terrible with HEVC and HDR files colour reproduction is very awful so why not integrate either of those open source player as default 

P.S i do know about play external player feature doing so will loose scrobbing

**Comment by cojoMan** [comment]
please add a player that supports HDR/HEVC etc. Having to switch to alternatives is awfull, also does not keep trakt progress.
