### ISSUE TITLE
Play with MPV option not appearing in windows

### ISSUE THREAD

**Issue by Darkmaster006** [Stremio/stremio-bugs#336]
**Describe the bug**
There's no option to 'Play with MPV' in my Stremio installed in Windows 8.1

**To Reproduce**
1. Play any magnet torrent.
2. Try to find Play with MPV.
3. No option.

**Desktop (please complete the following information):**
 - Windows 8.1
 - Firefox
 - 95

**Comment by Zabooby** [comment]
I have mpv and vlc when I right click  there is an option to 'Play with VLC' but not MPV.

Desktop (please complete the following information):

    Windows 10
    Firefox
    95

**Comment by TRtomasz** [comment]
This option is not available for windows, only on linux and macos

**Comment by Zabooby** [comment]
> This option is not available for windows, only on linux and macos

Funnily enough after tinkering with the server.js file mpv comes up as a right click option. No idea how I fixed it.

**Comment by Darkmaster006** [comment]
> > This option is not available for windows, only on linux and macos
> 
> Funnily enough after tinkering with the server.js file mpv comes up as a right click option. No idea how I fixed it.

If you figure it out, let me know. I don't really wanna use VLC.
