### ISSUE TITLE
User Interface Could not be loaded (initShellComm is not defined)

### ISSUE THREAD

**Issue by souranild** [Stremio/stremio-bugs#337]
**Describe the bug**
Opens with a weird interface, and nothing works (Manjaro)

**To Reproduce**
1. Open
2. See error

**Expected behavior**
A clear and concise description of what you expected to happen.Used to work just fine, until today. Tried with both AUR repository, and Flatpak. Same result. Tried to change internet. Still same.

**Screenshots**
![image](https://user-images.githubusercontent.com/42074408/146678302-f6dab034-b26c-40f0-829e-9b8124afada0.png)

**Desktop (please complete the following information):**
 - Operating System: Manjaro Linux
 - KDE Plasma Version: 5.23.3
 - KDE Frameworks Version: 5.88.0
 - Qt Version: 5.15.2
 - Kernel Version: 5.10.79-1-MANJARO (64-bit)

 - Version 4.4.142

**Comment by souranild** [comment]
Update: This was automatically solved the next day. I don't know what caused it. I don't know what solved it.

**Comment by vineet15889** [comment]
<img width="510" alt="Screenshot 2022-01-15 at 9 58 08 PM" src="https://user-images.githubusercontent.com/17078856/149629837-740642f0-f03f-4eb1-be59-187eee06c125.png">
I am facing this on mac

**Comment by ItsDrike** [comment]
I also experienced this issue from Arch Linux, a reboot seemed to have fixed it.

**Comment by jaruba** [comment]
this happens when the website at https://app.strem.io/shell-v4.4/#/ is not accessible, usually caused by regional outages
