### ISSUE TITLE
Play with MPV in Windows?

### ISSUE THREAD

**Issue by Darkmaster006** [Stremio/stremio-bugs#338]
Not a bug (seemingly), so more like a feature request. I was just wondering if the option to play with MPV could be added in the Windows version of Stremio. I currently dual-boot, so sometimes I'm using Windows (when I need to do stuff that can only be done in Windows) and sometimes I'm using Linux. But, having to boot into Linux in order to use the 'Play with MPV' option is not really practical. Can this be added into the Windows version? Thank you.

**Comment by TRtomasz** [comment]
Gear menu option is available only ony linux and mac. On Windows you can play in MPV using option "Launch player in a seaparte window" in the settings

**Comment by Darkmaster006** [comment]
> Gear menu option is available only ony linux and mac. On Windows you can play in MPV using option "Launch player in a seaparte window" in the settings

This doesn't really work. The only thing it does, at least for me, is open the video (when it opens and not just says 'Playback error') in an MPV window: that is, the video is still "played" in Stremio, since all the controls are there, the subtitles are there and not in the MPV window, etc., plus, you can't use any of the MPV options, can't fullscreen with F, can change subtitles, etc.
