### ISSUE TITLE
Stremio player makes Windows 10 crash and restart

### ISSUE THREAD

**Issue by imanvanassum** [Stremio/stremio-bugs#339]
**Describe the bug**
Whenever I watch a video on Stremio instead of streaming to VLC to watch there, it randomly freezes up. The screen will go black, the audio will continue for another 2-3 seconds before it becomes loud and artifact-y (for lack of a better description) and another 5-10 seconds later the PC will be restarting.

**To Reproduce**
1. Go to 'Any title in library'
2. Click on 'Watch whichever torrent source you want'
3. Wait for it ... (not sure how long, time varies)
4. Facepalm that you didn't choose to watch in VLC when the screen goes black and you hear the loud buzzing and alien voices.

**Expected behavior**
I'd like my PC not to crash when watching something through Stremio player.

**Screenshots**
I don't think a screenshot of a black screen will help.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1415
 - Browser N/A
 - Version 4.4.142

**Additional context**
If there is any log that Stremio writes to, I wouldn't know where to find it. Tell me and I will include it.

**Comment by TRtomasz** [comment]
Please tell us which exact streams you tried to play. And also if you have hardware accelerated decoding turned on in the settings. If know you should try to turn it on.

**Comment by imanvanassum** [comment]
Hardware accelerated decoding was turned on before, but after looking around for a solution a few months back I turned it off. Safe to say it doesn't make any difference.

Last time it happened was ~30 minutes ago on this stream: 
https://www.strem.io/s/series/letterkenny-4647692

**Comment by TRtomasz** [comment]
@imanvanassum  this not the stream this is the series. Please tell us which exact streams you have picked. You pick it from the right side panel before starting the playback

**Comment by imanvanassum** [comment]
Friend, my PC crashed. How am I supposed to know which one I picked? One with the most seeders probably, let's say:
share-link:https://www.strem.io/s/series/letterkenny-4647692
magnet:?xt=urn:btih:be935d20803d4b9c26e8d24577515bb8f58a34a1
stream:http://127.0.0.1:11470/be935d20803d4b9c26e8d24577515bb8f58a34a1/3

I don't know how to get you what you're asking for if it's not between those three.

**Comment by TRtomasz** [comment]
Hi,
I was not able to reproduce this issue with stream you have provided. Usually this kind of isuses are caused by faulty GPU driver. You might try to reinstall(or downgrade to previous version) it and then check.
