### ISSUE TITLE
No option to download subtitles when watching local files

### ISSUE THREAD

**Issue by bsphere** [Stremio/stremio-bugs#34]

**Comment by Ivshti** [comment]
can you elaborate? if you have Subtitles add-on enabled, it will fetch subtitles for local videos

**Comment by bsphere** [comment]
When dragging a local mkv file, sometimes it recognizes the series name, episode and season so everything is ok but sometimes all stremio recognizes is the file name (which is the release name) and the subtitles menu isn't even visible
