### ISSUE TITLE
Click 'next 15s', focus goes to 'back' button

### ISSUE THREAD

**Issue by roi-ravia** [Stremio/stremio-bugs#343]
**Describe the bug**
When a user clicks the 'next 15s' button, the focus goes to the 'back' button for about a second.
This causes the user that tries to click many times the 'next 15s' button so he can move to the middle of the video to accidentally click 'back' and move to the preview screen of the video.

**To Reproduce**
1. Start a video
2. Click on 'next 15s'
3. Focus goes to 'back' button

**Expected behavior**
I understand this might not be a bug but a UX decision, still, I would suggest that once the user has clicked on 'back/next 15s', keep the focus on the button.

**Why this is an issue:** 
When you try to click twice on the 'next 15s' button, you get redirected to the preview screen with the streaming options. 

**Desktop (please complete the following information):**
 - OS: Android TV

**Comment by TRtomasz** [comment]
Wait for the UI disappear and use left/right arrows or forward/rewind buttons to rewind as much you want.

**Comment by roiRavia95** [comment]
I know :)
The point is there will be users that will try to click that button and will get a buggy experience.
