### ISSUE TITLE
updates notifications no longer working :(                

### ISSUE THREAD

**Issue by M4dKiwi** [Stremio/stremio-bugs#346]
**Describe the bug**

updates notifications no longer working :(                

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen.   (bug fix next update?) 

my notifications completely stopped about a month or 2 ago, I thought it would get fixed by now.
(it cant be just me, as I have Stremio installed on both of my computers (same account)) 

I dont get why I can no longer find new series like 
'Alaskin killer bigfoot' ,'ghost loops'or even 'death walker'  - sure I can find the magnet links via magnetdl.com
but I did'nt used to have to use it so often to find a torrent that had been out for weeks ???

also it looks like many of the unofficial add ons need a good tidy up, so many are obsilite & no longer work
(I wish there was a simple template for an add on to scrape custom (pirate-link) sites such as magnetdl.com
or thepiratebay.org as it seems the current add ons link to dead pirate sites so now send back no data (becoming bloatware)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by M4dKiwi** [comment]
would be nice to know why this issue was closed as the problem has not been resolved?.
I noticed I'm not alone with this issue, which may be the reason.
perhaps before closing it would be more informitive if the reason was stated rather than ignored.
I assume it remains unresolved But (hopefully) still open in an earlier report ,It was the best feature 
yet notifications are now nonexistence - such a shame

**Comment by TRtomasz** [comment]
Hi it was closed as this is duplicate of #270 also you didnt add any content except the title. Issue template is there for a reason. So if you report an issue in the future please add all the data instead only the title.
