### ISSUE TITLE
Unsubscribing from the newsletter gives an internal server error

### ISSUE THREAD

**Issue by Jason-D-Gordon** [Stremio/stremio-bugs#348]
**Describe the bug**
When clicking the unsubscribe button on the newsletter email, it gives a 500 internal server error.

**To Reproduce**
1. Go to the newsletter email
2. Click on "here" where it says "If you don’t want to receive this email communication anymore, click **here** to unsubscribe."
3. Observe the internal server error

**Expected behavior**
Something that tells me that I'm unsubscribed

**Comment by TRtomasz** [comment]
Hi, we are aware of this, problem, sorry about this. But you dont have to unsubscribe as we do not send any emails at the moment.

**Comment by TRtomasz** [comment]
This should be fixed now.
