### ISSUE TITLE
Cast to TV button greyed out

### ISSUE THREAD

**Issue by htot** [Stremio/stremio-bugs#35]
As I understand clicking on the TV button (under Mobile/Tablet) should turn on the DLNA server, allowing my TV to connect. However, my TV detects only 1 DLNA server, but not Strem.io.

The problem is that the TV button is greyed out. Turning on --development doesn't show me anything useable.

I am on Ubuntu and start stremio with ./Stremio.sh

**Comment by Ivshti** [comment]
It should allow you to cast to your TV - using the media receiver part of the DLNA protocol.

Grayed out button means ssdp discovery isn't working for some reason.

What's your TV model?

**Comment by htot** [comment]
I have a Samsung BD/HDR connected to a Samsung TV
