### ISSUE TITLE
Error while starting stremio server

### ISSUE THREAD

**Issue by Nixos4444** [Stremio/stremio-bugs#350]
OS - Windows 10 21H1 Bulid -19044.1466
Log - Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

Engine invalid piece 7032 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7033 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7034 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7035 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7036 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7037 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7038 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 7039 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9120 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9121 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9122 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9123 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9124 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9125 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9126 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9127 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9128 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9129 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9130 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9131 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9132 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9133 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9134 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9135 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9136 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9137 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9138 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9139 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9140 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9141 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9142 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9143 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9144 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9145 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9146 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9147 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9148 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9149 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9150 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9151 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9136 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9137 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9138 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9139 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9140 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9141 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9142 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9143 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9144 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9145 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9146 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9147 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9148 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9149 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9150 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9151 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9152 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9153 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9154 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9155 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9156 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9157 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9158 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9159 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9160 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9161 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9162 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9163 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9164 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9165 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9166 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9167 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9168 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9169 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9170 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9171 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9172 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9173 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9174 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9175 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9184 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9185 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9186 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9187 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9188 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9189 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9190 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9191 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9176 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9177 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9178 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9179 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9180 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9181 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9182 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9183 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9192 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9193 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9194 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9195 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9196 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9197 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9198 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9199 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9200 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9201 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9202 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9203 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9204 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9205 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9206 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9207 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9208 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9209 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9210 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9211 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9212 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9213 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9214 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9215 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9216 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9217 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9218 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9219 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9220 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9221 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9222 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9223 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9200 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9201 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9202 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9203 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9204 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9205 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9206 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9207 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9208 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9209 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9210 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9211 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9212 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9213 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9214 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9215 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9216 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9217 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9218 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9219 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9220 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9221 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9222 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9223 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9224 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9225 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9226 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9227 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9228 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9229 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9230 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9231 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9232 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9233 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9234 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9235 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9236 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9237 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9238 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9239 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9224 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9225 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9226 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9227 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9228 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9229 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9230 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9231 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9232 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9233 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9234 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9235 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9236 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9237 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9238 for a1433173cce812dcf6611201183e34333d1499dd
Engine invalid piece 9239 for a1433173cce812dcf6611201183e34333d1499dd
internal/fs/utils.js:308
    throw err;
    ^

Error: EPERM: operation not permitted, open 'C:\Users\Nixos\AppData\Roaming\stremio\stremio-server\stremio-cache\a1433173cce812dcf6611201183e34333d1499dd\29'
    at Object.openSync (fs.js:476:3)
    at openFile (C:\Users\Nixos\AppData\Local\Programs\LNV\Stremio-4\server.js:138869:18)
    at write (C:\Users\Nixos\AppData\Local\Programs\LNV\Stremio-4\server.js:138881:5)
    at Timeout._onTimeout (C:\Users\Nixos\AppData\Local\Programs\LNV\Stremio-4\server.js:9098:34)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: 'C:\\Users\\Nixos\\AppData\\Roaming\\stremio\\stremio-server\\stremio-cache\\a1433173cce812dcf6611201183e34333d1499dd\\29'
}

**Comment by TRtomasz** [comment]
You are trying to watch a broken file, nost probably [poisoned](https://en.wikipedia.org/wiki/Torrent_poisoning)
