### ISSUE TITLE
The posters in Android's library were cut after playing the video.

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#352]
![Screenshot_20220214_133629_com stremio one](https://user-images.githubusercontent.com/58252651/153807520-b8abba03-6580-4523-95fc-f2942aecc59b.jpg)
![Screenshot_20220214_133708_com stremio one](https://user-images.githubusercontent.com/58252651/153807596-f7d7986b-0d49-46e5-ace6-7b863fc0ded9.jpg)

**Comment by TRtomasz** [comment]
![image](https://user-images.githubusercontent.com/40594253/154930855-71806747-31b4-4f4f-8faf-14651065e903.png)
Sorry i dont see any difference, could you be a little more specific?

**Comment by shanyan-wcx** [comment]
1. Enter my library, whether it's a movie or TV series
2. Click a video to start playing. You must wait until the video content is loaded
3. Turn off the played video
4. Go back to the poster wall of my library
5. Issue appears

**Comment by shanyan-wcx** [comment]
1. Enter my library, whether it's a movie or TV series
2. Click a video to start playing. You must wait until the video content is loaded
3. Turn off the played video
4. Go back to the poster wall of my library
5. Issue appears
