### ISSUE TITLE
The subtitles automatically selected when playing videos on Android will not be loaded. I have to click the subtitle button manually to load them.

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#353]
It won't even automatically select subtitles in the language I choose.

**Comment by TRtomasz** [comment]
Please update issue with template then we will be able to reopen it.

**Comment by shanyan-wcx** [comment]
**Describe the bug**
When the video is played, the subtitles are not loaded automatically, even if I have selected my preferred subtitle language. I had to click the subtitle button, and then close the subtitle selection interface to load the subtitles.

**To Reproduce**
Steps to reproduce the behavior:
1. Play video.
2. Subtitles are not loaded automatically.
3. Click the subtitle button and then click X.
4. The subtitles are finally loaded.

**Expected behavior**
Subtitles are automatically loaded when the video starts playing.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [HUAWEI P20 Pro]
 - OS: [Harmony 2.0]
 - Version [1.4.20]
 
**Additional context**
Add any other context about the problem here.

**Comment by shanyan-wcx** [comment]
Can you reopen it?

**Comment by TRtomasz** [comment]
I'm not able to reproduce this issue, they get loaded without opening subtitles menu. Perhaps you have to wait a little bit longer for them to get loaded.

**Comment by shanyan-wcx** [comment]
I waited for a long time, but the subtitles still didn't load. When there is only one subtitle in the language I choose, the situation of title appears. When there are multiple languages, no subtitles will be selected. Not only on Android, but also on windows.

**Comment by shanyan-wcx** [comment]
It seems that it will only remember the subtitles I selected last time. If I haven't watched this video before, it won't load subtitles. The default subtitle language option does not take effect.
