### ISSUE TITLE
Embedded subtitles won't work when casting to google chrome

### ISSUE THREAD

**Issue by IZyaI** [Stremio/stremio-bugs#355]
**From what I have researched this error only occurs on devices that use Google's chrome cast. I might test it on an amazon fire stick to check and will update this if it works fine**

**Embedded subtitles wont work when casting to google chrome, but if the media has external subtitles that works fine**

When selecting any sort of media that has embedded subtitles (this is most prominent in anime) you can watch it fine on the device, however when you try to cast it the subtitles are no longer present and the media will play (without issue except for subtitles being absent) 

**To Reproduce**
1. Go to The media you want to play (specifically media with embedded subtitles, again most Japanese anime has embedded subtitles) and play it
2. Click on the subtitles option and set it up to ensure they are working if not already (you should only need to toggle the on/off
3. Then proceed to attempt casting to smart TV or google chrome (or anything else that supports google chrome cast)

**Expected behavior**
Subtitles should not be present on the target device of choice when casting, only when you stop casting and view media on the source device.

**Tested on all devices that support Stremio:**
 
 - Version [4.4.142]

**Comment by TRtomasz** [comment]
This is normal. This is not supported. As far i know chromecast does not support them

**Comment by IZyaI** [comment]
> This is normal. This is not supported. As far i know chromecast does not support them

Yeah figured that out after contacting customer support. Ridiculous. Chrome cast is absolutely hopeless. Now i have to get a firestick or use a 3rd party app. Thanks for you're feedback though
