### ISSUE TITLE
The definition of playing video on the web is very low.

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#356]
**Describe the bug**
The definition of playing video on the web is very low.
**To Reproduce**
1.Playing video on the web.
2.It looks very low definition.

**Expected behavior**
It should be clear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser edge 98.0.1108.56
 - Version 4.4.142

**Additional context**

**Comment by TRtomasz** [comment]
Thats normal, some videos are in formats not supported in the web browser and requires transforming them to formats that browser supports this process sometimes can cause video quality degradation.
