### ISSUE TITLE
Stream stuttering and stopping on CCWGTV 

### ISSUE THREAD

**Issue by SOEBREN** [Stremio/stremio-bugs#357]
**To Reproduce**
1. Just start to stream something, it always happens with this version, everything before 1.4.20 has worked perfectly fine for me.

**Expected behavior**
Stream starts to stutter very lightly but it gets annoying once you notice it. Most streams only work for 10 minutes then they stop, the only way to continue watching is to close the app and restart it, but it'll still be the same and stutter and stop after 10 minutes.

** Chromecast with Google TV:**
 - OS: Android TV
 - Version 1.4.20 ARM (sideloaded)

**Comment by TRtomasz** [comment]
Stremio does not control available streams so we are not able to help with such issues when streams are buffering slowly, especially if this is a http stream

**Comment by SOEBREN** [comment]
Hmm gonna have to wait the problem out then, thanks for replying either way! :)
