### ISSUE TITLE
Library lost after upgrade to 3.5.5

### ISSUE THREAD

**Issue by BorisNaguet** [Stremio/stremio-bugs#36]
Hello,

I just launched my up-to-date install of Stremio, and I had lots of movies and series (some of them partially seen) in my library.
As it proposed me to update to 3.5.5, I accepted, but just after restart of the application my library became completely empty!

Is it stored somewhere? In which file that I could backup?
Please help :)

PS: I was not a registered user.

**Comment by Ivshti** [comment]
It's synced with our servers, and it's designed in a way that complete wipe-out is impossible by accident.

That's only if you have an account though.

Can you try this:
1. Quit all stremio.exe processes - kill them with the task manager if you have to
2. uninstall stremio, click 'yes" to removing all user data
3. install it again, log into your account

If you don't have an account the only thing you can do is quit all stremio.exe processes, launch again and hope it's there.

**Comment by BorisNaguet** [comment]
I do not have an account, I re-started (making sure all processes were stopped), but library is still empty.
Can you tell in which "file" or directory is the "database" stored locally? I might have a backup...

**Comment by Ivshti** [comment]
it's %APPDATA%/Stremio or ~/Library/Application Support/stremio

**Comment by BorisNaguet** [comment]
I'm on windows (7) so it's %APPDATA%/Stremio
and I do have a backup of the whole directory!

but when I restore it and restart, I have the "welcome to 3.5.5" ppanel, and the library is empty again.
I haven't looked at all files, but in IndexedDB I have a lot of 2mb files that are removed by the restart

before restart:
```
C:\Users\myUser\AppData\Roaming\stremio.backup\IndexedDB\file__0.indexeddb.leveldb
λ ll
total 14548
drwxr-xr-x   23 myUser  Admin     4096 Feb  8 23:35 .
drwxr-xr-x    1 myUser  Admin        0 Feb  8 23:35 ..
-rw-r--r--    1 myUser  Admin   159560 Feb  8 23:30 000003.log
-rw-r--r--    1 myUser  Admin  2618457 Jan 31 22:59 000321.log
-rw-r--r--    1 myUser  Admin  2127535 Jan 27 23:46 000323.bak
-rw-r--r--    1 myUser  Admin  2127535 Jan 27 23:46 000323.ldb
-rw-r--r--    1 myUser  Admin  2112920 Jan 27 23:46 000324.bak
-rw-r--r--    1 myUser  Admin  2112920 Jan 27 23:46 000324.ldb
-rw-r--r--    1 myUser  Admin  2120442 Jan 27 23:46 000325.bak
-rw-r--r--    1 myUser  Admin  2120442 Jan 27 23:46 000325.ldb
-rw-r--r--    1 myUser  Admin  2117915 Jan 27 23:46 000326.bak
-rw-r--r--    1 myUser  Admin  2117915 Jan 27 23:46 000326.ldb
-rw-r--r--    1 myUser  Admin  2122143 Jan 27 23:46 000327.bak
-rw-r--r--    1 myUser  Admin  2122143 Jan 27 23:46 000327.ldb
-rw-r--r--    1 myUser  Admin  2132601 Jan 27 23:46 000328.bak
-rw-r--r--    1 myUser  Admin  2132601 Jan 27 23:46 000328.ldb
-rw-r--r--    1 myUser  Admin   753346 Jan 27 23:46 000329.bak
-rw-r--r--    1 myUser  Admin   753346 Jan 27 23:46 000329.ldb
-rw-r--r--    1 myUser  Admin       16 Nov  5 23:41 CURRENT
-rw-r--r--    1 myUser  Admin        0 Nov  5 23:41 LOCK
-rw-r--r--    1 myUser  Admin      339 Jan 31 21:01 LOG
-rw-r--r--    1 myUser  Admin      336 Jan 31 11:51 LOG.old
-rw-r--r--    1 myUser  Admin    27365 Jan 27 23:46 MANIFEST-000001
```

after restart
```
C:\Users\myUser\AppData\Roaming\stremio\IndexedDB\file__0.indexeddb.leveldb
λ ll
total 119
drwxr-xr-x    7 myUser  Admin        0 Feb  8 23:36 .
drwxr-xr-x    1 myUser  Admin        0 Feb  8 23:36 ..
-rw-r--r--    1 myUser  Admin   239620 Feb  8 23:36 000003.log
-rw-r--r--    1 myUser  Admin       16 Feb  8 23:36 CURRENT
-rw-r--r--    1 myUser  Admin        0 Feb  8 23:36 LOCK
-rw-r--r--    1 myUser  Admin      146 Feb  8 23:36 LOG
-rw-r--r--    1 myUser  Admin       23 Feb  8 23:36 MANIFEST-000001
```

The 000321.log file seems to have a lot of info on series I have watched at least. 000003.log have info on movies, right?

**Comment by BorisNaguet** [comment]
I completely uninstalled stremio, and installed the old 3.3.3 (I had the installer on my pc), then I restored the whole Roaming/stremio dir, and started.

and ta da!!! Everything's there.
It keeps telling me I'm not up-to date, but I won't try to update tonight...

If it can be reproduced, I can send you a zip privately.
Good night.

**Comment by Ivshti** [comment]
@BorisNaguet 3.3.3 may be using medea instead of indexeddb btw 

This actually is expected behaviour, since the migration from 3.3 to 3.4 (I think first verison using indexeddb) loses user data, unless you're using an account. 

Unfortunately there's no warning for that in the app, because originally sync worked for anonymous users too but we disabled it to save server costs.

We'll implement library migration from anonymous accounts to registered and then - please make an account if you want to secure your library.

**Comment by Draxler** [comment]
is that mean that every time from now on when there be new update, all guest accounts will lost all library after upgrade is finished. Because me to was one of manny who lost everything afer last upgrade . i use guest account. I realy hope this wouldn't happend from now on with guest account to loose all library after upgrade.

**Comment by Ivshti** [comment]
No, it happens only on the update between 3.3 and 3.4 if I'm not mistaken. That's the moment we changed DB engine.

Stremio was always designed to use with an account to sync the library, the Guest account feature was only added due to demand.

**Comment by Draxler** [comment]
@Ivshti 

Thanks for quick respons and good news ..
Regards

**Comment by Ivshti** [comment]
@Draxler no, they are not synced, but data shouldn't be lost when upgrading. The only case when it was lost was a particular upgrade which changed the DB back-end. 

But for cases such as this, also other data loss, it's recommended to use an account.

**I'm implementing functionality to import library from your guest account when signing up. If anyone wants to translate** -> https://github.com/Stremio/stremio-translations/commit/f4c012b85abdf656d0f4f18e27fc92044b9e1c3c
