### ISSUE TITLE
Streaming server is not available

### ISSUE THREAD

**Issue by PL7963** [Stremio/stremio-bugs#361]
**Describe the bug**
The Streaming server is not available and when I open any videos it shows up the subtitle error and could not update casting device info. few seconds later it pops up playback error.
It works fine in the Windows Sandbox. But not my main device

**Screenshots**
![圖片](https://user-images.githubusercontent.com/44529370/158044432-a52e7b9f-0aee-457d-a41a-ff99bc7e6450.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 21H2 Build:22000.493]
 - Browser [Stremio Application]
 - Version [Stremio 4.4.142]

**Comment by TRtomasz** [comment]
It usually happens when something is blocking connection to local streaming server. It could be a VPN, Firewall, Proxy or Antivirus configuration. You should check locally which one it is.

**Comment by PL7963** [comment]
> It usually happens when something is blocking connection to local streaming server. It could be a VPN, Firewall, Proxy or Antivirus configuration. You should check locally which one it is.

It doesn't work. I have both tried use stremio without VPNs and disable Windows Defender.

**Comment by PL7963** [comment]
After I updated my windows. It's working again.
