### ISSUE TITLE
Stremio Client Lagging/VLC works fine

### ISSUE THREAD

**Issue by Arbiterz** [Stremio/stremio-bugs#362]
Stremio client lags when watching 4K content and uses up 90 to 100 percent usage of the CPU compared to when using VLC which doesn't have any trouble streaming or use up the amount of resources that the Stremio native client does. Audio plays fine its the actual playback of the video that lags and skips frames.  Apparently I have heard other people with more low end systems and that they can't stream 720p without it lagging but streaming on VLC work perfectly fine. It seems that Stremio is very resource heavy  compared to other media players when it comes to streaming

OS: Windows 10 Home

![image](https://user-images.githubusercontent.com/44362663/158192072-322a1fc1-d181-44d5-ba88-3e2bca37f658.png)

![image](https://user-images.githubusercontent.com/44362663/158192463-6dccef4d-c53e-4cf8-ae63-7e03e115c2da.png)

**Comment by TRtomasz** [comment]
Hi, have you tried to enable Hardware accelerated video decding in the settings?
you can find it in advanced part of player settings
![image](https://user-images.githubusercontent.com/40594253/158338923-66d069d3-e65b-457f-a185-737d578a48f4.png)

**Comment by Arbiterz** [comment]
Yes turning that on still lags the video playback

**Comment by TRtomasz** [comment]
@Arbiterz  could you tell me what GPU do you have in your computer?

**Comment by Arbiterz** [comment]
Nvidia Geforce 940mx an OEM laptop graphics card

**Comment by TRtomasz** [comment]
Moste likely caused due to old GPU that does not support and HW decoding method supported by MPV

**Comment by OisinSlevin** [comment]
I have this problem with a gtx 1070 and an Intel i5-6600k, its an older system, the playback is almost identical but it seems Stremios Player is highly inefficient at 4k. I have a macbook air and it is the same story, vlc uses 1/10th the processing power and its mostly CPU issues
