### ISSUE TITLE
Stremio is not available on Android TV store

### ISSUE THREAD

**Issue by b0** [Stremio/stremio-bugs#363]
Hello,

I would suggest adding Stremio to Android TV store for easier use on TV, and maybe some Andoid TV boxes...

I did transfer apk manually and it's working great.

Do you plan on adding it there?

Thank you for your work.

Best regards

**Comment by TRtomasz** [comment]
In order to install stremio on your TV box you have to sideload it. You can download it from our website for purpose of sideloading.

**Comment by b0** [comment]
I am aware of sideloading, as mentioned in my first comment. 
Issue or the question is about adding Stremio to Android TV store, just like it's added on regular Play Store.
For example, Kodi is available on Android TV store and on regular Play Store so Kodi doesn't need sideloading - just regular install from Store on TV.

So question is, why is Stremio not available on Android TV Store? Is it something techical or developers don't want it there?

BR
