### ISSUE TITLE
After win11 dormancy or logout, the streaming server goes offline

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-bugs#367]
**Describe the bug**
After win11 dormancy or logout, the streaming server goes offline

**To Reproduce**
1. Open stremio
2. System dormancy or logout
3. Re-enter the desktop
4. the streaming server goes offline

**Expected behavior**
Should not be offline

**Screenshots**
![image](https://user-images.githubusercontent.com/58252651/160249259-482e5632-d60a-4757-8ff8-a04d8fcf3596.png)

**Desktop (please complete the following information):**
 - OS: [Win11 beta 22581.100 ]
 - Version [4.4.142]

**Additional context**

**Comment by TRtomasz** [comment]
This is not reproducible on my system with windows 11. Basing on the currenct windows 11 market share which is ~15% i'm pretty sure this problem is somehow related only to your system configuration. Otherwise we would see such issues reported much more often.
