### ISSUE TITLE
Change in UI language is not being persisted

### ISSUE THREAD

**Issue by igoracmelo** [Stremio/stremio-bugs#368]
**Describe the bug**
If I change the app language, close and reopen it, it falls back to Portuguse (PT).
My system language is Portuguese (BR) by the way.

https://user-images.githubusercontent.com/85039990/160503377-99b9db4f-6b0e-425d-8be7-3286c0cae880.mp4

**To Reproduce**
1. Go to Settings -> Language
2. Change it to any other language
3. Reopen Stremio
4. Language falls back to default

**Expected behavior**
Be able to change the UI language and persist it.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Version: stremio_4.4.142-1_amd64.deb

**Comment by TRtomasz** [comment]
This feature will not work when you use a guest account. Not sure if this is intended @core1024

**Comment by TRtomasz** [comment]
Closing as this is intended behaviour
