### ISSUE TITLE
Forced description subtitles

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#369]
**Describe the bug**
When I start a video I might see description subtitles. I mean those subtitles that describe sounds. Subtitles are turned off in the settings. To turn them off for real I need to enable them and disable again. It's random, so might be hard to reproduce. They might vanish after leaving video and starting it back.

**To Reproduce**
1. Open a video
2. See that subs are disabled
3. See description subs at the same time

**Expected behavior**
No subs should be visible when they're disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/17256400/161435921-7497eae1-db69-4017-899d-636174b85ee1.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
![image](https://user-images.githubusercontent.com/17256400/161435988-35fdcc44-ce9b-4619-9f74-bfe5f9935865.png)

**Comment by TRtomasz** [comment]
Closing as this is not reproducible. If anyone come with a method to reproduce this issue, feel free to reopen it.
