### ISSUE TITLE
New version is available!

### ISSUE THREAD

**Issue by famousfortech** [Stremio/stremio-bugs#370]
I am having this message popped up saying "New version is available! Upgrade to the latest Stremio version" then there is a link that says "Reload the user interface". When I click on the link it reloads the user interface but again the message pops up. 

The version in my Stremio is 4.4.142
And the version on the Stremio website is 4.4.142 also.

![image](https://user-images.githubusercontent.com/67818666/162217234-57cdfa9b-642e-4e8b-a734-c268d45ae185.png)

![image](https://user-images.githubusercontent.com/67818666/162216938-2df8906a-72b9-41c1-921f-ad21d1453065.png)

**Comment by TRtomasz** [comment]
@famousfortech  should be fixed now, can you please confirm?

**Comment by famousfortech** [comment]
> @famousfortech should be fixed now, can you please confirm?

Yeah, it's fixed. I was just curious, when is the new Stremio desktop version coming?
