### ISSUE TITLE
Audio slowdown and videostutters on large files (4K, 50gb+ files) 

### ISSUE THREAD

**Issue by harun911** [Stremio/stremio-bugs#371]
Dear Developers, first of all, I want to thank you for this awesome app to stream content from various sources. Im in love with ease of use and the user interface of it. 

**Describe the bug**
I have sideloaded the apk on a Nvidia shield TV 2017 and connected my realdebrid account to it. Whenever I use the built-in player and try to stream large files, meaning 50gb+, then a peculiar issue occurs with audio slowdown and stutters. Whenever I try to use an external player, like MXplayer or VLC, this problem is non-existent.
I can make a video of the issue if that is wanted. 
I like the builtin player over external players mainly because of the way downloading subtitles work and how easy it is to switch to a different one. 

**To Reproduce**
1. Connect realdebrid account 
2. Play large file over 50gb+ with builtin player

**Expected behavior**
No stutters, no audio slowdown and smooth playback. 

**Screenshots**
I can record a video of the issue, if requested. 

**Smartphone (please complete the following information):**
 - Device: Shield TV 2017
 - OS: Android 11 (Shield Experience 9.0.0)

**Additional context**
The cache has been set to 5GB and HW Decoding Mode to Full Acceleration. 

Thank you so much for all the great work!

**Comment by TRtomasz** [comment]
Plaese try using our latest app version, we changed somethings that might have improved performance when watching very large files.

**Comment by harun911** [comment]
I have tried out the latest version. Unfortunately problems are still present. The stutters even seem worse then before :(.

**Comment by M1ndo** [comment]
> I have tried out the latest version. Unfortunately problems are still present. The stutters even seem worse then before :(.

The stutters are from your device performance (cpu), slow to decode large files (4k) which causes stutters.

**Comment by harun911** [comment]
> > I have tried out the latest version. Unfortunately problems are still present. The stutters even seem worse then before :(.
> 
> The stutters are from your device performance (cpu), slow to decode large files (4k) which causes stutters.

@M1ndo I highly doubt that, because I have 0 stutters using either MX player or VLC player. This is an issue with the built-in Stremio player. NOT a limitation of my hardware.

**Comment by TRtomasz** [comment]
we have released new Android TV app. Is it still happening when using this new app?

**Comment by harun911** [comment]
YES! I can see you guys changed the player and retained the automatic subtitle option! Large files stream perfect now without any issues. I can see the whole app has been revamped for android tv and the new interface looks great! Just some minor advice, I'm not fond of the horizontal view when selecting streams. It would be nice if you guys can make users toggle between a vertical list or a horizontal view withing the interface options. But streams work perfect now! Thanks so much for all your hard work! You guys made my day!

**Comment by harun911** [comment]
I also noticed, subtitles aren't perfect yet. It would be nice to add full filenames including framerates of the subtitle files. I tested 3 movies but wasn't able to set the correct subtitle from opensubtitles. Even though the correct ones are on there.
