### ISSUE TITLE
Stremio Network error

### ISSUE THREAD

**Issue by Nirgranth** [Stremio/stremio-bugs#372]
**Describe the bug**
Cant play anything, its is extremly choppy even on complete buffered youtube videos

**Screenshots**
![image](https://user-images.githubusercontent.com/48947296/162796554-76458b0e-84ac-423c-b1a2-dae6054ef24a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional (x64) Build 19044.1586 (21H2)

**Comment by TRtomasz** [comment]
This issue is in 99.999% (0.001% for cases i have never seen) caused by your PC configuration. It could be a vpn/proxy/firewall blocking access to the local streaming server. You should check your software configuration in order to fix this issue.

**Comment by Nirgranth** [comment]
i have tried reinstalling, turning of adguard, restarting, 
![image](https://user-images.githubusercontent.com/48947296/162968330-4ecb1e33-ce8a-4098-ba9d-c54600c64b04.png)
![image](https://user-images.githubusercontent.com/48947296/162968405-0695eeea-9a02-4a8c-a8ce-6714ca8331b9.png)
what should i do to diagnose this?
