### ISSUE TITLE
Audio doesn't play on default playback device after bluetooth disconnect/reconnect

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#373]
**Describe the bug**
If I disconnect my bluetooth headphones and then reconnect them while a video is  streaming/paused.
And then I reconnect my headphones, the audio of the video doesn't play on the headphones.
I have to exit the video and play it again for the audio to come back.

**Expected behavior**
The audio is supposed to play on my bluetooth headphones after I reconnect them.

**Desktop (please complete the following information):**
 - OS: Windows 11
 
 - Version 4.4.142

**Additional context**

**Comment by TRtomasz** [comment]
If not fixed with latest MPV updates we had, you should manually go to the volume mixer and change output device for Stremio
