### ISSUE TITLE
Streaming server won't start 

### ISSUE THREAD

**Issue by otuva** [Stremio/stremio-bugs#374]
**Describe the bug**
Stremio streaming server won't start.

**To Reproduce**
1. Start stremio
2. See error

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:2248) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/stremio/server.js:135945
      details.family = details.family.toLowerCase();
                                      ^

TypeError: details.family.toLowerCase is not a function
    at /opt/stremio/server.js:135945:39
    at Array.filter (<anonymous>)
    at /opt/stremio/server.js:135944:37
    at Array.map (<anonymous>)
    at Object.address (/opt/stremio/server.js:135939:37)
    at Server.<anonymous> (/opt/stremio/server.js:135075:37)
    at Server.emit (node:events:527:28)
    at Server.emit (node:domain:475:12)
    at emitListeningNT (node:net:1414:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.1.0
```

**Expected behavior**
To be able to start streaming server

**Screenshots**
![image](https://user-images.githubusercontent.com/67955086/167084038-c61008d2-3c3e-4f81-ba07-fde7f73dcc74.png)

**Desktop (please complete the following information):**
 - OS: EndeavourOS; Build ID: 2021.12.17
 - Browser: Mozilla Firefox 100.0 64 bit for arch linux
 - Version: 100

**Solution**

As suggested by the error, tried reinstalling knowing it won't fix anything.
However changing `/opt/stremio/server.js` line 135945 from

```
details.family = details.family.toLowerCase();
```

to

```
details.family = details.family.toString().toLowerCase();
```

Solved my problem

**Comment by PranavBhattarai** [comment]
1 honest curiosity:

Why are we taking gazillion years to release the next Stremio update?

_Sorry I really don't know where to ask._

**Comment by TRtomasz** [comment]
Please check https://github.com/Stremio/stremio-core/issues/294 for the workaround of this issue

**Comment by TRtomasz** [comment]
It has been fixed in the latest release.
