### ISSUE TITLE
Firestick: Stremio 1.3.4 apk, cant connect to stream when using VPN

### ISSUE THREAD

**Issue by JS-World66** [Stremio/stremio-bugs#377]
2019 4k Amazon Firestick, 1.3.4 ARM .apk
Noticed that if I am on a VPN (I've tried a couple) and I attempt to play an item in my library, upon choosing my source it will repeatedly fail to connect, title blinking indefinitely (1hr+) as it tries.
This is strange for a few reasons. First, I can open stremio, log in, view items in my library with loaded title cover images, check season listings, etc. It is only when I attempt to view the content that it fails using a VPN connection. Second, if I disable the VPN and use my normal internet connection, Stremio seems to load streams fine, including the ones I had trouble with specifically. Third, I have verified that this is an issue localized to the firestick specifically, google play store stremio.apk on an android phone works fine with or without VPN. Desktop apps with or without VPN also works fine, and I have been using this workaround for about a few weeks now. Fourth, the flashing title of the show you're attempting to load (tried a bunch of shows with similar issues so not title specific) stays flashing for a long time. Note, user can hit the 'back' button at any time and is not stuck in the loading menu.  

VPNs I've experienced this with:
Proton VPN, Thunder VPN

Phone with Play store .apk works fine: LG G7 ThinQ, Android 9, Model: LG-G710PM

And yes, I've tried re installs/different .apk versions from the Stremio website.

**Comment by TRtomasz** [comment]
Closing this issue as we have released new app just for android TV system. If it is still happening on android TV app please let us know
