### ISSUE TITLE
Add a feature to auto clear cache to fix this bug

### ISSUE THREAD

**Issue by eSkRo32** [Stremio/stremio-bugs#381]
I found a bug on my Nvidia Shield TV. 
As described Here 

https://www.reddit.com/r/StremioAddons/comments/v8zukn/torrentio_no_streams_found/

When movies don't return links, 
It seems clearing the cache fixes it! 

Would be Nice to have an auto clear cache in stremio settings. Auto Clear at Lunch or once closed or something. 

Thanks 👍

**Comment by TRtomasz** [comment]
Cache exists for a reason, it stores for example images and other metadata to reduce load on stremio and addons server. Making apps to autoclear cache would basically contradict the whole idea of having cache. It is more reasonable for users to manuall clear app cache in such cases.
