### ISSUE TITLE
When starting a new stream, the player tries to start before it has enough data and then stops, removing the controls

### ISSUE THREAD

**Issue by arpatma** [Stremio/stremio-bugs#382]
**Describe the bug**
When starting a new stream, the player tries to start before it has enough data and then stops, removing the controls, it cicles in an irritating hicup of 1 second of reproduction, undetermined pause, and another second of reprodution, pause... etc.

**To Reproduce**
Select a video or go to the next episode of a series automatically

**Expected behavior**
1. The player should wait for enough content to be buffered before trying to start.
2. The player should not try to resume content in hicups when it is clear that there is not enough buffered contend
3. The controls should be available in the periods of empty buffer so the user can PAUSE the video to allow for content to be further buffered.
4. There should be an automatic calculation of how much buffering is needed to avoid starting too early when it is clear that the buffer will be emptied during play - that is - if the speed of the download is less than the speed of the realtime content, the buffer should be fulled until it is possible to reproduce the all episode in one go, except if the user insists in seeing a part of the content. For this, the controls should not be removed as point 3 states.

**Screenshots**
Not relevant

**Desktop (please complete the following information):**
 - OS: Any
**Smartphone (please complete the following information):**
Not tested

**Additional context**
It happens all the time, without exception.
Tested with Internet connections from 30/3Mbps up to 100/10Mbs

**Comment by TRtomasz** [comment]
Stremio stats video when it has enough to play part of it. If you don't have cache turned on and try to play something that is not well seeded or hosted on a server that can provide high enough speed you can experience video buffering and laging but it is not something we controll.
