### ISSUE TITLE
Frame skips when subtitles are turned on

### ISSUE THREAD

**Issue by burkica** [Stremio/stremio-bugs#384]
**Describe the bug**
When subtitle, external or internal are turned on, on next subtitle line there are frame stuttering and frame skips. Using real debrid.

**To Reproduce**
Video plays pefectly until you turn on subtitles. On all videos and streams is the sam

**Expected behavior**
Not to stutter with subtitles

Device:
Xiaomi MI P1 55"
Android TV
APK downloaded from your site first recommended APK.

**Comment by TRtomasz** [comment]
Could you please provide more details so we can try to reproduce this issue?

**Comment by kuulemart** [comment]
Same for me on Chromecast with Google TV using StremIO 1.5.0 and Real Debrid. Currently using external player as a fix but it is a bit inconvienient.

**Comment by kuulemart** [comment]
StremIO 1.5.3 still has that issue on Chromecast with GoogleTV

**Comment by kuulemart** [comment]
Ok, now works fine with new Android TV interface.

**Comment by TRtomasz** [comment]
Thank you for the update! :)
