### ISSUE TITLE
Flatpak Cache Problem

### ISSUE THREAD

**Issue by otuva** [Stremio/stremio-bugs#386]
**Describe the bug**
Stremio tries to reach home folder for cache option even though it runs inside bubblewrap. If the permission for home folder is not granted stremio then fails to cache videos and save settings. 

**To Reproduce**
1. Run flatpak through cli 
2. See message 

```
...
hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /home/tfp/.stremio-server
Enabling casting...
...
```

4. Try to change cache settings and restart
5. See settings are not applied and stream was not cached

**Expected behavior**
Stremio should realize it's running under flatpak and set path's accordingly like steam client

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Browser: firefox for arch 102.0 (64-bit)
 - Stremio version: 4.4.142

**Solution/Workaround**
- Install flatseal for easy configuration
- Navigate to stremio

There are two applicable solutions just pick one. The first one is more preferable imo (change user `tfp` to your actual user)

1- Under environment section export home variable like

```
HOME=/home/tfp/.var/app/com.stremio.Stremio
```

2- Under filesystem > otherfiles add 

```
~/.stremio-server
```

**Solution screenshot**

![image](https://user-images.githubusercontent.com/67955086/177012102-4b7c12aa-31c5-48d7-9d22-54a58b3675ec.png)

**Comment by otuva** [comment]
For people who might find this issue later. Setting persistent files is actually better than workarounds above

![image](https://user-images.githubusercontent.com/67955086/220087204-122984e6-9a14-4dac-b7f4-430a35349b44.png)

**Comment by oguzkarayemis** [comment]
If it won't bother you, what is the difference? I already did the other one, so I'm curious about it.

**Comment by otuva** [comment]
@oguzkarayemis Virtually, there's no difference as long as Stremio has no access to home directory. Because what the app sees won't change anyway. This is for the sake of least alteration, meaning that if a directory does the job, might seem excessive to exporting your home variable.

Former is the one with only directory, latter is the one with the exported home variable
![image](https://user-images.githubusercontent.com/67955086/221091918-48b51de1-29ee-4111-9d15-76467896543d.png)
