### ISSUE TITLE
Cannot start Stremio, stremio: error while loading shared libraries: libmpv.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghostfish0** [Stremio/stremio-bugs#391]
**Describe the bug**
Can't start Stremio, i tried opening it from the terminal and then got this error: 
```
stremio: error while loading shared libraries: libmpv.so.2: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Open up Terminal 
2. `$ stremio`
3. Terminal returns the error`stremio: error while loading shared libraries: libmpv.so.2: cannot open shared object file: No such file or directory` and stremio dies.

**Expected behavior**
Stremio should start.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: Stremio 4.4.142-2

**Smartphone (please complete the following information):**

Thank you in advance!

**Comment by ghostfish0** [comment]
I reinstalled Stremio, it works fine now!

**Comment by Churchexe** [comment]
I'm getting this issue again on an arch derivative (endeavourOS) and I just reinstalled it and am still having the issue.
