### ISSUE TITLE
ERROR_CODE_IO_BAD_HTTP_STATUS

### ISSUE THREAD

**Issue by Qutaiba-Khader** [Stremio/stremio-bugs#392]
After last update v1.5.3 on Android TV (Nvidia shield+ Chromecast google TV) I'm facing this error for Most of videos

ERROR_CODE_IO_BAD_HTTP_STATUS

Screen shot: https://smartgemsbok-sto.energycdn.com/dl/VXs9ZztADg_pA0khKZ0y8Q/1660766133/874708575/62f40d19c37e92.87702378/Stremio_20220810_224934.png
![Stremio_20220810_224934](https://user-images.githubusercontent.com/6103683/184008696-c20a9e50-73f6-4fee-a00c-646cbec23500.png)

- Nothing changed when toggle (hardware acceleration)
- Nothing changed when toggle (Tunnelled playback) 
- The external player is working

**Comment by Malraoosh** [comment]
Same issue here.

**Comment by malikAbuqaoud** [comment]
I have the same issue 😕

**Comment by TayseerGh** [comment]
I'm getting the issue.

**Comment by haytham1990** [comment]
I hava the same issue.

**Comment by aeedrees** [comment]
I face the same issue

**Comment by YaheaZaid** [comment]
Unfortunately i am have same problem

**Comment by TheBeastLT** [comment]
Which addon are you using to play these streams?

**Comment by Qutaiba-Khader** [comment]
> Which addon are you using to play these streams?

Orion + Torrentio

Using real debird/ all debird/ premiumize

**Comment by TRtomasz** [comment]
This is caused by orion returning 5xx errors. This is not something caused by stremio.

**Comment by Qutaiba-Khader** [comment]
> This is caused by orion returning 5xx errors. This is not something caused by stremio.

I tested it without orion, nothing changed but i found that ((only real debird)) Links making this error (all debird+premiumize)) is working fine, but real debird is working on old version only , so there's something in new version (TV version)

**Comment by TRtomasz** [comment]
@Qutaiba-Khader  please give us a screenshot where you select streams that does work in old app version and does not work in the new TV app.

**Comment by Qutaiba-Khader** [comment]
> @Qutaiba-Khader please give us a screenshot where you select streams that does work in old app version and does not work in the new TV app.

@TRtomasz 
This is a small video to clarify more:
[https://doubtfullamb-sto.energycdn.com/dl/n59PLqBJsaWMiFGid7d7FA/1661248471/874708575/62fb69548d1008.33204504/InShot_20220816_125350243.mp4](https://doubtfullamb-sto.energycdn.com/dl/n59PLqBJsaWMiFGid7d7FA/1661248471/874708575/62fb69548d1008.33204504/InShot_20220816_125350243.mp4)

**Comment by Qutaiba-Khader** [comment]
After update v1.5.4 (TV edition) everything is working now, thanks guys
