### ISSUE TITLE
Subtitle bug Android TV

### ISSUE THREAD

**Issue by ProgRock1000** [Stremio/stremio-bugs#395]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ProgRock1000** [comment]
After you start playback, you can't change the caption you choose. No matter how many available captions exist, you select the caption you want, but playback always keeps the first one that was selected.

**Comment by TRtomasz** [comment]
This will be fixed in next release that should be available today.
