### ISSUE TITLE
No User Agent in Android TV version

### ISSUE THREAD

**Issue by ConanArther** [Stremio/stremio-bugs#396]
Hi, some addons are not working with the new Android TV version while they work with the old one. (The streams list do not appear in the menu)
[This addon is one of them](https://github.com/ssnjr2002/stremio-gdrive), I believe this is because these addons are not recognizing the new version's user agent.

Running `request.headers.get('User-Agent')` with the new version returns `none`, while running it on the regular version returns the correct user agent.

**Comment by jaruba** [comment]
@ConanArther but the lack of an `User-Agent` header should not cause such an issue, is there any reasoning behind the presumption that this is the issue?

**Comment by ConanArther** [comment]
> @ConanArther but the lack of an `User-Agent` header should not cause such an issue, is there any reasoning behind the presumption that this is the issue?

I was just guessing to be honest, I'm not a developer but I was just trying to figure out why it works with the old version but doesn't with the new one, and the lack of `user agent` was the only difference I could spot

Do you have a clue on why this is happening?

**Comment by jaruba** [comment]
> Do you have a clue on why this is happening?

Not yet, as the gdrive addon is a private addon (requires access token, etc) so we can't find any stream response extract to test with..

If you have such an example stream response from the addon, and can email it to me (my email is publicly available on my github account: https://github.com/jaruba ), then we could debug the issue in the app.

**Comment by ConanArther** [comment]
> > Do you have a clue on why this is happening?
> 
> Not yet, as the gdrive addon is a private addon (requires access token, etc) so we can't find any streams response extract to test with..
> 
> If you have such an example streams response from the addon, and can email it to me (my email is publicly available on my github account: https://github.com/jaruba ), then we could debug the issue in the app.

Would it be better if I create a temporary heroku account with the addon and hand you its user+pass so that you can test it out as much as you like?

**Comment by jaruba** [comment]
it might be better, as with an extract we can only debug parsing issues, with a running addon we can debug request / response header issues too.

**Comment by ConanArther** [comment]
It's fine by me
I'll create an account later today and email you the details 👍🏻
Thank you guys ♥️

**Comment by ConanArther** [comment]
I've sent you an email with the credentials, @jaruba 
Please let me know if anything else is needed

**Comment by jaruba** [comment]
@ConanArther we received it, thanks, we will keep you updated

**Comment by jaruba** [comment]
@ConanArther the fix can be found here, it's an addon issue: https://github.com/ssnjr2002/stremio-gdrive/issues/25

**Comment by ConanArther** [comment]
Thank you, jaruba, I really appreciate your help!

Now the only thing that's "missing" is the semi-transparent subtitle background lol or a blurred background like in the desktop version (just kidding though, it's not a big deal lol)

(I'll delete the heroku account since it's no longer needed, if that's fine with you)

**Comment by jaruba** [comment]
@ConanArther if it is working for you, then no, the heroku deployment is no longer needed

regarding feature requests, you can make such requests at https://github.com/Stremio/stremio-features , but i'm pretty sure this was requested before already

**Comment by AlyafeiAli** [comment]
Yes, it's working fine now, so I'll just delete it.
And don't worry about the feature request, I was just kidding lol
I appreciate your help and support
