### ISSUE TITLE
[Windows] Stremio 4.4.142 Server Stops Working

### ISSUE THREAD

**Issue by M1ndo** [Stremio/stremio-bugs#397]
Stremio shutdowns randomly after couple minutes of content consuming, Happened Multiple Times Throughout The Course Of Using Stremio.
There's a [Fix](https://github.com/Stremio/stremio-core/issues/294#issuecomment-1126595345) for Linux but what about windows?
```
QProcess::ProcessError code: 1

(node:1813) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by jaruba** [comment]
Moved to `stremio-bugs`, this is not a `stremio-core` issue.

The fix for Linux cannot be applied to Windows, because it's a Linux specific issue, these 2 issues are not related.

Do you have caching enabled? How much free disk space do you have on your main partition?

**Comment by M1ndo** [comment]
Closing as issue disappeared by itself.
