### ISSUE TITLE
(Android TV) (issue) weird behavior when selecting items from *Continue Watching* or *Library*

### ISSUE THREAD

**Issue by eSkRo32** [Stremio/stremio-bugs#398]
Hi there,
Not sure Stremio is meant to act this way but
When selecting stuff from 
*Continue Watching* or *library*
Instead of going in the description screen
Stremio plays the item.
So it doesn't let me select a stream link. 

Feels weird...
Specially when clicking on a tv show in my library. 
Stremio starts the stream right away 
Instead of letting me select a desired season & episode.. 

Thanks 👍

**Comment by TRtomasz** [comment]
Thanks for reporting, please next time use the template to report the issue.

**Comment by TRtomasz** [comment]
Stremio remembers streams you watched, but only locally. So if you try to continue watching something on other device it would show streams lists. But if you are trying to continue watching on the same device it will reuse the same stream you used last time.
