### ISSUE TITLE
(Android TV) (issue) items not dismissing in Library 

### ISSUE THREAD

**Issue by eSkRo32** [Stremio/stremio-bugs#399]
Hi again 👍
items in my library are not dismissing 
When i click & hold my "ok" button and select "dismiss" from the menu that appears....

But items do dismiss from library if
I click on my "ok" button on Any of them 
And on the description screen that appears 
select the *remove from library* button....

Thanks 👍

**Comment by jaruba** [comment]
The functionality of the "Dismiss" button is to remove the saved progress, like removing the item from Continue Watching.

I admit that "Dismiss" is a confusing name for this context.

For now, the only way to remove an item from library is to first open the item and pressing the "Remove from Library" button.
