### ISSUE TITLE
Can't select subtitles when casting content

### ISSUE THREAD

**Issue by LeunensMichiel** [Stremio/stremio-bugs#401]
**Describe the bug**
When using the macos app, I can't select select subtitles when chromecasting. It's like the menu disappeared.
On the Android app, something likewise happens. When chromecasting, I **can** access the subtitle menu, but the subtitles won't appear.

**To Reproduce**
1. (chrome)Cast something
2. Try to enable subtitles
3.  The subtitle menu/button is not showing (MACOS) or the subtitles won't turn on (Android). Even if the toggle switch is toggled on.

**Expected behavior**
Subtitles should show.

**Desktop (please complete the following information):**
 - OS: MacOS 12.5.1
 - Stremio App (latest)

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android 11
 - Version: latest stremio app in the play store

**Comment by TRtomasz** [comment]
If this is about embedded subtitles, this is currently not possible, it is because chromecast is not aware of embedded subs.

**Comment by LeunensMichiel** [comment]
> If this is about embedded subtitles, this is currently not possible, it is because chromecast is not aware of embedded subs.

Okay, didn't know that. But I'm having the same issue with addon subtitles.

**Comment by Skooopy** [comment]
Same for me

**Comment by pinkfloydsito** [comment]
Same for me
