### ISSUE TITLE
Chromecast with Google TV Playback Speed

### ISSUE THREAD

**Issue by ChaoDrake** [Stremio/stremio-bugs#402]
**Describe the bug**
Playback speed cannot be selected while watching a video, can move the slider but it does nothing when pressed. Features available on Android TV version do not work on Google TV (i.e. search results on home screen, continue watching on home screen). 

**To Reproduce**
1. Go to any stream.
2. Click on playback speed.
3. Scroll down to 2.0
4. See error: pressing does not change speed

**Expected behavior**
Pressing the playback speed should change the speed to selected speed (i.e. 1.5, 2.0 etc.)

**Screenshots**
No screenshot on Google TV.

**Smartphone (please complete the following information):**
 - Device: Chromecast with Google TV
 - OS: Android TV OS
 - Browser: No browser
 - Version 1.5.5 (Android TV version)

**Additional context**
No additional context.

**Comment by TRtomasz** [comment]
Please update your issue with the template

**Comment by ChaoDrake** [comment]
Updated with template above, hopefully it's correct.

**Comment by TRtomasz** [comment]
Closing this, simply some streams do not allow changing playback speed.
