### ISSUE TITLE
Crash during the Catalog load and scroll

### ISSUE THREAD

**Issue by michalss** [Stremio/stremio-bugs#405]
HI,

Im an developer and having a strange issue with my addon. When i try to load category it load oks, but once i scroll down with mouse its simple gets back to Board without any error, any warning, nothing. Is there any log file i can check what happened ? And its actually happening only with movie category.

**Comment by michalss** [comment]
This is actually happening only with application, on website https://app.strem.io/shell-v4.4/ its working just fine. Notice, there could be a slight delay with loading images from source, could be this an issue ? If so please fix it, since this free services can load resources  can get a little bit of time..

**Comment by TRtomasz** [comment]
Please use the template when reporting an issue. So we can have clear way to reproduce the issue.
