### ISSUE TITLE
Sync addons doesn't uninstall addons on Android tv 

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-bugs#406]
**Describe the bug**
When I add a new addon on my phone then delete it and sync my Android tv it doesn't remove the addon. I tried uninstalling and reinstalling the whole app and the addon still remains on my Android tv but not my phone 

**To Reproduce**
1. Install an addon on your phone
2. Sync addons on your android tv
3. Uninstall the addon on your phone
4. Resync and the addon will remain 

**Expected behavior**
The addon should be removed from the android tv as well 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Mi9 
 - OS: android 11
 - Version 1.5.5

Running on Android tv latest version of stremio 
**Additional context**

**Comment by TRtomasz** [comment]
Sorry, i'm not able to reproduce this issue. It work well with mobile and desktop app. Please recheck that you have internet connection on your mobile device. Or maybe you have addon installed twicem, Also If this is about some specific addon let us know which one.

**Comment by mo-5** [comment]
I just tested it out again it seems to sync correctly but only if I leave the addon uninstalled for a while then sync. It seems to occur with all the addons. Also if I watch something on my phone and then move to my tv my progress takes a long time to sync. I could close the issue if you are unable to reproduce it.
