### ISSUE TITLE
When i try to see some movies, i got a white screen.

### ISSUE THREAD

**Issue by Masshat** [Stremio/stremio-bugs#41]
Media[4796]: segfault at 0 ip           (null) sp 00007f24f3ed22d8 error 14 in Stremio-runtime[400000+3242000]

I get this error in the log of dmesg command.

**Comment by Ivshti** [comment]
Thank you for the error message! Any chance you're using 3.5.5 or 3.5.6?

**Comment by Masshat** [comment]
Hi, i'm using 3.5.5

**Comment by Masshat** [comment]
I got a white screen and stremio go back in the movies selections tab.

**Comment by Ivshti** [comment]
@Masshat please upgrade to latest Stremio from http://www.strem.io! Should be 3.5.7 and should fix the issue

**Comment by Masshat** [comment]
Thx you.
