### ISSUE TITLE
(Android TV)(Mi Box S) Opensubtitles Addon Won't Load

### ISSUE THREAD

**Issue by tarakbumba** [Stremio/stremio-bugs#410]
**Describe the bug**
I have installed opensubtitles addon and configured it correctly for my native language "Turkish". I use Stremio both on my phone, Windows PC and Mi Box S device. I can display movies/shows with subtitles fetched from Opensubtitles site via official addon on pc and phone. But Android Tv version of Stremio on my Mi Box S device doesn't display subtitles. Shows only "None". 

Addons screen doesn't list addons, only sync option is available. Thus, I cannot control if addon is really loaded. I removed stremio, re-installed, synced addons (which shows addons synced successfully) without success. My stremio version is 1.5.6

**To Reproduce**
1. Install opensubtitles addon with Turkish configured
2. Open a show on Android Tv app (for example House Of Dragons Part 1)
3. See there's no subtitles
4. Open same show on either desktop app or mobile app and see there's subtitles.

**Expected behavior**
Opensubtittles addon loaded and display subtitles.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro
 - Browser Edge
 - Version 4.4 Beta

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android 9
 - Version 1.5.5

**Comment by TRtomasz** [comment]
Sorry, we can't help with issues caused by community addons. Community opensubtitles addons seems to be not working. I can't install it.
