### ISSUE TITLE
Android tv watch history sync 

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-bugs#412]
**Describe the bug**

I noticed that when you watch on your phone and then want to switch to your tv you have to wait a few seconds for history to load (where you left off on your phone ) and sometimes it doesn't load up. Is it possible to make the api call before loading that way it's easier to just click and play. Currently I have to give it time and if I click too early then it sends me back to where I was on the android tv before watching on my phone. 

**To Reproduce**
1. Watch something on your android tv and then close it 
2. Go to android mobile version watch the same thing for a bit then close it  
4. Return back to your android tv and click on the same movie or show and you will see your phone progress was not loaded ( either not loaded or takes a few seconds to load)

Sometimes it loads progress but you have to wait a few seconds and if you click too early it goes back to what is saved in your android tv before using your phone.

**Expected behavior**
Load progress on app start instead of loading what's saved on the app and then making the API request.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: mi9
 - OS: android 10
 - Version latest version 

**Additional context**

**Comment by TRtomasz** [comment]
Please update your issue with te bug template.

**Comment by mo-5** [comment]
> Please update your issue with te bug template.

Updated

**Comment by TRtomasz** [comment]
More details will be needed to reproduce this issue. As at  the moment i can't reproduce it

**Comment by mo-5** [comment]
I am not sure. I am able to reproduce it every time.
1. Watch something on Android tv
2. Close the Android tv 
3. Open up the Android app on your phone continue watching 
4. Close the Android app on your phone 
5. Open up your tv again and click play on the same show

You will notice it will play from where you left off on the Android TV previously and disregard what you have watched on your phone

**Comment by TRtomasz** [comment]
I think you might have killed all your sessions and didn't relog on TV app aftter this. This cause TV app cannot synchornize. You should log out from the TV app and log in again.
