### ISSUE TITLE
Stremio instantly crashing when i move mouse out of the window

### ISSUE THREAD

**Issue by lucasfkm** [Stremio/stremio-bugs#417]
Stremio is instantly crashing after I login. If I try to maximize the Stremio's window. It also fails to give the problem report.
I'm running it on a ThinkPad T450 with Fedora 36 OS, still learning linux.

**Comment by TRtomasz** [comment]
First of all please use the template when reporting issue. 
Such issues usually is caused by faulty GPU drivers. You might try to change them.
But to confirm you should start stremio from terminal and send us terminal output log.
