### ISSUE TITLE
Android TV: displaying multiple subtitles lines at the same time 

### ISSUE THREAD

**Issue by emmylissa** [Stremio/stremio-bugs#420]
**Describe the bug**
When there should be more than one line of subtitle displayed, only one is showed.

For exemple, in anime particularly, it is common to have a subtitle line for the background discussions, one line for the main discussion and one for translation of signs on building. Or you can have one line for dialog and one line for the lyrics of the song.

The issue is exactly the same as described in issue #364, only I've noticed this on Android TV.

**To Reproduce**
1. Go to Koukyuu no karasu episode 1x2.
2. Go to time 22:16
3. Here I only have the subtitles for the lyrics displayed, not the dialog

**Expected behavior**
All subtitle lines should be displayed in screen

**Comment by TRtomasz** [comment]
closing as duplicated of https://github.com/Stremio/stremio-bugs/issues/364
