### ISSUE TITLE
Application reload on orientation change 

### ISSUE THREAD

**Issue by adarshsingh87** [Stremio/stremio-bugs#423]
**Describe the bug**
Changing the orientation of the device after the application launch results in a total reload(gets kicked out of the player) with a modal containing some json

**To Reproduce**
Steps to reproduce the behaviour:
1. Open application in portrait mode
2. Rotate the device to landscape
3. Observe the reload with the modal 

**Expected behaviour**
The application rotates, preserving the state. 

**Screenshots**
![Screenshot_20221105-013723_Stremio.jpg](https://user-images.githubusercontent.com/56337250/200065809-bb5c7e31-c7f1-449d-a915-9b9ad214bcd9.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s10 plus
 - OS: Android 12, one ui 4.1
 - Browser NA (Stock app)
 - Version 1.5.5

**Comment by TRtomasz** [comment]
Please update app to the latest version which is 1.5.8

**Comment by adarshsingh87** [comment]
any trusted source for download? the website is still on 1.5.5 and the app is unavailable on play store for me

**Comment by TRtomasz** [comment]
@adarshsingh87  should be available on our website soon.

**Comment by TRtomasz** [comment]
New app version is no available on our webpage, please let us know if it works.

**Comment by adarshsingh87** [comment]
It works now, thanks.
