### ISSUE TITLE
Error while loading shared libraries: libmpv.so.1

### ISSUE THREAD

**Issue by dyatlov86** [Stremio/stremio-bugs#426]
stremio throws an error while opening and this is the output

"stremio: error while loading shared libraries: libmpv.so.1: cannot open shared object file: no such file or directory"

[onur@onur-82kt ~]$ locate libmpv.so
/usr/lib/libmpv.so
/usr/lib/libmpv.so.2
/usr/lib/libmpv.so.2.0.0

btw, i use arch linux and it seems mpv did some changes.

i tried the below command and it works

`[onur@onur-82kt lib]$ sudo cp libmpv.so libmpv.so.1`

**Comment by shscs911** [comment]
@dyatlov86 
Rebuilding the package is sufficient to fix this. No need to copy the libraries.

* Using AUR helper like yay: `yay -S stremio`
* Using PKGBUILD: `makepkg -si` in the PKGBUILD location

**Comment by TRtomasz** [comment]
You have to install missing  libmpv.so.1 library
