### ISSUE TITLE
(Android TV) Some text appears cut on top or bottom

### ISSUE THREAD

**Issue by soliviantar** [Stremio/stremio-bugs#427]
**Describe the bug**
Some text appears cut at the bottom on the Marquee interface style streams selector and at the top on the player screen while playing.

**To Reproduce**
Stream selector:
1. Go to a settings, select the Marquee interface.
2. Search for a show. 
3. The text appears cut at the bottom of the last line (see screenshots).

Player:
1. Play a show on Stremio (internal player)
2. The title appears cut on the top part (see screenshots).

**Expected behavior**
Text should appear complete.

**Screenshots**
Marquee
![Screenshot_20221119-153837_Photos~2](https://user-images.githubusercontent.com/25809253/202856607-96bdea97-b703-4b93-bbf4-60c7e5d65a91.png)
![Screenshot_20221119-153856_Photos~2](https://user-images.githubusercontent.com/25809253/202856609-8a8800c3-5d8e-40f3-aefb-6b2c7f392267.png)

Player
![Screenshot_20221119-153948_Gallery~2](https://user-images.githubusercontent.com/25809253/202856612-eb083a61-58dd-4aa2-bf1b-52d9b889f8ef.png)

**Android TV:**
 - Device: Chromecast with Google TV HD
 - OS: Android 12
 - Stremio version: 1.5.6

**Comment by linguax-gc** [comment]
I noticed it also happens on the configuration screen in the player.
![Screenshot_20221119-162119_Photos~2](https://user-images.githubusercontent.com/25809253/202858144-1dbb5f0b-ce60-4828-88a0-93ddee6b85ef.png)

**Comment by TRtomasz** [comment]
seems to be fixed now

**Comment by soliviantar** [comment]
> seems to be fixed now

Is there a new Android TV version? I didn't see any on the Play Store. I'm on 1.6.7 and the problem persists.

**Comment by soliviantar** [comment]
Hi @TRtomasz this is not fixed, unfortunately.

See ![this](https://github.com/Stremio/stremio-bugs/assets/25809253/d52795f2-4143-4e05-a3ce-7a5d42744e16), for example.
