### ISSUE TITLE
New items doesn't load when going down via down arrow

### ISSUE THREAD

**Issue by edwyn-amador** [Stremio/stremio-bugs#428]
So, there's an issue in Stremio (Discover tab), it just doesn't load any new item when going down via down arrow, it requires a mouse scroll or pressing the End key. This happen because the border selection doesn't fully detect the height of the item, so whenever it requires a new pagination load the app doesn't know it has already reached all the way down needing to load new items. By scrolling down via scrollbar, mousewheel or by pressing the End key is the only way currently.

Please solve this issue to have a proper fully working keyword navigation, Thanks!

**Comment by edwyn-amador** [comment]
Any update on this?

**Comment by TRtomasz** [comment]
Sorry no update, this is low priority issue for us right now.

**Comment by edwyn-amador** [comment]
> Sorry no update, this is low priority issue for us right now.

I understand, well, at least I know that you are now aware of this bug/issue.

**Comment by TRtomasz** [comment]
should be fixed after redesign
