### ISSUE TITLE
libcrypto.so.1.1: cannot open shared object file: No such file or directory on Ubuntu 22.04

### ISSUE THREAD

**Issue by dhlpradip** [Stremio/stremio-bugs#429]
Stremio fails to open in ubuntu 22.04LTS with the folloeing message.
`stremio: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`
I tried a few things and figured out that ubuntu 22.04 doesn't support _libssl1.1_ and rather comes with _libssl3_.
Is this why this is happening? How Can I solve it?
![Screenshot from 2022-11-26 09-52-59](https://user-images.githubusercontent.com/25703330/204072092-75960ed1-5e01-4892-8d61-7488492ec0fb.png)

**Comment by TRtomasz** [comment]
You have to install missing library manually.

**Comment by root-phantasoft** [comment]
That isn't a great response. It's, of course, your prerogative to mark this "won't fix" and close it, but "you have to install the missing library manually" isn't an ideal response, as the library isn't really  missing. Stremio is still using a *very* outdated version of the library, one that is not supported on modern Linux distros. The two previous versions of Ubuntu already don't support that version of libcrypto, and there is no way to install it without breaking other stuff. 

Not working in 22.10 nor 22.04, so both the current and the LTS release.
