### ISSUE TITLE
Add option to edit vertical of sub

### ISSUE THREAD

**Issue by kedaitinh12** [Stremio/stremio-bugs#430]
Some video i watch had hardsub and when use subtitles, the softsub overlap hardsub and can't read. Will pleasure if developer add option to edit vertical of softsub will read easily. I use android TV 11

**Comment by RDKRACZ** [comment]
> this feature is available on stremio for android TV and it is called "vertical offset"

What about Stremio desktop? It seems like there is no such option there.
![image](https://user-images.githubusercontent.com/43277609/209480932-b3beecba-30ac-4870-b2e6-98a17cf7c923.png)
