### ISSUE TITLE
His Dark Materials' meta data has wrong dates

### ISSUE THREAD

**Issue by victorgveloso** [Stremio/stremio-bugs#432]
**Describe the bug**
His Dark Materials is out. CineMeta says it is upcoming. Why?

**Expected behavior**
Episodes 1 and 2 launched last week.
Episodes 3 and 4 launched yesterday. 
Episodes 5 and 6 will be aired on Dec. 21

**Screenshots**
![Screenshot_20221215_212749](https://user-images.githubusercontent.com/11022419/208007968-f55db7c7-32c2-4b8b-8cbd-0236d1bd7ab4.png)

**Desktop (please complete the following information):**
 - OS: -NA-
 - Browser  -NA-
 - Version  -NA- [Server side or cache delay]

**Comment by TRtomasz** [comment]
Stremio does not control such data, it is not something that can be considered a bug.
