### ISSUE TITLE
Crackling in the sound

### ISSUE THREAD

**Issue by Filmoo** [Stremio/stremio-bugs#434]
**Describe the bug**
Crackling in the sounds are there when I launch an episode of Neon Genesis Evangelion. It can be fixed by switching the audio track from the 5.1 to the 2.0, leaving the options menu, and switching back the audio track 5.1 .

**To Reproduce**
1. Launch an episode of Neon Genesis Evangelion  with the 5.1 QAAC audio track, and it should be there.

**Expected behavior**
No crackling in sound

**Screenshots**
One of the torrent that has the issue :
![IMG_20221223_222935](https://user-images.githubusercontent.com/77511905/209407077-6751ac74-07fe-4a22-ac30-235bdaf285c9.jpg)
The two audio tracks (can't really fully show them) :
![IMG_20221223_223851](https://user-images.githubusercontent.com/77511905/209407747-a7bd572b-e594-46ff-b319-628416fda57c.jpg)

**Smartphone :**
 - Device: One plus 9
 - OS: OxygenOS 13.0 | Android13
 - Browser: Application
 - Version: 1.5.8

**Additional context**
The bug seems fairly easy to fix, but can be really anoying. I guess it comes from having 2 audio tracks. Never had this issue on previous torrents. Maybe one of the audio is wrong ? I'm kind of clueless, I'd really like to debug this 😈

**Comment by TRtomasz** [comment]
can't reproduce on my device, it works fine, guess your device can't decode 5.1 audio track properly thats why there is `crackling`
