### ISSUE TITLE
Subtitles too high when the cursor is moved?

### ISSUE THREAD

**Issue by RDKRACZ** [Stremio/stremio-bugs#435]
This would fit better in the discussion tab, but these are disabled for this repo.

I think the subtitles are displayed too high when the progress bar is being displayed. 
![Screenshot from 2022-12-25 21-10-46](https://user-images.githubusercontent.com/43277609/209480998-8b6e8fbc-774a-46b3-9ac1-60a9e8ff4e1b.png)
![Screenshot from 2022-12-25 21-11-00](https://user-images.githubusercontent.com/43277609/209480999-577ff363-df05-4754-aad2-e9510d8f8473.png)

**Comment by TRtomasz** [comment]
Subtitles are moved up when UI is displayed to avoid covering subtitles with UI.
