### ISSUE TITLE
Stremio caching over the cache limit

### ISSUE THREAD

**Issue by RDKRACZ** [Stremio/stremio-bugs#436]
#215
What are the requirements for Stremio to clear video cache? Is it clearing it only when the cache limit is reached, or maybe some different conditions? In my experience, the limit was set to 2 GB, but in the Android TV settings I can see the app size is nearly 2960 MB.
When I disabled the cache, then played a movie and paused it, the connection status info / streaming report button was still indicating that the buffer size is getting larger even a minute later.

**Comment by TRtomasz** [comment]
Stremio clears cache when you start playing a video and cache limit has been reached. If you play a single video file that size is larger than cache size you set it will still take as much space as that file needs.
