### ISSUE TITLE
ESC and Backspace exits fullscreen

### ISSUE THREAD

**Issue by raycekar** [Stremio/stremio-bugs#437]
Im running Debian Stable with i3 (version 4.19.1-1) and Stremio deb package (Stremio 4.4.159, Web UI 4.4.159, Server 4.19.0) downloaded from the official site.

In running in fullscreen mode, when trying to go back using either the Esc or Backspace keys, stremio exits fullscreen.  I have i3 bound to only meta + f to enter full screen.

So, when in fullscreen, pressing either exits full screen but does not go back.
when in windowed mode, pressing either goes back in the stremio UI.

I am referencing this post for keyboard shortcuts: https://stremio.zendesk.com/hc/en-us/articles/360022892811-Shortcuts-in-stremio

**Comment by TRtomasz** [comment]
I can confirm it works like this, but as this is what users used to, i guess we don't wanna change it. Unless @jaruba  thinks differently

**Comment by raycekar** [comment]
can we maybe expose the keyboard shortcuts then so that they are editable by the user? that way a user can change the back shortcut so that it doesn't have to exit?
