### ISSUE TITLE
Video freezes after a few seconds reproducing

### ISSUE THREAD

**Issue by Zeioth** [Stremio/stremio-bugs#438]
**Describe the bug**
Video freezes after a few seconds reproducing, until I move the mouse cursor. As soon as I stop moving the cursor, the issue come back. On VLC it works fine.

**To Reproduce**
1. On linux (arch+sway) → mpv 0.35.0, stremio 4.4.159
2. Start watching a chapter, it will happen.

**Expected behavior**
The chapter reproduces normally.

**Desktop (please complete the following information):**
 - OS: arch+sway
 - Version: mpv 0.35.0, stremio 4.4.159
It's been happening for a few months i'd say. It used to work fine. I've tried to reinstall mpv and stremio from AUR, but the issue remains.

Ideas?

**Comment by Zeioth** [comment]
It seems to work fine after disabling hardware accel. So very likely related to https://github.com/Stremio/stremio-bugs/issues/123

**Comment by TRtomasz** [comment]
you could try doing `export QSG_RENDER_LOOP=basic` and then to try run stremio.

**Comment by Zeioth** [comment]
I've tested watching a couple chapters with QSG_RENDER_LOOP=basic and GPU acceleration disabled on Stremio. The issue seems indeed to be gone.

I'm gonna keep testing during today and report back tomorrow.

**Comment by Zeioth** [comment]
Still testing, but I think the culprit was the env var ENABLE_VKBASALT=1, which I was using to apply LUT to stremio. When using it, after a couple minutes the issue manifests. Intesestingly, Stremio logs the next warning when it happens:

    [vo/opengl-cb] mpv_render_context_render() not being called or stuck.

[This ](https://github.com/mpv-player/mpv/blob/master/libmpv/render.h#L71) is what MPV says about the warning.

**Comment by Zeioth** [comment]
Still researching, but when it happens, stremio logs the next:

    mpv_render_context_render() not being called or stuck.

**Comment by Zeioth** [comment]
Report: I've updated both stremio and mesa (to v23) and I havent had the issue in many days. I'll keep testing for another couple weeks. If all it's ok we can close the issue.
