### ISSUE TITLE
[Android TV] Subtitle files from inside torrents not available

### ISSUE THREAD

**Issue by nblondiau** [Stremio/stremio-bugs#439]
**Describe the bug**
The subtitle files from inside torrents are not available on the Android TV client.

**To Reproduce**

- Uninstall every subtitles add-ons, so that the only available subs are from the torrent.
- Sync the add-ons on the Android TV client.
- Start watching a movie from a torrent featuring subtitles (typically under Subs/*.srt) on the Android TV client.

**Expected behavior**
The list of available subtitles language should be populated and selectable.

**Screenshots**
The subtitles list is empty.

![Stremio_20230108_180204](https://user-images.githubusercontent.com/6884594/211209336-482b895f-9da7-4349-8f8d-082c7c66dbfc.png)

**Android TV (please complete the following information):**
 - Nvidia Shield TV Pro
 - OS: Android 11 patch level April 5 2022/ Shield SW 9.1.1

**Additional context**
Watching the same magnet link from the same Stremio account on both the Windows and Android client is working as intended.

**Comment by TRtomasz** [comment]
That's not a bug this should be done on addon level, as subtitles has to be provided by addons
