### ISSUE TITLE
Pinning the app to taskbar and opening it results in new app on the taskbar. [Pic in descp]

### ISSUE THREAD

**Issue by pateldhruv1993** [Stremio/stremio-bugs#44]
[http://i.imgur.com/4fsBx8Y.gifv](url)

Might be happening because you're allowing multiple instances of the same app? May be allow us to choose whether multiple instances of the app should be allowed or not in the app (like VLC does). As this might also resolve your the problem where the apps process keeps running in the background sometimes when you exit the app through 'X'

Btw the same thing works as expected on Discord so seems like there is a solution in the electron api itself

**Comment by Ivshti** [comment]
Is that windows 10? I cannot wrap my head around where the problem can be - being single-instance in Electron for Win is a bit tricky, requires opening a socket and then listening on it - which we do and it works OK usually. I can see how it can be buggy in some cases, so I need to think about what the problem may be.

**Comment by pateldhruv1993** [comment]
Oh yeah. Forgot that it is supposed to minimize to tray by default. But it used to be that even when you quit the app from tray it would keep running in the background and you'd have to end the process through task manager. But I don't think I've encountered that problem recently so I'm assuming that particular bug is already been patched?

And yes this is windows 10. Don't know if you make a log file or something that I can provide you to be more helpful with the taskbar bug.

**Comment by Ivshti** [comment]
@pateldhruv1993 you can start stremio with a debug log with

%LOCALAPPDATA%\Programs\LNV\Stremio\Stremio.exe launch --development

it could be a random issue, as I've seen Electron have an issue, rarely, at random in some cases
