### ISSUE TITLE
Media control by bluetooth device not workin in Stremio 1.5.7 [androidTV]

### ISSUE THREAD

**Issue by SanKalp4** [Stremio/stremio-bugs#442]
**Describe the bug**
Media control ⏯️ by bluetooth device not workin in Stremio 1.5.7 [androidTV]

Please fix this.

**To Reproduce**

Open stremio, connect your TV with bluetooth, play any content in stremio and try to pause/play it from bluetooth device itself.

**Expected behavior**

In the previous version of Stremio androidTV which had cache option enabled ,I was able to seamlessly play -pause a content in stremio using my bluetooth earphones.

In the newest update, I see that the media control options are not working from bluetooth. I have to reach out my remote everytime i want to pause or play a cinema or series.

Please fix this. I have tried with all my bluetooth devices and did a compare between previous version and the latest 1.5.7 one, previous version is confirmed to let play pause with bluetooth device onboard control button /gesture.

**Comment by TRtomasz** [comment]
We have never had such feature added to the TV app, are you saying it worked correctly in previous tv app version?

**Comment by SanKalp4** [comment]
Kindly try to replicate this from your end. This feature was super important to me and many who use tws to watch movies without disturbing family members. If a call or message comes in midway, it is super convenient to pause from the bluetooth earbuds gesture control rather than reaching out for the remote. Basically the updated Stremio tv app needs to have android media control like Spotify or other apps which allows playback control from bluetooth devices too.

**Comment by SanKalp4** [comment]
Working now.
