### ISSUE TITLE
going to the next episode then returning to the previous one erases your progress 

### ISSUE THREAD

**Issue by mo-5** [Stremio/stremio-bugs#444]
**Describe the bug**
After watching an episode for a bit and you go to the next then return to your current episode your progress is deleted and it starts from the beginning 
**To Reproduce**
1. Watch an episode for a bit
2. mid way Select next episode 
3. Go back to previous episode
4. It will start from the beginning instead of where you left off 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TRtomasz** [comment]
Yes progress i remembered only for one episode from series, it always worked like this, i don't think this is a bug. @jaruba  what do you think?

**Comment by jaruba** [comment]
@TRtomasz @mo-5 this is unfixable because of the watched bitfield logic we use, which in turn greatly compresses the data required to save per user.

Simply put, it is by design and cannot be solutioned.
