### ISSUE TITLE
(Android TV) Logo loading doesn't appear progress bar

### ISSUE THREAD

**Issue by manoskop** [Stremio/stremio-bugs#446]
**Describe the bug**
Before playing video player the movie/show's logo loading doesn't appear progress bar, it just flashes and turns gray and that's it.
Let's be clear, I mean the progress doesn't fill up the logo (movie/show's title art), it blinks then stuck with transparent grey colour.

**To Reproduce**
1. Go to search a movie/show.
2. On stream selector page, choose any stream and whatever quality.
3. Then you see the logo that doesn't display progress before player launches.

**Expected behavior**
It should display the progress like what it does on Android mobile.

**Android TV:**
 - Device: Google Chromecast with Google TV 4K
 - OS: Android 10
 - Stremio version 1.5.7

**Additional context**
I have tried on my Android smartphone with latest version, it shows normally.
For me it matters a lot, because it's useful for how fast it loads and completes successfully, before watching.
Do you have that issue too? Because I'm still looking for what went wrong and if it's my device's fault or it's a general bug.

**Comment by TRtomasz** [comment]
Not sure what you mean here? that playback does not start at all? Logo is indicating loading progress but if something does not load or is loading very slowly it is normal that there is no progress.

**Comment by manoskop** [comment]
No it's not what I meant. The playback works well, I mean it actually starts normally without delays even though the progress of logo doesn't appear at all, it just blinks then stuck with transparent grey colour and that's it, and then it goes straight to the player.
That's the issue I mean, I can't figure out what is causing it...
I suppose the latest updates caused this. It wasn't there on Android non TV version.

**Comment by TRtomasz** [comment]
closing as should be fixed in 1.5.11
