### ISSUE TITLE
Trakt not scrobbling episodes suddenly

### ISSUE THREAD

**Issue by KavGoat** [Stremio/stremio-bugs#449]
**Describe the bug**
A few weeks ago everything was working fine. Now, when I finish watching an episode, it no longer marks as watched. It does not even scrobble anymore. The trakt scrobbling and marking as watched works for movies however. I have tried reautharizing trakt and everything in stremio. I have tired on both the desktop app and the android tv app.

**To Reproduce**
1. Watch an episode. Power book raising kanan S02E10 definitely does not work.

**Expected behavior**
Should mark as watched once I finish the episode

**Comment by TRtomasz** [comment]
Please try reauthenticate, perhaps your token expired.

**Comment by KavGoat** [comment]
I have done that several times and it still does not explain why the episodes do not work but movies somehow do.

**Comment by TRtomasz** [comment]
i'v just checked and it is working fine for me for both Series and Movies, What have you tried to play? If addon is not providing proper imdbID trakt will not be able to track this. It could happen for anime addons.

**Comment by KavGoat** [comment]
I am using Torrentio. I tried and looks like episodes are working but only "Power book raising kanan" tv show does not work. Maybe some kind of error with the id's or something.

**Comment by TRtomasz** [comment]
looks like this is caused by this series, perhaps trakt can't identify it or addon does not provide correct imdbid for this series.
