### ISSUE TITLE
Color issues when playing some video

### ISSUE THREAD

**Issue by roisec** [Stremio/stremio-bugs#451]
**Describe the bug**
When I start some videos in 4k, the screen colors became very weird, I need to choose other movie version to fix that.
Some other 4k works well...
This issue occurs only in streamio app.
I tried to disable the hardware acceleration without success. 

Anyone have any idea how to solve it? 
I have an Xiami Mi box 4k.
![image](https://user-images.githubusercontent.com/68992144/223853252-cefa9589-796f-45e7-9295-230a2e8b7ef9.jpg)
![image](https://user-images.githubusercontent.com/68992144/223853330-ad3ed5ce-ba59-47cc-ab94-63023c79d6ca.jpg)

**Comment by roisec** [comment]
When I start some video the screen colors changed and the issue persist for the entire experience (even when I outside of streamio) .
See example bellow command.

**Comment by TRtomasz** [comment]
Stremio does not change anything related to the colors. Most likely your TV is not correctly handling switching between HDR/NON HDR content.
