### ISSUE TITLE
Stremio uses cpu, when it just open, app should use less resources when in background or foreground.

### ISSUE THREAD

**Issue by waleedrana777** [Stremio/stremio-bugs#453]
**Describe the bug**
When Stremio is open on windows, my laptop starts to heat up because I always have tons of stuff open already but I feel like stremio uses cpu when it shouldn't really! , I know that my cpu corei5 3rd gen is not strong enough but it feels like it is not the most optimized application. HOWEVER it is not the main source of cpu usage, I just think it uses a little more than a simple app should take.
One reason could be when I am streaming any video from any magnet link, it is downloading and assembling at the same time, which could be leading to more cpu usage.

**To Reproduce**
1. Open Stremio on Windows
2. You might/might not watch anything but have a bunch of other stuff open with it that also use cpu, like the browser and vscode
3. Laptop will feel like its fan is running on full speed if you were already doing cpu dependent tasks.

**Expected behavior**
Sometimes, you will notice slowing down of computer along with other applications running along.

**Desktop (please complete the following information):**
 - OS: Windows 10 2H22

**Additional context**
Stremio is not the main problem but I think something like tauri or flutter could improve the cpu usage or efficiency of the app. Sorry for making demands out here. I am happy to help if any needed. I am a flutter developer myself!

**Comment by core1024** [comment]
Hello. We are working on improved version of Stremio that, in theory, should be much efficient and also use less disk space. You can try a build from this link https://dl.strem.io/shell-win/experimental/Stremio+5.0.0.exe but keep in mind that this is in very early stage and it is not well tested so it may crash or hang. It is also possible to miss some features from the current version as this is entirely new code base.

**Comment by waleedrana777** [comment]
That's awesome and good to know, I will try this out! Thanks so much for making it more better!
