### ISSUE TITLE
Slow trailers / buffering problem

### ISSUE THREAD

**Issue by rebelcode-xr** [Stremio/stremio-bugs#456]
**Describe the bug**
Every time I try to watch a trailer it stops almost immediately for buffering.
Watching them is a pain, so I always end up searching them on FreeTube/YT.
I tested it with very fast Internet connections, that's not the issue: only Stremio behaves like that.
Torrent streaming works great.

**To Reproduce**
1. Pick a movie with a trailer and play the trailer
2. Trailer starts after few seconds but stops immediately after around 1 second for buffering
3. plays few seconds, stops for buffering again...and goes on like this making it impossible to watch
4. I tried to pause it to allow the buffer to fill more, the video goes on a bit more but stops again after few seconds
5. I ended up avoiding watching trailers in Stremio: I use FreeTube and it works perfectly

**Expected behavior**
I expect the trailer to start almost immediately and play without any interruption.

**Desktop:**
 - OS: Mac OS Monterey
 - Version: Stremio-UI 4.4.159 / Server 4.19.0

**Comment by TRtomasz** [comment]
i'v just checked and they are working fine, cant reproduce this.

**Comment by pabloab** [comment]
I always had this issue (+5y), trailers slow/choppy and with low quality. Also mentioned on [this Reddit](https://www.reddit.com/r/Stremio/comments/xglojm/choppy_stuttering_trailers/). Now on 4.4.142-1, Ubuntu 20.04 LTS.

**Comment by rebelcode-xr** [comment]
bug still present in the latest version, after the re-design

**Comment by erohtar** [comment]
Same problem for me
