### ISSUE TITLE
Addons not loading 

### ISSUE THREAD

**Issue by mlandd** [Stremio/stremio-bugs#458]
**Describe the bug**
Addons not loading 
I tried deleting and reinstalling the addon
I tried deleting and reinstalling stremio
Tried quitting and reopening stremio
Restarting the computer 
Nothing worked

**To Reproduce**
1. Go to '...' movie
2. Click on '....' any moovie
3. Scroll down to '....' addons loading
4. See error no addons available 

**Expected behavior**
Addons available again

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaruba** [comment]
There is not enough details to help with ur issue, but if the addon is not loading, then it is most probably a community addon issue and not an app issue

We can only help with app issues, not community addons issues. (as we do not create, nor offer the community addons)
