### ISSUE TITLE
Buttons too large on mobile, fast forward accidentally when dragging from bottom to open android buttons.

### ISSUE THREAD

**Issue by ilan1009** [Stremio/stremio-bugs#459]
**Describe the bug**
On most android mobile devices, you have UI buttons on the bottom of the screen used to "back", go to home, and view open apps.

On the mobile android app, when dragging from bottom to view the buttons, it clicks on forward (15 seconds)

**To Reproduce**
1. Open stremio on mobile
2. Stream any torrent 
3. Enter landscape mode
4. Hard to use buttons without forwarding the video

**Expected behavior**
In my opinion, the back and forwards buttons shouldn't take up a ⅓ of the screen and instead have their "box" similarly sized to the icon.

**Smartphone (please complete the following information):**
 - Device: Samsung S21+
 - OS: stock samsung android
 - Latest version

**Comment by TRtomasz** [comment]
closing, as app has been redesigned
