### ISSUE TITLE
Latest Android TV update can't play streams from an addon

### ISSUE THREAD

**Issue by AlyafeiAli** [Stremio/stremio-bugs#465]
**Describe the bug**  
I updated to v1.5.8 of Stremio Android TV on my Shield TV and the streams of [this addon](https://github.com/ssnjr2002/stremio-gdrive) stopped working for some reason.  
The streams do appear in the list, but when I click on one, it doesn't play. It switches to libvlc and then gives an error message which says `mediaplayer error code-1 extra 0`.  
This happens with all the addon's streams, regardless of the quality.  
I had to roll back to v1.5.7 which works like a charm.

This is a screenshot example of the addon's response to Stremio:  
![image](https://github.com/Stremio/stremio-bugs/assets/52626961/84caba4c-4afa-4189-a603-1b4d7585b29f)

**To Reproduce**
1. Configure and Install the addon
2. Select a movie or a series
3. Choose any stream

**Expected behavior**
The streams are supposed to play without any errors, just like they do in v1.5.7

**Screenshots**
This is a screenshot example of the addon's response to Stremio:  
![image](https://github.com/Stremio/stremio-bugs/assets/52626961/84caba4c-4afa-4189-a603-1b4d7585b29f)

**Smartphone (please complete the following information):**
 - Device: Shield TV 2017
 - OS: Android TV 11
 - Version: v1.5.8

**Additional context**
[I created an issue in the addon's page](https://github.com/ssnjr2002/stremio-gdrive/issues/37#issue-1740257424), but I don't think the issue is from it, since it works fine on v1.5.7

**Comment by AlyafeiAli** [comment]
The issue is still there in v1.5.10

**Comment by TRtomasz** [comment]
we have released 1.5.11 yesterday please let us know if it is working now

**Comment by AlyafeiAli** [comment]
Will do. But I couldn't find v1.5.11 anywhere, could you please link it?

**Comment by TRtomasz** [comment]
it is available in the playstore

**Comment by AlyafeiAli** [comment]
Oh thanks. I'll keep you posted 👍🏻

**Comment by AlyafeiAli** [comment]
Thank you so much!  
The issue has been fixed in v1.5.11
