### ISSUE TITLE
 "No Streamable Video Found" Error in Addon when Torrent is in Portuguese

### ISSUE THREAD

**Issue by rodrigoneal** [Stremio/stremio-bugs#468]
Summary:
I am currently developing an addon, and during my testing phase, I encountered an issue where the addon displays an error message stating "No Streamable Video Found" specifically when the torrent content is in Portuguese.

Description:
While conducting tests on my addon, I discovered that when attempting to stream video content from a torrent in the Portuguese language, the addon fails to locate any streamable videos and prompts the error message mentioned above. This issue is isolated to torrents in the Portuguese language, as I have successfully streamed videos from torrents in other languages without any problems.

Troubleshooting Steps:
To address this problem, I diligently searched the internet for possible solutions or workarounds. Unfortunately, I have not been able to find any relevant information or guidance on resolving this specific issue. I have attempted different configurations and settings within the addon, but none have successfully resolved the problem so far.

Expected Behavior:
When a user selects a torrent containing video content in Portuguese, the addon should be able to identify and stream the available videos without encountering the "No Streamable Video Found" error.

Actual Behavior:
However, the current behavior is such that when attempting to stream videos from torrents in Portuguese, the addon fails to recognize any streamable videos and presents the error message "No Streamable Video Found."

Attachments:
If necessary, I can provide logs or any additional information to further investigate and address this bug.

Steps to Reproduce:

    Install the addon on the specified platform.
    Search for and select a torrent with video content in Portuguese.
    Attempt to stream the videos from the torrent.
    Observe the error message "No Streamable Video Found" being displayed.

**Comment by TRtomasz** [comment]
Looks like an issue for stremio-addon-sdk, are you sure you are following documentation ?
https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md
`infoHash - string, info hash of a torrent file, and fileIdx is the index of the video file within the torrent; if fileIdx is not specified, the largest file in the torrent will be selected
fileIdx - number, the index of the video file within the torrent (from infoHash); if fileIdx is not specified, the largest file in the torrent will be selected`

**Comment by rodrigoneal** [comment]
I managed to fix the streaming problem, and it turned out to be the torrent hash causing the issue.

Thanks again for your patience and support.
