### ISSUE TITLE
Board Gui unusable in 3.5.9 

### ISSUE THREAD

**Issue by Sazhra** [Stremio/stremio-bugs#47]
After the most recent update going to the board presents a single line of "New Episodes" which shows 5 shows and a small sliver of a sixth box before being cut off by the scroll bar, There are also 3 other shows that are separated out from the "new episodes" for an unknown reason.  All of these are organized with the oldest episodes to the right where anything beyond 5 gets cut off.  There is no horizontal wrapping or scroll bar to allow for access to the older shows. Re-sizing the window simply changes the size of everything and continues to cut off the boxes at the same point.  The old board worked perfectly, and while I like the idea of having the shows grouped it doesn't list all of them and without the ability to see anything but the 5 most recent releases of most things the board is essentially unusable.

**Comment by Ivshti** [comment]
WE'll hot-patch that in a few minutes, re-start your app (maybe twice) to see it in action. We added a scroll-bar, which is not the perfect UX, but does the job until the UI is perfected

**Comment by Sazhra** [comment]
![stremio](https://cloud.githubusercontent.com/assets/18078877/14057115/24c3e95e-f2cd-11e5-8581-ce4993670f0c.png)

**Comment by Ivshti** [comment]
As I said, maybe you have to re-start the app a few times or give it time for the change to propagate

**Comment by Sazhra** [comment]
Awesome response time O.O
I was in the middle of posting the screenshot when you answered.
Will give it a few, thanks so much :)

**Comment by Ivshti** [comment]
Nice! I hope it appears for you soon!

BTW It's enabled for Linux and Windows, with the assumption that OS X users usually have side-scrolling mouses
