### ISSUE TITLE
LIVE error

### ISSUE THREAD

**Issue by syed9966** [Stremio/stremio-bugs#470]
**Describe the bug**

Hi, when I try to play few contents, an error appears. Will this error stop if I purchase and configure realdebrid to this app?
I use torrentio addon without realdebrid.
This was on YTS and any other large formats post the same error

**To Reproduce**
1. Go to search and select Harry Potter chamber of secrets
2. Click on the movie title from cinemeta addon list
3. Scroll down to YTS source 4k
4. See error : the content plays a few minutes and turns blank. A LIVE lable appers on the bottom left

**Expected behavior**
The movie is supposed to play without going blank. It has enough seeds to torrent.

**Screenshots**

![Screenshot_2023-06-10-04-46-08-169_com stremio one](https://github.com/Stremio/stremio-bugs/assets/24852765/9b9ab8f2-9b7d-441e-bb1c-7613498a6b2c)

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro
 - OS: Android 12

**Additional context**
Add any other context about the problem here

**Comment by syed9966** [comment]
Not only on YTS, most content with over 3 GB has the same error. Can it be solved if I am subscribed to REALDEBRID?

**Comment by TRtomasz** [comment]
Stremio does not controll available streams, if streams stops load there is nothing we can do about this. Regarding Live label we know about this issue and fix will be released with next update.
