### ISSUE TITLE
Signal display lost

### ISSUE THREAD

**Issue by JesusHassio** [Stremio/stremio-bugs#475]
**Describe the bug**
HDMI Signal display is lost, like if you have no device connected or is powered off.

**To Reproduce**
1. Click on a stream to play a movie/show.
2.  Resolution and framerate changes and the stream begins correctly.
3. Press back on the remote (to stop and go to the previous screen).
4. Signal display is lost until i reboot my device.

**Expected behavior**
Go back to the previous screen (i guess It has to revert to the default resolution and framerate)

**Platform (please complete the following information):**
 - Device: Nvidia SHIELD TV 2017
 - OS: Android TV 11
 - App versión: 1.5.11

**Additional context**
Seems to happen random. Also It happens when pressing "pause" and, after a couple of minutes, the device screensaver goes On.
I'm guessing that is related to the resolution change and It has to go back to the default. Not happening on the previous versión of the app.

**Comment by TRtomasz** [comment]
Could be a device issue, i mean stremio does not control this kind of stuff like signal

**Comment by JesusHassio** [comment]
....may be.
Using the previous version of the app, the issue is gone.... but notice that it doesn't change the resolution nor the framerate, never, wathever the stream it plays, it stays fixed always (at least is what is shows on the info displayed on my tv).
Also it doesn't happen with other similar streaming apps.
Is there any way i can check some info on that? I know how to enable Hdmi cec debug on my system, but i don't know how to see that debug info

**Comment by TRtomasz** [comment]
You can disable frame rate and resoltuon adjustments in the settings.

**Comment by JesusHassio** [comment]
Sure, i know. But not an option to me, i want that when i'm watching movies or shows.
In fact, until this last version, i was discarding the app in front of other options as my main streaming app.

**Comment by TRtomasz** [comment]
imo it looks like a hardware issue, maybe just an issue with the hdmi cable you might try using different one if you have a replacement

**Comment by janowakps** [comment]
I have exactly the same problem, in my case it's a Chromecast 4k and a Philips OLED 803 TV

@JesusHassio did you manage to fix it?

**Comment by JesusHassio** [comment]
> I have exactly the same problem, in my case it's a Chromecast 4k and a Philips OLED 803 TV
> 
> @JesusHassio did you manage to fix it?
> 
> @TRtomasz I don't think it's a hardware issue, I use many apps: kodi, cloudstream, netflix, prime video, disney etc and this problem only occurs with the stremio app

Its not happening to me with the last app version available on my device. Sorry i cant help.
