### ISSUE TITLE
Skip end credits button disappeared 

### ISSUE THREAD

**Issue by SSwaggerSoulss** [Stremio/stremio-bugs#477]
A few updates ago the green button in the bottom right corner to skip end credits disappeared on Android TV.

I tried adjusting the seconds for when the button should appear but no luck.

Device: Android TV
OS version: Android 9
Stremio version: 1.5.11

**Comment by SSwaggerSoulss** [comment]
Next video pop up duration is set to 35s and auto play next episode is enabled.

**Comment by jaruba** [comment]
maybe the reason you don't see it is because you press the next video button manually in the UI prior to reaching 35s before the video ends?

**Comment by SSwaggerSoulss** [comment]
I tried manually skipping to the last seconds of the episode and still don't see it unfortunately.

**Comment by TRtomasz** [comment]
yeah @SSwaggerSoulss  please do it if possible i guess it can be usefull.

**Comment by SSwaggerSoulss** [comment]
Sorry for my late reply.

Uploaded the video to my mega cloud.

Please find the link below:

https://mega.nz/file/NZUnxCZa#ycrWYXM_xIBzV70GVPb6peX4ByKIbaZMcbqtuPdeY-U

**Comment by SSwaggerSoulss** [comment]
So far I have tried with no success:

1. Switching off tunneled playback
2. Switching off auto play next video
3. Switching to libVLC player
4. Reinstalling Stremio

**Comment by TRtomasz** [comment]
thanks, will check this out, maybe it only happens when you play something from continue watching

**Comment by SSwaggerSoulss** [comment]
Thanks for checking! Just tried a random tv series I have not watched before and skipped to the last few seconds and unfortunately still don't see the button. Do you think an addon might be causing this? I can list all the addon I have installed.

**Comment by SSwaggerSoulss** [comment]
Actually I just tried with a brand new account with only one add-on installed and I still don't see the bottom so I guess I don't shouldn't be an issue.

**Comment by TRtomasz** [comment]
Hi, thanks for the update i will try next week again to see if i can reproduce this issue

**Comment by SSwaggerSoulss** [comment]
Hi, I am using torrentio. Worked fine with the version where you first introduced the feature but at some point it stopped working. Maybe I can test it, do you have by any chance the old version?

**Comment by TRtomasz** [comment]
Closing as we can't reproduce this issue.
