### ISSUE TITLE
Freeze on MBP OSX 10.10.5

### ISSUE THREAD

**Issue by antoninom** [Stremio/stremio-bugs#48]
Hi,
I'm waiting for this problem to be fixed since 3.5.2 version but neither the last update solved it.
So i launch Stremio and the program starts but stay freezed  and the only thing I can do is to force the exit from the program (all the cpu fans sounds like a jumbo jet during a take off)...

anybody could help me?

thank you

**Comment by Ivshti** [comment]
@antoninom are you sure it worked in 3.5.2? You can download old versions easily:
http://www.strem.io/Stremio3.5.2.dmg

**Comment by antoninom** [comment]
Perhaps I haven't made myself clear :-) 
It never works! I find out strem.io when 3.5.2 was already out...

**Comment by Ivshti** [comment]
@antoninom that's better, at least we know it's not an issue that appeared in recent versions 

Which version of OS X, what type of MBP, etc?

**Comment by antoninom** [comment]
OSX 10.10.5 Yosemite
MacbookPro 13" Late 2011 2.8 Intel Core i7 16 GB RAM

**Comment by antoninom** [comment]
any news?

**Comment by Ivshti** [comment]
@antoninom try this. Quit Stremio, Open Terminal and write:
/Applications/Stremio.app/Contents/MacOS/Electron . --disable-dht --no-dht 

Let me know what happens

**Comment by antoninom** [comment]
![schermata 2016-04-06 alle 02 35 41](https://cloud.githubusercontent.com/assets/18199562/14302372/52b34a2c-fba0-11e5-90bf-f99df24ccca9.png)

![schermata 2016-04-06 alle 02 36 24](https://cloud.githubusercontent.com/assets/18199562/14302375/5ef86ede-fba0-11e5-995b-e6ca91fcc9a1.png)


can't click anything on stremio window...

**Comment by antoninom** [comment]
Ivo could you try to help me again?

**Comment by Ivshti** [comment]
@antoninom does the hover effect work when you put your mouse over "sign up" and "guest login"; i.e. does the window respond

**Comment by antoninom** [comment]
Nope! :-)
Windows doesn't respond...
Freeze at start...

**Comment by antoninom** [comment]
I tried even with last release 3.5.10 Window completely stucked...


![schermata 2016-04-14 alle 15 58 29](https://cloud.githubusercontent.com/assets/18199562/14530554/ca808708-0259-11e6-9f7a-19b8f0a3c06d.png)

**Comment by Ivshti** [comment]
@antoninom I literarily have no clue...

Can you try with that in the Terminal:

/Applications/Stremio.app/Contents/MacOS/Electron . --development

To see if there's anything suspicious going on

**Comment by antoninom** [comment]
Part 1
![schermata 2016-04-14 alle 20 40 59](https://cloud.githubusercontent.com/assets/18199562/14539630/75a58ea4-0281-11e6-940a-8abbc3c5ebea.png)

Rightside bar (2nd part)

![schermata 2016-04-14 alle 20 41 10](https://cloud.githubusercontent.com/assets/18199562/14539647/86017bbe-0281-11e6-9b1e-2b23562d97a5.png)

Bottom (see warnings)

![schermata 2016-04-14 alle 20 40 36](https://cloud.githubusercontent.com/assets/18199562/14539655/924f5210-0281-11e6-9911-9bf48e1ca75c.png)


Main windows still the same (frozen).

**Comment by Ivshti** [comment]
Questions:
1. Does the debugger window work
2. Can you try "/Applications/Stremio.app/Contents/MacOS/Electron . --development --disable-transparent"
3. Does Google Chrome work fine on your Mac?

**Comment by antoninom** [comment]
1. I'm not sure I have understood the question (which window do you mean?)
2. It - finally starts! - but when I try to choose any streaming the window look this way

![schermata 2016-04-14 alle 21 15 17](https://cloud.githubusercontent.com/assets/18199562/14540622/3ab62ae2-0286-11e6-82ce-d7940a62db1b.png)

![schermata 2016-04-14 alle 21 08 06](https://cloud.githubusercontent.com/assets/18199562/14540636/45f89f84-0286-11e6-802b-b35c5826e261.png)

![schermata 2016-04-14 alle 21 13 14](https://cloud.githubusercontent.com/assets/18199562/14540641/4a1f9ce8-0286-11e6-9c58-d10650f424dc.png)

3. I suppose the answer is "no". But I don't experience nothing wrong with Chrome. What do you suggest me to do?

p.s.: I think you are gonna made my day! It seems that something changed after i reboot stremio without terminal... :-)

**Comment by Ivshti** [comment]
@antoninom interesting. Not really good in the grand scheme of things though, since I still have no clue what the issue may be :) 

I hope no one else experiences it

**Comment by antoninom** [comment]
Now I'm just worried about potential security danger using Stremio...

**Comment by antoninom** [comment]
Thank you very very much!

**Comment by wormangel** [comment]
Similar issue here.. My MBP is a MBP Retina, early-2013
Intel Core i5 2.6GHz, 8 GB RAM... it's a poweful machine, but Stremio takes 100% CPU when I launch it.
Running OS X 10.11.2

The main windows is not responsive. Sometimes I'm able to click on 'Series' or scroll a little bit in the list, or type some letters in the Search box, just to see it freezing forever. Tried the commands up there to no avail :(

It's the latest version, just downloaded it.

**Comment by Ivshti** [comment]
@wormangel can you try the same thing?

> 1. Does the debugger window work
> 2. Can you try "/Applications/Stremio.app/Contents/MacOS/Electron . --development --disable-transparent"
> 3. Does Google Chrome work fine on your Mac?

**Comment by wormangel** [comment]
Google Chrome works fine.
Debugger window displays but nothing strange there.

I think I've also tried the disable-transparent flag, but will try again later. Maybe something else in my MBP is conflicting with whatever Stremio uses. Will try to figure it out.

I'm using it right now in a Macbook Air mid-2013 with the most recent El Capitain and it works flawlessly, no freezes.

**Comment by Ivshti** [comment]
@wormangel let me know on the results of disable transparent.

Also try disabling Finder.

If you have many video files locally (do you?), it could be some sort of a bug with the file indexing

**Comment by Narayanan170** [comment]
Unfortunately, your suggested solutions don't seem to work for me. I can put up a screenshot if you like of the developer console, but nothing seems irregular

**Comment by Ivshti** [comment]
@Narayanan170 sure, screenshot always helps; also, if the dev console isn't freezing, you can do a cpu profile for around 10-20 seconds and send a screenshot of that

**Comment by Narayanan170** [comment]
Does this help in any way?
https://monosnap.com/file/091LnpRogM2BmFF7rBgcEA08ltisx9#

**Comment by Narayanan170** [comment]
I can start profiling, but when I press stop, it continues recording...
