### ISSUE TITLE
TV Show "Only murders in the building" no episodes on Android, no streams on GTV

### ISSUE THREAD

**Issue by sylverstream** [Stremio/stremio-bugs#481]
The TV show "Only murders in the building (2021)" has issues.
On Android it doesn't show any episodes and on Android TV (Google Chromecast with TV 4k) it shows the episodes, but every episode shows No Streams Found.

I confirmed on Lemmy that it's not just my config, someone else could replicate it.

**Comment by sylverstream** [comment]
> works fine here, try clearing app cache? or provide screenshots?

An App cache refresh has fixed the "no episode issue" on Android. However, it still shows "No Streams Found" on both Android as well as CCWGTV. Or is this an issue with the Torrentio plugin as I'm using that for my streams? @jaruba

**Comment by jaruba** [comment]
Shouldn't be, I see streams everywhere. I even watched it y-day as I'm also following that series. (It has a good mix of family friendly, actors with good chemistry and mild humor, unusual for a mysterie series, but it works well.) Maybe try changing the DNS provider to Google or Cloudflare, clear cache again and restart the app?

This isn't an app issue for sure.. Some 3rd party may be interfering.. or maybe u didn't restart the app after deleting the app cache?

**Comment by sylverstream** [comment]
@jaruba I've found out the show appears twice on Stremio. One of them has the issue. I've asked on Lemmy too and more people seem to have the same issue as me.
The "faulty" show is the first search result, and is this one: https://www.strem.io/s/series/only-murders-in-the-building-11691774

The one that works is https://www.strem.io/s/series/only-murders-in-the-building-12851524

**Comment by jaruba** [comment]
Hmm, I see that there are indeed 2 search results, but for both I have the correct number of episodes and i get streams too..

**Comment by jaruba** [comment]
We are now deduplicating the search results better, there is nothing more we can do imo, each addon is responsible for sending the correct IMDB ID for series / movies
