### ISSUE TITLE
Streamio on android tv > open the app by first time failed to create a QR , get error 13

### ISSUE THREAD

**Issue by bennyscash1** [Stremio/stremio-bugs#483]
**Describe the bug**
Android tv version android 12 

**To Reproduce**
On my streamer 6k magcebic streamer
[https://www.aliexpress.com/item/1005005663944227.html?spm=a2g0o.productlist.main.1.4e28393bCBIEAP&algo_pvid=1daec966-1361-47ac-8c87-a8f1855a121d&algo_exp_id=1daec966-1361-47ac-8c87-a8f1855a121d-0&pdp_npi=4%40dis%21ILS%21267.35%2184.65%21%21%2169.20%21%21%4021038edf16927076879464523e3f03%2112000033939848499%21sea%21IL%21132815686%21&curPageLogUid=Hwo9zWlLfuJM]

Navigate to Google store
Search for streamio 
download the updated one (22.08.2023)
open it 
try to get the QR code

**Expected behavior**
The QR code will display 

**Actual result**
Display an error :
Env: failed to fetch  Miiddlware error: permission denied (os error 13)

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/127658116/da99e34d-d50c-45fa-ba56-278fbe3fe9bd)
 - Version android tv 12
 - Streamio version 1.5.11(com.streamio.one)

**Additional context**
I've tried many options to fix it but with no succeed so far

**Comment by jaruba** [comment]
This is an Android OS error, not an app error.

I know it can happen if you are trying to run Stremio from an external storage device in some scenarios.

**Comment by bennyscash1** [comment]
thank you for the answer
For me it reproduces consistently
I would be very happy if we could find a solution or any workaround.
I am available on Whatsapp

**Comment by bennyscash1** [comment]
After clarification
The app store is currently on version 1.5.1
The official website version is 1.6.1
Indeed, the bug was fixed in the new versions on the website (beta) but not in the Google Store
Thank you!
