### ISSUE TITLE
Show with combined episodes not handled properly

### ISSUE THREAD

**Issue by sylverstream** [Stremio/stremio-bugs#484]
**Describe the bug**
The following show seems to have combined episodes. Eg when I watch E01 it shows results with E01 and E02. When I check E02 I see same results as E01

https://www.strem.io/s/series/star-vs-the-forces-of-evil-2758770

**To Reproduce**
1. Go to https://www.strem.io/s/series/star-vs-the-forces-of-evil-2758770
2. Click E01
3. Results are for combined episodes E01E02

**Expected behavior**
It shows E01 and E02 as one episode / entry.

**Comment by TRtomasz** [comment]
We do not controll this content episodes list is provided by thetvdb ot tmdb.
