### ISSUE TITLE
Layout Error

### ISSUE THREAD

**Issue by Heart247** [Stremio/stremio-bugs#485]
I just got the new update and the layout looks all messed up the new design is not shown I only see text, I cant scroll. you will see what I mean in the screenshot I provided.

1. Just first time running it
 after the new update.

![myscreenshot](https://github.com/Stremio/stremio-bugs/assets/105014554/965d9845-6aef-4aa5-ab60-f8898c02a303)

**Desktop:**
 - OS: Windows 10 2021 LTSC 21H2
 - Browser: Chrome dev
 - Version: 118.0.5951.0 (Official Build) dev (64-bit)

**Comment by TRtomasz** [comment]
Please just try pressiing F5 in stremio app window to refresh the app, if this does not help
Then please follow this instruction to remove stremio manually and install it again https://stremio.zendesk.com/hc/en-us/articles/360019465820-How-to-remove-stremio-manually-on-Windows
