### ISSUE TITLE
Continue Watching navigation arrow is present even if no scroll is possible

### ISSUE THREAD

**Issue by P-Jay357** [Stremio/stremio-bugs#489]
The navigation arrow for Continue Watching is always visible if you hover over the section, even if there aren't enough entries to warrant a horizontal scroll. This does not occur for "Movies - Popular" or any of the other Home page sections, they behave as you would expect.

This is with the new Windows Desktop update (4.4.160).

![Screenshot 2023-08-25 220548](https://github.com/Stremio/stremio-bugs/assets/43815586/fec13242-d184-4d84-ac37-89f97056b2eb)

**Comment by TRtomasz** [comment]
Not a bug it is displayed for all rows
