### ISSUE TITLE
Stremio doesn't work after it automatically updated

### ISSUE THREAD

**Issue by pingpongpangpungpeng** [Stremio/stremio-bugs#49]
After the latest update Stremio won't open anymore. Every time I open it, a window pops up. 

`A JavaScript error occurred in the main process

Uncaught Exception:
Error: Unable to find a valid app at Object.<anonymous> (/Applications/Stremio.app/Contents/Resources/atom.asar/browser/lib/init.js:92:11)
at object.<anonymous> (/Appliocations.Stremio.app/Contents/Resources/atom.asar/browser/lib/init.js:124:4) 
at Module._compile (module.js:424:36)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:129:18)
at node.js:981:3`

Does anyone has a solution?

Thanks

**Comment by Ivshti** [comment]
can you try to re-install? most likely a corrupted update

**Comment by jrxpress** [comment]
i am having the same issue with my mac version 3.6.5 ... it stops works after java update yesterday and it says "No Available Windows" after i try to re install ....

**Comment by jrxpress** [comment]
i just got it back after update using the beta version !! Stremio+4.0.0-beta.25.dmg
