### ISSUE TITLE
Raised black levels (or gamma curve) in built-in player

### ISSUE THREAD

**Issue by ferongr** [Stremio/stremio-bugs#490]
Video looks washed out when played in Stremio's built-in player. VLC, standalone MPV or browser video do not exhibit this issue. All "video enhancement" settings in the AMD software are disabled.

Screenshot for reference. Stremio on the left, mpv on the right.

![screenshot](https://github.com/Stremio/stremio-bugs/assets/544658/b2b8d4b2-45df-4894-b2ba-eb45d1c57a63)

System Info:
Windows 10 22H2
Chome 116.0.5845.111 

DxDiag output attached
[DxDiag.txt](https://github.com/Stremio/stremio-bugs/files/12444459/DxDiag.txt)

**Comment by TRtomasz** [comment]
Try enabling hardware accelerated decoding in the settings and check again.

**Comment by ferongr** [comment]
Is was enabled in the first place, but disabling it makes he issue disappear.

**Comment by Enigmatic-Onion** [comment]
this issue either is still present or has returned. i've observed this in the desktop as well. 
https://github.com/Stremio/stremio-shell-ng/issues/104/
It's not an issue with hardware acceleration, as my browser is hardware accelerated, same with mpv and the community stremio app i've tested.
