### ISSUE TITLE
Addons not loading after the new update 4.4.160 

### ISSUE THREAD

**Issue by Ci0n457** [Stremio/stremio-bugs#491]
Already reinstalled the app, it opens fine, no interface problems, but it is not loading and not showing any link/addon in any of my devices (computer, notebook and mobile) and there are a bunch of addons installed, tried to reproduce external magnet links and didn't work also. I'm extremely sad with this.

**Comment by TRtomasz** [comment]
Sorry, it is not possible to understand what is your issue from your message. Sounds like you were using a  guest account, they do not persist installed addons.
