### ISSUE TITLE
Windows desktop: new UI size is smaller 

### ISSUE THREAD

**Issue by bgood7** [Stremio/stremio-bugs#493]
Hi,

1. The stemio app ui size reduced significantly and there is no app setting to change it. I have an issue with this small UI and need you to fix it
2. On the previos versions, I changed windows 10 setting: "Change the resolution of the display\Scale and layout\Change the size of text, apps and other items" and it reflected in the stremio app
3. New desktop version 4.4.160 upgraded automatically after I clicked the new version popup in the stemion app (announcing the new Update & App Redesign).
4. There should be a prompt asking if the user wants to upgrade to the latest version.
5. My device is running Windows 10 Pro version 22H2 Build 19045.3324

Thank you and great job on the the new UI
bgood7

**Comment by TRtomasz** [comment]
Here is comparison and it is scalling. Could you please explain what you mean?
175% at 4k screen
![image](https://github.com/Stremio/stremio-bugs/assets/40594253/7dd9e5c8-f12e-426a-bfa1-074c4a111155)
100%
![image](https://github.com/Stremio/stremio-bugs/assets/40594253/cc97f7c9-7fe7-4bac-85d1-502876e6f01b)

**Comment by bgood7** [comment]
The change in my screen is not reflected as it did in the previous stremio version, and text appears smaller and unreadable.
It forces me to change the windows scale from 200% to 250% which is too big for other apps.
You should find a soultion for this, by adding a setting in stremio desktop app or by testing the previous version response for the windows setting (Change the resolution of the display\Scale and layout\Change the size of text, apps and other items)

**Comment by TRtomasz** [comment]
@bgood7  do you think only text size is too small or something else is too small too?

**Comment by bgood7** [comment]
@TRtomasz only the text is too small. 
One more request: The response time in the **Disocver** page is very slow;
1. It stops loading movies, see screenshot
2. When clicking on several titles it takes ~5 seconds for the info to appear
![Capture](https://github.com/Stremio/stremio-bugs/assets/33121503/98cd36a0-9973-4c6e-bb00-1e52a5812430)

**Comment by nukeop** [comment]
I have already reported this, but my issue was closed.

This UI has unreadable text on any screen with larger pixel density. It used to be fine in the previous version, which I'd like to keep, but I was forced to update against my will. The whole UI is inferior in many ways.

**Comment by TRtomasz** [comment]
we made some changes to make UI more scalable, do you think it ist still too small?

**Comment by errende** [comment]
> we made some changes to make UI more scalable, do you think it ist still too small?

Is there plans to make the UI more extensible? I upscaled 175% for my 3k screen and can't resize the stremio app into a more comfortable smaller sized windows, it just won't let me resize it smaller than 3/4 of my screen.

**Comment by TRtomasz** [comment]
We do not plan to make such modifications to the current UI.
