### ISSUE TITLE
Minor bugs after the new Stremio UI update on the windows desktop app

### ISSUE THREAD

**Issue by Sakshem** [Stremio/stremio-bugs#494]
There are a few bugs I would like to address, but these bugs are not so big as to warrant separate issues.
**1) Directly opening the stream when clicking on a movie/series in the Continue Watching section**
Before the latest update, whenever a user clicked on a series/movie in the Continue Watching section, the user would see a page with the series/movie title, genre, summary, and a list of episodes (called "metadetails-content-UzSEV" found this after using the inspect element in web) in the case of series with the stream options based on the addons installed. However, after this new update, if the user clicks on a series or movie in that section, it directly opens the stream or video where the user previously left off instead of that page (I find the info page to be shown first convenient so I can move on to the next episode if I have closed the video or stream during the end credits of a series and would like to move on to the next episode from that page). Before this UI update, this used to be the feature if I directly clicked on the Stremio logo play button in the middle of the video card display, and when clicked anywhere else on that card, it would show the movie/series page.
Video showcasing the bug: https://drive.google.com/file/d/15H37eLyYxfn2vVXKsep7bRqnlrcxcc-y/view?usp=sharing

**2) Meta-Info-Container slow loading in the discover section**
In the Discover section of the Windows desktop app, when clicking on a movie/series. The detail card (meta-info-container-tlmcb according to the inspect element in web) displaying further information like movie/series title logo, duration, year of release, IMDB rating, description, casts, genre, and so on is loading gradually and not everything altogether; for instance, when clicked on a movie, its title logo is updating after every other piece of content is loaded. and portrays a laggy response altogether. In my opinion, it should display everything in that container altogether and not update it separately. The response is much slower than before the update, and I believe it's because of two reasons. First, the background blur image, and second, the movie/series title logo. The title logo seems to take a few extra milliseconds to load compared to the rest of the content. Caching some of this might solve the issue, or maybe just showing everything only after everything is loaded might do the trick.
Video showcasing the bug: https://drive.google.com/file/d/1VVvYTIG7uUplzsPYaMAkcN3l2ckkLLY5/view?usp=sharing

**3) The Pause/Play button twitches when clicked**
While watching a series/movie using an addon (in my case, torrentio, although I haven't tested it for other official addons, I don't think it's an addon issue), when clicking on the pause button with the mouse or while using the space bar to pause only once, there are times when the button would show the play button logo first, then the pause button, and then eventually display the play button logo, showcasing a twitching response. This all happens within milliseconds but is something the user can notice. This issue is something I've noticed after the new UI update and was not an issue before this update. So something in the new update is causing this.
Video showcasing the bug: https://drive.google.com/file/d/17jwOP708cTsBEJTobHhd9WoW5iC3J4YN/view?usp=sharing

**Desktop**
 - OS: Windows 11
 - Browser: Windows Desktop App

**Comment by TRtomasz** [comment]
It was always directly opening previously opened stream this was not changed. It happens only if you open it again on the same device you used before.

**Comment by Sakshem** [comment]
I am quite certain we could see the series page first instead of directly opening the stream where we left off. However, we could open the stream directly from where we left off if we clicked on the play button logo that was present in the center of the container as I mentioned above, in the same device I have used to watch it before. This isn't possible now after the new update and seems like a downgrade.

**Comment by KleoPetroff** [comment]
> I am quite certain we could see the series page first instead of directly opening the stream where we left off. However, we could open the stream directly from where we left off if we clicked on the play button logo that was present in the center of the container as I mentioned above, in the same device I have used to watch it before. This isn't possible now after the new update and seems like a downgrade.

That's exactly how it functioned, at least on the desktop version. That was convenient because you could choose a different source if you like.

**Comment by TRtomasz** [comment]
1 is fixed with context menu added 2. is also fixed 3. is not fixed for now we will track it internally though.
