### ISSUE TITLE
Redesign improvements

### ISSUE THREAD

**Issue by jcfjcfjcf** [Stremio/stremio-bugs#496]
One thing in this new version of the redesign, I noticed that the subtitles font has changed and I like the way it was before, could you go back to that one or have more font options to choose from? in addition to this new redesign.

Would it be possible, for example, in a series that has 3 seasons when opening each one of them to show the date and year it was released? because it only shows the date, I would like to see the year.

Would it be possible when searching for example "popular movies" not open this window with the movie on the side? because it hinders the visualization going down the page.

Version 4.4 for Windows

**Comment by TRtomasz** [comment]
We added full release date in todays release
