### ISSUE TITLE
Guest login option missing (privacy concern)

### ISSUE THREAD

**Issue by JamieGoodson** [Stremio/stremio-bugs#497]
**Describe the bug**
The guest login option is missing - I am now forced to login via email/password which I do not want to do for privacy/tracking reasons.

**To Reproduce**
Open Stremio - see that there is no guest login option.

**Expected behavior**
A guest login option, as was available before the UI rebrand.

**Screenshots**
![stremio](https://github.com/Stremio/stremio-bugs/assets/4729966/4c73e81d-089f-4103-8a72-1df4b50f0a6f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Unknown (no option to view version in the app without logging in)
 
 
 Thanks! From what I've seen online, the rebrand looks awesome :)

**Comment by TRtomasz** [comment]
It is not missing @JamieGoodson it is in the same place as always -> Signup -> Guest Login

**Comment by nukeop** [comment]
Why is it hidden? There should be 1. a button that lets you skip this with one click, 2. it should save the preference not to use an account and not ask on the next launch.
