### ISSUE TITLE
Login with facebook error

### ISSUE THREAD

**Issue by MaKuj** [Stremio/stremio-bugs#498]
Facebook login on the website is not working

1. Go to https://www.stremio.com/login
2. Click on login with facebook

Should login with facebook. Link seems dead.

**Comment by KleoPetroff** [comment]
Because of this, the login to Stremio on Android TV using Facebook is not working as well, as it redirects to the website login.

**Comment by TRtomasz** [comment]
should be fixed now

**Comment by albaluz35** [comment]
Greetings. The same problem for me again. 
From Google TV it redirected me from the QR and when I try to login with Facebook from my Google Chrome browser in my android smartphone, it doesn't work
