### ISSUE TITLE
Addons page issues (Windows Desktop version 4.4.160)

### ISSUE THREAD

**Issue by P-Jay357** [Stremio/stremio-bugs#500]
The main search bar has an "X" button which appears if there is some text in the search bar. However, the Search addons search bar does not have this feature.

![Screenshot 2023-08-26 174824](https://github.com/Stremio/stremio-bugs/assets/43815586/0c2b7d20-b75b-489d-87e1-fe91279f43f1)

Also, if I have a search term for Community Addons, and then tap My Addons, the search is cleared, rather than persist throughout the different types of addon lists.

Finally, the white selected Addon list border does not work as expected, and sometimes is even bordering a different list to the one which is selected.

![Screenshot 2023-08-26 175020](https://github.com/Stremio/stremio-bugs/assets/43815586/2c043c5b-020d-4a2e-ba9c-97641c272547)

This white border then disappears if you click anywhere else in the app.

**Comment by TRtomasz** [comment]
Addons search is 'interactive' you type it start searching right after same happens when you remove search with backspace button is not needed in this case
