### ISSUE TITLE
Choppy Animations

### ISSUE THREAD

**Issue by vishwaprotim** [Stremio/stremio-bugs#503]
**Description**
Animations in the latest version of Stremio Desktop (4.4.160) on Windows 11 feels heavy, choppy, slow and not smooth

**Steps To Reproduce**
1. Open Stremio Desktop 4.4.160
2. Go to home tab
	- Tiles (Poster Cards) are loading very slowly
	- Scrolling is not smooth, choppy
3. Click on Discover tab
	- Scroll up and down
	- Scroll Animation is very choppy (feels too heavy)
4. Play any movie of your choice
5. Once player starts/resumes, click on the arrow on right side of the screen to display the "Details Pane"
	- The slide in and slide out animation of details pane is not smooth, and very slow

**Expected behavior**
Animations should be smooth

**Screenshots/Screen Grabs**

https://github.com/Stremio/stremio-bugs/assets/14358431/683c6869-fe37-4a48-9f1b-63ec676bd7d6

**Desktop:**
 - OS: Windows 11
 - Browser - NA 
 - Version - Stremio Desktop V 4.4.160

**Comment by TRtomasz** [comment]
should be fixed in new release
