### ISSUE TITLE
UTF-8 subtitles are not rendering correctly. version 1.6.1 (android tv)

### ISSUE THREAD

**Issue by lowlevel-1989** [Stremio/stremio-bugs#504]
**Describe the bug**
Starting from the latest published version 1.6.1, UTF-8 subtitles are not rendering correctly and display strange characters.

**To Reproduce**
Activate previously viewed Spanish subtitles.

**Expected behavior**
Render special characters correctly with UTF-8 encoding.

**Android TV**
 - Device: firetv 4k
 - Stremio Version: 1.6.1

**Comment by TRtomasz** [comment]
All subtitles are UTF8 subtitles, do you mean some specific symbols?

**Comment by lowlevel-1989** [comment]
> All subtitles are UTF8 subtitles, do you mean some specific symbols?

It only happens on fire tv (Android TV), on smartphones it doesn't have that problem.

examples of characters: ó ñ á.

and it was after they released the latest version.

**Comment by lowlevel-1989** [comment]
I have identified the issue, and it only occurs in the TV version.

When the Content-Type header is set to text/plain, the characters on the TV do not render correctly, but they work correctly on an Android smartphone.

![image](https://github.com/Stremio/stremio-bugs/assets/8493573/380009f6-67e0-4b7d-a05e-140d2ec1addc)

By changing to Content-Type: application/force-download and Content-Transfer-Encoding: Binary, this problem no longer occurs in the TV version.

![image](https://github.com/Stremio/stremio-bugs/assets/8493573/8391e34f-2ca9-4d7b-83f3-107f65723c78)

**Comment by TRtomasz** [comment]
It is required for subtitles to be in utf-8 format other formats might fail.

**Comment by lowlevel-1989** [comment]
@TRtomasz the subtitles are utf8, I have already commented that it works on the smartphone.  I think you don't bother to do the tests, when even the same subtitle works on TV, changing only the header.

**Comment by TRtomasz** [comment]
if you dont specify `charset` using `text/plain` content might be decoded using default encoding and cause issues, also default decodings could be different between platforms. i guess if you set charset to 'utf-8` and still use `text/plain` it will work too

**Comment by lowlevel-1989** [comment]
> if you dont specify `charset` using `text/plain` content might be decoded using default encoding and cause issues, also default decodings could be different between platforms. i guess if you set charset to 'utf-8' and still use`text/plain` it will work too

![image](https://github.com/Stremio/stremio-bugs/assets/8493573/25bd8398-b4a6-4847-854a-a89f6605d414)

works fine, thank you very much.
