### ISSUE TITLE
[Android TV] Adjusting movie sound not working

### ISSUE THREAD

**Issue by technout** [Stremio/stremio-bugs#505]
**Describe the bug**
I cannot change the volume with my android volume setting, like i can do for all my other android tv apps.
With android volume setting, i mean this: [Change volume](https://support.google.com/android/answer/9082609?hl=en)
On any smartphone you have upper/down volume buttons and on android TV you have these buttons on the android remote.

**To Reproduce**
1. Open your favorite movie or tv show, watch it in the default exoplayer.
2. Adjust the audio volume, with the android remote.
3. Android default audio overlay indicator shows that volume goes up or down.
[bug] Android volume setting is completely ignored and stuck at 100% volume when using Stremio 1.6.1.

**Expected behavior**
Adjust the audio volume, with the android remote: hearing that the audio goes up or down.
In version 1.5.9 of Stremio this was working well.

**Smartphone:**
 - Device: [Android TV box A95X F3 Air](https://androidpctv.com/review-a95x-f3-opinion/) (4GB RAM / 64GB storage version)
 - OS: Android 9.0
 - Stremio version 1.6.1

**Additional context**
Now I have to adjust the volume setting with my TV remote. And use two remotes to control the Stremio app.

**Comment by TRtomasz** [comment]
tested on mi box s controlling sound volume from remote is wotking fine. 
instruction you provided is for android phones not android tv so looks like you have some weird hybrid of a mobile system installed on a device claiming to be a tv box, sadly we will not be able fix this issue.
