### ISSUE TITLE
Stremio 1.6

### ISSUE THREAD

**Issue by Cmai7385** [Stremio/stremio-bugs#507]
In the new version 1.6.0, the text on streams is difficukt to read, because of the background.   Could you make the text larger  or clearer.  Thank you

Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Android OS version 9
 -

**Smartphone (please complete the following information):**
 - Device: Minix U22xj max
 Version 9 (pie)
 

**Additional context**

**Comment by TRtomasz** [comment]
1.6.0 is mobile app version, you should use tv app version on your device if it is not a phone.

**Comment by Cmai7385** [comment]
Also, if this is the incorrect version for Android OS and a minix U22xj max, please direct me to the correct version.

Currently 1.6.0 works fine on my minix.  All I was requesting was a change to the synopsis if possible.  Otherwise the app works perfectly, apart from some movies having missing synopsis.    Which I reported to support at Stremio.  Who then replied, that they were aware of the issue and working to fix it.

The Android TV version of this app, does not work well on my minix, with a completely different layout.

**Comment by TRtomasz** [comment]
Sorry we are not able to fix issues to the mobile app that are only visible on devices that are tv boxes.

**Comment by Cmai7385** [comment]
Ok Tomasz.  Thank you for your replies🙏🏻
