### ISSUE TITLE
Add option to Autoupdate in-app (Android TV side loaded)

### ISSUE THREAD

**Issue by peposcon** [Stremio/stremio-bugs#511]
Hi, I think that an autoupdate specific to Android TV witch has been side loaded would be a great improvement for keeping the app updated. I can imagine that that version of the app has the lowest number of users that are using the latest release, because of that inconvenience . Some apps (like smart tube) already do this. If there's a problem implementing this with the google store policy well, the android tv download .apk from the webpage can be bytes different with this option enabled.

**Comment by TRtomasz** [comment]
We do not plan to create such feature as it would be an additional cost for ust.

**Comment by peposcon** [comment]
> We do not plan to create such feature as it would be an additional cost for ust.

I can help develop that feature if you want. Gladly
