### ISSUE TITLE
Thumbnails are not resizing correctly (only in Desktop App)

### ISSUE THREAD

**Issue by roshank231** [Stremio/stremio-bugs#514]
**Describe the bug**
The desktop application does not automatically resize thumbnail images to fill empty space. This behavior is inconsistent with the Web App and Fire-TV app, where the thumbnails are resized to fill any empty space.

**Steps to reproduce the behavior:**

Go to the desktop application.
Navigate to Addon.
Observe that the thumbnail image does not resize to fill the empty space, resulting in thumbnails with empty borders.

**Expected behavior**
The thumbnail images should automatically resize to fill any empty space, similar to how it works in all other Stremio variants.

**Screenshots:**

**Desktop App (Fills incorrectly):** 

![image](https://github.com/Stremio/stremio-bugs/assets/83808600/2005d463-59e3-4bb7-abaa-8ad354afa1d3)

**Android TV app (Fills correctly):**

![image](https://github.com/Stremio/stremio-bugs/assets/83808600/348254a0-abe2-4ab2-9d30-298bc04d35d7)

**Web App (Fills Correctly):**

![image](https://github.com/Stremio/stremio-bugs/assets/83808600/9f759aa0-c08f-4008-9e07-a61ff00349fd)

**Desktop:**

OS: Windows 11
Version: 4.4.160

**Additional context**
This issue is specific to the desktop application and does not occur in the Web App or Fire-TV app. The Addon specifically uses an array of video objects and uses the "thumbnail" property to manually set the thumbnail

**Comment by tymmesyde** [comment]
Hi, thank you for your report,
Could you provide which addon are you using to access this content ?

**Comment by roshank231** [comment]
you can find it here: https://github.com/roshank231/optest

(install manifest: https://github.com/roshank231/optest/blob/main/manifest.json)

it pulls images from the one pace website (https://onepace.net/), Here is an example URL:

- https://onepace.net/images/episodes/cover-romance-dawn-01.webp
