### ISSUE TITLE
Comparison between Stremiio web and Desktop app

### ISSUE THREAD

**Issue by steevan464** [Stremio/stremio-bugs#517]
Stremio web is much more fluid than desktop app. But in stremio web the continue watching is not proper. Unlike in Desktop app in stremio web continue watching is not snapping to the recently watched episode. I'm submitting a video detailing this issues please make Desktop app fluid like stremio web. Thanks

https://github.com/Stremio/stremio-bugs/assets/143721101/64e4f7f3-75db-4a7b-9395-8c380ac399ed

https://github.com/Stremio/stremio-bugs/assets/143721101/d644a974-b6de-4a11-8ea5-24bd0eb4ea20

https://github.com/Stremio/stremio-bugs/assets/143721101/7ae7b0b5-ad3c-4d64-a865-848eeb08be2e

https://github.com/Stremio/stremio-bugs/assets/143721101/59463dbd-25e2-4d96-a613-af4202fd2fa6

The first 2 is desktop app then stremio web

**Comment by TRtomasz** [comment]
These are two separate apps created in different technologies, one is very old other one is quite new. They were redesigned to look similar but will never be the same.

**Comment by steevan464** [comment]
Can you make changes in web version. In continue watching section like in
desktop app

**Comment by TRtomasz** [comment]
wen app already has there three dots menu where you can open the same menu as in desktop app.

**Comment by steevan464** [comment]
Yes but if I click on details in stremio web it will go to the last season
of the series no matter where I watched. Also when I click on the centre
portion in continue watching then the app goes to list of add-ons without
showing the episode list. Atleast you can fix that right?
