### ISSUE TITLE
Stremio web issues

### ISSUE THREAD

**Issue by steevan464** [Stremio/stremio-bugs#518]
I've posted an issue here comparing stremio desktop and stremio web and I said stremio web is more fluid than stremio desktop.For that  I got a response saying stremio web is using new engine and that's why its much more fluid. I totaly agree to that. But there are some issues in stremio web which I want to address  here 
1: In continue watching if I click on details it will go to the last season if I am watching a series no matter where I stopped 
2: In continue watching if I click on the big poster of particular series, in other apps like stremio desktop and stremio mobile it usually resumes. But in stremio web it goes to the list of addons of the series which I've watched. And its just list of addons means I cannot change the episode in that window. I will submit videos  confirming what I've said 

https://github.com/Stremio/stremio-bugs/assets/143721101/a77655fc-c632-4ba5-b2dd-c49758587dc8

 

https://github.com/Stremio/stremio-bugs/assets/143721101/90ad1721-387c-4f59-9fd9-f32082f333ef

Please Fix these issues. By the way I LOVE STREMIO:)))

**Comment by TRtomasz** [comment]
should be fixed now
