### ISSUE TITLE
Initial Buffering Issue on Android TV

### ISSUE THREAD

**Issue by xybydy** [Stremio/stremio-bugs#519]
Most of the torrent contents not buffering, all I see is splash screen with the movies logo on. But the weird thing is I can easily open the exact same source from stremio app on phone on the wifi network.

I even did a factory reset on my android tv box (xiaomi mi box s) but the problem is still persists. Rebooting the android tv or force stopping stremio fixes the issue, only for one or two playbacks.

I am not really sure if the app has logging feature to share for debugging.

**Android TV:**
 - Device: Xiaomi Mibox S 4K
 - OS: Android 9
 - Kernel Version: 4.9.113
 - Build: Pl.3933 release-keys

**Additional context**
- Stremio Version: 1.6.1
- Default Player: Exo Player
- Torrent Profile: Ultra fast
- Hardware-accelerated decoding: ON
- Tunnelled Playback: OFF
- Frame rate matching: OFF

**Comment by TRtomasz** [comment]
Please check in the settings for your TV app if the streaming server status is online

**Comment by xybydy** [comment]
It is online actually.

**Comment by TRtomasz** [comment]
Do you use any kind of vpn on your TV that you dont use on your mobile?

**Comment by xybydy** [comment]
No sir. I do not have vpn on my android TV.

**Comment by enko2974** [comment]
The same problem  ,almost every time,90% of time after 1 min of the video i get 9-10seconds buffering with realdebrid,then everything is ok,what coud be the problem?
Mi4k stick , stremio 1.6.3 , android tv 11 OS

**Comment by drjaking** [comment]
Same issue, Firestick 4k. Often crashes too

**Comment by TRtomasz** [comment]
closing as not reproducible, unless someone has a reproducible exmaple we can reopen otherwise it suggest local issues.
