### ISSUE TITLE
I can't cast to my Samsung Smart TV

### ISSUE THREAD

**Issue by gleisonfelipe** [Stremio/stremio-bugs#52]
The TV button on stremio it is greyed. Only the tablet option is available.

Any advice?

**Comment by Ivshti** [comment]
try re-starting the tv, re-starting stremio

other things you can try:

- disable firewall
- change something on the connection - e.g. try with a different wifi connection

**Comment by asozcan** [comment]
Allah belanizi versin, bi is yapiyorsunuz, duzgun yapin kardesim. Iki film izleyip keyif yapacaktik, makine elimizde kaldi. Apple'in da allah bin belasini versin. Servet degerindeki makineye hdmi cikis koymamis, insallah geberir amk cocuklari.
