### ISSUE TITLE
Shows without air dates display incorrect data.

### ISSUE THREAD

**Issue by ljransom** [Stremio/stremio-bugs#520]
**Describe the bug**
If tvdb lists episodes of a show that are yet to have confirmed dates, stremio displays bad data which impacts continue watching and if you are caught up.

**To Reproduce**
1. Search for a show that has episodes without air dates. For example "solar opposites" season 5
2. Select season 5 and observe strange air dates for each episode. For example  "Jan 2,1"

**Expected behavior**
No air date should be displayed at all. With how it incorrectly displays a date, this causes issues with continue watching and the app believes you still have episodes to watch. The date displayed isn't even in a correct format.

Screenshot:

![Screenshot_2023-09-01-22-54-28-03_6012fa4d4ddec268fc5c7112cbb265e7~2](https://github.com/Stremio/stremio-bugs/assets/76923908/3309bc87-2628-47ae-b50a-b6ea1a150f8d)

 - OS: ANDROID TV 12
 - Browser: N/A
 - Version: 1.6.1

**Additional context**
I have spoken to tvdb about this who have confirmed there is nothing on their end that would cause this.

**Comment by TRtomasz** [comment]
there is no bug here, released date is required, and we display what addon returns
