### ISSUE TITLE
Stuttering , choppiness , lag navigating during playback . 

### ISSUE THREAD

**Issue by mizanbalance** [Stremio/stremio-bugs#522]
Hello guys ,
I have an amazon fire hd 10 2019  (  fire os 7.3.1.8 build date 30 jan 2021  used fire toolbox to add google services and remove amazon ones ) 
I recently got the new update on my android tablet , on which it worked perfectly till i updated .
The interface is ok  , but when i select a video to play , during play the interface is laggy , sometimes i can't even pause or change subtitles , for instance i have to press 5-6 times for the layout to activate to see the pause button . and then again couple of times for the pause to register .  I can live with that :)  , but the more pressing issue is that the video playback is a choppy mess / scrambled  , like not having enough time to draw a scene and frame by frame it shows pieces and blocks of the scene for couple of seconds ( a bit like buffering issue ) then for a bit it works well , and then the choppiness begins again . Funny thing is that the audio continues playing with no problem during the choppiness . 
So far i've tested different cache / hardware acceleration settings , 1080-720p streams .  haven't checked external player yet . 
Internet is peachy on the tablet using wifi ,  100+ mbps depending on position , router is in a different room , but same thing happens even if i'm close and not clogging the network . 
Might be something with decoding the video stream during playback  .

**Comment by TRtomasz** [comment]
We are aware of this issue and we are working to improve performance sorry about this.

**Comment by mizanbalance** [comment]
No problemo , thank u for the reply ! , desktop is working good :)

**Comment by GStrategos** [comment]
Hey, guys! Having the exact same issue with Google Chromecast tv and stremio. The version before the big update, was almost perfect, but this one is kinda destroying my viewing experienced and I have too restarting my device all the time, due to lag and choppiness. I'm grateful for your work and I hope you'll be able to restore performance. Cheers!

**Comment by TRtomasz** [comment]
should be fixed with 1.6.6 release.
