### ISSUE TITLE
The tabs interface for the number of seasons was pretty convenient in the old stremio

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#523]
Right now the seasons have been consolidated in a drop down menu.
While this leads to a cleaner look, it prevents you from getting an "at a glance view" of how many seasons a particular series has.
It would be great if the tabs could be reintroduced.
Thanks

**Comment by TRtomasz** [comment]
It will not be reintroduced, i don't see why would it matter that much something has seasons. It is not like it is hidden now and you have to look 5 minutes for this information.
