### ISSUE TITLE
Greek translation does not fit properly

### ISSUE THREAD

**Issue by CDrosos** [Stremio/stremio-bugs#525]
text on buttons overlapping each other
![Screenshot_20230902-190804_Stremio](https://github.com/Stremio/stremio-bugs/assets/10176426/ca9ed070-7853-454e-a487-4d30ed6200a2)

**Comment by CDrosos** [comment]
the live version still has overlapping text as shows in the image at the bottom, it has been fixed but its not live yet?

**Comment by TRtomasz** [comment]
Correct it has been fixed but not live yet will be fixed once we release the update.
