### ISSUE TITLE
Opening the sidebar makes player laggy in desktop app [windows 11]

### ISSUE THREAD

**Issue by Akyllyde** [Stremio/stremio-bugs#528]
**Describe the bug**
Clicking the sidebar open arrow causes the the player UI to fade way in a laggy way. Also, makes the Sidebar un-scrollable.

**To Reproduce**
1. Open any video in stremio video player
2. Click on 'sidebar arrow' (`o` shortcut in keybord)
3. feel pain

**Desktop:**
 - OS: Windows 11 v22H2

**Comment by TRtomasz** [comment]
Sorry, i cant reproduce whatever you mean by 'fade away in a laggy way' perhaps your PC is not very powerfull or you have hardware accelerated decoding turned off in the settings, this can cause high cpu usage.  We will fix issue where it cant be scrolled using keyboard, it is scrollable with mouse only currently.
Regarding margins please  create a separate issue for this we will investigate then. Please remember one issue - one bug on one platform.

**Comment by Akyllyde** [comment]
@TRtomasz You are right. I had hardware accelerated decoding turned off. Turning it on and restarting stremio fixed the laggy animation when opening sidebar.
