### ISSUE TITLE
Sport event torrent identified as documentary and displaying only one file instead of five

### ISSUE THREAD

**Issue by Rachid90** [Stremio/stremio-bugs#531]
I wanted to watch a MotoGP weekend on Stremio (+ torrentio). I pasted the magnet link, but it identified it as a documentary and displayed only one file (on the right-hand side) instead of five files.

**To Reproduce**
1. Copy [this magnet link](HTTP://    magnet:?xt=urn:btih:354B27137023AD603616A9655AA3D531DB69A56B&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=Moto%20Grand%20Prix%20(MotoGP%2C%20Moto2%2C%20Moto3)%202023%20%D0%AD%D1%82%D0%B0%D0%BF%2011%20Spain%20(Catalunya)%20%D0%9A%D0%B2%D0%B0%D0%BB%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F%2C%20%D1%81%D0%BF%D1%80%D0%B8%D0%BD%D1%82%20(MotoGP)%2C%20%D0%B3%D0%BE%D0%BD%D0%BA%D0%B8%20(MotoGP%2C%20Moto%202%2C%20Moto%203)%20%5B1080p%2C%2050fps%2C%20H.2) (remove the **_'http://'_**. It was for the hyperlink to appear correctly).
2. Wait a bit, and you'll see that instead of showing the five files of the torrent, it shows only one file, and it identifies it as a documentary.

**Expected behavior**
See a list of five files that contains the MotoGP weekend.

**Screenshots**
https://i.imgur.com/eOyrvtl.png

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 22h2
 - Version of Stremio: 4.4.160

**Comment by TRtomasz** [comment]
You are trying to watch something that is not a valid series/video it is normal that stremio cant recognize it and fails to display files.

**Comment by Rachid90** [comment]
> You are trying to watch something that is not a valid series/video it is normal that stremio cant recognize it and fails to display files.

Is there a way to bypass this?
