### ISSUE TITLE
Subtitles dragging for Windows version doesn't work

### ISSUE THREAD

**Issue by jcfjcfjcf** [Stremio/stremio-bugs#532]
How do you put subtitles in the Windows version?
Because it's always been dragging and I can't do that anymore, it gives an error message.
All subtitle files end in .srt and I was always able to put them in and use them, but sometimes it gives me an error. I need a solution.

Version 4.4.160

**Comment by TRtomasz** [comment]
Subtitles has to be .srt and in utf-8 format

**Comment by TRtomasz** [comment]
https://www.cin.ufpe.br/~amng/Notepad++Portable/App/Notepad++/user.manual/documentation/notepad-user-manual/document-properties/encoding.html
