### ISSUE TITLE
Tract not working on Android phone app

### ISSUE THREAD

**Issue by asaddon** [Stremio/stremio-bugs#534]
**Describe the bug**
Trackt integration of the official addon ( I believe it's official since it is preinstalled) is not working on Android App neither history syncing nor scrobbling but working perfectly on Android TV app. 
I've tried reconnecting the Trackt integration but still the same. 

**To Reproduce**
1. Open Android App
2. Play anything
3. Check Trackt

**Expected behavior**
Trackt history sync and scrobling should work on Android phone.

**Smartphone (please complete the following information):**
 - Device: POCO F3
 - OS: MIUI 14.0.7
  - APP Version 1.6.1

**Additional context**

**Comment by TRtomasz** [comment]
closing as not reproduicble
