### ISSUE TITLE
On Explayer on ccwgtv I get ERROR_CODE_AUDIO_TRACK_INIT_FAILED

### ISSUE THREAD

**Issue by sylverstream** [Stremio/stremio-bugs#535]
**Describe the bug**
On certain streams on ccwgtv I get the full screen error ERROR_CODE_AUDIO_TRACK_INIT_FAILED 
The video and audio play fine though. 
It only seems to happen on the first streams which have the highest resolution/bit rate. 
Only happens in exoplayer. 
Switching to libvlc fixes the problem but has other issues, so I want to use exoplayer. 
Similar issue here which was closed as fixed, but issue persists. 

https://github.com/Stremio/stremio-bugs/issues/513#issue-1875049881

**Comment by sylverstream** [comment]
Update: I've manually downgraded to 1.5.11 and problem is gone. Still needs to be fixed of course.
Download links are in this Reddit post from people with the same problem: https://www.reddit.com/r/Stremio/comments/16bvas1/comment/jzg4i11/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by jaruba** [comment]
latest release v1.6.3 fixes this issue: https://blog.stremio.com/stremio-tech-update-23-android-tv-desktop-mobile-fixes/
