### ISSUE TITLE
Google Assistant won't find results on Google TV

### ISSUE THREAD

**Issue by avsha114** [Stremio/stremio-bugs#536]
**Describe the bug**
I own a Mi Box S 2nd generation with Google TV OS.
The voice search with google assistant is not showing results from Stremio like with Netflix etc.
I also have a 1st generation Mi Box S with the old Android TV and it works perfectly on the old OS. There's a button to show in Stremio after the search.
I rechecked Stremio on the "Searchable apps" section in the assistant settings.

**To Reproduce**
Use the remote voice search button to search for a movie/tv show.

**Expected behavior**
Like in the Android TV version - show the result with an "show in stremio" button or something like that.

**Screenshots**
not really necessary.

**Desktop (please complete the following information):**
 - OS: Google TV

**Smartphone (please complete the following information):**
Mi Box S 2nd Gen.

**Additional context**
I rechecked Stremio on the "Searchable apps" section in the assistant settings.

**Comment by TRtomasz** [comment]
This is not a stremio bug google tv and android tv are separate OSses and simply google tv does not allow everyone to add such things.
