### ISSUE TITLE
On launching Stremio recently, it changed the UI skin and I can't go back to the regular one

### ISSUE THREAD

**Issue by nukeop** [Stremio/stremio-bugs#540]
**Describe the bug**
I have not updated Stremio. Despite that, the interface changed completely one day, just after launching it as regular.

That interface features badly placed buttons, extremely small, undreadable fonts, and bafflingly placed elements. I think it must be a bug, because I have never changed any UI skins, nor have I updated the program at all.

**To Reproduce**
I can't go back to the previous version now, so I don't know how to reproduce it.

**Expected behavior**
I expected Stremio to keep looking and working exactly the same as always.

**Screenshots**
<img width="1274" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/12746779/1527254f-1388-4908-931f-cf98da15113d">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 4.4.160

**Additional context**
N/A

**Comment by jaruba** [comment]
this is not an issue and it cannot be solutioned, this is the new Stremio app design

**Comment by nukeop** [comment]
Ok, so how do I go back to the normal design? Why did it update if I did not update the program, and how do I prevent it from happening again?

**Comment by nukeop** [comment]
BTW, this new UI is missing some crucial info, like the number of seeds when loading streams.

**Comment by jaruba** [comment]
you cannot go back to the previous design, this was a branding change too

you also cannot use an older version for the old design and stop updates, all app versions use the same design

please create individual issues for the bugs u find in the new design so we can keep track of them

**Comment by nukeop** [comment]
Why did you think it's a good idea to force this update onto unwilling users? It's extremely creepy that there even is a mechanism to update a program on my computer against my will, and it's being actively used with no way back.

**Comment by jaruba** [comment]
For desktop it's a web UI, and it has always been so, this is no different than any website updating their design and brand. Although I understand ur nostalgia, this will be the Stremio brand and design as it was decided by the company, there is nothing "creepy" about it.

**Comment by nukeop** [comment]
I was never under the impression that this is just an embedded website. Why ship a desktop program at all? And why do you feel you're authorized to make changes to programs on my PC?

**Comment by jaruba** [comment]
It is not "just an embedded website", it is the Stremio desktop app and it is using a web UI and a shell, which gives access to MPV (the internal player) and the local server. (check the`stremio-shell` repository, it is open source).

There is also a dedicated Stremio Web app: 
(`stremio-web` is also an open source project)
https://web.stremio.com/ that can use Stremio Desktop or Stremio Service (the `stremio-service` repo) as the streaming server / companion app for transcoding / transmuxing for browser support.

Maybe I seem rude to you, I assure you that this is not my intention. The majority of users have requested a redesign for many years, there have been so many people that dedicated their time to redesigning all the Stremio apps and brand (not just desktop), in which time all our apps suffered from lack of developer time to evolve.

There has been no change to "your PC", this is a website change, the desktop UI has always been delivered online through our servers, the choice of using a web UI was for costs (foremost) and update speed reasons. Without using a web UI, it would have been much harder to suffer the costs of the project for you and all other users. There is also an auto-updater that is used rarely for streaming server updates mostly.

Stremio is a large project and it was time for a change, the users wanted it for a long time too and it was a huge effort on our side also, but a big change in design was inevitable.. we have used the previous design for 5+ years, I believe.

**Comment by nukeop** [comment]
And? Don't fix what's not broken, it was perfectly good. Now the font is so small it's unreadable, and I can't change that.

**Comment by nukeop** [comment]
For anyone stumbling into this in the future, you can restore the previous interface if you deny Stremio access to the internet at startup. Later you can enable internet access, and the UI stays the same.

There's no reason for a completely locally working program to be an embedded remote website. It could very well be local HTML, just like my music player, Nuclear works.
