### ISSUE TITLE
Feature request: Always start video in external player (PC)

### ISSUE THREAD

**Issue by fedew04** [Stremio/stremio-bugs#542]
The Android app of Stremio has an option to always start the video in an external player. I suggest that this same feature is added to the Desktop app. The Desktop app already gives you the option to open in other players when you're inside the video, but it would be very useful if you could set it to open in an external player by default.
![image](https://github.com/Stremio/stremio-bugs/assets/65686048/41aae210-2c48-4271-8d1d-453afa3ef5ac)

**Comment by fedew04** [comment]
@TRtomasz was this closed because it was accepted or because I should've posted it on stremio-features? (I only just realized that repo exists). Sorry for bothering with the ping.

**Comment by TRtomasz** [comment]
this kind of feature request already exists in the stremio-features repo - https://github.com/Stremio/stremio-features/issues/207

**Comment by fedew04** [comment]
oh, is it in development?
