### ISSUE TITLE
Description and links are not showing, need to click 2 times on the show to display 

### ISSUE THREAD

**Issue by sunilroy007** [Stremio/stremio-bugs#543]
when  ever I click on any series or movie it doesn't show description or links it just show poster and add to library, I need to click back and click on the same show for links and description to display correctly in both  android mobile and android Tv... I android TV I can't see any description of the show but I can see links, this bug is not new and it's been there since 6 months but now only I am writing this as I thought its just my issue but even after the new ui update this issue is still there so I definitely think its a bug

**To Reproduce**
1. Go to ' homepage or any series or movie'
2. Click on 'series or movie'
3. Scroll down to 'just click on the show'
4. first time when you click on the show it just shows poster and add to library that's it,  but if you go back and click on the same show the it displays everything correctly... this is not limited to one show I need to click on every show like this 2 times to get it work properly... I android TV even if I click on the show 2 times it doesn't show any description or ratings, it just display picture and links.

**Expected behavior**
I think it should show everything perfectly in 1st click right?

**Screenshots**
![Screenshot_2023-09-15-12-41-50-02_5a1e11fa41055108da81eb54eea93a2a](https://github.com/Stremio/stremio-bugs/assets/57356030/a272ab81-2dac-4c52-ba86-89d9623dd61e)

**Smartphone (please complete the following information):**
 - Device: [realme 3 pro]
 - OS: [android 11]
 - Browser [brave or chrome]
 - Version [stremio version latest, brave browser or chrome latest]

Android TV

Sony X800H
android 9
version latest stremio

**Comment by sunilroy007** [comment]
And sometimes like this too when opened.... screenshot from android phone but this is how it shows on Android TV too


![Screenshot_2023-09-15-12-57-52-13_5a1e11fa41055108da81eb54eea93a2a](https://github.com/Stremio/stremio-bugs/assets/57356030/60c7a4f2-37d9-4fbb-885d-02b546a07370)

**Comment by TRtomasz** [comment]
I cant reproduce this, if you open something you watched before it navigate straight to the last watched episode. You can click three dots(or long press on android tv) to open details without going to specific episode
