### ISSUE TITLE
App not working on Android TV since latest  Fire TV update (OS 7.6.5.2)

### ISSUE THREAD

**Issue by yuriamorimcc** [Stremio/stremio-bugs#545]
Hey guys! I just did an update on the software of my Fire Tv (to OS 7.6.5.2) and now the Stremio app is not opening anymore. 😭 I've downloaded the 1.61 APK installer from the website and updated the previous version I had installed, but still no success on getting it to open and function properly. Is there any new updates coming soon? Any help will be greatly appreciated!!!

**Comment by TRtomasz** [comment]
Which one exactly have you downladed and what do you mean by 'is not opening anymore'?

**Comment by lowlevel-1989** [comment]
> Hey guys! I just did an update on the software of my Fire Tv (to OS 7.6.5.2) and now the Stremio app is not opening anymore. 😭 I've downloaded the 1.61 APK installer from the website and updated the previous version I had installed, but still no success on getting it to open and function properly. Is there any new updates coming soon? Any help will be greatly appreciated!!!

I have the Fire TV Stick 4K with Fire OS 6.2.9.8, and Stremio is working perfectly. If you're experiencing any issues or have questions, feel free to share the specific problems you're encountering or provide some screenshots, and I'll be happy to assist.

**Comment by yuriamorimcc** [comment]
> Which one exactly have you downladed and what do you mean by 'is not opening anymore'?

Hello, thanks for answering and sorry for the lack of description of the problem I'm facing. I have downloaded the first link on the Android TV list on Stremio's downloads page: [Stremio 1.6.1 ARM APK](https://dl.strem.io/android/v1.6.1-com.stremio.one/com.stremio.one-1.6.1-7048601-armeabi-v7a.apk)

I've managed to complete the installation normally, but afterwards the app just stopped working. What happens is that I click on the app (the logo is still the old one in the main menu) and then the new logo pop's up, like it's opening, but after a few seconds the app fails to launch and the screen goes back to the Home page. I recorded a small video to demonstrate it happening (https://www.youtube.com/shorts/y3hk8vnd6B0).

My Fire TV Stick's model is the 3d Generation, btw. I had a previous version of the Stremio app installed on it (the one that was available for the public around May of 2023) and it was working just fine. I did overwrite the previous installation with the new one, could that be the issue?

After that first failed attempt, I actually did tried installing from another file [Stremio 1.6.1 x86_64 APK] but with this one the installation didn't finish. Another possibility is for me to delete the app and do a clean install with the new installer. Just let me know which installer should I use, please.

Thanks in advance!

**Comment by yuriamorimcc** [comment]
Any inputs?

**Comment by TRtomasz** [comment]
thank you for letting us know, will close the issue then.
