### ISSUE TITLE
Just showing the "subscription" links or perio

### ISSUE THREAD

**Issue by marcelasales** [Stremio/stremio-bugs#548]
I am using my account (not a guest account) and I am trying to watch anything but it doesnt show any links except for the subscription ones as netflix, amazon, hbo etc. 
I already installed all the addons possible and nothing is working on my device. 
I've been using stremio for a very long time and never had any issues like this one. I dont know what to do anymore.. I already reinstalled the app and everything. 🫠

Example:
![Screenshot_20230916_200624_Stremio](https://github.com/Stremio/stremio-bugs/assets/87813355/31209bcb-5788-41da-9f63-72f870655f57)

**Smartphone**
 - Device: Galaxy S21 5G
 - OS: Android 13

**Comment by TRtomasz** [comment]
this is not a bug, we do not controll available addons or streams you should check addons forum if you are looking for more addons.
