### ISSUE TITLE
I can't login or create a new account

### ISSUE THREAD

**Issue by GabrielRJ28** [Stremio/stremio-bugs#55]
I needed to reinstall stremio on my notebook since then i can't login or create a new account to use the program

When i put my login and password the "connect" button doesn't response, the same thing happens when i try to registrate a new login and password

When i try to registrate with facebook, the login works but the "connect" button doesn't

And i can't use de guest login too

Somebody knows how to fix that?

Thanks
Country Brazil

**Comment by Ivshti** [comment]
could be related to https://github.com/Stremio/stremio-bugs/issues/46
