### ISSUE TITLE
Addon dev - Live stream http URL in stremio Web not supported

### ISSUE THREAD

**Issue by adaladdin** [Stremio/stremio-bugs#552]
**Describe the bug**
I am developing a personal addon for watching live streaming videos. I currently have it fully functioning and catalogs/streams/playing the live streams are being pulled in and work properly on the windows desktop application of stremio and also android.

On the web version of stermio however... First off it uses the Meta api handle to retrieve the video instead of the Catalog controller which is fine because I've handled both. I made sure the Meta handle returns the expected Meta object as expected, giving it the Stream video as it's output and I can see everything properly as I should on the web.

When clicking to play it, I receive Video is not supported message, with an option to open in external player.

There is further logs in the console that mentions disallowing mixed-content between https and http which is true since the live stream I'm particularly playing is served via http

**To Reproduce**
1. Get an addon that can provide live streams (over http, not https)
2. Use stremio web
3. Ensure you have a valid configured streaming server
4. Go to the category the addon provides
5. Play the live stream

**Expected behavior**
I would expect stremio-web to be able to play a live stream of any sort (m3u playlist file, .ts extension on a live stream)

Especially if stremio-web uses a valid dedicated streaming server

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/110638825/f81c54d6-dc53-4dc8-bc4f-bf1d49c784b4)
![image](https://github.com/Stremio/stremio-bugs/assets/110638825/b9718755-d1ea-48c4-873c-640612f214bf)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
I am not sure if the problem is 'mixed-content' part of it or if it's the actual web player not supporting a live stream format.

If it is being blocked due to http, perhaps consider adding a toggle option to allow for http?

**EDIT**
I was able to get around the mixed-content error by build and running a local version of stremio-web with header tag
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />`
in index.html

and it seems to have taken care of the mixed-content error. However, the unsupported video message is still appearing.

I've also tested this with another addon that is available on the community addons: H Mr Danger Internet TV
and it seems to have the same behavior.

**Comment by TRtomasz** [comment]
This is not possible and `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />` only changes requests to https from http is servers do not have valid certificates it will not work.
