### ISSUE TITLE
Share links not working

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#553]
**Describe the bug**
The movie share links are not working
**To Reproduce**
1. Open the movie page
2. Press the Share button and open link
3. Press the Download Stremio button
4. It shows an error

**Expected behavior**
For the share link to work normally 
**Screenshots**
Added
**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Brave
 - Version: 1.58.131

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12 MIUI 13
 - Browser: Brave
 - Version: 1.57.62

**Additional context**
/
![Screenshot_2023-09-25-11-23-52-347_com brave browser](https://github.com/Stremio/stremio-bugs/assets/18757054/79488b9d-33f5-4193-8441-a42b415cb521)
![Screenshot_2023-09-25-11-23-54-194_com brave browser](https://github.com/Stremio/stremio-bugs/assets/18757054/154770c2-db94-4e19-ae9a-6761ddc30d14)
![Screenshot_2023-09-25-11-24-25-593_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/df2f250d-a61d-49c4-964d-f4c043f703cc)
![Screenshot_2023-09-25-11-24-34-328_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/6b21ddfc-085d-4750-a8c9-86f7f69159d3)

**Comment by TRtomasz** [comment]
should be working now
