### ISSUE TITLE
Subtitles hard to see

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#554]
**Describe the bug**
Subtitles are often hard to see, can you improve their design?
**To Reproduce**
1. Select subtitle language
2. Disable the background overlay
3. Optionally increase subtitle size

**Expected behavior**
For the subtitles to be less transparent and better to see
**Screenshots**
Added
**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Brave
 - Version 1.58.131

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12 MIUI 13
 - Browser Brave
 - Version 1.57.62

**Additional context**
/
![Screenshot_2023-09-25-11-12-45-261_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/cd74aecc-22bb-4a6a-9cad-017cfbac05f1)
![Screenshot_2023-09-25-11-24-25-593_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/57a2c77b-273c-452e-b31b-2a122ecedbd3)
![Screenshot_2023-09-25-11-24-34-328_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/a57618fb-1c17-47f6-9f7a-207c53472e41)
![Screenshot_2023-09-25-14-45-14-274_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/a1f97f41-4b3e-438d-9c9a-5900bf1a3c54)

**Comment by TRtomasz** [comment]
I will close this issue cause subs does not have  transparency at all and they are perfectly visible. If you want them more visible as you wrote you can increase size or use black background color
