### ISSUE TITLE
[Feature Request] Autoplay Feature (+ maybe Filter settings)

### ISSUE THREAD

**Issue by tundrablasen** [Stremio/stremio-bugs#556]
I would be great if we could get an autoplay feature. instead of manually choosing a source, just play the first source.

additionally it could be possible to add filter settings to the stremio settings

**Comment by TRtomasz** [comment]
There already is autoplay next episode feature you can enable it from the settings.

**Comment by tundrablasen** [comment]
> There already is autoplay next episode feature you can enable it from the settings.

lets continue here https://github.com/Stremio/stremio-features/issues/528
