### ISSUE TITLE
Episode descriptions for non-English series are in native language rather than English, and some series have no information

### ISSUE THREAD

**Issue by who-is-matt** [Stremio/stremio-bugs#560]
**Description of the bug**
Episode descriptions for most non-English series are in their native language rather than English.

This is happening to me for almost all non-English series, except for a few that still have episode descriptions in English, and a small number of series that no longer have any information for episodes and are therefore entirely unable to be watched. Just looking through those series in my Library...

Episode descriptions for the South Korean series _Squid Game_, _Island_, _Vagabond_, _The Silent Sea_, _Hellbound_, _The Uncanny Counter_, _Black Knight_, _Alice in Borderland_, _Hotel del Luna_, _Kingdom_, _All of Us Are Dead_, _My Name_, and _Sweet Home_ are in Korean.

Episode descriptions for the anime _That Time I Got Reincarnated as a Slime_, _Demon Slayer_, _Heavenly Delusion_, _My Hero Academia_, _Made in Abyss_, _KamiKatsu_, _Parasyte_, _Tokyo Ghoul_, _Goblin Slayer_, _Fire Force_, _Vermeil in Gold_, _Re:Zero_, _One Punch Man_, and _Konosuba_ and are in Japanese.

However, exceptions I've found are _Ergo Proxy_, _Highschool of the Dead_, _FLCL_, _Soul Eater,_ _Hell's Paradise_, _Cowboy Bebop_ (1998), and _Puella Magi Madoka Magica_, which have episode descriptions in English.

Episode descriptions for the Spanish series _Welcome to Eden_ are in Spanish. Episode descriptions for the German series _Pagan Peak_ and _Dark_ are in German. Episode descriptions for the Egyptian series _Paranormal_ are in Arabic.

As with anime, there seem to be exceptions, such as episode descriptions for the French series _Lupin_, which are in English.

Selecting entries for _Jujutsu Kaizen_, _Spy x Family_, _Overlord_, or _Devilman: Crybaby_ results in a screen saying "No information found about this". I get this screen regardless of whether I select these series from my Library or from Search results.  **This may be an unrelated issue, but appeared at the same time as the language issue and likewise seems to be a problem with the metadata provider.**

**To Reproduce**
1. Search for or navigate to any of the series listed above as having native-language episode descriptions or a complete lack of episode descriptions.
2. Click on the series to open the episode selection screen.
3. Either see the "No information found about this" screen, or scroll to any episode to view the non-English episode description.

**Expected behavior**
Episode descriptions should all be in English (or ideally a language specified by the user, perhaps with a fallback to English if episode descriptions in the specified language aren't available)

**Screenshots**
Korean series _The Uncanny Counter_ episode description in Korean:
![Stremio_20231001_213221](https://github.com/Stremio/stremio-bugs/assets/4270243/790286ae-2fc8-4a98-8889-e2f9c4095df2)

Spanish series _Welcome to Eden_ episode description in Spanish:
![Stremio_20231001_212106](https://github.com/Stremio/stremio-bugs/assets/4270243/3253a231-7038-4603-b359-d266337fa06b)

German series _Pagan Peak_ episode description in German:
![Stremio_20231001_212135](https://github.com/Stremio/stremio-bugs/assets/4270243/836c497f-e421-4202-91e5-a6120d13be5e)

Egyptian series _Paranormal_ episode description in Arabic:
![Stremio_20231001_212217](https://github.com/Stremio/stremio-bugs/assets/4270243/3c8c7f27-913c-4b11-abba-1ab974ab3ce6)

**Exception**, French series _Lupin_ episode description in English:
![Stremio_20231001_212245](https://github.com/Stremio/stremio-bugs/assets/4270243/a2127482-d5d9-4dd9-a56d-98f887b93996)

"No information found about this" when selecting _Jujutsu Kaizen_ series:
![Stremio_20231001_213825](https://github.com/Stremio/stremio-bugs/assets/4270243/e7356d47-f2f6-46b0-86a1-6dad65ee1a5f)

**Platform**
 - Device: nVidia Shield TV Pro
 - OS: Android TV 9.1.1(33.2.0.157)

**Additional context**
While episode descriptions are not currently available on the desktop version of Stremio, episode titles of at least some of the non-English series mentioned above are listed in their native language when viewing them in the desktop version of Stremio on Linux.  It seems likely that when the desktop interface is fixed so that episode descriptions are once again viewable that this issue with non-English series will apply to desktop as well.

**Comment by TRtomasz** [comment]
this should be fixed soon automatically once cache expires, sorry about this.
