### ISSUE TITLE
Subtitle no track

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#565]
**Describe the bug**
Subtitles won't load and the player shows No track message
**To Reproduce**
1. Open a movie or series
2. Choose a subtitle
3. It will show a Loading subtitles message and then the No tracks message

**Expected behavior**
For the subtitles to be loaded and showed

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Brave
 - Version 1.58.135

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12 MIUI 13
 - Browser Brave
 - Version 1.57.62

**Additional context**
/
![Screenshot_2023-10-05-02-12-43-297_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/2a57300c-eabf-4f5f-bac0-d78b46c118ca)
![Screenshot_2023-10-05-02-12-49-126_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/5f67208e-0f41-46c4-b328-28b46aa27738)
![Screenshot_2023-10-05-02-16-01-067_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/2a0d76aa-077b-4b82-bc90-8af032bfd3a7)
![Screenshot_2023-10-05-02-16-11-966_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/81fd1d73-068a-4637-80db-894d01d5d8a2)

**Comment by TRtomasz** [comment]
I can't reproduce this, what is your location and internet provider? You could try using a vpn set to different location please.

**Comment by GKid94** [comment]
> I can't reproduce this, what is your location and internet provider? You could try using a vpn set to different location please.

Serbia, ST Cable

**Comment by TRtomasz** [comment]
were you able to verify if this happens when using a vpn?

**Comment by GKid94** [comment]
> were you able to verify if this happens when using a vpn?

I'm already using VPN in the AdAway app

**Comment by TRtomasz** [comment]
Have you tried using different vpn server? or different vpn? or no vpn at all

**Comment by GKid94** [comment]
> Have you tried using different vpn server? or different vpn? or no vpn at all

Yes, it's the same

**Comment by kaltamimi** [comment]
Me too I have the same issue.

**Comment by assafmo** [comment]
Me too

**Comment by arierep60** [comment]
Same issue here. It's working fine on my desktop but then on laptop and on mi Mi TV Stick 4K does not load any subtitles.
Already tried to uninstall addons and install again but it does not fix the problem :(

**Comment by arierep60** [comment]
> Same issue here. It's working fine on my desktop but then on laptop and on mi Mi TV Stick 4K does not load any subtitles. Already tried to uninstall addons and install again but it does not fix the problem :(

Well, got it working on my laptop now.
Uninstal stremio, and on my desktop (which was working fine) did a log-out, then log-in again, and then log in on laptop and it loaded the correct addons and it's working fine now.
Just need to uninstall and install again on my Mi TV Stick 4k to see if it solved the problem

**Comment by TRtomasz** [comment]
@GKid94  is this happening with new opensubtitles v3 addon?

**Comment by GKid94** [comment]
> @GKid94 is this happening with new opensubtitles v3 addon?

Still happens
![Screenshot_2023-10-23-22-01-30-458_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/4630e298-037c-4857-bce6-2b6235d9760b)

**Comment by GKid94** [comment]
Can you also add official addons for movie and series streams because Torrentio has connection problems

**Comment by TRtomasz** [comment]
We do not create new addons, content addons are created by the community. I will close this issue as it has been fixed

**Comment by GKid94** [comment]
> We do not create new addons, content addons are created by the community. I will close this issue as it has been fixed

It's not fixed, I sent you a screenshot of the bug again

**Comment by jaruba** [comment]
@GKid94 give it a bit of time, we did say that it make take up to 48h (in the official blog post) for us to perfect it as it is a completely new addon that can have bugs, we are constantly working on building and perfecting it for 3 days..

**Comment by GKid94** [comment]
> @GKid94 give it a bit of time, we did say that it make take up to 48h (in the official blog post) for us to perfect it as it is a completely new addon that can have bugs, we are constantly working on building and perfecting it for 3 days..

Ok, but what about the movies and series official addons? You said that you can't add addons but you added a new subtitle one

**Comment by bediu** [comment]
This is still not working

**Comment by bidzapfc** [comment]
This is happening now again

**Comment by TRtomasz** [comment]
This issue is not caused by stremio moste likely opensubtitles is blocking your ip
