### ISSUE TITLE
Cinemeta doesn't show torrents of an anime

### ISSUE THREAD

**Issue by Pab10Suarez** [Stremio/stremio-bugs#566]
**Describe the bug**
Cinemeta doesn't show torrents of an anime, but i can find it in cinemeta

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/29072142/80e2a537-c685-4e1c-9b89-0d84ae12f6b7)
Here's what i see with cinemeta but if i use another provider (kitsu) the torrents are  showed up 
![image](https://github.com/Stremio/stremio-bugs/assets/29072142/44fe323a-60cc-4632-a78d-f7e78ff1a503)

**Desktop (please complete the following information):**
 - OS: Windows
![image](https://github.com/Stremio/stremio-bugs/assets/29072142/15ecfa70-7438-4834-9d31-be385032ec7b)

**Comment by kevingmz** [comment]
Having the same issue for a couple days now

**Comment by TRtomasz** [comment]
should be fixed now

**Comment by Pab10Suarez** [comment]
> should be fixed now
now the torrents appear but not the next and new chapters, should i do something for refres it?
![image](https://github.com/Stremio/stremio-bugs/assets/29072142/76122b7b-3127-45df-adee-f5ef3a941a7c)

**Comment by kevingmz** [comment]
It was working for a few days but I think it's not working again, even weirder, looks like the old episodes work, but they new ones don't get any working torrents listed
