### ISSUE TITLE
Subtitle problems

### ISSUE THREAD

**Issue by Maremelows** [Stremio/stremio-bugs#569]
Please do something about the subtitles. They never synchronize with the movie or series.I'm having this problem in the Android app.I've tried this with different series or movies,I've tried shared versions of the same content with different addons.I've tried all the available subtitle options,I've tried to re-select them from +/- but they never synchronize.Please do something to fix the problems with the subtitles.No matter what I've done I can't solve this problem.My phone is Samsumg Galaxy A23.My phone has Android 13 OS.My Stremio application version is 1.6.7.

**Comment by TRtomasz** [comment]
Stremio does not controll available subtitles. They might be created for different version of same video, like one having different FPS. They might not be possible to synchronize at all, but i have checked and synchornization feature is working fine, i can make subtitles appear earlier and later.
