### ISSUE TITLE
Stremio playback speed setting disrupts subtitle synchronization.

### ISSUE THREAD

**Issue by Maremelows** [Stremio/stremio-bugs#572]
**Describe the bug**
In Stremio, subtitle synchronization works almost flawlessly when the playback speed setting remains constant, but when I increase the playback speed, the subtitle synchronization is broken. Subtitle comes late or does not come during the conversation, the next sentence comes

**Expected behavior**
The playback speed setting should not disrupt subtitle synchronization.

**Smartphone (please complete the following information):**
 - Device:Samsung Galaxy A23
 - OS:Android 13
 - Version:1.6.7

**Comment by TRtomasz** [comment]
Cant reproduce both embedded and external subtitles are working fine with playback speed increased. Perhaps you used not synchronized subtitles
