### ISSUE TITLE
Subtitle size not adjustable when using libVLC on Stremio Android TV v1.6.3

### ISSUE THREAD

**Issue by jammekod** [Stremio/stremio-bugs#573]
On the Stremio app for Android TV (version 1.6.3), when I switch to the libVLC player, I am unable to adjust the subtitle size. This issue does not occur when using the default ExoPlayer; however, due to playback lag issues on my Android box which I have mentioned in my previous bug report #568 , I prefer to use libVLC, it solves the lag problem for me for certain video files. The default subtitle size on libVLC is notably large and I'd like an option to reduce it to 80% but can't.

Steps to reproduce:
Launch Stremio on Android TV.
Navigate to Settings > Playback > Default Player.
Switch to the libVLC player.
Play any content with subtitles.
Try adjusting the subtitle size.
Expected behavior:
Subtitle size should be adjustable on libVLC, similar to how it is on ExoPlayer.

Actual behavior:
Subtitle size remains at a default size (too large) and there's no option to adjust it when using libVLC.

Additional information:
Device: Telia Play Hub
OS Version: Android 10
Stremio Version: 1.6.3

This issue does not exist when using ExoPlayer, but due to playback lags on ExoPlayer, I'm compelled to use libVLC.

Suggestion:
It would be great to have a global subtitle size setting in the app that affects all players or to bring the subtitle size adjustment functionality to libVLC.

**Comment by TRtomasz** [comment]
vlc does not have feature to change subs size, this is not a stremio bug

**Comment by jammekod** [comment]
Thanks for the great work! 😀
