### ISSUE TITLE
Playback progress not remembered on libVLC in Stremio for Android TV (v.1.6.3)

### ISSUE THREAD

**Issue by jammekod** [Stremio/stremio-bugs#574]
On the Stremio app running on my Telia Play Hub with Android TV OS 10, the app remembers where I stopped playing a file/video when using the default ExoPlayer. This "resume playback" functionality is not present when I switch to libVLC, which makes me start from the beginning every time I play a file that I previously paused and exited the app.

**Steps to reproduce:**
Launch Stremio on Telia Play Hub.
Navigate to Settings > Playerback > Default Player.
Switch to the libVLC player.
Play any content and pause at any point.
Exit the playback and then try to play the same content again.

**Expected behavior:**
The content should resume from where it was paused, similar to how ExoPlayer behaves.

**Actual behavior:**
The content starts playing from the beginning, ignoring the previously paused/stopped position.

**Additional information:**
Device: Telia Play Hub
OS Version: Android 10
Stremio Version: 1.6.3

This issue does not occur when using the default ExoPlayer.

**Suggestion:**
It would be ideal if libVLC could also remember the playback position, providing a consistent user experience across both players in the app.

**Comment by TRtomasz** [comment]
I was not able to reproduce this issue.
