### ISSUE TITLE
Marking a TV series as Watched causes notifications to not work for new episodes

### ISSUE THREAD

**Issue by P-Jay357** [Stremio/stremio-bugs#576]
I've notcied this hapen so much that I now unmark TV series' as watched, oherwise I can miss new episodes. This also happens if Stremio marks a series as watched automatically after I have caught up with the series.

This means that new episodes don't appear on the Home Page under the New Episodes header.

I use the Windows Desktop app, but the behaviour is the same on my Android phone.

The version I have is v4.4.164

**Comment by TRtomasz** [comment]
This is intended, not a bug currently.
