### ISSUE TITLE
Interapted in the middle of a stream on android tv version 1.6.3

### ISSUE THREAD

**Issue by enko2974** [Stremio/stremio-bugs#578]
Sometimes in the middle of a strem , especially on avi files , gets interapted and switch on the  other player libVLC,and there is stuttering .

My device is mi4k stick on android tv 11 OS and i have real debrid , stremio version android tv 1.6.3

Thank you,

**Comment by TRtomasz** [comment]
This is not a stremio bug, player gets switched when player encounters on error in playing the stream.

**Comment by enko2974** [comment]
Thank you,earlier was not hapening ,because of that i asked.
