### ISSUE TITLE
Casting custom subtitles to Chromecast won't work

### ISSUE THREAD

**Issue by wormangel** [Stremio/stremio-bugs#58]
This is more or less the same as https://github.com/Stremio/stremio-bugs/issues/17
Apparently it was never fixed. Any plans of making it work?

**Comment by Ivshti** [comment]
Yes, in 3.6 or 4.0 versions, which will be in Alpha a 2-3 weeks.

Since this is fixed by design in the next iterations, and we've focused all efforts on them, the fix probably won't be 'backported' to 3.5 series

**Comment by Ivshti** [comment]
closing as duplicate of #17

**Comment by Ivshti** [comment]
@wormangel please check the #17 thread
