### ISSUE TITLE
Buffering more than required.

### ISSUE THREAD

**Issue by gaurovgiri** [Stremio/stremio-bugs#582]
**Describe the bug**
When I'm watching some specific movies or series, the buffering exceeds the mentioned buffered size yet it do not even cross 50% when the network status is checked.

**To Reproduce**
1. Search for Loki
2. Load a episode
3. Check network status

**Expected behavior**
If it mentions 2.58 GB of Buffer Size, then buffering should complete in 2.58 GB with 100% and not exceed any more than that.

**Screenshots**
![LOKI](https://github.com/Stremio/stremio-bugs/assets/64427471/62e4321f-e845-4648-90c8-0346debbe6cc)
![LOKI2](https://github.com/Stremio/stremio-bugs/assets/64427471/287bb81e-428c-4cee-8d5a-25eee97224ad)

**Desktop (please complete the following information):**
 - OS: Fedora 38

**Additional context**
I have reinstalled the application twice.

**Comment by TRtomasz** [comment]
This could happen in case of: torrent poisoning, broken torrent file, or simply description is wrong and file size is different.
