### ISSUE TITLE
Opensubtitles official addon isn't working

### ISSUE THREAD

**Issue by Arturvitormb** [Stremio/stremio-bugs#583]
The addon is simply not working, on any platform

**Comment by jaruba** [comment]
this seems to be a problem on the opensubtitles service side, we sent a message to the admin of the service and are awaiting his reply

**Comment by Arturvitormb** [comment]
> this seems to be a problem on the opensubtitles service side, we sent a message to the admin of the service and are awaiting his reply

OpenSubtitle.org added cloureflare's bot protect now, maybe its this

**Comment by jaruba** [comment]
@Arturvitormb it seems to be related as it is affecting the API too, but there is nothing that we can do unless the service admin changes it back and answers us

**Comment by TRtomasz** [comment]
@Arturvitormb  you should see now opensubtitles v3 addon in the addon catalog you can install it and try using

**Comment by tfouto** [comment]
> @Arturvitormb you should see now opensubtitles v3 addon in the addon catalog you can install it and try using

It works, but When I exit and Start Stremio again, I have to install it again. Installation wont persist and wi default to old version, even if I uninstall the old version.

**Comment by jaruba** [comment]
official blog post about the incident: https://blog.stremio.com/opensubtitles-addon-fixed/
