### ISSUE TITLE
Subtitulos não funcionam em Google Tv. Xiaomi Mi box 2 generation

### ISSUE THREAD

**Issue by Seno1963** [Stremio/stremio-bugs#585]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Gp2mv3** [comment]
Duplicate of #583

**Comment by jaruba** [comment]
as stated, it is a duplicate, check the other issue pls
