### ISSUE TITLE
Graphical button visibility inside player

### ISSUE THREAD

**Issue by Leoxur** [Stremio/stremio-bugs#586]
![IMG_20231022_154532~2](https://github.com/Stremio/stremio-bugs/assets/9626769/c162fb18-e5ba-4955-892f-a332d87a483c)
**Describe the bug**
The Active Tab highlighting should be much more noticeable. So it's indistinguishable, the only way to understand Is to plot the audio clicks -> Moving to the last Tab on the left/right side and coming back from there.

**To Reproduce**
1. Go to 'player'
2. Click on 'stop'
3. Navigate througth tabs (ExternalPlayer/ReproducionSpeed/Scale/Subtitles/Menu)
4. It's almost impossible to distinguisg wich tabs Is actually selected

**Expected behavior**
The Active Tab highlighting should be much more noticeable. So that Is possibile tò navigate throught menu.

**Desktop (please complete the following information):**
 - OS: [e.g. FireOS]
 - Browser [e.g. Stremio App]
 - Version [e.g. 1.6.7]

**Additional context**
I was using 1.5.8 version until Yesterday, with old interface there wasn't any problem

**Comment by TRtomasz** [comment]
This is mobile app designed for mobile devices, this will not be changed. 
You can install Tv app on your device where visibility should be better.
