### ISSUE TITLE
default subtitle romanian language

### ISSUE THREAD

**Issue by mizanbalance** [Stremio/stremio-bugs#587]
Hey guys , i wanted to set for a friend default language for subtitles : Romanian , in the settings there is Limba Romana , but every movie/tv series when the playback starts , the sub does not activate mainly because the name of the subtitle language in the selection menu is actually rum , can you guys look into it/change it ? i have tested english , italiano , the same name being in both default subtitle settings and also during playback and it auto activated . but Limba Romana showing up as rum during playback does not toggle the activation . Cheers !
![rum](https://github.com/Stremio/stremio-bugs/assets/143603515/d4d0ed85-0bef-4894-bbd2-4b931ac0c680)

**Comment by TRtomasz** [comment]
These are embedded subs we do not controll their names they are like this embedded in the video file.

**Comment by mizanbalance** [comment]
In the stremio-tech-update-13 , it says it will now prioritize embedded subs , i have not seen in any movie/tv series the name Limba Romana for embedded subs , only rum , ( only in the addon sub i saw Limba Romana , but it will not load because the priority are the embedded subs ) . That is why i am asking if you could look into it and change the Limba Romana selectable in the default sub settings into rum .  or maybe add an option to select priority of the subs either embedded or from addons .
I have now tested multiple tvseries/movies from the main streaming services ( netflix , amazon , disney+, hbo ) , and all movies/tv series that have embedded subs show Limba Romana as rum .  I only ask if it is possible for you guys to replace Limba Romana from the select default subs settings , to rum .

![stream](https://github.com/Stremio/stremio-bugs/assets/143603515/55490df4-df36-43a0-9dc6-f52ca66676f8)
