### ISSUE TITLE
Subtitles not being found in some contents on the add-on v3

### ISSUE THREAD

**Issue by GuilhermeGreggio** [Stremio/stremio-bugs#589]
**Describe the bug**
After the problem with the old OpenSubtitles add-on and the substitution with the v3, i notice that the episodes of "Law and Order: Organized Crime" no longer find subtitles of open subtitles, noticed that "Ray Donovan: The Movie" has the same problem. I was watching both with subtitles on the previous version of add-on. Tested with two different accounts and the same problem appears.

I notice the problem on Android TV but i tested on Android 13 and Linux apps and both has the same problem. What is strange is that some other movies and series doesn't have this problem with the update. I check on OpenSubtitles to see if they had subtitles and it does.

**To Reproduce**
1. Go to "Ray Donovan: The Movie";
2. Click on Reproduce;
3. Scroll down to Subtitles;
4. See error where no subtitles is found.

**Expected behavior**
It should found subtitles like it was founding with the previous version of the OpenSubtitles add-on.

**Screenshots**
[image](https://github.com/Stremio/stremio-bugs/assets/104743143/c025004e-497e-4197-904d-b644ebb6e697)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.10
 - Browser: I'm using the official app from Flathub.
 - Version: 4.4.164

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: LineageOS 13
 - Browser: I'm using the official app from Play Store.
 - Version: 1.6.8

**Additional context**
I don't know how to make a more technical analyses but i would like to know how and I'm available for any tests needed.

Thanks for the amazing software!

**Comment by jaruba** [comment]
@GuilhermeGreggio we are constantly debugging the new addon and making changes, we pushed a possible fix for the missing subtitles about an hour ago, may still take a few hours for cache to expire too
