### ISSUE TITLE
Can't use Stremio (Cloudflare's captcha)

### ISSUE THREAD

**Issue by jechevarria** [Stremio/stremio-bugs#59]
Hi,

when I start stremio the message: "no stremio add on for this type. showing saved items" appears 

So I started with --development argument. This is the output:  [v3.5.13, same for v3.5.12]

<img width="1377" alt="captura de pantalla 2016-05-16 a la s 11 04 04 p m" src="https://cloud.githubusercontent.com/assets/2848007/15311059/909c60d0-1bbc-11e6-8ac6-6dc5c901385d.png">
<img width="799" alt="captura de pantalla 2016-05-16 a la s 11 04 52 p m" src="https://cloud.githubusercontent.com/assets/2848007/15311069/a449e058-1bbc-11e6-9a17-85ab09442dbc.png">

I tried reinstall the app, but it's the same output (and I'm already login).

**Comment by Ivshti** [comment]
This is very difficult to debug, as CloudFlare's security is a bit risky to disable.

The security gets triggered because someone in your ISP or with a similar IP is suspected of DDOS attacks, or because you're using stremio with tor/vpn that has been blacklisted by cloudflare

**Comment by krapgras** [comment]
https://support.cloudflare.com/hc/en-us/articles/200504045-Using-Cloudflare-with-your-API

This would be a place to start i guess, of course it depends on the plan you guys use from cloudflare. It will probably not fix the whole problem but checking the WAF could maybe mitigate a few of the problems. I'm pretty sure some of the api calls can be excluded, as i bed not all of them will create a security risk based on what your backend does.

**Comment by TRtomasz** [comment]
Closing. It hasn't happened since over a year
