### ISSUE TITLE
App problems

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#591]
1) Add contact info in the app
2) The subtitle outline needs to be fixed because they are hard to see on some backgrounds when the black background is disabled
3) Serbian subtitles often have broken letters
![Screenshot_2023-10-26-02-37-15-346_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/118081d9-8f45-440a-a507-74937d8b0f24)
![Screenshot_2023-10-26-02-37-09-105_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/36a92381-d949-4e01-a932-2d4677556ded)
![Screenshot_2023-10-26-02-34-34-536_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/b68f1340-03ea-45d3-b4a5-8eb0b6242240)
![Screenshot_2023-10-26-02-33-36-899_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/ba1fc23a-0d63-49f0-96f3-e3354c29a2be)
![Screenshot_2023-10-26-02-32-52-262_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/18640ec9-ded1-4937-b53f-b2bc72024c78)

**Comment by TRtomasz** [comment]
1. I have no idea what this is, this must be something only displayed on xiaomi devices
2.  If you want subtitles visible on different background then use black background thats why exactly it was added
3.  Which subtitles exactly this are - What movie/series/season/episode/language and subtitles variant(number on the list)

**Comment by TRtomasz** [comment]
I'm not able to reproduce subtitles issue, all characters are displayed properly. Perhaps it was temporary due to changes in the opensubtitles addon.

**Comment by GKid94** [comment]
> I'm not able to reproduce subtitles issue, all characters are displayed properly. Perhaps it was temporary due to changes in the opensubtitles addon.

It's fixed now, and the subtitles look better to me on the PC version 🙂
![Screenshot 2023-10-31 222627](https://github.com/Stremio/stremio-bugs/assets/18757054/f0e45f80-32e6-452e-991b-ba64d54958a7)

**Comment by GKid94** [comment]
@TRtomasz It would be great if you can also add official movies and series addons because Torrentio has connection problems
