### ISSUE TITLE
Android TV default player

### ISSUE THREAD

**Issue by stremioandroidplayersucks** [Stremio/stremio-bugs#592]
Bought a nvidia shield pro just incase it was the firestick that was the issue, turns out it wasn't. (I use rd+tor)

A lot of the time using stremio default players (libvlc/exoplayer) most of the time I run into playback issues error signs, lag, _**_AUDIO DELAY_**_ (especially when using rewind) , stuttering and no decent rewind/fastforward. As soon as I use vlc app as an external player not a single one of these issues occur and from what I've read most people using android streaming devices run into these issues and go external. I've tried very low files and still run into these issues especially audio delay.

I would just continue to use external apps but when they self exit due to device going to sleep or manually exiting you can not continue where you were without opening stremio selecting what you were previously watching and fast forwarding to where you were every time while also not having the opensub option either.

The player turns Stremio from a 9/10 app to a 5/10... shame.

**Comment by TRtomasz** [comment]
Please remember, one bug - one open issue. Do not put multiple issues into one report this is not possible to manage.
Regarding your issues, these are not reproducible, and you didn't provide enough details about your devices setup (TV/Speakers) to even consider what could be the reason. At this point as there are no other people reporting such issues i guess your hardware is causing this issues.
