### ISSUE TITLE
Guest Login is not saved. Critical user interface bug.

### ISSUE THREAD

**Issue by artivision** [Stremio/stremio-bugs#593]
Why i repeating Guest Login every time that i open Stremio? Happening for months now. Also why Guest Login is hidden behind mail login? Why there is an obligation for any type of login anyway, shouldn't be optional and definitely not the intro screen? Do you understand that the app have taken the wrong road? Is this on purpose and not a bug? As a seller of small factor Linux PCs, i'm obligated to remove Stremio, because i have not enough email accounts to do the job. This deserves an article.

**Comment by TRtomasz** [comment]
This is not a bug, if you want to have everything saved you should create an account.
As stremio does not require email confirmation at this moment you can use even a fake email. But you will not be able to use password reset feature then.

**Comment by artivision** [comment]
> This is not a bug, if you want to have everything saved you should create an account. As stremio does not require email confirmation at this moment you can use even a fake email. But you will not be able to use password reset feature then.

What are you talking about? Every preference or externally installed plugin i want is normally saved in Guest account, there is no problem there. The problem is that every time i start Stremio i see the Login screen again as spam. Can you make it one time decision? Example: If i choose guest login, stays there till i reset. It destroys the interface of the Computer Boxes i sell.

**Comment by TRtomasz** [comment]
This is how it was decided and we do not plan to change it.

**Comment by odomingao** [comment]
Please reconsider, as the current behavior is unobnoxious UX. If I do not want to sign up, please respect my decision and don't nag me every time..

**Comment by SmilerRyan** [comment]
I agree, and would prefer to manually sync my addons if any (I use a default install and only one addon). I wouldn't mind a banner at the top of the screen to sign up on the homepage but don't force me to click sign up, accept the terms and make a new guest account every time to access my local install.

**Comment by agenel** [comment]
bs
