### ISSUE TITLE
Trakt Scrobbling stopped working on MacOS

### ISSUE THREAD

**Issue by lolwalla** [Stremio/stremio-bugs#594]
**Describe the bug**
Shows/movies that I watch on Stremio no longer update Trakt History. Trakt integration worked fine till yesterday (30.10.23) and now has suddenly stopped working.

I have tried uninstalling re authenticating Trakt, reinstalling Stremio to no avail. 

**To Reproduce**
1. Watch any show/movie in Stremio (MacOS client)
2. Go to Trakt and view history

**Expected behavior**
Trakt history is updated based on shows/movies watched in Stremio

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by TRtomasz** [comment]
i'am not able to reproduce issue. It is working ok today, and i see trakt being synchronized yesterday. Please try to log out from trakt in stremio and reauthenticate it once again.
