### ISSUE TITLE
TV shows and movies all showing as 'Unavailable' - Now unable to login

### ISSUE THREAD

**Issue by Navarian** [Stremio/stremio-bugs#6]
As the title says really. I've posted more info and a screencap here 'https://www.reddit.com/r/Stremio/comments/3rkb2w/anybody_else_getting_this_consistently_more_info/'

And again, thanks for the awesome work :)

**Comment by Ivshti** [comment]
Hello,

Our infrastructure is under constant updating now to handle the new users.

There are going to be outages like that from time to time, for at least another week.

It's mostly resolved now ;)
