### ISSUE TITLE
Empty folders not removed from cache

### ISSUE THREAD

**Issue by middevonian** [Stremio/stremio-bugs#60]
When the cache is cleared the contents of the folders with random long fixed-length names are removed, but the empty folders remain. As the number of these empty folders increases over time, it becomes harder to locate the cache folder containing the latest downloaded content should you want to save it. The folders should be removed along with their contents, or a 'clear cache' option could be added to the settings.

**Comment by TRtomasz** [comment]
Closing this issue. We moved it to our local repository.
