### ISSUE TITLE
Lack of thumbnails in seasons 2 and up for some shows

### ISSUE THREAD

**Issue by knosuhor** [Stremio/stremio-bugs#602]
**Describe the bug**
Cinemata seems to be grabbing thumbnails from TMDB, but season number and number of episodes somewhere else (tvdb, imdb?). Thumbnails for season 1 shows fine, but season 2 and up won't load any (since those seasons do not exist on TMDB). 

**To Reproduce**
Open any show with cinemata metadata that have all its episodes grouped as one season on themoviedb.org.
I noticed it on Jujutsu Kaisen and Rent a girlfriend, probably mostly happens to anime, but some other shows might have similar problem.

Thumbnails match those on tmdb (but episode numbering don't):
https://www.themoviedb.org/tv/95479/season/1

**Expected behavior**
Thumbnail source should be same as data to prevent mismatch (if possible). 

**Screenshots**
<img width="551" alt="Zrzut ekranu 2023-11-19 230535" src="https://github.com/Stremio/stremio-bugs/assets/15619804/189d8b44-db4b-489e-ac47-3bbd55d3483e">
<img width="536" alt="Zrzut ekranu 2023-11-19 230410" src="https://github.com/Stremio/stremio-bugs/assets/15619804/363592b5-1f8b-49cc-80ab-2dd8b2c57b1a">

Happens on all platforms.

**Comment by knosuhor** [comment]
One more thing, would it be possible for Cinemeta to do it same way as this addon?
https://github.com/mrcanelas/tmdb-addon/blob/main/static/diferentOrder.json
https://github.com/mrcanelas/tmdb-addon/blob/main/lib/getEpisodes.js

**Comment by sutulustus** [comment]
Hello @TRtomasz this is indeed a bug in cinemeta v3 episode season numbering. You actually have the corrent data on cinemeta-live.

Here is an example of thumbnail missing:
https://v3-cinemeta.strem.io/meta/series/tt12343534.json
Right and Wrong - S2E18
https://episodes.metahub.space/tt12343534/2/18/w780.jpg

Here is the same episode with correct thumbnail:
https://cinemeta-live.strem.io/meta/series/tt12343534.json
Right and Wrong - S1E42
https://episodes.metahub.space/tt12343534/1/42/w780.jpg

This is same with Naruto and Naruto Shipuden
