### ISSUE TITLE
Stremioweb stuck on logo

### ISSUE THREAD

**Issue by frenesus** [Stremio/stremio-bugs#605]
**Describe the bug**
Stremioweb dont work. Stuck on logo with stremioserver open or stremio desktop app open.

**To Reproduce**
Select any midia and they wont play.

**Expected behavior**
Play the video

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/127832773/07566d80-b357-4005-9bb5-00ef55b0d004)

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome,firefox,edge

Using the torrentio addon with and without.

**Comment by TRtomasz** [comment]
Please provide more details to reproduce this, otherwise i have to assume you are trying to open a torrent stream that does not have enough seeds.

**Comment by frenesus** [comment]
The vídeo play on stremio desktop app. I use realdebrid and wont play on stremioweb, so i dont think that it is a seed problem.
If i play the video on stremioweb with the stremioserver or the stremiodesktop closed, the video play but with no sound.

**Comment by frenesus** [comment]
do i have to reopen a issue or this will be viewed?

**Comment by frenesus** [comment]
@TRtomasz

**Comment by TRtomasz** [comment]
I'v just checked and it works just fine with RD streams.  Something playing in the desktop app is not indicator that it should play too in the web app as they are two separate products. Please check in the settings if streaming server is detected. Also if you have multiple users using same debrid account it could be limited to only one ip address.

**Comment by frenesus** [comment]
i think i giving up
stremio-server always on, but sometimes don't play the video, sometimes don't play the audio, sometimes give me a error that the stream is not supported, with realdebrid or without
