### ISSUE TITLE
You can't add external subtitles

### ISSUE THREAD

**Issue by Myliak** [Stremio/stremio-bugs#608]
**Describe the bug**
Based on official documentation (https://stremio.zendesk.com/hc/en-us/articles/360021228152-External-Subtitles) you can add external subtitles by drag and drop the subtitle file on player window, but it's not working. I am playing/streaming from local file.

**To Reproduce**
1. Play a movie/video/series supporting subtitles
2. Get any .srt file for a test
3. Try to drag and drop the file into video player window
4. It's not working, looks like it's not supported (you see red "can't drop here" icon on cursor)

**Expected behavior**
It should import and use the srt file for the currently playing video

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Desktop Application
 - Version:
![image](https://github.com/Stremio/stremio-bugs/assets/45968109/604fea84-737f-4d8e-bb5e-2c2ccfa91afc)

**Comment by TRtomasz** [comment]
They must in srt format and encoded in utf8, it works just fine.

**Comment by Myliak** [comment]
What the hell, that's really strange. Something must have been wrong on my side, today it's working perfectly, might be after PC restart. Sorry for invalid bug report.
