### ISSUE TITLE
(Stremio Android TV) Wrong channel order for OPUS 5.1 / 7.1 audio tracks

### ISSUE THREAD

**Issue by johnmolina** [Stremio/stremio-bugs#613]
**Describe the bug**
There is a bug in Android that causes a wrong channel order for OPUS 5.1 or 7.1 multichannel audio playback in ExoPlayer with Android platform decoders.

Its very obvious once you know about it because it switches the center channel with the right channel, so all the dialogue now comes from the right instead of the center. The LFE channel also switches places with one of the side/back surround channels.

This also affects devices with just two speakers because the down-mix to stereo uses the same wrong channel order.

Check out this thread for more info: https://github.com/google/ExoPlayer/issues/8396

It seems the only way to fix this bug is:
- Google fixes the bug in Android itself <- lol
or
- Apps have to use ExoPlayer extensions like ffmpeg to decode OPUS multichannel audio

For Stremio it seems that the Android Mobile version already uses an ExoPlayer extension for OPUS since it is not affected by this bug. But the Android TV version is affected by this bug.

I hope Stremio Android TV can switch to an ExoPlayer extension like ffmpeg with libopus decode for OPUS multichannel audio so the channels play back correctly.

**To Reproduce**
1. Install Stremio Android TV on any Android device.
4. Try to playback a file with OPUS 5.1 or 7.1 audio tracks.
5. Channel order is wrong, audio channels are switched around. All dialogue is played back from the right speaker instead of center.

**Expected behavior**
Stremio Android TV should play back OPUS multichannel audio with the correct channel order like Stremio Android Mobile version.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Devices: Amazon Fire Stick 4K Max (1st GEN), Samsung Galaxy S23, Samsung Galaxy Tab S9
 - OS: Android 10-13
 - App: Stremio TV 1.6.4 ARM / ARM64
 - Player: Integrated ExoPlayer

**Additional context**
N/A

**Comment by johnmolina** [comment]
@TRtomasz Your comment is not really helpful.

Yes, using ExoPlayer without hardware acceleration or switching to libVLC in Stremio AndroidTV will result in the correct channel order for multichannel OPUS audio since both options no longer use the bugged Android platform OPUS audio decoders.

BUT both options are unable to properly play back 4K AV1 and 4K AV1 HDR video. Some other video formats struggle as well and you only get a video slideshow or a black screen.

Most of the files that use OPUS multichannel audio also use advanced video codecs like HEVC or AV1.

This bug can only be fixed without affecting video decoding with an override to use ffmpeg for multichannel OPUS audio tracks while keeping hardware acceleration for the video tracks in ExoPlayer.


Btw i assumed in my Issue that Stremio Android Mobile is not affected because it already uses ExoPlayer + ffmpeg extension. It seems this is wrong and the real reason is that it uses libVLC.

**Comment by TRtomasz** [comment]
I dont think we will focus on making a workaround since this is is not very popular audio format. IT should get fixed in exo, you can switch player to LibVlc on your TV in stremio settings.

**Comment by johnmolina** [comment]
@TRtomasz There will be a fix for this bug in the next Media3 / ExoPlayer bugfix and minor release. Please update Stremio Android TV when this becomes available.

https://github.com/google/ExoPlayer/issues/8396#issuecomment-1840539915

https://github.com/androidx/media/commit/b1541b096f9dc4d1f9ca71b6743c836f6bd4de89

**Comment by johnmolina** [comment]
@TRtomasz A fix for this bug has been released with Androidx Media3 1.2.1. I hope you can update Stremio AndroidTV.

https://github.com/androidx/media/blob/release/RELEASENOTES.md
