### ISSUE TITLE
Default subtitle Limba Romana - rum 

### ISSUE THREAD

**Issue by mizanbalance** [Stremio/stremio-bugs#615]
![rum](https://user-images.githubusercontent.com/143603515/286030781-109a6bef-ab83-47b5-b18a-d889e76692da.png)

Trying to help my dad so he can watch shows/movies without the need to open and select sub every movie/episode . 
English works peachy .

In the stremio-tech-update-13 , it says it will now prioritize embedded subs , i have not seen in any movie/tv series the name Limba Romana for embedded subs , only rum , ( only in the addon sub i saw Limba Romana , but it will not load because the priority are the embedded subs ) . That is why i am asking if you could look into it and change the Limba Romana selectable in the default sub settings into rum .  or maybe add an option to select priority of the subs either embedded or from addons . 

I have now tested multiple tvseries/movies from the main streaming services ( netflix , amazon , disney+, hbo ) , and all movies/tv series that have embedded subs show Limba Romana as rum .  I only ask if it is possible for you guys to replace Limba Romana from the select default subs settings , to rum .

![stream](https://github.com/Stremio/stremio-bugs/assets/143603515/55490df4-df36-43a0-9dc6-f52ca66676f8)

_Originally posted by @mizanbalance in https://github.com/Stremio/stremio-bugs/issues/587#issuecomment-1775411468_

**Comment by TRtomasz** [comment]
auto select subtitles does not work with embedded subs, we have an issue open for this already so i will close this one
