### ISSUE TITLE
Stremio app/Samsung

### ISSUE THREAD

**Issue by Robertc125** [Stremio/stremio-bugs#619]
**Describe the bug**
So,I have Stremio on my  Firestick/Samsung tv and android phone and I have all addons installed 
The problems:
1.For The Samsung tv app is laggy and have moments when give me Unknown error at torrents when load and when I select to automate select a subtitle it doesnt,and for me I cant see Romanian subtitles just "limba romana" and I want to have both of them (Romanian and limba romana)
2. The subtitles are not the same idk how,I have some subtitles on my phone that are fit perfect but on tv is not and I tried all (Romanian/limba romana subtitles) and yes apparently are 2 different things from subtitles addons

**Comment by jaruba** [comment]
> For The Samsung tv app is laggy

You can change the theme to "default" and disable the animations in the app settings to improve the app performance, what exact model is your Samsung TV?
