### ISSUE TITLE
Hide adult addons

### ISSUE THREAD

**Issue by kiwec** [Stremio/stremio-bugs#621]
Clicking on the addons button shows you the community addons section, the first of which is a hentai website addon. Not very slick, especially if you want to use stremio with family.

18+ addons should be hidden behind a toggle in account settings.

The addons list is small enough one could go over it and manually select the ones to filter out; no need for something complex.

**Comment by megadrive** [comment]
👍 

I back this as well.

**Comment by TRtomasz** [comment]
Stremio currently does not have any adult proection and for now we do not plan to add it.
