### ISSUE TITLE
Subtitles not loading on Samsung

### ISSUE THREAD

**Issue by LuccaPrado** [Stremio/stremio-bugs#622]
**Describe the bug**
The multi sub embedded torrents are not showing all subs on Samsung app (Model The frame 2022), while the phone app on same torrent shows. 
Tested on different torrents and the Brazilian Portuguese Subtitles failed to appear everytime.

**To Reproduce**
1. Go to an multi embedded subs torrent
2. Open subtitles
3. See that there isn't all subs that you would see on mobile.

**Expected behavior**
Subtitle options not showing all embedded subtitle options.

**Tv(please complete the following information):**
 - Device: Samsung The frame 2022

**Comment by TRtomasz** [comment]
Emedded br-pt subs will be moste likely under PT language since they usually are marked as Portuguese in the track
