### ISSUE TITLE
Library only displays some movies

### ISSUE THREAD

**Issue by dms89** [Stremio/stremio-bugs#63]
I'm on a MacBook Pro running OS X Yosemite 10.10.5, and Stremio 3.5.12.

Ever since I started using Stremio, I have been unable to display the series in my library. There is no button or anything of the sort to switch from a movies view in the library to a series view. This is all I see.
<img width="1240" alt="screen shot 2016-05-27 at 12 00 17 am" src="https://cloud.githubusercontent.com/assets/19594380/15581273/2d817b0e-239e-11e6-9e65-3ffcb17a8dd4.png">

How do I display the series in my library? Or is there a problem with my software? I've tried reinstalling several times, but to no avail.

**Comment by Ivshti** [comment]
This can be DB corruption

First, make sure you're logged into an account (not guest) so that you can restore your Library 

Then do this:
rm -rf ~/"Library/Application Support/stremio"

Then re-login after starting stremio again
