### ISSUE TITLE
The player keeps displaying ERROR_CODE_IO_UNSPECIFIED when streaming content

### ISSUE THREAD

**Issue by AleksaMCode** [Stremio/stremio-bugs#630]
**Describe the bug**
While streaming content, at random time video and audio stops while displaying at the middle of the screen **Stremur** holding power cords and below the cat **ERROR_CODE_IO_UNSPECIFIED** text is displayed (there is screenshot below). After a few seconds, video resumes and it keeps cycling between frozen and unfrozen states while the cat and the message stays present on the screen. To resolve the problem, I would stop the stream and choose another source for the video (video with x264 codec).

**To Reproduce**
1. Go to Stremio,
2. Click on a show a want to watch.
3. Play a new episode of the show.
4. See the error after *x* seconds.

This has only happened so far when playing videos with x265 codec, but not all of them.

**Expected behavior**
To stop the stream and display a descriptive message what the problem is, because the **ERROR_CODE_IO_UNSPECIFIED** means nothing to the end user.

**Screenshots**
![stremio-error](https://github.com/Stremio/stremio-bugs/assets/23129943/3a052f1b-5baa-4b4a-ab75-09738cb5d1a5)

**Android TV Box:**
- Device: Xiaomi Mi TV Box S (MIBOX 4 version 9)
 - OS: MIUI (Kernel: 4.9.113)
 - Stremio: Android app
 - Version: 1.6.4

**Additional context**
I found [this](https://www.reddit.com/r/Stremio/comments/wpw8pk/error_code_io_unspecified/) Reddit post where someone referenced the same problem.

**Comment by TRtomasz** [comment]
We do not controll error codes they come from the video player made by google called exo/media3
