### ISSUE TITLE
Stremio does not find my paramount plus app.

### ISSUE THREAD

**Issue by SRG123456** [Stremio/stremio-bugs#631]
Installed on google tv.  When trying to open a series or movie and selecting Paramount plus HD as the provider, Stremio fails to acknowledge that the program is there.  it specifically says "You don't have an app that can do this".    I do have the app, it is installed and runs fine when I use it stand-alone.      Stremio will open paramount plus if I select it with PRIME, but my subscription with paramount is not with Prime.

**Comment by TRtomasz** [comment]
These are not apps deep link they are http link and these can be only opened in a web browser which you dont have installed

**Comment by SRG123456** [comment]
But if that was the case, why does it open when I use it without Stremio?
