### ISSUE TITLE
Links not loading

### ISSUE THREAD

**Issue by Killroy0700** [Stremio/stremio-bugs#633]
After last app's update all movies in my library could not loading RealDebrid links. Loading only via main page of app or via search option.

Im using Android Box Android 11 core ver. 5.4.180-ab4674 and Stremio App ver. 1.6.6

**Comment by TRtomasz** [comment]
Please update to 1.6.7 should be fixed now

**Comment by Killroy0700** [comment]
Everything works with 1.6.7 version. THX
