### ISSUE TITLE
Stremio crashing + ucrtbase.dll

### ISSUE THREAD

**Issue by danielmaiahist** [Stremio/stremio-bugs#634]
**Describe the bug**
Stremio crashes while loading any file/movie/series

**To Reproduce**
1. Open Stremio, Choose any file/movie/series/episode
2. Click on Play (Maybe it starts loading, but doesn't complete)
3. Crash

**Expected behavior**
Load the file/movie/series as normally would

**Desktop**
 - OS: Windows 11 23H2 build 22631.2787
 - Stremio Version: 4.4.164/4.4.165

**Tested on Android Smartphone**
 - Device: Samsung A71
 - Status: No Problem

**Additional context**
Windows Event Log Viewer shows error with UCRTBASE.dll. Details attached on file
[stremio_ucrtbase_error.txt](https://github.com/Stremio/stremio-bugs/files/13768018/stremio_ucrtbase_error.txt)

**Comment by danielmaiahist** [comment]
Version **4.4.142** was tested, and this issue is **NOT** present.

**Comment by TomBonnot** [comment]
I have the same error, 
I don't know where to find the Stremio's Logs, but at least the Event Viewer is showing me the same error. It's kind of disturbing
I've already tried to remove and install again Stremio (Removed completely with BCU)

**Comment by TRtomasz** [comment]
you could try the following https://forums.flightsimulator.com/t/how-to-troubleshoot-faulting-module-ucrtbase-dll-and-or-exception-code-0xc0000005-crashes/591670 and let us know if any of these helped
