### ISSUE TITLE
Cinemeta makes streams on other add-ons disapear

### ISSUE THREAD

**Issue by asolvang** [Stremio/stremio-bugs#64]
Stremas in all add-ons works when Stremio is started, while watching first episode/movie/ect. cinemeta is started (notification pops up) and then no new streams are available.

**Comment by Ivshti** [comment]
any update on that? does it persist?

**Comment by asolvang** [comment]
Hi. 

 

No I believe it does not. 

Have not noticed it the last couple of days. 

 

Thank you

 


Med vennlig hilsen

 

Anders Solvang

Business Developer







——————————————————

// 9711 5421 // www.gendiet.no <http://www.gendiet.no>  //

——————————————————

 

Fra: Ivo Georgiev [mailto:notifications@github.com] 
Sendt: tirsdag 31. mai 2016 21.54
Til: Stremio/stremio-bugs <stremio-bugs@noreply.github.com>
Kopi: asolvang <anders@gendiet.no>; Author <author@noreply.github.com>
Emne: Re: [Stremio/stremio-bugs] Cinemeta makes streams on other add-ons disapear (#64)

 

any update on that? does it persist?
