### ISSUE TITLE
Problem with embedded subtitles

### ISSUE THREAD

**Issue by ofek087** [Stremio/stremio-bugs#643]
Hello,I set my default language to Hebrew and whenever I’m watching a show which have embedded subtitles it loads by default English subtitles instead of what I’ve set as default in settings. This problem doesn’t seem to appear when the subtitles are from an addon and not embedded. Also I’ve noticed that this problem only exists on the androird tv version. I’ve checked on my laptop and it’s working well.
--

**Comment by TRtomasz** [comment]
closing as a duplicate
