### ISSUE TITLE
After removing show from continue watching in Android doesn't reflect in Stremio App on mac

### ISSUE THREAD

**Issue by riyad1989** [Stremio/stremio-bugs#647]
**Describe the bug**
If you try to remove a movie/series in the (Continue Watching) section from Android App, it doesn't reflect on Mac App and still you can find them there and you need to remove them using the Stremio App on Mac, unless if you start removing from Mac App it will be removed also from Android App.

**To Reproduce**
1. Go to Android Mobile App in ' Continue Watching Section '
2. Click on ' The 3 dots right below the show then dismiss '
3. Go to Stremio App on Mac you will find the show still there.

**Expected behavior**
If you are logged in Stremio App from any platform, you should be able to remove any of the shows on Contuine Watching section and it has to reflect on your account on any platform, meaning to be removed from other App on other platforms.

**Screenshots**
1- In Android App showing the movie that wanted to be dismissed from the continue watching section ...
![1](https://github.com/Stremio/stremio-bugs/assets/155687797/cdc5f0b6-6cd6-45b8-bbef-7cb403035e4f)

2- In Android App showing that the movie is already dismissed ...
![2](https://github.com/Stremio/stremio-bugs/assets/155687797/71741896-6227-4223-92e4-d3be03b270f9)

3- In Mac App the same movie still there ...
<img width="1343" alt="Screenshot 2024-01-05 at 2 50 07 AM" src="https://github.com/Stremio/stremio-bugs/assets/155687797/76099c4d-fbea-48e6-b42e-d3ef3fbba02d">

**Mac Laptop**
 - MacOS version: Ventura 13.5.1
 - Stremio App version: 4.4.165

**Smartphone**
 - Device: [Xiaomi POCO X4 Pro 5G]
 - OS: [MIUI 14.0.3]
 - Stremio Android App version: 1.6.9

**Comment by TRtomasz** [comment]
You have to reset your desktop app otherwise it will not be refreshed
