### ISSUE TITLE
Search text crash while dragging

### ISSUE THREAD

**Issue by n4rwal0** [Stremio/stremio-bugs#649]
**Describe the bug**
The desktop app crashes after dragging the text in search bar.

**To Reproduce**
1. Go to Search Bar
2. Type the text
3. Select and drag the text away 
4. App freezes for 5s second and then close itself

**Expected behavior**
I should be able to drag text from search bar to paste it maybe elsewhere, in a browser ec..

**Screenshots**
![stremio_NMVl9UGug7](https://github.com/Stremio/stremio-bugs/assets/55855634/6d00c8d8-19c2-427d-80ca-1be71b352b34)

**Desktop:**
 - OS: Win 11 64 bit
 - Browser Streamio app
 - Version 4.4.165

**Comment by TRtomasz** [comment]
If you want to copy text you could use well known shortcuts like ctrl+c and ctrl + v
