### ISSUE TITLE
Episodes not displaying or missing

### ISSUE THREAD

**Issue by amancke** [Stremio/stremio-bugs#65]
**STR:**
1. Open Stremio
2. Go to your Library (can be directly from Discover)
3. Open any Series page 
4. Observe

**ER:** All episodes should be displayed for you to select
**CR:** Nothing on the right side panel and SUB4SUB4SUB4SUB4SUB4SUB4SUB4.... on SUMMARY

**OS:** OS X El Capitan 10.11.6 Beta (15G7b)
![screenshot 2016-05-26 19 45 00](https://cloud.githubusercontent.com/assets/6270795/15592490/a00f8112-237a-11e6-9bd6-5ec108b4cb50.png)
![screenshot 2016-05-26 19 46 32](https://cloud.githubusercontent.com/assets/6270795/15592491/a032f20a-237a-11e6-9507-38a28df54fef.png)

**Comment by Ivshti** [comment]
Can you try updating to the latest version? This seems like a bug which was fixed in 3.6.0
