### ISSUE TITLE
Samsung TV: Crash when new episode return empty data (Null)

### ISSUE THREAD

**Issue by SubEdict** [Stremio/stremio-bugs#650]
**Describe the bug**
Stremio freezes/stops responding if a show/season/episode missing data (total blank, not even 01. TBA).

**To Reproduce**
A new poster shows up for a series that I know starting a new session/episode. 
After one click on the poster to get into the series info, I see it's blank and the season's selector shows "..." instead of numbers.
From this point, Stremio stops responding and needs the "Kill-App" (Hold 3 seconds on the remote return button) to exit back the TV.

**Expected behavior**
On blank empty-info (Null) don't crash and let the user click return. :)

**Screenshots**
[Very similar to this one](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2F8j8muvh28cf61.png%3Fwidth%3D1914%26format%3Dpng%26auto%3Dwebp%26s%3D273a9ef5ef28cc859e7361e886284ade14c28f5f)

- OS: Tizen
- Samsung TV: UE43TU7100, Q95T.
- Stremio Version 1.0.1

**Comment by TRtomasz** [comment]
Closing for no if this is still present please let me know in the commebt, it was most likely fiexed already
