### ISSUE TITLE
Failed to play some streams in Android and Web Client

### ISSUE THREAD

**Issue by mhdzumair** [Stremio/stremio-bugs#651]
**Describe the bug**
Stremio failed to play **some stream** links in Android and Web Player. The links are working in Stremio Android TV client. Mac & linux clients. 

**To Reproduce**
1. Go to [MediaFusion Confgure page](https://882b9915d0fe-mediafusion.baby-beamup.club/configure)
2. Select 'seedr' from Streaming Provider. Click "Authorize with Seedr" to authenticate with your seedr account. If not, create an account. Its free service. (Also note that I'm not promoting my referral link. Just create Seedr account from google)
3. All the catagories are selected by default so just scroll down and click on the "Install Addon"
4. Now open the streamio in above mention clients. Open any movies and play a stream. 
5. It will download into seedr, and it will redirect the URL into Video URL. 

**Expected behavior**
Video should be playable without any issues in all Streamio client. The other stream providers like PikPak (Free), Real-Debrid are working fine in all clients.

**Screenshots**

**Android Client:**
 - Device: Samsung S22U
 - OS: Android 14
 - Version: 1.6.9
 
![Screenshot_20240110_151053_Stremio](https://github.com/Stremio/stremio-bugs/assets/44891939/59734f25-64bb-4c7c-9200-493caea7079d)

**Web Client:**
 - OS: MacOS
 - Browser: Firefox
 - Version: 
    - APP Version: 5.0.0-beta.4
    - Server Version: 4.20.3
  
![image](https://github.com/Stremio/stremio-bugs/assets/44891939/93094c09-3e2d-45b2-a9c9-da4a58879385)

**Additional context**

**Debug Logs in Android Client**
> Note that i removed the userdata path from below URLs but the redirect URL of seedr is actual URL.

Logs are added in https://pastebin.com/vehXdQpv

**Debug Logs in Web Client stremio server**
> Note that i removed the userdata path from below URL
```
-> GET /hlsv2/cec657e4109c2e34bd95cb581d2bf5da/video0.m3u8?mediaURL=https%3A%2F%2F882b9915d0fe-mediafusion.baby-beamup.club%2Fstreaming_provider%3Finfo_hash%3Db669533d63be84a68f482dae5966d0e3ea86de59&maxAudioChannels=2&videoCodecs=h264&videoCodecs=vp9&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus 
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at Socket.onclose (internal/streams/end-of-stream.js:121:38)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Pipe.<anonymous> (net.js:673:12) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
hls-converter cec657e4109c2e34bd95cb581d2bf5da is inactive, destroying it
hls-converter cec657e4109c2e34bd95cb581d2bf5da destoyed
```

**Comment by Learner00100** [comment]
In Samsung tv app also, it working.
Playback fails in Android mobile client alone.

**Comment by Learner00100** [comment]
In Android mobile apk 1.5.9, it's working.
But recent apk release it give error, don't know from exactly which version it breaks

**Comment by TRtomasz** [comment]
as you can see in the logs this issue isn't caused by stremio `01-10 12:37:15.517  8426 15371 E VLC     : [b400007ca72cfc20/3c0b] libvlc stream: HTTP 307 error`  Vlc cant get the stream.

**Comment by mhdzumair** [comment]
@TRtomasz  307 is Temporary redirect.  Why isn't redirecting to the location URL?

**Comment by mhdzumair** [comment]
On additional note: 
The stream is working in mobile application when running on external player as vlc. So its not directly issue with vlc. I have provided you as much as information i got. @TRtomasz please reopen the issue.

**Comment by mhdzumair** [comment]
@TRtomasz the reason for failing is because of the URL character contains '[]'. Renaming the file in seedr.cc and getting the link is fixing the issue in streamio Android client. So this is an issue in stremio android player. Please re-open the issue. 

Sample URLs:

![image](https://github.com/Stremio/stremio-bugs/assets/44891939/76e092df-ee79-4db1-98f3-d8021ba6216f)

Working link in Android client without '[]' character: https://nw20.seedr.cc/ff_get/1691768020/www.1TamilMV.im%20-%20The%20Three%20Musketeers%20-%20Part%20II%20Milady%20(2023)TamilFan%20Dub-%20HDCAM-Rip%20-%20720p%20-%20x264%20-%20AAC%20-%201GB.mkv?st=eGX1OVl6C9nkwkilPpuvvg&e=1705502984

Not working link in Android client: https://nw20.seedr.cc/ff_get/1692228376/www.1TamilMV.im%20-%20The%20Three%20Musketeers%20-%20Part%20II%20Milady%20(2023)_Tamil_[Fan%20Dub]_-%20HDCAM-Rip%20-%20720p%20-%20x264%20-%20AAC%20-%201GB.mkv?st=fi-GTDj1co1n0ZGzoeVqYA&e=1705503130

Both links are working in browser to download. (Not sure about link validity. let me know if the link is not working when you test.)
