### ISSUE TITLE
Server not working when I try to play anything

### ISSUE THREAD

**Issue by otDan** [Stremio/stremio-bugs#652]
**Describe the bug**

```
Stremio streaming server has thrown an error
QProcess::ProcessError code: 1

(node:42040) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use stremio-runtime --trace-deprecation ... to show where the warning was created)
C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:36012
var code = error ? 500 : 200, body = JSON.stringify({
^

TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Object'
--- property 'issuerCertificate' closes the circle
at JSON.stringify ()
at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:36012:59
at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:27013:52
at C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:59684:29
at ClientRequest. (C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:27580:25)
at ClientRequest.f (C:\Users\otDan\AppData\Local\Programs\LNV\Stremio-4\server.js:6431:70)
at ClientRequest.emit (events.js:315:20)
at ClientRequest.EventEmitter.emit (domain.js:486:12)
at TLSSocket.socketErrorListener (_http_client.js:469:9)
at TLSSocket.emit (events.js:315:20)
at TLSSocket.EventEmitter.emit (domain.js:486:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**To Reproduce**
1. Host a streaming server
2. Any time someone tries to play something with that streaming server it throws this error

**Expected behavior**
Play videos using the streaming server

**Desktop and Smartphone:**
 - OS: Windows, iOS
 - Browser Chrome, Brave, Safari (Tried all I had mobile and desktop)
 
**Additional context**
I only managed to play an episode of a show once, after that I could not get the streaming server to work once...

**Comment by otDan** [comment]
> @otDan which exact stream have you tried?

@TRtomasz are you asking which source? not exactly sure what you are asking, if you are asking about how I am hosting the streaming server enabling the https I get:
![image](https://github.com/Stremio/stremio-bugs/assets/59731738/93f8ac47-2d98-4143-b876-1ba65e90651d)
 so I am just using the local streaming server and connecting to it with my ip, the ports are also open, not sure what else I have to do since it worked once and I have not touched anything to make it stop working

**Comment by TRtomasz** [comment]
disable https endoint in the settings if getting the certificate is failing
and yes stream is the source you choose from the long list that appears on the right side of the app.
