### ISSUE TITLE
No Dolby Atmos signal (stremio 1.6.7)

### ISSUE THREAD

**Issue by Tasoik** [Stremio/stremio-bugs#653]
Hello, I'm using these equipment:
Media player: Fire TV 4K max (with the latest firmware)
AV receiver: Marantz preamp 7704
Projector: Epson 9300
settings Fire Tv :  audio -> best available. Auto frame rate : ON.
settings stremio (1.6.7) exoplayer.  Frame rate and resolution: ON.

When the track is Dolby Atmos, I ALWAYS get a signal Dolby Digital+  instead of Dolby Atmos.
I tried external players (kodi, vlc, just player) with the same results.

From other streaming services (Netflix/Disney+) I get Dolby Atmos just fine. 

Any idea what might be wrong?

**Comment by TRtomasz** [comment]
Please enable tunneled playback in the settings

**Comment by Tasoik** [comment]
I tried and I get a loud buzzer from my speakers.

Στις Παρ 12 Ιαν 2024, 12:54 ο χρήστης Tomasz ***@***.***>
έγραψε:

**Comment by Tasoik** [comment]
Why did you close the issue? The issue has not been resolved!

**Comment by TRtomasz** [comment]
This is basically only one setting that is in stremio to controll this. Looks like an issue with your receiver or its configuration
