### ISSUE TITLE
Serbian subtitles out of sync

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#658]
**Describe the bug**
The Serbian subtitles are out of sync on movies and series

**To Reproduce**
1. Open a movie or a TV show
2. Select the Serbian subtitle and watch

**Expected behavior**
For the Serbian subtitles to be in sync with the movies and shows

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave browser
 - Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone (please complete the following information):**
 - Device: Redmi 9 
 - OS: Android 12, MIUI 13
 - Browser Brave browser
 - Version 1.61.116

**Additional context**
/
![Screenshot 2024-01-15 022921](https://github.com/Stremio/stremio-bugs/assets/18757054/c310947e-c223-4bac-af6a-588498b31737)
![Screenshot 2024-01-15 022940](https://github.com/Stremio/stremio-bugs/assets/18757054/25674921-2c3d-40ef-bc69-2b6ec58ff6ea)
![Screenshot 2024-01-15 023010](https://github.com/Stremio/stremio-bugs/assets/18757054/124a8988-7fc0-4674-9338-0dc8adf90094)

**Comment by TRtomasz** [comment]
We do  not controll subtitles, you can use adjust timing option, or perhaps select different stream that will be in sync with subtitles.

**Comment by GKid94** [comment]
> We do not controll subtitles, you can use adjust timing option, or perhaps select different stream that will be in sync with subtitles.

Then who manages the Open Subtitles addon? It says that it's a official Stremio addon?

**Comment by TRtomasz** [comment]
We manage addon, we do not manage subtitles as they come from opensubtitles.

**Comment by GKid94** [comment]
> We manage addon, we do not manage subtitles as they come from opensubtitles.

Can you check and update the addon?

**Comment by TRtomasz** [comment]
@GKid94 as i wrote, we do not controll subtitles they come from opensubtitles.

**Comment by GKid94** [comment]
> @GKid94 as i wrote, we do not controll subtitles they come from opensubtitles.

They work when I download them and play them in VLC but in Stremio they don't work
