### ISSUE TITLE
White lines on right and bottom edges

### ISSUE THREAD

**Issue by Suor** [Stremio/stremio-bugs#66]
I use Strem.io with Ubuntu 16.04 and it has white lines on right and bottom edges. They show up both in window and fullscreen mode, the last one being the most annoying.

**Comment by Ivshti** [comment]
can you please upload screenshots?

**Comment by Darkin47** [comment]
I confirm this bug. Here is a screenshot: http://puu.sh/pdeDm/dd209be929.png

**Comment by VoyTechnology** [comment]
Confirmed. I have the same issue.
