### ISSUE TITLE
When I start Stremio, I encounter the following error (please refer to the attached image): 'The execution of code cannot continue because Qt5Core.dll is not found. This problem can be resolved by reinstalling the program.'

### ISSUE THREAD

**Issue by knnb1** [Stremio/stremio-bugs#663]
PC - When I start Stremio, I encounter the following error (please refer to the attached image): 'The execution of code cannot continue because Qt5Core.dll is not found. This problem can be resolved by reinstalling the program.'

I have attempted the following solutions, but none of them have worked:

I uninstalled and reinstalled both the latest version of Stremio and the previous version, ensuring that all remaining files and folders from the previous installation were deleted.
I downloaded the latest version of Qt5Core and placed the file in the system32 directory for 64-bit systems. I then restarted and/or powered off the PC.
I updated my drivers.
I updated to the latest version of DirectX.
I added an exception in the antivirus software.
I tested whether it worked by disabling the antivirus (but it still didn't work).
I ran Stremio as an Administrator.
Also https://stremio.zendesk.com/hc/en-us/articles/360019465820-How-to-remove-stremio-manually-on-Windows
Downloaded and installed the latest Visual C++ Redistributable Packages for Visual Studio from the official Microsoft website
Also followed below steps:
 -   Open Command Prompt as Administrator.
 -  Type sfc /scannow and press Enter.
 -   Wait for the process to complete and then restart your computer.

 
Despite trying all of these steps, the error continues to persist

**To Reproduce**
whenever I try to open the program

**Screenshots**
![Error](https://github.com/Stremio/stremio-bugs/assets/157022257/e7e2e2c9-e562-4277-b8f8-17d4be53592e)
![Captura de pantalla 2024-01-11 135335](https://github.com/Stremio/stremio-bugs/assets/157022257/3da20045-1dec-427e-9f96-70813c51d26c)

**Desktop:**
 - OS: Windows 11
 - Browser: Mozilla
 - Version: 121.0.1  64-Bit

**Comment by TRtomasz** [comment]
this file gets installed with stremio, and if it is not present in Stremio installation folder than most likely something on your PC is causing this, could be some kind antivirus or antimalware software doing it for no reason as this file is comming from standard and well known QT framework. Could be also some malware modifying files after installation. There is no point in downloading and placing QTCore.dll from random places on the internet as it could cause more harm. This file gets installed in following directory `AppData\Local\Programs\LNV\Stremio-4`

**Comment by knnb1** [comment]
Hello Tomasz!

Thank you for the quick response. I'd like to add a bit more information,
which I think makes it even stranger.

I switched to a laptop that came freshly formatted. The first day of use,
Stremio was working correctly, but from the second day onwards, it stopped
working.

Regarding the antivirus, when I disable it, it still doesn't work. Is that
enough to know if the antivirus is the problem? I've also run a scan to see
if I've been infected, and it says I haven't.

I'm attaching a screenshot of QT in Stremio-4 in case it helps.
[image: QT.png]

By the way, do you know why the thread no longer appears on the forum?

[image: imagen.png]

Thank you very much for your assistance!

**Comment by TRtomasz** [comment]
sorry, images are not visible, not sure how you added them. Also what forum do you mean?

**Comment by knnb1** [comment]
Hello Tomasz!

Ah! Sorry about the images, I just dropped them in the email. I have now
attached one, and for the other (the forum issue), I'll send you the link
where it was before and now it's gone:
https://github.com/Stremio/stremio-bugs/issues

Thank you very much for your assistance!

**Comment by TRtomasz** [comment]
Sorry email attachments are not visible here you should do it directly from the github UI
