### ISSUE TITLE
HTTP streaming server not connecting to iOS webapp

### ISSUE THREAD

**Issue by sirensongss** [Stremio/stremio-bugs#669]
When starting the streaming server via the desktop app, iOS's webapp via safari or firefox can't connect to the server. 

1. Launch Stremio on windows 10 or macOS
2. Open settings
3. Scroll down to streaming
4. copy streaming server URL
5. paste into streaming settings on iOS webapp

**Expected behavior**
iOS app shows confirmation of connection,

**Screenshots**
<img width="375" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/91817275/8281f0b0-7efe-4b6d-a91e-ff7a26a5e122">
<img width="1428" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/91817275/9d3b58c3-bbed-4735-911b-a98709c93ef7">

**Desktop (please complete the following information):**
 - Windows 10, macOS
 - Browser firefox
 - Version 4.4.171

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020, iPad Mini
 - OS: 17.2.1
 - Browser safari
 - Version 5.0.0-beta 4

**Comment by daaf85** [comment]
<img width="458" alt="Scherm­afbeelding 2025-01-05 om 21 32 14" src="https://github.com/user-attachments/assets/736d4c51-414f-4c51-9e49-561cbc1bf226" />

having the same issue in mij iOS webbrowser, see screenshot above. Who does have a solution for this?
