### ISSUE TITLE
Channels and TV channels in Board only partially implemented in v. 3.6.0

### ISSUE THREAD

**Issue by middevonian** [Stremio/stremio-bugs#67]
Clicking on any content item in Channels or TV channels in Board shows the Batman v Superman movie every time, with the play button enabled for TV channel items but not for Channel items.

Also, I can't find a way to disable channels and TV channels in Board: de-selecting YouTube, Guidebox and Filmon.tv in Settings disables these channels in Discover but not in Board.

OS: Windows 10, 64 bit.

**Comment by Ivshti** [comment]
This is a bug, it's not expected behaviour / impartial implementation. 

It doesn't usually work that way, so possible reasons can be
1) corrupt DB
2) losing connection to channels add-ons

Try re-installing from scratch perhaps, if you have an account so you can restore library

**Comment by middevonian** [comment]
Thanks for your reply Ivshti. Your point 2) has lead me to understand the issue: what I'm seeing happens because I've deselected YouTube, Guidebox and Filmon.tv in the settings. When I reselect these, the channels in Board work correctly. The bug is that when these official Add-ons are deselected, the channels should disappear from Board as well as in Discover.

**Comment by Ivshti** [comment]
Right. That makes total sense.

We will fix that board thing in the next release, should be easy to fix
