### ISSUE TITLE
Consistent Crashes on Android TV with Stremio 1.6.7 During 4K and 1080p Playback

### ISSUE THREAD

**Issue by gyCfjSnO** [Stremio/stremio-bugs#673]
**Describe the bug**
When playing media (both 4K and 1080p) on the Stremio app, the app either crashes immediately, returning to the Android TV home screen, or plays for 1-2 minutes before the audio and picture begin to lag, followed by a crash.

**To Reproduce**
1. Open the Stremio app on either the Sony KD-65X9500H or Xiaomi TV Box S (2nd Gen).
2. Select and play any media (tried with various shows/movies).
3. Observe one of two issues:
   - The app attempts to load the media, then crashes to the home screen.
   - The media plays for 1-2 minutes, then audio and picture lag before the app crashes.

**Expected behavior**
The media should play smoothly without interruptions, lag, or crashes.

**Smartphone (please complete the following information):**
- Device: Sony KD-65X9500H, Xiaomi TV Box S (2nd Gen)
- OS: Android TV 10 (Sony), Android TV 11 (Xiaomi)
- Security Patch: 1 February 2023 (Sony), 5 January 2023 (Xiaomi)
- OS Build: BRAVIA_UR3_PA-user 10 QTG3.200305.006.S36 660521 release-keys (Sony), rtt0.211222.001.683 release-keys (Xiaomi)
- Stremio Version: 1.6.7 (on both devices)

**Additional context**
- The issue occurs consistently, regardless of the media being played.
- The problem started recently, but it's unclear whether it's due to a Stremio update or an Android TV update.
- Addons in use: Cinemeta, YouTube, OpenSubtitles, IMDB Catalogs, Torrentio, TMDB Alternatives, Torrent Catalogs, OpenSubtitles v3, Rotten Tomatoes Catalogs, Community OpenSubtitles, The Movie Database Addon.
- Network conditions are stable with high-speed results from the Real-Debrid speed test (e.g., SYD1: 279.96 Mbps, Cloudflare: 222.74 Mbps).
- Modified/used settings in the Stremio app:
  - Players: Exoplayer & libVLC (default players).
  - Enabled/disabled hardware-accelerated decoding.
  - Enabled/disabled tunnelled playback.
  - Enabled/disabled frame rate matching.
- The issue persists even after a factory reset on the Xiaomi TV Box S (2nd Gen).
- The app was working perfectly beforehand, and there's no clear indication of what has changed.

**Comment by TRtomasz** [comment]
Please Try disabling frame rate matching and check if it happens then

**Comment by this-is-cinema** [comment]
Same thing happened on my google chromecast when I tried playing too large of a file. Filtering for sizes <5GB fixed the issue for me. Hope that helps!

**Comment by FunkeCoder23** [comment]
This happens for me too, even on smaller (~1GB files)

**Comment by Pampaloco** [comment]
same thing with me. I am using kodi as external player and this fix de issue. Mi tv box is very bad for stremio, and this new update is buggy. a shame.

**Comment by TRtomasz** [comment]
Closing, this will be fixed in the next Android Tv app release https://github.com/Stremio/stremio-bugs/issues/722
