### ISSUE TITLE
Many problem after get big WebUI upgrade

### ISSUE THREAD

**Issue by blackPantherOS** [Stremio/stremio-bugs#674]
After many years usage without any problems, the few months ago arrived the modern interface upgrade for Stremio with many bugs:

**Describe the bug**

- The old custom extensions are lost and cannot install again, because get error messages
- The subtitles does not work from any plugins (installed) 
- The movie screen does not displayed on TV **sound playing only** , the loading picture still displaying
- The new interface hard usable with air mouse and remote control,
- The popup keyboard of TV (overlap content issue / LGWebOS)

**With desktop application on PC (Linux):**

- Playing working, sound, screen: ok
- Embedded subtitles : ok
- OpenSubtitles do not work, even IF displayed the availability of subtitles from plugin, sometimes does not displayed subtitles but available on site.
- 

Yes, yes I know, the subtitle issue maybe it's a plugin issue, but I, and we used it for many years before you guys did a big update. All our users have been complaining, since Stremio are "new"... The main issue, that does not show screens after start playing on TVs...

Translation of attached error message: 
An error occurred while loading the subtitles
No tracks

![2024-01-26_16-07](https://github.com/Stremio/stremio-bugs/assets/12883566/ce5b720f-4b0e-4942-8d07-8a765485cd23)

**Comment by TRtomasz** [comment]
please use 1 issue per one bug reports, we are not able to solve them like this, without any details.
