### ISSUE TITLE
Subtitle problems

### ISSUE THREAD

**Issue by Maremelows** [Stremio/stremio-bugs#675]
**Describe the bug**
Hello good day, I get an error like this in Stremio.When I select the subtitle in Turkish, regardless of the content, the subtitle does not appear and the text in the photo appears.And this does not change from the beginning to the end of the content.I installed all the plugins that should be added, even uninstalled and reinstalled them, but the result did not change.Can you help me with this issue?
![Screenshot_20240127_143937_Stremio](https://github.com/Stremio/stremio-bugs/assets/125856651/2dc2915c-4c3c-4855-9d2f-4fc27c46eb7d)

**Smartphone (please complete the following information):**
 - Device:Samsung Galaxy A23
 - OS:Android 13
 -Version:1.6.9

**Comment by TRtomasz** [comment]
this is not related to stremio and looks like it comes from unofficial addon.

**Comment by Maremelows** [comment]
> this is not related to stremio and looks like it comes from unofficial addon.

This is a problem with Stremio. I can prove it any way you want. Also, it's ridiculous that you're so indifferent because it's an unofficial addon. At least you can offer a solution. I can't watch anything on Stremio because of this error.

**Comment by jaruba** [comment]
@Maremelows https://github.com/Stremio/stremio-bugs/issues/571#issuecomment-1755605832
