### ISSUE TITLE
Web Os cant change language from main language given by release 

### ISSUE THREAD

**Issue by arrow00009** [Stremio/stremio-bugs#677]
**Describe the bug**

**To Reproduce**
1. Go to '...'web stremio 
2. Click on '....' any japanese anime or movie with dual audio
3. It only plays whatever audio is the primary tested on lg webos and on mobile browser

**Expected behavior**
So i would like to play in Japanese language which i selected but it plays random english language. Even though it has dual audio same goes for some russian releases it plays in russian language ,there is no option in web browser to choose primary and secondary languages 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]lg web os 
 - Browser [e.g. chrome, safari]chrome mobile
 - Version latest 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] lg g2 and mobile realme z7
 - 
 - Browser [e.g. stock browser, safari] chrome 

**Additional context**

**Comment by TRtomasz** [comment]
Not possible to change audio as on web os you dont have streaming server, should be fixable soon with the option to run server on your desktop and use it in the webos app.
