### ISSUE TITLE
Windows app only showing limited items under continue watching

### ISSUE THREAD

**Issue by sniiks** [Stremio/stremio-bugs#679]
_**Description**_
On the Windows app of Stremio, the continue watching section is limited to a certain amount of titles without the ability to scroll/view all. Other sections like Movies, Series, Channels, etc. all have 10 items and the ability to view more whereas continue watching only has 8 items and not this same function.

_**To reproduce**_
1. Go to the homepage of Stremio
2. Click on the arrow at the right-hand side under "continue watching"

_**Expected behavior**_
Clicking on the scroll arrow should show additional series/movies but it doesn't do anything by pressing it.

_**Screenshots**_
https://i.imgur.com/yWVFkt1.jpeg

_**Desktop**_
 - OS: Windows 10 (22H2) / Windows 11
 - Stremio Version: 4.4.165

**Comment by TRtomasz** [comment]
This is not a bug, this is the limitation and it will not be changed in the current app.
