### ISSUE TITLE
audio issues

### ISSUE THREAD

**Issue by Harith163** [Stremio/stremio-bugs#68]
The in-built player's audio just stops when I cmd-tab out of an episode. This error has existed for quite some time in all the versions so far. I use the mac version 3.6 update as of now.

No other player does this on my mac and I couldn't find a similar issue on the bug tracker.

Regards,
Kaushik

**Comment by Ivshti** [comment]
indeed, there's no similar issue that we've heard of even

does it continue to play or does the entire video pause?

**Comment by Ivshti** [comment]
Does the audio return when you focus into the window?

**Comment by Harith163** [comment]
Here are my observations.

1)This bug only occurs when the entire stremio window is covered. If I have
part of a window of some other application open and atleast some part part
of the stremio application visible in the background then the bug does not
happen.

2) The video itself continues to stream but sort-of pauses? The audio
doesn't play for 1-2 seconds and the video is greyed out when I return.

I will attach some photos for what I mean.

**Comment by Harith163** [comment]
proper pics

http://imgur.com/a/w00TU

**Comment by Ivshti** [comment]
First - we appreciate the details you're providing. It's very helpful.

Second - I'd like to re-iterate again that we've heard for all sorts of issues on OS X, but not this one. We are also testing and developing on OS X

My point - this seems like low-level behaviour, yet OS X does not include such behaviours. It's also extremely rare. Can you revise your system to check if you have any power savers (or such) installed, provide exact OS X version and device spec, and maybe tweak the power settings.

Also please try playing something with the Channels (YouTube) add-on or TV (filmon.tv) - those things do not use libvlc, but the HTML5 player.
