### ISSUE TITLE
Subtitles on the TV app are out of sync

### ISSUE THREAD

**Issue by rinnarii** [Stremio/stremio-bugs#680]
**Describe the bug**
Some shows/movies on the TV app has their subtitles out of sync. Tried all the English subtitle options on TV and they are all not synced. On Linux however, the subtitle is on sync for the embedded and addons. I have to manually set the subtitle delay on the TV which is mildly an inconvenience as I have to experiment which setting will make it synchronized.

**To Reproduce**
1. Play a video
2. Enable the subtitles (to English) or have it automatically on the settings.

**Expected behavior**
For the videos to be in sync out of the box.

**Additional context**
I'm thinking if TV might have been sourcing from OpenSubtitles, could that be the problem? Does the Linux app get its subtitle from the video itself?

**Comment by TRtomasz** [comment]
Stremio does not controll subtitles they come from open subtitles so we do not controll if they are in sync

**Comment by rinnarii** [comment]
> Stremio does not controll subtitles they come from open subtitles so we do not controll if they are in sync

How about the subtitles when playing through Linux/Android phone? Aren't those the embedded subtitles from the video files torrented by Stremio itself?
I tried manually downloading the torrent files and the embedded subtitles are in sync, maybe we can utilize that on TV?
If so, is it possible that the TV app can get the subtitles from the files as well like other operating systems?

That's the solution I can think of, unless the TV has limitations on media files.

**Comment by TRtomasz** [comment]
yes they indeed could be embedded and for some videos embedded subtitles are not available using the tizen app.
