### ISSUE TITLE
Audio stops working after waking up from sleep on windows 11

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#681]
**Describe the bug**
Audio stops working after waking up from sleep on windows 11 and have to exit and start the app again for it to start working again.

**To Reproduce**
1. Start stremio
2. Play something
3. Pause it
4. Put computer to sleep
5. Log into computer and resume playback

**Expected behavior**
Audio should play

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version : 4.4.165

**Comment by TRtomasz** [comment]
Cant reproduce this, audio works fine on my dekstop. Any chance you use some bluetooth speakers?

**Comment by VVispy** [comment]
ive been having this issue as well @TRtomasz @rp1231 
latest stremio v5 windows. using monitor speakers. putting pc to sleep while stremio is the focused tab.
