### ISSUE TITLE
Stremio Web cannot be opened in the browser on Samsung TVs 

### ISSUE THREAD

**Issue by marcushrq** [Stremio/stremio-bugs#684]
When trying to access Stremio Web through the Samsung TV's web browser (version 3.1.11260 TizenBrowser) only the purple background of the Web page is shown, without any information. 

It would be ideal to provide access to the website via Samsung TVs, it would be the best way to watch content without the need for an app on the TV.

![20240209_231752](https://github.com/Stremio/stremio-bugs/assets/142295488/6aa88b51-65b3-4d98-adaf-59bc7015dc32)

**Comment by TRtomasz** [comment]
If you have old TV it will not be able to run the website. We provide apps for samsung TVs for all tvs starting from 2019.
