### ISSUE TITLE
Wrong poster + background image for the show "From The Earth To The Moon" (1998)

### ISSUE THREAD

**Issue by mufasa85** [Stremio/stremio-bugs#686]
**Describe the bug**
This show: https://web.stremio.com/#/detail/series/tt0120570 has some anime poster and thumbnail instead of the right one. The poster says "Detective Conan". 

I see this bug both in desktop and web version. 

**To Reproduce**

**Expected behavior**
See the right poster and background for this show

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/309567/72e9bf51-9e64-492d-b7cd-ba555e1c9a6a)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Chrome
 - Version: 121.0.6167.161 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TRtomasz** [comment]
this should be fixed now
