### ISSUE TITLE
[Android] In the new account, some addons are not actually installed.

### ISSUE THREAD

**Issue by Vance-ng-vn** [Stremio/stremio-bugs#687]
Some people have reported to me that the Subscene and Opensubtitles v3 plus addons are not working for them.

And strangely, the new accounts, or the guest accounts, they're do not actually send any requests to the subtitles addons. I also remember that Stremio had a similar issue about a month ago, where addons were not actually installed!

*And an issue with all accounts, addons like Superflix return 'subtitles' both with the 'stream', and the subtitles addon also doesn't work.

**Comment by TRtomasz** [comment]
i'v just tried with new account and subscene addont returns a timeout error, Opensubtitles community also returns an error. Opensbutitles v3 plus worked just fine

**Comment by swiezaczek** [comment]
Could you please clarify if you're referring to the Android app? I haven't encountered any problems on my PC, even with new accounts.

I've noticed that an older account enables me to use both Subscene and OpenSubtitles v3 add-ons without any issues on both Android and PC. It seems that, for newer accounts, only the official OpenSubtitles is functional on Android. Subscene and OpenSubtitles v3 plus are not working.

After conducting extensive testing over the past few days, I have eliminated the firewall, DNS, and the inaccessible addon server as potential causes of the issues.

**Comment by swiezaczek** [comment]
> i'v just tried with new account and subscene addont returns a timeout error, Opensubtitles community also returns an error. Opensbutitles v3 plus worked just fine

Could you please clarify if you're referring to the Android app? I haven't encountered any problems on my PC, even with new accounts.

I've noticed that an older account enables me to use both Subscene and OpenSubtitles v3 add-ons without any issues on both Android and PC. It seems that, for newer accounts, only the official OpenSubtitles v3 is functional on Android. Subscene and OpenSubtitles v3 plus are not working.

After conducting extensive testing over the past few days, I have eliminated the firewall, DNS, and the inaccessible addon server as potential causes of the issues.

**Comment by TRtomasz** [comment]
Android app with new account.

**Comment by swiezaczek** [comment]
> Android app with new account.

Could you log in to this one of my testing account :

wibave5789@tospage.com
qwerty21

Would you mind testing it out to verify its functionality? If needed, you're welcome to make any changes to the account for diagnostic purposes, including reinstalling addons.

**Comment by Vance-ng-vn** [comment]
`"resources":[{"name":"subtitles","types":["movie","series"],"idPrefixes":["tt","kitsu"]}]`

I suspect that the Android version is not handling correctly when the resource is an 'object' instead of a 'string,' but it's strange that this bug only appears on the new accounts...

**Comment by Vance-ng-vn** [comment]
> i'v just tried with new account and subscene addont returns a timeout error, Opensubtitles community also returns an error. Opensbutitles v3 plus worked just fine

Subscene-hamorny, if the app returning an error, that's great, but I'm sure that the app is not sending any requests (no error notifications).

**Comment by Vance-ng-vn** [comment]
And I double-checked, I confirm that the bug only occurs when the resource is an object, should I update the manifest? I'll wait for your confirmation.

**Comment by Vance-ng-vn** [comment]
For some reason, I updated the manifest.json of Subscene (Object to string), and it's working now...

From Object
```javascript
"resources":[{"name":"subtitles","types":["movie","series"],"idPrefixes":["tt","kitsu"]}]
```

To String
```javascript
"resources": [
        "subtitles"
    ],
    "types": [
        "movie",
        "series",
        "subtitles"
    ],
    "idPrefixes": [
        "tt",
        "kitsu"
    ]
]
```

**Comment by swiezaczek** [comment]
> For some reason, I updated the manifest.json of Subscene (Object to string), and it's working now...
> 
> From Object
> 
> ```js
> "resources":[{"name":"subtitles","types":["movie","series"],"idPrefixes":["tt","kitsu"]}]
> ```
> 
> To String
> 
> ```js
> "resources": [
>         "subtitles"
> ],
> "types": [
>         "movie",
>         "series",
>         "subtitles"
> ],
> "idPrefixes": [
>         "tt",
>         "kitsu"
> ]
> ```

In summary, Stremio should accept both objects and strings, but you can address the issue by converting objects to strings on your end? 

I can verify that the problem has been resolved following the adjustments you made. I found it necessary to reinstall the Subscene addon afterwards. Could you resolve the same issue with Opensubtitles v3 Plus and Yifysubtitles?

Also podnapisi addon doesnt work, but the issue seems to be different. Can you address it?

**Comment by Vance-ng-vn** [comment]
> > For some reason, I updated the manifest.json of Subscene (Object to string), and it's working now...
> > 
> > From Object
> > 
> > ```js
> > "resources":[{"name":"subtitles","types":["movie","series"],"idPrefixes":["tt","kitsu"]}]
> > ```
> > 
> > To String
> > 
> > ```js
> > "resources": [
> >         "subtitles"
> > ],
> > "types": [
> >         "movie",
> >         "series",
> >         "subtitles"
> > ],
> > "idPrefixes": [
> >         "tt",
> >         "kitsu"
> > ]
> > ```
> 
> In summary, Stremio should accept both objects and strings, but you can address the issue by converting objects to strings on your end? 
> 
> I can verify that the problem has been resolved following the adjustments you made. I found it necessary to reinstall the Subscene addon afterwards. Could you resolve the same issue with Opensubtitles v3 Plus and Yifysubtitles?
> 
> Also the Podnapisi addon is not functioning properly for some longer time. Could you please address this issue or remove the addon from the unofficial addons list in Stremio to prevent any confusion? 


I think Stremio could fix it at the server level, instead of addons changing due to bugs to work!

And for Podnapsi + Yify, you need to contact @dexter21767.

**Comment by Vance-ng-vn** [comment]
Yeah, it was working on Android... but after converting from object to string, it seems to have stopped working on PC with HTTPS streams like shluflix and superflix...

**Comment by jaruba** [comment]
The android mobile app was fixed, it should send requests to all subtitle addons now, see: https://blog.stremio.com/stremio-tech-update-29-stremio-mobile-updated/
