### ISSUE TITLE
Doesn't show episode's title, but notification show it

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#691]
**Describe the bug**

**To Reproduce**
1. See a notification with an episode title
2. Click on it to be transported to the tv show
3. See that the episode is missing the title, it's just called `Episode #`.

**Expected behavior**
TV show suppose to fetch the episode title like the notification did.

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/17256400/a4564099-2ca9-4ba4-963d-6a8dfe0455a0)
![image](https://github.com/Stremio/stremio-bugs/assets/17256400/4127f0be-1c7b-4f05-ab4b-b28cfa4dfccd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: app
 - Version: 4.4.165

**Comment by TRtomasz** [comment]
This is not a bug, this could happen due to multiple issues like caching. But we will check if our crawler is up to the date thanks.
