### ISSUE TITLE
Cinemeta error retrieving information about this

### ISSUE THREAD

**Issue by Destinyg133** [Stremio/stremio-bugs#693]
**Describe the bug**
Cinemeta fails on getting metadata ex: UFC 298

**To Reproduce**
1. Go to 'board'
2. Click on 'search box'
3. Search for UFC 298
4. See error : retrieving information about this

**Expected behavior**
It should pull correct metadata and addons should find correct source for needed search but all it does is find breakdowns rather than full show.... All other cards seem to find fine and works like excpected but this one fails 

**Screenshots**
![Screenshot_2024-02-18-13-51-04-499_com stremio one](https://github.com/Stremio/stremio-bugs/assets/22103363/0f4116ac-2c0f-4151-9886-e12b25041daa)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox
 

**Smartphone (please complete the following information):**
 - Device: Xiaomi MI10t
 - OS: miui 
 - Browser firefox
 

**Additional context**
Other cards seem to fetch fine, problem lies on ufc298 which is newest one

![Screenshot_2024-02-18-13-56-40-106_com stremio one](https://github.com/Stremio/stremio-bugs/assets/22103363/52a2a418-b3ab-49c0-acb8-3fd768879ba6)

**Comment by TRtomasz** [comment]
this is not a bug we simply do not have data about this.
