### ISSUE TITLE
Samsung TV: Library only load the first 35–40 titles.

### ISSUE THREAD

**Issue by SubEdict** [Stremio/stremio-bugs#697]
I have more than 300 TV shows titles in library, but on Samsung TV it's only showing about 40.
This is also ruining the Continue watching → Browse for more (+) gets to the same library that show only 40 list titles.

Samsung TV Q95T
 - OS: Tizen
 - Stremio 1.2.1

**Comment by bunyamoz** [comment]
Interested in this as well as I'm having the same issue for a long time. I've reported the bug a couple of weeks ago but it wasn't solved and the issue was closed.

**Comment by TRtomasz** [comment]
i can confirm it will be fixed in next release, once it gets approved in the store(no timeline for this sorry)

**Comment by SubEdict** [comment]
Works great! Perfect fix after v.1.6.3, Tizen 5.5.
Thanks.
