### ISSUE TITLE
Trakt Addon Not Showing Collection

### ISSUE THREAD

**Issue by memyselfandi123321** [Stremio/stremio-bugs#698]
I’ve uninstalled and reinstalled my addons and since doing this, Trakt is no longer showing my collection, only popular and trending movies & series. I’ve carried out all the recommended steps several times in a bid to rectify this; including revoking access to Trakt, uninstalling and reinstalling the Trakt addon and reauthorising in Trakt. I’ve reached out to Trakt who recommended doing everything I’ve already done, and suggested I contact Stremio, which I’m now doing.

Mecool KM2+ running Android TV OS 11
Stremio version 1.6.7
Trakt addon version 0.1.2

**Comment by CrudeCreations** [comment]
Have you logged into the stremio website and clicked the 'import' button under account settings? This fixed all of my Trakt Watch list etc and synced it into my profile.

![image](https://github.com/Stremio/stremio-bugs/assets/132678134/a69fb4fd-0ec9-480e-97a6-ddc490b63e4e)

**Comment by memyselfandi123321** [comment]
Thanks for that CrudeCreations, this has solved the issue👍🏻
