### ISSUE TITLE
Subtitle no tracks bug

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#699]
**Describe the bug**
Subtitles won't load and show no tracks error

**To Reproduce**
1. Play something in Stremio
2. Choose subtitles

**Expected behavior**
For the subtitles to be loaded and shown

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit 
 - Browser Brave
 - Version 1.62.165

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12, MIUI 13 
 - Browser Brave
 - Version 1.62.162

**Additional context**
/
![Screenshot_2024-02-22-05-02-56-710_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/f21bc694-8c87-493a-b20f-6d17cc869d3b)
![Screenshot_2024-02-22-05-02-49-262_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/7e9395ca-52d5-4660-8104-15ad5e05c0fe)
![Screenshot_2024-02-22-05-03-54-477_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/50c437d1-e7f1-4356-963a-6cfd40a8f5e4)
![Screenshot_2024-02-22-05-04-33-687_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/f40cbfe7-10ec-4504-a2ad-394da77f6971)
![Screenshot_2024-02-22-05-04-40-256_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/a2fc0994-ed4f-448d-aba0-fa5e01ee366e)

**Comment by GKid94** [comment]
@TRtomasz Still happens 
![Screenshot_2024-04-18-05-02-11-067_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/f8bca756-a280-41e4-87a3-cb69864d07e2)
![Screenshot_2024-04-18-05-02-17-510_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/00d47590-d6f0-4eb1-be9d-b55b5798737c)
![Screenshot_2024-04-18-05-02-32-194_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/d9e8ad81-3826-46a5-9bac-aa97ef6af501)
![Screenshot_2024-04-18-05-02-44-660_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/0f16ca0f-a6a2-4d21-8fe6-bde5a55cebb0)

**Comment by TRtomasz** [comment]
Due to multiple reasons you might see message like that:
Ongoing opensubtitles issue
Problem with subtitles reencoding to utf-8
Opensubititles/cloudflare blocking your ip address.
