### ISSUE TITLE
Won't stream to 4th gen Apple TV

### ISSUE THREAD

**Issue by kieranhogg** [Stremio/stremio-bugs#70]
The correct Apple TV is recognised but trying to play results in it going back to the main page and nothing on the Apple TV.

**Comment by Ivshti** [comment]
Thanks for reporting

we are working on this issue, but we have to resolve a lot of DLNA issues first, so it's not close on the roadmap unfortunately :(

**Comment by yo0x** [comment]
any updates about this issue??? thnks

**Comment by Ivshti** [comment]
Yes, and unfortunately not in a good direction. Apple recently pushed an update to Apple TV 4 that disallows third-party (non Apple Store) apps from casting to it.

The only way is to go through our iOS app, but this will take a while as it first requires that we implement iOS app linking to desktop app

The other way is to play through QuickTime, we'll try that very soon with our 4.x desktop series.

**Comment by Ivshti** [comment]
Airplay has been discontinued
