### ISSUE TITLE
Local files are not getting indexed

### ISSUE THREAD

**Issue by seahindeniz** [Stremio/stremio-bugs#704]
**Describe the bug**
I have local files stored in my external hard drive, but Stremio is not able to index files even though files are downloaded and contains the same naming as the one that shows when I choose an episode from the list. 

I can confirm that I have two TV shows. They both downloaded from the same source and all files are stored in the same hard drive.
I can individually find files when I search from the Start Menu (Windows 11) and both files of both TV shows are being listed.
I can confirm that 1 TV show files are being shows on Stremio as I watch though Stremio, but the other one doesn't register files.

The file path `"F:\Dizi\Stargate SG-1 (1994) Season 1-10 S01-10 (1080p BluRay x265 HEVC 10bit DD 5.1 EDGE2020)\Season 1\Stargate SG-1 - S01E01-E02 - Children of the Gods (1080p x265 EDGE2020).mkv"`

**To Reproduce**
1. Download `Stargate-SG-1-1997-Season-1-10-S01-10-1080p-BluRay-x265-HEVC-10bit-DD-5-1-EDGE2020`
2. Move files to an external hard drive
3. Expect them to be indexed

**Expected behavior**
Files should be listed under local files in Stremio
![image](https://github.com/Stremio/stremio-bugs/assets/5789670/722dc030-b6b8-4a4b-a948-6f2f1220a429)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Version [e.g. 22] Stremio 4.4.165

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**
I have tried restarting, re-indexing
![image](https://github.com/Stremio/stremio-bugs/assets/5789670/fb8f7880-2a87-419f-8aa1-5d473325134a)

**Comment by seahindeniz** [comment]
I have also tried moving files to `C:\` but that didn't work as well

**Comment by TRtomasz** [comment]
this is how we search for files https://github.com/Stremio/stremio-local-addon/blob/master/lib/findFiles/win.js#L7 if you see any issue with this feel free to fix it

**Comment by seahindeniz** [comment]
Hi @TRtomasz, thanks for the point. Seems like the issue is related to an upstream library. Opened a new PR, however I'm not sure if it's maintained

**Comment by seahindeniz** [comment]
Hi @TRtomasz 👋🏻 are there any procedure left for releasing the new version that I might have missed, or is there a manual testing stage blocks the deployment?

**Comment by TRtomasz** [comment]
@seahindeniz  local addon comes with the server, we have to make a full release to make it available to users

**Comment by seahindeniz** [comment]
He;;p @TRtomasz may I know when's the new version with the new Local Addon version is going to be released? 
If it's not yet planned, do you have a sort of timeline or public backlog I could follow?
