### ISSUE TITLE
It says that my Caching drive is inaccessible, and thus I cannot watch films or series on either the App or the Browser.

### ISSUE THREAD

**Issue by AndreBC321** [Stremio/stremio-bugs#705]
**Describe the bug**
When I want to watch a movie or series on Stremio, it's like it's doing nothing but loading until it says the connection is too bad to stream. At first I thought it was my internet, but that didn't make sense because it has worked perfectly fine even with the same internet. Next, I thought it was some of the Addons that didn't work, but I've tried every single one of them with a movie I want to see and they all came up with the same result. When I looked into settings I could see that it says Caching drive was unavailable. I tried uninstalling Stremio and reinstalling to see if that worked but it didn't, I then tried viewing through the browser but the problem was there too.

**To Reproduce**

**Screenshots**
![Skærmbillede 2024-02-24 000429](https://github.com/Stremio/stremio-bugs/assets/162126452/ddf5825f-84b5-4fe9-a640-e75df350c697)
![Skærmbillede 2024-02-24 000646](https://github.com/Stremio/stremio-bugs/assets/162126452/132cce93-4862-46a8-99d1-3a1a872270a3)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version +4.4.165

**Comment by TRtomasz** [comment]
This is not related, default cache directory is sometimes marked as unavailable, you can switch to just C and it will create new cache directory directly there, and warning will be gone. `until it says the connection is too bad` this means that you are trying to play a stream that is poorly accessible or your ISP is blocking some connections.
