### ISSUE TITLE
Dolby vision when used on any show goes dark 

### ISSUE THREAD

**Issue by arrow00009** [Stremio/stremio-bugs#706]
**Describe the bug**
A clear and concise description of what the bug is.dolby vision on Lg g2 with firestick 4k doesnt work for some reason it goes dark ,can hear only voice and subtitles and my lg tv pops up showing dolby vision tag but tv goes dark 

**To Reproduce**

**Expected behavior**
It should work without a problem i has used a day before now its not working properly 

**Screenshots**

**TV (please complete the following information):**
 - Device: [LG G2 OLED ,fire stick 4k ]
 - OS: [e.g. fire stick latest version ]
 - Version [last lg os and latest fire stick os)
**Additional context**
Its happening quite recently im currently on stremio version 1.6.7 also for some reason when i changed to external video player it doesnt even do that now ,tried clearing cache will test with delete data and cache

**Comment by arrow00009** [comment]
HDR files working fine but Dv has this issue

**Comment by TRtomasz** [comment]
We do not controll this, we use exoplayer and if has bugs there is nothing we can do about it. Only thing we can do is to update it which we do with each release.

**Comment by TRtomasz** [comment]
There was no new release since December i think

**Comment by vabue** [comment]
That's the lnk where Exoplayer team is discussing possible fix - https://github.com/google/ExoPlayer/issues/11096
