### ISSUE TITLE
Stremio windows app keeps crashing when it should open the player 

### ISSUE THREAD

**Issue by Theywhoreport** [Stremio/stremio-bugs#707]
**Describe the bug**
The stremio app crashes when it supposed to play any video from any server/addon. This occurs ever since I installed it. The web version+stremio service works just fine.

Things I have already done:
- Uninstalled and reinstalled it (x5, twice manually);
- Changed my DNS from private to public;
- Grant every permission to stremio on Windows Defender's Firewall;
- Checked settings like "Hardware-accelerated decoding" and "launch player in a separate window (advanced)" which get unchecked after stremio crashes;
- Checked if I had enough storage for cache and move arround all possible option regarding cache;
- Turned the PC off and back on;
- Uninstall and reinstall all my addons

**To Reproduce**
1. Select a media to play
2. Select the addon server to launch the player (any server) 
3. Wait for the server to load
4. Stremio crashes at the end of the loading, instead of opening the player

**Expected behavior**
I expected the stremio player to launch and allow me to watch my media, or to play the file on another media player.  

**Screenshots**
ZIP file with video lower

**Desktop (please complete the following information):**
 - Gigabyte Z390 UD
- Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
- msi GeForce RTX 2600 Ti
- Driver GeForce Game Ready 551.61
- Windows 11 Pro 10.0.22621 (64bits)
- Windows Defender
- No VPN
- No Proxy
- Public DNS

[Stremio Crash.zip](https://github.com/Stremio/stremio-bugs/files/14531209/Stremio.Crash.zip)

**Comment by TRtomasz** [comment]
Do not enable "launch in a separate window" and try again  just hardware acceleration is needed

**Comment by Theywhoreport** [comment]
> Do not enable "launch in a separate window" and try again just hardware acceleration is needed

I did it, it worked for 20sec then crashed. Now it doesn't work again even with those settings as you said

**Comment by TRtomasz** [comment]
You could try removing GPU drivers using DDU and then install them again.

**Comment by Theywhoreport** [comment]
Also did that and didn't fix it... But thank you for helping !

**Comment by TRtomasz** [comment]
@Theywhoreport  you can try experimental new shell version let us know if it is working without any issues https://drive.google.com/file/d/1otlJN_uNZYpbwBLqKXfxzsxNNcCnnTj8/view?usp=sharing

**Comment by TRtomasz** [comment]
So looks like an issue with MPV on your system moste likely due to gpu driversi would say, try runnign DDU once again and install  previous gpu drivers version

**Comment by gusmaia00** [comment]
same here

**Comment by AlxRou** [comment]
Same here.
Since yesterday i open Stremio, i click on any movie to play and it crashes.
I've tried several solutions but nothing works.
Any news on this problem???

**Comment by Rookie-Rock** [comment]
I have the same issue

**Comment by AlxRou** [comment]
Rookie-Rock, download the experimental version from TheyWhoReport's post above. 
This version is working for me.

**Comment by Rookie-Rock** [comment]
@AlxRou  Thanks for the suggestion. I've now tried it and still face the same issues. When I move Stremio to my other monitor, which is bigger both physically and in resolution, the text appears blurry, as if it keeps the lower resolution from the other monitor. If I try to enter fullscreen on the bigger monitor, the application crashes two out of three times.

**Comment by NawaSM** [comment]
Hey, I had this same issue but recently found a redditor that shared a solution that worked for me. What I did was enable hardware acceleration and increase the cache to 5GB.
Hopefully this works for you all too.

**Comment by seascape** [comment]
Yep, enabling hardware acceleration seems to have fixed the formerly frequent Windows client crashes. 👍

**Comment by Pravinrajput00** [comment]
stremio app keep crashing, when try to play something. 
I am not able to access shell version, can someone provide the link again?

**Comment by itprosam** [comment]
> stremio app keep crashing, when try to play something. I am not able to access shell version, can someone provide the link again?

Same started happening to me. I am using the Latest version on Windows 11.
Hardware acceleration is turned on and Cache is set to 5gb and Launch player in a separate window is disabled

Please advise..
