### ISSUE TITLE
cursor theme isnt being respected under plasma 6 wayland

### ISSUE THREAD

**Issue by polluxau** [Stremio/stremio-bugs#708]
**Describe the bug**
im using stremio flatpak with xdg-desktop-portal kde and gtk installed under plasma 6 wayland, this is the only app for me that doesnt respect the theming of the cursor on plasma 6, on plasma 5 it had no issues with the cursor

**To Reproduce**
1. use plasma 6 on wayland
2. install stremio flatpak
3. see cursor not being respected

**Expected behavior**
the cursor should be correct from the theme that is used
![Screenshot_20240308_204154](https://github.com/Stremio/stremio-bugs/assets/81181814/03e958f2-c179-46a7-8c64-ac84906dd3d1)

**Screenshots**
![Screenshot_20240308_203844](https://github.com/Stremio/stremio-bugs/assets/81181814/d7c3ca50-79b9-4a63-8b72-248140150d86)

**Desktop (please complete the following information):**
 - OS: arch linux
 - Version 4.4.165

**Additional context**

**Comment by polluxau** [comment]
> First sentence from Plasma 6 documentation `Plasma 6 is built on top of Qt 6` since stremio is build using QT5 this moste likely explains the issue.

I thought so too, ill close this then and wait lol

**Comment by TRtomasz** [comment]
i found this too, maybe you can perform same steps to fix it https://github.com/flatpak/flatpak/issues/709
