### ISSUE TITLE
Local Storage not working

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-bugs#71]
Hi, I'm having some troubles with Stremio Add-on Local Files. I have installed npm on Windows and then I tried to install the add-on Local Files as says the readme file, here (https://github.com/Stremio/stremio-local-files). I followed the steps 
1: npm install stremio-local-files, 
2: cd node_modules/stremio-local-files, and 
when I hit step 3 (npm start), it gave me an error log (in the print):

![local_files_error](https://cloud.githubusercontent.com/assets/20742408/17272229/3b0fa754-5667-11e6-8b71-6e4142d196d4.png)

I entered on the add-on Local Files repository and notice that the line it show as an error (LOCAL_FILES_LOG=1) don't exist in the file it was referenced (index.js). Could be, perhaps, a mistake? Or did I wrong in something?

Thanks!

**Comment by Ivshti** [comment]
Try just `node index.js` ?

**Comment by aziol-harbortown** [comment]
Hi, thanks for the help!

I'd uninstalled and installed the add-on again, and a different error appears:

![local_files_error2](https://cloud.githubusercontent.com/assets/20742408/17274453/530140c4-56b8-11e6-8a1f-8fedcfef007f.png)

I've searched the error and it appears to be in the spawn arguments at index.js file, I guess. I looked at the file and change the win32 to win64 (line 40). I run it again and it works, but the last step fail, it says "localhost connection refused". Did I need something like Wamp Server to work?

Thanks, again!

**Comment by Ivshti** [comment]
can you update to v1.5.1 and try again?
there was a silly error with path to DS.exe 

But anyway, even in the current state, it should be working and finding files in a fixed set of directories (Downloads, Desktop) 
Now, when it can spawn DS.exe it will find on your whole system

**Comment by aziol-harbortown** [comment]
It didn't worked, then I've changed line 40 (win32 to win64), and 'npm start' work, but the browser shows the same error in step 3 (http://localhost:3033/stremio/v1): localhost connection refused.
This one I don't know how to fix.

**Comment by Ivshti** [comment]
Sorry for the delayed answer

You mean, when you open http://localhost:3033/stremio/v1 in the browser, it says conncetion refused, even though `npm start` runs and outputs a message that it's listening to 3033?

Can you verify that your firewall is off?

**Comment by aziol-harbortown** [comment]
When I hit npm start it shows the following:

-----------------------------------------------------------------------------------------------------------------
> C:\Users\username\node_modules\stremio-local-files>npm start
> 
> stremio-local-files@1.5.1 start C:\Users\username\node_modules\stremio
-local-files
> node index.js
> 
> C:\Users\username\node_modules\stremio-local-files\index.js:79
>     if (f.match("stremio-cache")) return false;
>          ^
> 
> TypeError: Cannot read property 'match' of undefined
>     at isFileInteresting (C:\Users\username\node_modules\stremio-local-f
> iles\index.js:79:10)
>     at LineStream.exploreFile (C:\Users\username\node_modules\stremio-lo
> cal-files\index.js:109:11)
>     at emitOne (events.js:77:13)
>     at LineStream.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at LineStream.Readable.push (_stream_readable.js:111:10)
>     at LineStream.Transform.push (_stream_transform.js:128:32)
>     at LineStream._pushBuffer (C:\Users\username\node_modules\stremio-lo
> cal-files\node_modules\byline\lib\byline.js:125:17)
>     at LineStream._transform (C:\Users\username\node_modules\stremio-loc
> al-files\node_modules\byline\lib\byline.js:116:8)
>     at LineStream.Transform._read (_stream_transform.js:167:10)
> 
> npm ERR! Windows_NT 6.1.7600
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> npm ERR! code ELIFECYCLE
> npm ERR! stremio-local-files@1.5.1 start: `node index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the stremio-local-files@1.5.1 start script 'node index.js'.
> npm ERR! This is most likely a problem with the stremio-local-files package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node index.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs stremio-local-files
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls stremio-local-files
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\username\node_modules\stremio-local-files\npm-debu
> g.log
> 
> C:\Users\username\node_modules\stremio-local-files>
> 
-----------------------------------------------------------------------------------------------------------------

Then, like I said before I've changed the line 40 (win32 to win64) that it's my system architecture. I thought it was the problem. I hit npm start again and no errors appears, just this: 

-----------------------------------------------------------------------------------------------------------------

> C:\Users\username\node_modules\stremio-local-files>npm start
> 
> stremio-local-files@1.5.1 start C:\Users\username\node_modules\stremio
> -local-files
> node index.js
> 
> 
> C:\Users\username\node_modules\stremio-local-files>

-----------------------------------------------------------------------------------------------------------------

I've checked and my firewall it's on, but I tried to add a packet rule to 3033 and the port 3033 and even disable the firewall, but it still didn't work.

P.S: It's ok, you don't have the obligation to answer me, I just thank you for your attention.
