### ISSUE TITLE
Desktop app crashes immediately on launch

### ISSUE THREAD

**Issue by dalmackay** [Stremio/stremio-bugs#712]
I've had this issue since I first got stremio a year ago. But normally I just launch it a few more times and it works. As of yesterday it has stopped doing that, and is completely unusable now.

The crash log says that my detected openGL version is GLES 2.0. This is incorrect. I have confirmed that I am on openGL 4.6.

I have only found one person with the same problem : https://github.com/Stremio/stremio-bugs/issues/345
But their solution did not work for me. I have completely reinstalled my graphics drivers with DDU. I have rebooted, reinstalled, changed directories, checked libmpv dependencies, etc.

1. Click on 'stremio.exe'

Windows 10, EVGA 3090, 5700x, b550, 48gb ram, 500mbps dl/ul

crash log: 

[libmpv_render] GL_VERSION='OpenGL ES 2.0 (ANGLE 2.1.0.57ea533f79a7)'
[libmpv_render] Detected GLES 2.0.
[libmpv_render] GL_VENDOR='Google Inc.'
[libmpv_render] GL_RENDERER='ANGLE (NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0)'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 1.00 (ANGLE 2.1.0.57ea533f79a7)'
[libmpv_render] Loaded extension GL_EXT_unpack_subimage.
[libmpv_render] Loaded extension GL_EXT_texture_rg.
[libmpv_render] Loaded extension GL_EXT_color_buffer_half_float.
[libmpv_render] Loaded extension GL_EXT_disjoint_timer_query.
[libmpv_render] Function glDebugMessageCallback from extension GL_KHR_debug not found.
[libmpv_render] Loaded extension GL_ANGLE_translated_shader_source.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] 16 bit UNORM textures not available.
[libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'd3d11-egl'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-egl'
[libmpv_render] Loading hwdec driver 'd3d11va'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-dxgi'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'dxva2-dxinterop'
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'cuda-nvdec'
[libmpv_render/cuda-nvdec] need OpenGL >= 2.1 or OpenGL-ES >= 3.0
[libmpv_render/cuda-nvdec] CUDA hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.

**Comment by TRtomasz** [comment]
As written in post you linked, have you tried using DDU?

**Comment by dalmackay** [comment]
Yes, as stated in my post

> But their solution did not work for me. I have completely reinstalled my graphics drivers with DDU.

**Comment by TRtomasz** [comment]
you might check this out https://github.com/Stremio/stremio-bugs/issues/715 if you have voicemeter banan, voice meter potato or any other software that is interfering with audio/video settings this might be causing the issue.

**Comment by dalmackay** [comment]
I did find that post, unfortunately I don't have anything like that running. Even tested in safe mode to confirm

**Comment by TRtomasz** [comment]
All decoders are failing to load there is nothing we can do to fix this as this is fully related to MPV.
