### ISSUE TITLE
Notifications stopped showing episode's title

### ISSUE THREAD

**Issue by maxoku** [Stremio/stremio-bugs#717]
**Describe the bug**
Notifications don't show episode's title anymore.

**To Reproduce**
1. Go to Home page when you have notifications.
2. See that there are no episode titles, only show's title.

**Expected behavior**
Notifications should contain episode's titles like before.

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/17256400/3f150808-5d00-490d-a329-69601ec3cd04)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser app
 - Version 
![image](https://github.com/Stremio/stremio-bugs/assets/17256400/6cd5687c-415b-4f2e-bd3a-4e4d089976d4)

**Comment by TRtomasz** [comment]
I have titles so perhaps we will need a bit more details

**Comment by maxoku** [comment]
@TRtomasz What details you need?

**Comment by TRtomasz** [comment]
Fix will be included in the next release
