### ISSUE TITLE
Exoplayer always detects PCM signal 

### ISSUE THREAD

**Issue by friendGR** [Stremio/stremio-bugs#719]
Hello , there is an audio problem with Exoplayer . The receiver detects signal Multichannel In (PCM) instead of HD formats. With libvlc the audio is OK but the video is stuttering. I strongly prefer exoplayer for smooth playback. Please UPDATE EXOPLAYER. Check the info of the receiver. 
![Capture](https://github.com/Stremio/stremio-bugs/assets/164328554/a51c0e99-1edd-4ad3-b064-d6d723eff93c)

Stremio Android TV: 1.6.7
Fire Tv 4K Max gen2 media streamer. Audio settings: Best Available

**Comment by TRtomasz** [comment]
We are not able to control exo player bugs. It will be updated in the next release
