### ISSUE TITLE
Torrents with Asian characters in the Downloads folder cause the program to freeze

### ISSUE THREAD

**Issue by chocolatkey** [Stremio/stremio-bugs#72]
It seems Stremio scans the User's Downloads folder on Windows, and I was having the problem that it would freeze about 3 secs after startup. After looking everywhere, I eventually saw is was complaining about my downloaded torrents (name in error message in console would turn up as question marks, seems like a UTF-8 fail). After I moved the torrents away from the downloads folder, it worked fine.

**Comment by Ivshti** [comment]
How many files did you have? Maybe it's the pure count that made it freeze

**Comment by chocolatkey** [comment]
I had 270. I'll try to reproduce the problem

**Comment by chocolatkey** [comment]
![image](https://cloud.githubusercontent.com/assets/13407784/18027217/9e0ccbcc-6c5e-11e6-8b99-f0fffd2995c0.png)
Ok I copied the torrents back, and now when I start it freezes with constant 25% CPU
![image](https://cloud.githubusercontent.com/assets/13407784/18027220/b594fd5a-6c5e-11e6-8cba-707c7583d401.png)
