### ISSUE TITLE
Stremio app on Samsung TV won't log in.

### ISSUE THREAD

**Issue by gfkeller** [Stremio/stremio-bugs#720]
Stremio app on Samsung TV won't log in.

I scanned the QR code with my mobile device. It opens the browser and says the login was successful, but nothing happens on the TV app.

I've tried using Google Chrome and Firefox on my phone, normal and private mode, and Edge on my Windows computer, but the TV app still won't connect.

There should be a manual login option available.

**Comment by TRtomasz** [comment]
Is there any error message on the TV app side? Please look carefully

**Comment by gfkeller** [comment]
No, there is no change on the TV screen. 
The app keeps counting down the QR code expiration time, but nothing happens.
No new message or image appears.

**Comment by TRtomasz** [comment]
try to log out and log in from the web app on your phone

**Comment by gfkeller** [comment]
I've logged in to the web app many times on different browsers, including private browsing mode.

**Comment by TRtomasz** [comment]
You could try opening link on your desktop instead scanning it with your phone

**Comment by gfkeller** [comment]
I also did that.

**Comment by TRtomasz** [comment]
since we do not see any outage moste likely something with is wrong with your connectivity, you might try using a vpn on your TV.

**Comment by gfkeller** [comment]
why would that be? i use stremio on my desktop with no vpn

**Comment by gfkeller** [comment]
There should be a manual login option available.
