### ISSUE TITLE
[Android TV] Cropped clearart logos on homescreen channels

### ISSUE THREAD

**Issue by izao88** [Stremio/stremio-bugs#721]
https://github.com/Stremio/stremio-bugs/assets/151614284/d3a02a2c-81a3-4410-95c3-fb2bb714213e

Using Nvidia Shield, possible to remove these logos on the bottom left of the posters?

**Comment by TRtomasz** [comment]
This is caused by 3rd party launcher, there is nothing we can do about this at this point
