### ISSUE TITLE
Stremio Android TV crashing after few minutes of video playing

### ISSUE THREAD

**Issue by mhdzumair** [Stremio/stremio-bugs#722]
**Describe the bug**
Stremio Android TV crashing after few minutes of video playing (around 2.30 mins) with MediaFusion - Real-Debrid stream.  As i observe the logcat on two different versions, the `1.6.3` get killed by lowmemorykiller and `1.6.7` get crashed after i see the warning message   `Failed retrieving opensub hash: java.io.IOException: unexpected end of stream on http://127.0.0.1:11470`

**To Reproduce**
1. Go to 'https://mediafusion.elfhosted.com/configure'
2. Configure the addon with RD, enable catalogs like TamilHD, prowlarr etc, and enable all resolutions, finally enable sorting orders and install the addon. 
3. Goto any movie catalog and click on play for higher size movie (>5GB)
4. After playing for few minutes, Stremio get crashed. 

**Expected behavior**
Should play the stream without getting crashed.

**TV (please complete the following information):**
 - Device: Android_TV_1080p_API_30 Emulator x86
 - OS: Android TV OS 11
 - Version 1.6.7 and 1.6.3

**Additional context**
**Debug logs on v1.6.7:** https://pastebin.com/XHDe1URY
**Debug logs on v1.6.3:** https://pastebin.com/bd3EYqZS

**Comment by xbmcalok** [comment]
Unable to watch any streams due to above issue.

**Comment by ericvlog** [comment]
me too!

**Comment by Iron56716** [comment]
Same issue here.

**Comment by KarthiSurfer** [comment]
yes same issue here

**Comment by mhdzumair** [comment]
I think this maybe similar to the issue https://github.com/Stremio/stremio-bugs/issues/673

**Comment by binoymathewk** [comment]
Same issue for me too.. i think its mainly in Android TV version

**Comment by mhdzumair** [comment]
> i have no crash after the `failed retrieving open sub hash:..` warning stream loads for a moment then and continue the playback

This is specially happening on lower end device. 

I was tested through AVD. Here is my configs.
![image](https://github.com/Stremio/stremio-bugs/assets/44891939/da004ff6-714c-46a4-8a03-5d8737a607e5)
![image](https://github.com/Stremio/stremio-bugs/assets/44891939/ce59a6fd-03b3-4d70-a40a-33ea06a22d22)

**Comment by Neo402** [comment]
Ever since they updated to elfhoster. Trouble started.

**Comment by mhdzumair** [comment]
Issue will be resolved by stremio-server update.
