### ISSUE TITLE
Meta Quest 3 No Sound during stream playback

### ISSUE THREAD

**Issue by SunnyOd** [Stremio/stremio-bugs#723]
So I've installed Stremio on the Quest 3 using fdroid and when I try to watch a stream it doesn't give any audio output. I've tried tweaking the settings in the app so that I try different configurations and options related to audio but nothing seems to work. 

**Smartphone (please complete the following information):**
 - Device: Meta Quest 3
 - OS: Android 12 (Quest OS v62)
 - Browser N/A
 - Stremio Version 1.6.10

When I first installed the app on meta quest OS version 61 the sound wasn't working, but then I left it for when version 62 came out and that seemed to fix it. This worked for a couple of days when I tried it and it was great. I've gone back to it again yesterday for the first time in 2 weeks and sound is broken again. I haven't made any changes, I'm still running Quest OS 62 and Stremio 1.6.10.

**Comment by TRtomasz** [comment]
We will not be able to help with such issues, this device is not officially supported. You can try following community tutorials https://stremio.zendesk.com/hc/en-us/articles/17914295823890-Stremio-on-Meta-Quest
