### ISSUE TITLE
Stremio Services can not remove from mac startup apps

### ISSUE THREAD

**Issue by bilalmalkoc** [Stremio/stremio-bugs#724]
**Describe the bug**
I checked Mac "Open at Login" items and there is no Stremio Service.
Checked right click on the dock, Open at Login is unchecked.

But Stremio Services are still opening on startup.

I checked this folders and i can not find related file with Stremio. May be i don't know it's name idk.
/Library/LaunchAgents
/Library/LaunchDeamons
/System/Library/LaunchAgents
/System/Library/LaunchDeamons

**Desktop (please complete the following information):**
 - OS: macOS Sonome 14.4.1
 - Stremio Services: 0.1.12

**Comment by TRtomasz** [comment]
Stremio service does not even have such option so moste likely something is in your system configuration or you simply selected option to reopen apps again on reboot

**Comment by AlvinHV** [comment]
I believe it is indeed a launch service. Try deleting file in this path or go to settings -> General -> Login items -> disable open.

 /Users/<Username>/Library/LaunchAgents/com.stremio.service.plist
