### ISSUE TITLE
Flatpak unverified 

### ISSUE THREAD

**Issue by polluxau** [Stremio/stremio-bugs#727]
**Describe the bug**

**To Reproduce**
1. Go to flathub.org
2. Click on stremio
3. See a orange icon under the logo saying its unverified 
4. Users could be wary if it's official or not and may not install it

**Expected behavior**
Should show a verified badge meaning its officially verified by flathub being the official app maintained by stremio devs/contributors 

**Screenshots**
![Screenshot_20240329-030627_Firefox.png](https://github.com/Stremio/stremio-bugs/assets/81181814/7ee39ac8-3115-418a-af0d-a490e019ee5d)

![Screenshot_20240329-031106_Firefox.png](https://github.com/Stremio/stremio-bugs/assets/81181814/1fad484b-b1ec-4e99-adfe-ea91ffb7da14)

**Comment by core1024** [comment]
It should be verified now
