### ISSUE TITLE
HELP! Everything Is GOING Wrong!!!!

### ISSUE THREAD

**Issue by Harith163** [Stremio/stremio-bugs#73]
I was using stremio just fine. I Exited one episode and switched to another show and chose an episode. It said no addons available;click to show all available addons. I know that I have all the addons enabled and recalled that this happens when I have an internet issue. I restarted the wifi(at the modem then at my laptop) and still same issue. I wasn't able to uninstall any addons or add any for that fact. In the addons column it showed nothing! I then proceeded to uninstall and reinstall stremio using the alternative installer and it kept giving me file missing messages. What should I do???

**Comment by Harith163** [comment]
![screenshot 18](https://cloud.githubusercontent.com/assets/18382195/18038776/1b6202ac-6d6a-11e6-8cd7-d66d7e501c66.png)
![screenshot 19](https://cloud.githubusercontent.com/assets/18382195/18038796/1bc3a50c-6d6a-11e6-9013-509152ed96b8.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/18382195/18038797/1bc60cf2-6d6a-11e6-94d5-267900686e5d.png)
![screenshot 21](https://cloud.githubusercontent.com/assets/18382195/18038799/1bd09d2a-6d6a-11e6-9887-fe721cc77da8.png)
![screenshot 22](https://cloud.githubusercontent.com/assets/18382195/18038800/1bd1c6fa-6d6a-11e6-89e7-707b4d89c724.png)
![screenshot 23](https://cloud.githubusercontent.com/assets/18382195/18038781/1ba2175c-6d6a-11e6-8c8c-e4c131ff5536.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/18382195/18038777/1b69efc6-6d6a-11e6-88d4-fb2f789cabcd.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/18382195/18038783/1ba60b00-6d6a-11e6-882f-a586d6c27f67.png)
![screenshot 1](https://cloud.githubusercontent.com/assets/18382195/18038782/1ba5f156-6d6a-11e6-99a0-9ac66f464304.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/18382195/18038784/1ba98960-6d6a-11e6-9668-3c65145879f7.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/18382195/18038785/1baba25e-6d6a-11e6-84d1-af542ef522be.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/18382195/18038786/1baf66a0-6d6a-11e6-8a95-8e9f7f5e0596.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/18382195/18038778/1b7f5924-6d6a-11e6-9bbf-ae41e3ad2151.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/18382195/18038779/1b864aae-6d6a-11e6-8a7d-a976ed544711.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/18382195/18038788/1bb3ab3e-6d6a-11e6-8ded-fd492002f3c6.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/18382195/18038787/1bb326e6-6d6a-11e6-8a5e-94a76503318f.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/18382195/18038790/1bb5ba1e-6d6a-11e6-90ee-d1bd4c287f02.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/18382195/18038791/1bb806b6-6d6a-11e6-96b7-1e1aa1bdb4b8.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/18382195/18038789/1bb5b460-6d6a-11e6-98f3-ceb3f2e4ef8c.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/18382195/18038780/1b989f88-6d6a-11e6-9788-abda95b2f070.png)
![screenshot 13](https://cloud.githubusercontent.com/assets/18382195/18038792/1bba3058-6d6a-11e6-90ca-532d353c5fbc.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/18382195/18038793/1bbed1e4-6d6a-11e6-9ac4-e5ae68c2d7a5.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/18382195/18038794/1bc03d18-6d6a-11e6-8dc2-b6456a420d39.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/18382195/18038798/1bc64514-6d6a-11e6-8653-133259381247.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/18382195/18038795/1bc34ce2-6d6a-11e6-9d11-7cf8bcd1d869.png)

**Comment by Ivshti** [comment]
The problem with re-installation is that you haven't quit the currently running stremio. If you have no way to do it (e.g. tray icon), open the task manager and stop all stremio.exe processes.

Also, the reason for this is most likely cloudflare blocking you. It's the only common thing between all add-ons. Can you try behind a VPN or from another internet connection?

**Comment by Harith163** [comment]
So I did what you suggested and stopped all stremio processes via Task Manager then ran the reinstalation process. IT now installed and took me to the login page where I proceeded to put in my username and password. The problem now is , the moment I start typing the password, It takes me to the sign up page! Even if I try to sign up, it doesn't let me! Is this going back to the issue with cloudflare?

**Comment by Ivshti** [comment]
Absolutely, and it's a big one too. As it also blocks the central API besides the add-ons.

YOu can try another network connection / VPN

Or the same network connection, but inside the browser -> http://alpha4.strem.io (keep in mind, streaming does not work on the web version for now except for filmon)

**Comment by Harith163** [comment]
So, I can't try out another connection for a few more days... but I can confirm that the browser version works perfectly, as expected that is. Could you please tell me how I can disable cloudflare?

This issue has made me temporarily switch to the android version. I have several improvements in mind for the android version. Is there a github page for it? I understand that it is in alpha but I would still like to see what is happening.

**Comment by Ivshti** [comment]
@Harith163 no github, but you should report issues with it here
