### ISSUE TITLE
S23 ultra adaptive refresh rate

### ISSUE THREAD

**Issue by DivineForce** [Stremio/stremio-bugs#730]
**Describe the bug**
The Samsung Galaxy S23 Ultra is equipped with an adaptive refresh rate screen that can adjust between 1 and 120 Hz. However, i want to report that the refresh rate drops to low values after a minute of not touching the screen,  when streaming through apps like YouTube or the Gallery video player are running. This issue does not occur on the Galaxy S10, which has a fixed refresh rate of 60 Hz.

**To Reproduce**
1. Open stremio
2. Start any video
3. Idle 1 min without touching the screen
4. Framerate drops too low and chopping starts till touches screen again

**Expected behavior**
I expect it to maintain the required framerate accordingly than having touch the screen myself every 1 minute to get the refresh rate back up

**Smartphone (please complete the following information):**
 - Device: galaxy s23 ultra
 - OS: oneui 6.0/6.1 android 14
 - Browser : samsung internet/chrome
 - stremio version: 1.6.10

**Additional context**
I can debug anything required and share logs including system gpu etc if required

Best regards!

**Comment by TRtomasz** [comment]
How is this a stremio issue? we do not controll refresh rate

**Comment by DivineForce** [comment]
> How is this a stremio issue? we do not controll refresh rate
The issue only occurs in stremio i have hardware acceleration on and all settings checked to work probably while it doesnt happen with other apps i an trying to look at google documentations if there any service or intent that allows stream/player to prevent system from dropping framerate

**Comment by TRtomasz** [comment]
we do not plan to implement frame rate matching in the current mobile app, sorry.
