### ISSUE TITLE
the meta interface of the plugin I wrote does not show anything (works in the web version)

### ISSUE THREAD

**Issue by aflextr** [Stremio/stremio-bugs#731]
**Describe the bug**
The plugin I wrote used to work smoothly, but since 1 week it has been giving a black screen in the meta interface in the stremio application. There is no error on the console screen. (there is also a problem in android and windows versions, the web version works without any problems)

**To Reproduce**
1. Search 'anime name + ax.  e.g:demon slayer ax'
2. scroll down until the name of the plugin appears
3. click on any anime

**Expected behavior**
The meta interface of the anime should come normally..

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/53778891/c92ca739-d7fe-489f-b8a8-239e15d4ab08)
![image](https://github.com/Stremio/stremio-bugs/assets/53778891/5541e1ca-a808-4827-b31b-986e2120ad77)
![image](https://github.com/Stremio/stremio-bugs/assets/53778891/3ecb1ab7-755a-49af-8abf-71bb6092c043)

Web Version : 
![image](https://github.com/Stremio/stremio-bugs/assets/53778891/1587194e-962a-4b71-82cb-a53bb09c92ba)

**Desktop (please complete the following information):**
 - OS: [Windows 11 x64 pro]
 - Browser [msedge]
 - Version [123.0.2420.65]

**Smartphone (please complete the following information):**
 - Device: [Tecno CH7N]
 - OS: [Android 14]
 - Browser [Chrome]
 - Version [123.0.6312.41]

**Additional context**
Plugin uses http stream instead of torrent
When I open it in the web version, the meta interface comes without any problems.
When I open it with Stremion's desktop app or the app on the phone, it looks like in the screenshot.

addon url : https://animecix-stremio-addon.onrender.com/
addon source code : https://github.com/aflextr/animecix-stremio-addon/

meta code : 
```
 if (type === "series" && id) {
            metaObj = {
                id: id,
                type: "series",
                name: find.name_english,
                background: find.backdrop,
                country: find.country || "JP",
                genres: [],
                season: find.season_count,
                videos: [],
                imdbRating: Number(find.rating),
                description: find.description,
                releaseInfo: String(find.year),
                poster: find.poster,
                posterShape: 'poster',
            }
            // anime genres
            find.genres.forEach(element => {
                metaObj.genres.push(element.display_name)
            });
            //video
            for (let i = 0; i < find.season_count; i++) {
                var animeler = await search.SearchVideoDetail(find.type, findId, find.name_english, i + 1);
                animeler.forEach(element => {
                    metaObj.videos.push({
                        id: element.id,
                        _id: findId,
                        title: element.name,
                        released: new Date(element.release_date),
                        season: element.season_number,
                        episode: element.episode_number,
                        overview: element.description || "",
                        thumbnail: element.poster
                    });
                });
            }
            meta.push(metaObj.videos);
            return Promise.resolve({ meta: metaObj })

```

detail code url : https://github.com/aflextr/animecix-stremio-addon/blob/main/addon.js

**Comment by dexter21767-dev** [comment]
@aflextr  i wasn't able to reproduce on the desktop app, are u sure that you're using the latest version? 
u can find the app version in the settings page on the bottom left corner.
![image](https://github.com/Stremio/stremio-bugs/assets/127498984/8da79f5b-121d-4965-83be-8b143489982f)

**Comment by aflextr** [comment]
> @aflextr i wasn't able to reproduce on the desktop app, are u sure that you're using the latest version? u can find the app version in the settings page on the bottom left corner. ![image](https://private-user-images.githubusercontent.com/127498984/318133923-8da79f5b-121d-4965-83be-8b143489982f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDY4NzAsIm5iZiI6MTcxMTc0NjU3MCwicGF0aCI6Ii8xMjc0OTg5ODQvMzE4MTMzOTIzLThkYTc5ZjViLTEyMWQtNDk2NS04M2JlLThiMTQzNDg5OTgyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQyMTA5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODRmYWU3Y2VhYzYyODJiYWNkYzM3NjI3ZWViZGM2Y2QzYTNmMTk5NTQyZGFhMTY5NzEwMTg0NDE3MzVlNmE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nQc2R91R57BNZgkXD29KA803HCzpHWu6iCQc_yAi49E)

yeap latest version
![image](https://github.com/Stremio/stremio-bugs/assets/53778891/3c0b7c52-8dc6-4441-a669-200b2a8c406a)

**Comment by dexter21767-dev** [comment]
here's how your addon is appearing for me on stremio desktop.
![image](https://github.com/Stremio/stremio-bugs/assets/127498984/b7eb9d5b-ebf1-4ce0-b5d9-00528838a865)


u can also test the desktop version on browser using this link 
https://app.strem.io/shell-v4.4/#/

**Comment by aflextr** [comment]
> here's how your addon is appearing for me on stremio desktop. ![image](https://private-user-images.githubusercontent.com/127498984/318157650-b7eb9d5b-ebf1-4ce0-b5d9-00528838a865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NDQwNDQsIm5iZiI6MTcxMTg0Mzc0NCwicGF0aCI6Ii8xMjc0OTg5ODQvMzE4MTU3NjUwLWI3ZWI5ZDViLWViZjEtNGNlMC1iNWQ5LTAwNTI4ODM4YTg2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQwMDA5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmNhM2E1NWUzNThiNTUxMzQxZmM0Zjg5NzZlNjZmZDVjNzQwZGQwZWU5NjA0ZDY2YWIwNjkyOGEyYTEyMTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3aoWv2_Y3M3tfVE85Q6Dm2ytMatpLD1Vq-lwvS-gl7I)
> 
> there's a chance that it's not appearing correctly for you due to caching as i see that u have set the caching to "max-age=86400, public" which is 24 hours.
> 
> u can also test the desktop version on browser using this link https://app.strem.io/shell-v4.4/#/

Thanks fixed
