### ISSUE TITLE
Exoplayer issue with an subtitle addon 

### ISSUE THREAD

**Issue by Atreus93** [Stremio/stremio-bugs#732]
There is a problem with Exoplayer on Android tv with Subscene  - the Harmony Remake addon ( i know it's NOT an official addon, but the addon owner says it's issue related to stremio end). The problem is the subtitles of this addon don't display when i play a TV shows with Exoplayer. Sometimes i need to force stop and clear cache data of the app so the subtitles can display and i need to do  this every time i reopen or open anothervideo. Or wait 10-15 minutes before opening the video so finally and maybe the subtitles works.

- Open any tv show episode on Exoplayer, choose sub from subscene - Harmony remake. (maybe at this step you have luck to see it displayed on screen)
- Close the video and reopen it again.
- now you should not see the subtitle on the screen, unless you open the video with libVLC. 

---.

- it works good with ilbVLC player
- it works good with another devices like phone. 
- others subtitles addon work good.
- no issues with movies. (Edit: it does have issue with movies: subtitles disappear in the middle of movies on explorer)

Android tv 1.6.7

Also tried with 1.6.8  and 1.6.9 >> those updates even force stop and clear cache move don't help to fix the issue anymore. 

Many users noticed this problem.

Thanks.

**Comment by TRtomasz** [comment]
i'v just checked and it works perfectly finr on android tv too with exoplayer

**Comment by Atreus93** [comment]
> i'v just checked and it works perfectly finr on android tv too with exoplayer

Sorry, i forgot to close  the issue. It is fixed days ago by the addon owner.
