### ISSUE TITLE
Embedded subtitles don't appear on Samsung TV, impossible to watch anime

### ISSUE THREAD

**Issue by Max20720** [Stremio/stremio-bugs#736]
Embedded subtitles don't appear on Samsung TV

1. Go to any anime
2. Open an episode from Nyaa
3. Open subtitles
4. "None"

![Screenshot_20240404-131416](https://github.com/Stremio/stremio-bugs/assets/165971944/e809c411-3836-46fc-84d4-34ff252db27a)
![20240404_125729](https://github.com/Stremio/stremio-bugs/assets/165971944/a49b23f6-aa68-4fd4-9a29-77ea7661f65d)

Subtitles that show up on any other device don't appear in the Samsung TV

 - Device: Samsung TV UN43CU7700GXZD
 - Software: T-KSU2ECUABC-1402.8, E3371400, BT - S
 - OS: Tizen7
 - Version: Teather v1.2.1

I was thinking about starting using Stremio and getting a Real-Debrid subscription but if I can't watch anime then I won't be able to

**Comment by TRtomasz** [comment]
Please use the search feature before creating new issue, you would find out that this has been reported before
