### ISSUE TITLE
Wrong Background Image 

### ISSUE THREAD

**Issue by Kildare92** [Stremio/stremio-bugs#737]
When pulling up the show "I, Claudius" in Stremio, the poster is correct but the background image is completely incorrect. It appears to be for an award show or something else completely unrelated.

**To Reproduce**
1. Go to Stremio
2. Click on Discover
3. Search for "[I, Claudius](https://web.stremio.com/#/detail/series/tt0074006)" and select the series. https://web.stremio.com/#/detail/series/tt0074006

The poster and other details of the show are correct, but the background image alone is completely wrong. Is this a Cinemeta issue?

[Screenshot](https://imgur.com/a/SW9yxmx)
![image](https://github.com/Stremio/stremio-bugs/assets/166088897/960c5217-5c16-49f2-859e-757ef9150c93)

**Desktop (please complete the following information):**
 - OS: Windows 11, Firestick
 - Firefox [on Windows 11], same in desktop app
 - Version 4.4.168

**Comment by TRtomasz** [comment]
will be refreshed soon
