### ISSUE TITLE
Stremio freezes when maximized

### ISSUE THREAD

**Issue by wout000** [Stremio/stremio-bugs#74]
Stremio starts up, but doesn't show. When you click on the icon in taskbar it opens up (small window) and works perfectly until you try to maximize it. Everything freezes (even the windows start button) and you need to kill it using task manager.

**Comment by Ivshti** [comment]
which Windows version?

**Comment by wout000** [comment]
Windows 10 Pro insider version build 14915

**Comment by Ivshti** [comment]
@wout000 is the preview version expected to get some updates? if so, can we check if those fix the issue?

**Comment by wout000** [comment]
New builds will be released starting next week. I will update and see if they fix the problem.
It looks to be locking up whenever the window is maximized. In task manager there are 4 stremio.exe instances running when it freezes.

**Comment by wout000** [comment]
New builds will be released starting next week. I will update and see if they fix the problem.
It looks to be locking up whenever the window is maximized. In task manager there are 4 stremio.exe instances running when it freezes.

**Comment by andreoav** [comment]
+1

**Comment by andreoav** [comment]
Same problem.

Windows 10 Pro Insider Preview - Build 15014 (and previous insider builds)

**Comment by andersonid** [comment]
same here. macosx 10.12.3

**Comment by ItzzTies** [comment]
Same here, windows 10 Pro - build 15063.138. Hardware is not my problem either i think: i5-4460, 16gb dual channel 2400mhz ram, gtx 1070 xtreme gaming, gigabyte g1.sniper.b6 and corsair cx650m.
