### ISSUE TITLE
Authenticating Trakt via Apple throws "invalid_request"

### ISSUE THREAD

**Issue by luckb0t** [Stremio/stremio-bugs#743]
**Describe the bug**
When trying to link Stremio with Trakt via Apple ID the error "invalid_request - Invalid web redirect url" is thrown

**To Reproduce**
1. Click on "Trackt Scrobbling" Authenticate
2. User is redirected to Trakt Login mask "https://api.trakt.tv/auth/signin"
3. User tries to Sign in via "Apple"
4. Apple website throws "invalid_request - Invalid web redirect url.

**Expected behavior**
Login to Trakt via Apple is working and linking Trakt to Stremio Account

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS Sonoma
 - Chrome & Safari - same issue

**Comment by TRtomasz** [comment]
as written on reddit, this is not a stremio issue
