### ISSUE TITLE
Fire TV stick 4K Max - Screen turns brown when playing a movie file

### ISSUE THREAD

**Issue by Wahab417** [Stremio/stremio-bugs#747]
When I try to watch some movie files, the screen turns brown and I can’t see any control.

**To Reproduce**
1. Go to Top Gun Maverick
2. Click on the torrent with 74.44GB file size
3. Screen turns brown with no controls, while sound is playing

**Expected behavior**
The movie should play normally as it is playing perfectly on google chrome cast and samsung TV

**TV (please complete the following information):**
 - Device: Fire TV stick 4K max (2nd Gen)
 - OS: Android TV
 - Version 1.6.9
 
![image](https://github.com/Stremio/stremio-bugs/assets/167028601/fb88e39b-9e6d-4461-8982-43dcaad7ef77)
![image](https://github.com/Stremio/stremio-bugs/assets/167028601/ee10f24e-27fd-4026-b03e-da924d6e1977)

**Comment by TRtomasz** [comment]
not a stremio issuem we can fix issues that comes from exoplayer. You could try changing tunneled playback setting in the settings
