### ISSUE TITLE
Fire TV stick 4K max (gen 2)- Video is split when playing Dolby vision content

### ISSUE THREAD

**Issue by Wahab417** [Stremio/stremio-bugs#748]
When I try to watch some movie files, the screen shows in a grid with part of the movie screen repeated. After further investigation, I found out that this only happens with movies with Dolby vision it gets displayed as SDR on Samsung TVs. We need to have an option to disable Dolby vision.

To Reproduce

Go to Kung fu Panda 4
Click on the first torrent 15.9GB
Screen shows a weird grid 

Expected behavior
The movie should play normally as it is playing perfectly on google chrome cast and samsung TV

TV

Device: Fire TV stick 4K max (2nd Gen)
OS: Android TV
Version 1.6.9

![image](https://github.com/Stremio/stremio-bugs/assets/167028601/9c09b166-efe0-4314-be71-96378a382fd4)

**Comment by TRtomasz** [comment]
https://github.com/google/ExoPlayer/issues/11096
not a stremio issue, we can fix this.
