### ISSUE TITLE
UI bug in Windows: progress bar continually moving to left 

### ISSUE THREAD

**Issue by JonahGroendal** [Stremio/stremio-bugs#749]
**Describe the bug**
The progress bar shows the video continually seeking back in time in a loop. It starts at your current point in the video then zooms to the left across the screen until it's at the start, then resets to the point where you are at the video and starts again, over and over in a loop and never stopping. The video plays normally, but the progress bar is always showing, and user control of seeking the video is blocked.

**To Reproduce**
It's somewhat inconsistent, but happens most of the times I play a video. Simply play a video and observe the behavior. It isn't apparent until you're maybe 1/4 of the way through a video.

**Expected behavior**
Progress bar works properly and disappears when not being used.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Stremio desktop app
 - Version 4.4.168

**Comment by TRtomasz** [comment]
Please provided a video with the issue otherwise it is not possible to even imagine it.

**Comment by JonahGroendal** [comment]
Just tried to get a video but the bug isn't happening right now for some reason. It happens often though, so I'll update this issue with a video the next time it happens. Shouldn't take very long.

**Comment by JonahGroendal** [comment]
https://github.com/Stremio/stremio-bugs/assets/13501607/8975efcb-3a29-4f1c-ba3b-b2b36d38fa90

It took longer than usual to start happening again but here it is

**Comment by TRtomasz** [comment]
Closing as not reproducible i would guess that some button on your keyboard gets locked

**Comment by JonahGroendal** [comment]
That's not it. I've had it happen on multiple different systems with different OSs even

**Comment by TRtomasz** [comment]
@JonahGroendal  app has over 30 millions of users and you are the only one that reported such issue, i dont think so it is possible. Perhaps you used same keyboard with all the devices. And this looks exactly like someone keeps an arrow pressed down, once it gets to the begining it jumps back to the position where you started pressing it.

**Comment by JonahGroendal** [comment]
Not possible. One of the systems was a Google TV. The other was Windows

**Comment by JonahGroendal** [comment]
@PlayboiiiCartiii no I never found a solution but I've been watching on GoogleTV recently and haven't had it on there
