### ISSUE TITLE
stremio freeze on linux

### ISSUE THREAD

**Issue by logsanctuary** [Stremio/stremio-bugs#75]
With the lastest version after a few minutes of playing a video streamio freeze, download continue but there are no video.

**Comment by Ivshti** [comment]
Can you try to install/update vlc?

**Comment by logsanctuary** [comment]
It is the same with vlc, but i see they are only 10 seeders and a lot of waiting...could this come from the torrent stream ?

**Comment by Ivshti** [comment]
@logsanctuary can be; can you try with something other than bittorrent (discover -> channels or discover -> tv)
