### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by Dypanrich** [Stremio/stremio-bugs#752]
[**Describe](url
![20240417_173130](https://github.com/Stremio/stremio-bugs/assets/167435513/c59684e1-debe-47c8-bbbb-5f3c195dc299)
![20240417_173004](https://github.com/Stremio/stremio-bugs/assets/167435513/eac6a0af-2356-46bc-8c0f-40483284f5d6)
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**

**Comment by TRtomasz** [comment]
works fine on chromecast 4k so perhaps your device simply cant decode it.

**Comment by Dypanrich** [comment]
Firestick 4k error just started a week ago not on all streams though,

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
