### ISSUE TITLE
Android: cache size not respected, app ends up using ~10GB of space

### ISSUE THREAD

**Issue by dany123** [Stremio/stremio-bugs#755]
**Describe the bug**
I am using Stremio on an android tablet (Samsung Tab A8) with limited internal memory storage (32GB, about 10GB free) and Stremio ends up using it all of it every few weeks even though Cache size in settings is set at 2GB. 

**To Reproduce**
Use Stremio normally to watch stuff (various addons, mostly torrentio, (+/-RD) and superflix). Cache size in settings is set at 2GB.
Go into android settings -> Apps -> Stremio and check out the Storage size, it starts at ~150MB on a fresh install and it slowly goes up with usage and never clears itself down. 
Note: right now I'm watching an anime with 200-400MB episodes so it's not an issue of watching a 10GB movie that's being cached, the app doesn't seem to want to clean up old episodes.
Eventually I get the android "low storage space" warning and have to manually go to android settings -> Apps -> Stremio and manually clear data. Note that in android' settigns it's "Data" that increases, not Cache to easily clean it up.
The annoying part is that after clearing data I have to log in again + configure all my settings as they end up defaulted.

I've been doing this about every few weeks for the last year. I don't understand how this cache size works, is it doing something else entirely? Do [some?] addons ignore it? Does it matter if I start multiple shows/movies?

**Expected behavior**
Stremio's app size should never exceed the MAX of (cache size) and (current video size), automatically cleaning up older cached videos when set limit  is reached.

**Screenshots**
![1  cache size](https://github.com/Stremio/stremio-bugs/assets/3215812/b018feb9-7362-4d37-aa03-db0d146e5ebb)
![2  settings](https://github.com/Stremio/stremio-bugs/assets/3215812/6221d241-eca8-405a-ab4e-3586239255f1)

**Smartphone (please complete the following information):**
Stremio 1.6.12 (was the same for previous updates over the last year)
Samsung Tab A8, Android 14 (was the same on 13)

**Additional context**
Note: the tablet has a big microSD memory card with plenty of free space but Stremio doesn't use it even if moved to SD card in android's settings (I posted a feature request here: #https://github.com/Stremio/stremio-features/issues/423 regarding this a while back, but this is not related to the memory card, I am using Stremio on internal memory as default/standard as possible and the bug is still there, I just want to not have to clear data manually).

**Comment by TRtomasz** [comment]
Thats not a bug, this is how cache works, it will use as much space as a file you are trying to play. This will get cleared with the next file you starts playing.

**Comment by dany123** [comment]
Hello, please re-read my report, I already said this is **NOT** my case in the previous post:

> Note: right now I'm watching an anime with 200-400MB episodes so it's not an issue of watching a 10GB movie that's being cached, the app doesn't seem to want to clean up old episodes.

I've also cleaned up the data 3 days ago, watched only ~300MB episodes and storage is already at 3.6GB with cache limit at 2GB. This is clearly a bug.

**Comment by dany123** [comment]
So is this report going to remain closed for no reason?

**Comment by dany123** [comment]
Updating with a workaround in case anyone else is being affected by this: setting cache size to "no-cache" immediately clears all cached data. So at least this option works all the time and I don't need to clear data in android settings.

**Comment by Gater73** [comment]
Being getting the same issue in Win10, while working with "No cache" it works almost like regular streaming, but with cache set to 2GB it should, not cache more than 2GB, the downloading happens in a linear way so theres no reason the app shouldnt be able to cut the old file up if it exceeds 2GB, plus even if it is a 1GB file the apps still holds up old 1GB files until more than 15GB are consumed and my ssd gets full, please look at this developer, also take a look at the clear local storage, doesnt seem to works also

**Comment by dany123** [comment]
Try to post a brand new issue as it seems he misread my post and just ignored any reply after the closure.

**Comment by Uchihamadra793** [comment]
> **Describe the bug** I am using Stremio on an android tablet (Samsung Tab A8) with limited internal memory storage (32GB, about 10GB free) and Stremio ends up using it all of it every few weeks even though Cache size in settings is set at 2GB.
> 
> **To Reproduce** Use Stremio normally to watch stuff (various addons, mostly torrentio, (+/-RD) and superflix). Cache size in settings is set at 2GB. Go into android settings -> Apps -> Stremio and check out the Storage size, it starts at ~150MB on a fresh install and it slowly goes up with usage and never clears itself down. Note: right now I'm watching an anime with 200-400MB episodes so it's not an issue of watching a 10GB movie that's being cached, the app doesn't seem to want to clean up old episodes. Eventually I get the android "low storage space" warning and have to manually go to android settings -> Apps -> Stremio and manually clear data. Note that in android' settigns it's "Data" that increases, not Cache to easily clean it up. The annoying part is that after clearing data I have to log in again + configure all my settings as they end up defaulted.
> 
> I've been doing this about every few weeks for the last year. I don't understand how this cache size works, is it doing something else entirely? Do [some?] addons ignore it? Does it matter if I start multiple shows/movies?
> 
> **Expected behavior** Stremio's app size should never exceed the MAX of (cache size) and (current video size), automatically cleaning up older cached videos when set limit is reached.
> 
> **Screenshots** ![1  cache size](https://github.com/Stremio/stremio-bugs/assets/3215812/b018feb9-7362-4d37-aa03-db0d146e5ebb) ![2  settings](https://github.com/Stremio/stremio-bugs/assets/3215812/6221d241-eca8-405a-ab4e-3586239255f1)
> 
> **Smartphone (please complete the following information):** Stremio 1.6.12 (was the same for previous updates over the last year) Samsung Tab A8, Android 14 (was the same on 13)
> 
> **Additional context** Note: the tablet has a big microSD memory card with plenty of free space but Stremio doesn't use it even if moved to SD card in android's settings (I posted a feature request here: #[Stremio/stremio-features#423](https://github.com/Stremio/stremio-features/issues/423) regarding this a while back, but this is not related to the memory card, I am using Stremio on internal memory as default/standard as possible and the bug is still there, I just want to not have to clear data manually).

Bro I am facing similar issue it's frustrating how to solve this.

**Comment by dany123** [comment]
I just switched permanently to "No caching" and this has mostly solved the issue yet still happens very rarely so I just clear data and log in again.
I would guess this bug doesn't affect everyone so... probably will never be fully fixed.

**Comment by oleglucic** [comment]
As Tomasz has said, this is not a bug but the way caching works. The limit is a _soft limit_ and the app will always download the whole streaming file to ensure smooth playback. The only thing to prevent this is setting caching to none.

**Comment by dany123** [comment]
> this is not a bug but the way caching works

Hi Oleg, I'm a software developer and I understand how caching should work and I am certain there is an intermittent bug here regarding cleanup! Maybe the app gets put to sleep and the cleanup job isn't run properly on resume. I don't know how or why, but sometimes this works as expected and sometimes, **over a few weeks**, cache goes up until it fills up the entire storage. 

I've already mentioned that this happens even with small video files from different shows, there is no way a bunch of separate 300-500MB files need to remain cached over multiple weeks to the point they add up to >10GB. Especially since they are not part of the same stream (=different shows).

**Comment by buigilter** [comment]
Also a developer - affected by the issue described here - and it seems the Stremio support doesn't reads the requests with the appropriate level of attention or may need to require for a technical advice before closing this kind of request.

I also tried to catch your attention by creating another issue without success : https://github.com/Stremio/stremio-bugs/issues/1598

Should we go to the point where we have to make a local cron on every client that clear your cache ? :/

**Comment by oleglucic** [comment]
@dany123 Thanks for the detailed follow-up. As a developer, your perspective on this is really helpful, and you're right—what you're describing sounds less like a feature and more like an intermittent bug with the cleanup process. The app shouldn't be holding onto multiple small files from different shows to the point of filling your storage over several weeks. It's very plausible that the cleanup job is being interrupted, perhaps by Android's power management. To help the team get a clearer picture, could you tell me if this happens on any other Android devices you may have, or only on your Galaxy Tab? That would help narrow down if it's a device-specific issue.

**Comment by buigilter** [comment]
it is also happening on my computer on Ubuntu latest lts

**Comment by dany123** [comment]
> could you tell me if this happens on any other Android devices you may have, or only on your Galaxy Tab?

I mostly use Stremio on my Samsung Tab so this might not be very relevant.
On my phone (Samsung S24), Stremio is currently using 1.93GB (configured cache at 2GB), so the cleanup works perfectly here.

I think a major difference between the 2 devices is the amount of RAM, the tablet only has 3GB but the phone 8GB. The stremio app is likely killed way more often on the tablet by the android's automatic low memory manangement.

Btw, thank you for aknowledging the issue. Even if it won't get fixed too soon without a clear replication it is nice to not be completely shut down even after a detalied report.

**Comment by oleglucic** [comment]
I'm really sorry for the experiences of both of you. It looks like the issue is cross-platform, which makes this even more puzzling. For Android, it might be an interaction bug between Stremio's cache management and Android's low-level memory management on resource-constrained devices, which explains why low-ram devices don't flush cache on time. So, the bug is also available on Windows and Linux?

**Comment by TRtomasz** [comment]
There is no process that runs in the background, once you start another stream that requires cache, used space will be checked if cache size has been reached, files will be removed.

**Comment by dany123** [comment]
Can you make a build that logs this action for me to run and provide debug data (maybe list the cache contents as I don't have root to see it directly)

**Comment by TRtomasz** [comment]
you shoukd be able to see in the logcat logs information abou cache being cleared

**Comment by Gater73** [comment]
I switched to No Cache on my Arch Installation too, otherwise Stremio will literally eat up 200+ GB even with cache set to 2GB and i dont watch 4k, only 1080p, there is no file above 10gb in the cache directory either in Windows or Arch, this makes me not able to cache the entire thing and constantly have to close out of stremio completely before i can hit play again it i keep something open half way through and i feel like that might also nerf my ability to seed and there is no cache files, i would strongly suggest the devs do a completely lookover this caching system

**Comment by dany123** [comment]
I'll look into the logs tomorrow and get back with relevant info. Thanks.

**Comment by dany123** [comment]
I had Stremio's cache set to no-cache so it will take a few days until I get back into the bugged state.

I assume this is the interesting log to look for when cache gets bigger: 
`Resizing cache size to 0MB from 0MB by deleting 0 files`
For now it works correctly:
`Resizing cache size to 2048MB from 2588MB by deleting 6 files`

**Comment by dany123** [comment]
Took me 2 weeks but I managed to get the cache to ~5GB. I'm not sure this is clear from the logs but ALL files I watched were under 1GB. Most around 5-600MB per episode.


I think I have a theory: the cache worked correctly until I started mostly watching a single show using the torrentio addon and always choosing the same torrent/season swarm (torrentio can stream individual episodes from a full season package).
Is it possible that when using torrentio, the app considers the entire season as a "single file" and doesn't cleanup anything in cache until I switch to another show? So if an episode is 500MB, by the time I reach episode 10, the season is now using 5GB of storage and can't clean it up until I switch to a different show?


Note that I didn't have the logcat app running continuously for the 2 weeks, I only started it occasionally for data gathering and when I saw the cache go over 2GB. I hope it has useful data.
At the begining I watched multiple different shows (which is why I think the cache worked correctly).
I only started watching mostly a single show in the last week which is also when the cache went above 2GB consistently.
I still watched a few other shows during this - which is why I think the cache occasionally went down.
On the very last day of logs I intentionally clicked on multiple random episodes to see if the cache eventually got cleared -> it did, but not on the very first shows I clicked, it took a few random clicks.

I will continue to investigate on my side and I'm willing to install a debug build if you need me to.

link with the individual logcat recordings filtered by "com.stremio.one" (expires in 3 days): https://we.tl/t-IPSf24z3Lk

<img width="987" height="351" alt="Image" src="https://github.com/user-attachments/assets/dff9dca1-95d7-4d8c-a417-3a92d85ef2c0" />

**Comment by pdaryll** [comment]
any update on this?

**Comment by dany123** [comment]
For me the workaround of closing the app (force close or dismiss), then reopen and immediately play another show for a bit. As long as this works I'm fine with this not being a prioritsed bug.

This fully makes sense to me, Stremio/torrentio can't delete a file from an active torrent and it only checks for cache size after "starting" that torrent so it never has the chance to cleanup the cache if you're binge watching a show. 
A code fix would need to do the cache check at another time, but I imagine there's a bunch of complex conditions to be made (for example don't cleanup the cache if there's only one large file that has already been downloaded or if the user tries to play that exact older episode, etc). It will probably add more complexity than it's worth for the rarity of this bug.

**Comment by TRtomasz** [comment]
Lost it, what @dany123  wrote is true, multiple files from same torrent are considered one, it is not possible to partially remove them.
