### ISSUE TITLE
Android: Keyboard does not launch when the search field is selected

### ISSUE THREAD

**Issue by stewartie4** [Stremio/stremio-bugs#756]
**Describe the bug**
On Android TV the keyboard does not launch when the search option is selected on remotes that send a NUMPAD_ENTER keycode. 

**To Reproduce**
Using an amazon fire tv remote on a nvidia shield (or any other remote that sends NUMPAD_ENTER keycode)
1. Click on the search option on the menu
2. Press the "right" arrow to select the search field 
3. Press the select button on the remote when the field is highlighted
4. The onscreen keyboard will not launch

**Expected behavior**
It is bad user experience that the user has 3 key presses in order to search:
- click search option in menu
- click right arrow, past the mic option
- click the search field 
I would expect the onscreen keyboard to launch as soon as search option in menu in selected, or at least this behaviour being configurable in the settings.
Regardless of this, I would further expect NUMPAD_ENTER to also count as ENTER and the keyboard be launched.

**Screenshots**
<img width="1614" alt="image" src="https://github.com/Stremio/stremio-bugs/assets/18306778/21e73525-fa45-4184-85ad-1950cfe69c40">

**TV (please complete the following information):**
 - Device: Nvidia shield 
 - OS: Android TV
 - Version Latest google play release

**Additional Info**
Other people encountering the same issue: https://www.reddit.com/r/Stremio/comments/1626g1v/keyboard_not_appearing_when_clicking_on_the/

**Comment by TRtomasz** [comment]
Keyboard gets opened when you press dpad center button

**Comment by gloarb** [comment]
> Keyboard gets opened when you press dpad center button

No

**Comment by TRtomasz** [comment]
Closing as there is no bug.

**Comment by MaRmARk0** [comment]
Sorry guys with bothering again, but I have freshly installed Stremio on Chromecast 4K and am encountering exactly same bug. Keyboard is not opening whatever I do. 

As I have default Chromecast remote there's no numpad so I can't bring keyboard on by pressing a number (as someone on Reddit stated). My kids are furious about this. Currently we can't search without a phone in hand.
