### ISSUE TITLE
Screensaver Android TV Issue

### ISSUE THREAD

**Issue by KarthiSurfer** [Stremio/stremio-bugs#757]
**Describe the bug**
Im using Android TV and screensaver is automatically turning on while playing any video in stremio

**TV (please complete the following information):**
 - Device: [Acer TV R4]
 - OS: [Android TV]
 - Version [1.6.9]

**Comment by TRtomasz** [comment]
I guess if this was true we would see multiple reports from our users about it. I personally use tv app every day on multiple different devices and this has never happened.
