### ISSUE TITLE
Chromecast subtitles not working

### ISSUE THREAD

**Issue by jsf15** [Stremio/stremio-bugs#76]
Hey, 

this is the same issue as #17 an #58 and a bunch of others. I'm using a Chromecast 2.0 in any TV and I run a mid-2010 MacBook Pro with macOS Sierra. I'm using 3.6.5 Stremio version.
Basically I cannot stream the in-built subtitles to my Chromecast, they simply don't appear in there (is not a matter or resizing). Haven't be able to debug much but I've tried to only stream the video an then the subtitles and vice versa but nothing happens.

Could use a little help please

**Comment by Ivshti** [comment]
Hello, I re-opened the issue #17 

By "built in" you mean the ones which appear on the SUBS icon? If so, it's not the same issue

**Comment by jsf15** [comment]
Exactly those. I've tried a couple more times and some times it works some times it doesn't, it's very erratic.

**Comment by Ivshti** [comment]
should be solved now

**Comment by bbugarski** [comment]
@Ivshti Wich version will have the fix
I am currently running: 
Stremio 4.0.29
Server 4.1.30
Shell 4.4.7

Thanks

**Comment by missbruni** [comment]
is broken again...

Stremio 4.4.10
Web 4.4.17
Server 4.2.3

**Comment by kvn1351** [comment]
Please fix it.
