### ISSUE TITLE
Local Files Addon Fails to Display Downloaded Content in Series and Movies Sections

### ISSUE THREAD

**Issue by KijtIlHijrow** [Stremio/stremio-bugs#760]
### Describe the bug
The Local Files addon does not display any downloaded content in the "Series" and "Movies" sections, despite files being present and the add-on being installed. There is no error message; the addon simply fails to show the content.

### To Reproduce
1. Open Stremio.
2. Navigate to 'Series' or 'Movies'.
3. Attempt to view episodes or movies that have been downloaded locally and should be accessible via the Local Files addon.
4. Observe that the Local Files addon does not load or display the downloaded content.

### Expected behaviour
I expected the Local Files addon to display the episodes and movies that I downloaded through Stremio in the respective 'Series' and 'Movies' sections, allowing for easy access and organisation of local content.

### Screenshots and videos
All attached on my case 39553, where Karan advised me to raise the bug here.

### Desktop:
- OS: Windows 10
- Browser: Not applicable - using desktop app
- Version: 4.4

### Additional context
This issue has persisted despite following all troubleshooting steps provided by Stremio support, including manually removing and reinstalling the app and verifying that all relevant settings and options are correctly configured.

**Comment by TRtomasz** [comment]
Please tell us:
What are the names of example files?
Where are files located, is this an network disk? Do you have windows indexing enabled?
Do you have local addon enabled in the settings?

**Comment by KijtIlHijrow** [comment]
Thank you for your prompt response and guidance. Apologies for the delay; it took some time to configure and complete the Windows Indexing.

#### Details Requested:
- **Names of Example Files**:  
  1. `C:\Users\keith\Downloads\[Anime Time] The Seven Deadly Sins - 03.mkv`
  2. `C:\Users\keith\Downloads\[Anime Time] The Seven Deadly Sins - 04.mkv`
  3. `C:\Users\keith\Downloads\[Anime Time] The Seven Deadly Sins - 05.mkv`

- **Location of Files**:  
  The files are located on the device's primary disk (C:). Windows Indexing is enabled and has been completed as shown in the attached screenshot.

- **Screenshot of Windows Indexing**:  
  ![Windows Indexing Screenshot](https://github.com/Stremio/stremio-bugs/assets/109229591/6bc25ca3-778b-467e-91c8-01208fcd18d8)

- **Local Addon Status**:  
  The Local Files addon is enabled. I have attached a video link below demonstrating the settings configuration.

#### Attachments:
- **Video of Local Addon Settings**:  
  [View Video](https://github.com/Stremio/stremio-bugs/assets/109229591/fed9a8b6-712f-4b9a-b38b-b485a20acc49)

Thank you again for your assistance!

**Comment by TRtomasz** [comment]
It is not possible to parse these file names as series files names they are missing basic stuff as season episode indicator like `S01E01`

**Comment by KijtIlHijrow** [comment]
That did indeed fix them, thanks so much! Just figured that having downloaded them from Stremio, no modifications were necessary. Cheers, Tomasz!
