### ISSUE TITLE
Runtime 5.15-22.08 end-of-life report

### ISSUE THREAD

**Issue by S-Pz** [Stremio/stremio-bugs#761]
A runtime issue occurs with the org.kde.Platform branch 5.15-22.08. The branch is now end-of-life, and it is recommended to move to the latest Qt 5.15-based stable version of the Platform and SDK.

To reproduce the behavior flow :
- open the terminal command;
- type : `$ flatpack update`

Screenshots
![image](https://github.com/Stremio/stremio-bugs/assets/87339625/e88e210f-9062-4d46-9238-17aac3adcf6d)
![image](https://github.com/Stremio/stremio-bugs/assets/87339625/50028f53-c978-43e7-90ec-dc044e4f2e37)

Desktop:
OS: Linux (Pop!_OS 22.04 LTS)
Stremio Version: 4.4.168

**Comment by TRtomasz** [comment]
should be fixed https://github.com/flathub/com.stremio.Stremio/issues/25
