### ISSUE TITLE
initShellComm is not defined

### ISSUE THREAD

**Issue by FGYada1984** [Stremio/stremio-bugs#764]
**Describe the bug**
The application can't load the interface. I've uninstalled it completely (removing the user and cache files) reinstalled it and I've also tried connecting via vpn (nordvpn) and with google dns, cloudfare and nordvpn, when I try to open a title directly via the browser (https://app.strem.io/shell-v4.4/#/) in some titles it manages to load, but in the middle of playback it fails and then can't load anymore.

**To Reproduce**
1. Open App
2. See error

**Expected behavior**
load the app and play.

**Screenshots**
![Captura de tela de 2024-04-30 10-38-20](https://github.com/Stremio/stremio-bugs/assets/96778505/95461c87-0e20-4075-b8ab-4571d41a53d0)
![Captura de tela de 2024-04-30 10-53-39](https://github.com/Stremio/stremio-bugs/assets/96778505/00156652-9375-48ce-987b-a2a870ff930a)

**Desktop**
OS: openSUSE Tumbleweed x86_64
DE: GNOME 46.0 
APP: flatpak 4.4.168

**Comment by FGYada1984** [comment]
> [Downgrading](https://wiki.archlinux.org/title/Flatpak#Downgrade_a_runtime_or_application) it to the previous version will work. As far as I can see, only Tumbleweed users seem to be affected by this issue for now, but I don't know why.

you were right, I downgraded and everything worked normally again, thank you.

**Comment by FGYada1984** [comment]
> @FGYada1984 I think this is the solution: [#793 (comment)](https://github.com/Stremio/stremio-bugs/issues/793#issuecomment-2173290049)

Worked! Thanks a lot!

**Comment by JorgeDLS** [comment]
For any OSX users, install p11-kit with Homebrew executing `brew install p11-kit`

**Comment by mauricioklein** [comment]
For OSX users in Apple Silicon, installing `p11-kit` isn't enough.

There's, however, a re-compiled version of Stremio for M1 available [here](https://github.com/noripcord/stremio-m1)
