### ISSUE TITLE
stremio getting crashed after loading sometimes closes before even loads 

### ISSUE THREAD

**Issue by arrow00009** [Stremio/stremio-bugs#770]
**Describe the bug**
I have tested it on mi box 4k Android box and fire stick 4k (its unbearable in fire tv stick)

**To Reproduce**
1. Go to '...'stream big files 
2. Click on '....'play movie like avatar 
See crash both on fire stick 4k (andriod tv version ) and mi box 4k andriod tv version 1.6.9 on both devices

**Expected behavior**
Used to work on the same 1.6.9 3days ago now it crashes every 2mins

**TV (please complete the following information):**
 - Device: [ Mi Box S 4K, fire stick devices]
 - OS: [Android TV 12]
 - Version [1.6.9 stremio]

**Additional context**
I sometikes could able to stream for abit but since 3days something changed both fire tv and android version is unwatchable

**Comment by reachvineetjain** [comment]
I have a similar issue on the fire tv stick. Stremio application crashes and I am back at the home page. Once it even rebooted. There is no specific content it happens on. This might be an issue with the exoplayer as running content on a external player like vlc runs well.
