### ISSUE TITLE
Dolby Vision not playing on LG app

### ISSUE THREAD

**Issue by JoJoGatito** [Stremio/stremio-bugs#772]
**Describe the bug**
Files with Dolby Vision and HDR only play HDR on LG stremio app. They work on CCwGTV.

**To Reproduce**
1. Play file with Dolby Vision and HDR
2. App only plays HDR

**Expected behavior**
Dolby Vision being selected over HDR

**Screenshots**

**Desktop (please complete the following information):**
 - OS:

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: LG CX
 - OS: WebOS
 - Version 5.5.0-1107

**Additional context**

**Comment by TRtomasz** [comment]
Please do not compare android tv and web os app. These are two different apps running on different devices with different systems and capabilities. You should check for TV software update and then check again if dolby vision is working.

**Comment by jaruba** [comment]
an update won't solve this, LG TV does not support DV and it cannot be solutioned by us, the app can only play what the TV is capable of playing

**Comment by lokitech** [comment]
@jaruba can you please explain what do you mean by LG TV does not support DV since it is listed as supported here: https://www.dolby.com/experience/televisions/lg-cx-oled-tv/

Plus I can play it normally when using my Amazon Firestick.

Thank you in advance!

**Comment by jaruba** [comment]
we are sending a streaming url to the LG internal player, it decides if it can play it or not and if it can, it plays it

maybe ur TV supports DV, but it doesn't mean that it supports the audio codec used for that stream, or maybe it decides that it does not support 5.1 or 7.1 audio because it's not hooked up to some soundbar to offer support for it

regardless, Stremio does not control what the video player is capable to handle on LG TV, if it says it can't play it, then the TV surely decided that it can't

**Comment by mithunnivas** [comment]
i have similar problem, DV movies play fine on plex, disney, netflix. 
but only on stremio the screen images shows pink, blue etc colors.

**Comment by jaruba** [comment]
@mithunnivas disney and netflix probably say that the video is DoVi but streams HDR to you, Plex will transcode (from the external Plex server) the video for support on ur device, so you are probably not playing DoVi there either

LG TV internal player supports what it supports, depending on the TV you purchased the video / audio support may be different, we cannot add DoVi support magically where there is none

**Comment by mithunnivas** [comment]
i have a LG CX 77 inch tv. 
when i play DoVi files the logo pops up and shows on apple tv also.

**Comment by jaruba** [comment]
Not sure what to tell you more than I already did, we send the files to the LG TV internal video player and they play it, HDR works fine this way and we do nothing special for it, if it refuses to play DoVi properly, i really don't know what we could do about that

**Comment by krebsf01** [comment]
> Not sure what to tell you more than I already did, we send the files to the LG TV internal video player and they play it, HDR works fine this way and we do nothing special for it, if it refuses to play DoVi properly, i really don't know what we could do about that

I just want to add that the problem seems to occur when playing mkv files, today I tried playing a MP4 file with real Debrid and DV worked fine

**Comment by makapav** [comment]
I can confirm that I have the exact same issue where DV files that do not have the .mp4 extension produce a pink hue. Only HDR files playback fine in any format. That being said, I've also seen when a movie is paused for too long, the LG internal video player surfaces and its UI takes over.

I suspect this cannot be fixed by the Stremio team but I came here to update with my the experience and add that the issue still exists.

**Comment by JasonBSteele** [comment]
> I can confirm that I have the exact same issue where DV files that do not have the .mp4 extension produce a pink hue. The issue also happens on lots of Real-Debrid files that don't seem to have any file extension. Only HDR files playback fine in any format. That being said, I've also seen when a movie is paused for too long, the LG internal video player surfaces and its UI takes over.
> 
> I suspect this cannot be fixed by the Stremio team but I came here to update with my the experience and add that the issue still exists.
> 
> PS On LG TVs, at least the OLED generations (2021 C1) the TV identifies if it is playing back an HDR or a Dolby Vision/ DV videostream. In this case of the pink hues, no such detection notice pops up for the .mkv DV files or those without any file extension.

As quoted and still happening today on an LG C3

**Comment by thiago-mota** [comment]
Well, reading some comments here made me realize that my LG C4 only wont reproduce DV if its a MKV file. 

Mp4 work just fine
