### ISSUE TITLE
LG TV App: Posters/background art not appearing when playing media

### ISSUE THREAD

**Issue by jservs7** [Stremio/stremio-bugs#776]
**Describe the bug**
When trying to play any movie or series via the LG TV app, the media title image will appear, but no background or posters will load. This feature works fine when using Stremio via a Chromecast. 

**To Reproduce**
Open any available movie or series episode. 

**Expected behavior**
The title image will play along with a background image/poster of the movie or series episode. 

**TV (please complete the following information):**
 - Device: LG C3 OLED OLED65C3PUA
 - OS: LG WebOS 
 - Version: 03.30.76

**Comment by TRtomasz** [comment]
I do not understand what is the issue, could you please provide a video of the issue?

**Comment by jservs7** [comment]
Backgrounds NOT showing on LG app:

https://uploadnow.io/f/fm5H4gM

Backgrounds showing on Chromecast app:

https://uploadnow.io/f/KhRn0rd

**Comment by jservs7** [comment]
Just re-opened with links to videos.

**Comment by TRtomasz** [comment]
This is not a bug, these are two separate apps so they do not share functionalities
