### ISSUE TITLE
Second monitor issue

### ISSUE THREAD

**Issue by VladV1V** [Stremio/stremio-bugs#777]
**Describe the bug**
Whenever I move stremio app to my bigger monitor I am unable to tap buttons that give many choices
![image](https://github.com/Stremio/stremio-bugs/assets/53034271/6d4087a1-9772-4d78-8606-f500df3e9e63)

**To Reproduce**
1. Just drag stremio to the second monitor and tap the year choice for example. The choice won't appear and there will only be white overlay. If I do drag stremio back to my main monitor then it works

**Expected behavior**
Ability for it to work on the second monitor as well

**Desktop (please complete the following information):**
 - OS: Windows (On Linux it works and on Windows not)
 - Browser: Desktop version
 - Version: 4.4

**Comment by TRtomasz** [comment]
i'v just checked and everything is fine, what size/resolution is your 'bigger monitor'?
