### ISSUE TITLE
Watched shows missing from main screen

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#778]
**Describe the bug**
Watched shows missing from the Continue watching section 

**To Reproduce**
1. Watch something
2. Exit the app 
3. Open it again

**Expected behavior**
For the watched shows to show on the main screen continue watching section 

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit 
 - Browser Brave
 - Version 1.65.130

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12 MIUI 13 
 - Browser Brave
 - Version 1.65.126

**TV (please complete the following information):**
 - Device: Fox Led TV 32DLE188
 - OS: Android
 - Version 7 

**Additional context**
/
![Screenshot_2024-05-08-22-50-42-519_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/446b1f1e-0d9f-4675-a228-8252d20c6ccb)
![Screenshot_2024-05-08-22-50-56-707_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/092a8881-f162-4d51-b588-39a93d77d904)

**Comment by TRtomasz** [comment]
cant reproduce
