### ISSUE TITLE
Description Bug - Samsung TV app

### ISSUE THREAD

**Issue by xlrdrgz** [Stremio/stremio-bugs#785]
**Describe the Bug**
The description or synopsis for a media won't update (apparent on series). T

Uploading 20240510_202323.mp4…

he description or the synopsis will only refresh AFTER the media has been loaded or watched.

**To Reproduce**
1. Select a Media (apparent on series or titles with multiple episodes)
2. Select a Season
3. Scroll through the episodes
4. Synopsis from the first episode will show up on a different unrelated episode.

**Expected Behavior**
Synopsis or description must CHANGE depending on the episode.

**TV**
 - Device: [Samsung URU7100]
 - OS: [Tizen 5]
 - Version [Theater v1.2.1]

**Comment by kKaskak** [comment]
this was fixed in the new version.
