### ISSUE TITLE
Official OpenSubtitles add-on does not show all subs available on the website   

### ISSUE THREAD

**Issue by jan-kleks** [Stremio/stremio-bugs#787]
**Describe the bug**
The official OpenSubtitles add-on does not show all subs available on the website: https://www.opensubtitles.com/

**To Reproduce**
1) Look for subtitles, e.g. for this movie: https://www.imdb.com/title/tt0416044/ on https://www.opensubtitles.com/
2) Look for subtitles, e.g. in Polish -- there are 3 pages of available subtitles
3) You cannot see any Polish subtitles in Stremio

**Additional context**
- the problem occurs on mobile and on desktop
- the problem is also mentioned here: https://old.reddit.com/r/Stremio/comments/1bc9na1/opensubtitles_not_fetching_all_the_available/ and here: https://old.reddit.com/r/Stremio/comments/18ripdc/why_opensubtitlesv3_is_not_showing_all_options/
- there are also AI-generated subtitles on https://www.opensubtitles.com/, it might be interesting to be able to turn them on in the official add-on as well (optionally, of course as there might be a difference in quality vs those created by humans)

**Comment by ahmadesat** [comment]
I am facing same issue as well.
It simply doesn't fetch all the subs available.

Other people pointed out that most sub files are "incompatible" with Stremio, so I'm not sure where to go from there.
Hoping that Stremio team would find a way to make all the sub files work.

**Comment by TRtomasz** [comment]
There is no bug, i'v checked few subtitles files for polish language, they all have CD1 in their names suggesting that there are more files for other CDs. Like in older times movies were split on multiple CDs. We filter out subtitles with CD1/CD2 in the name because they usually cover only part of the video. You can always download them manually and drag and drop into stremio if you use desktop app.

**Comment by jan-kleks** [comment]
@TRtomasz I can see your logic when it comes to the movies split onto multiple CDs. However, I cannot see **ANY** subtitles in Stremio for the movie I mentioned above... Maybe something else is wrong with the filtering?

Another example of a movie with many subs on OpenSubtitles website, and none showing in Stremio: https://www.imdb.com/title/tt0365748/

**Comment by TRtomasz** [comment]
Same issue all marked as `CD1`

**Comment by jan-kleks** [comment]
@TRtomasz I am sad :( because I really do not want to sound ungrateful (for your awesome work!), or as if I am wasting your time but I think the issue is really there.

I have found out there was a little discussion regarding this very problem on reddit: https://old.reddit.com/r/Stremio/comments/1ct03fd/official_opensubtitles_addon_does_not_show_all/

And this discussion brought might attention [to these exact subtitles](https://www.opensubtitles.com/en/subtitles/shaun-of-the-dead-2004-1080p-bluray-h264-aac-rarbg). **And as you can see they are in the srt format, and no CD1 in the file name.** As this is a pretty popular movie, it is really weird that I can't see these (seemingly meeting your criteria), or for that matter any other Polish subtitles when watching it.

[Another movie, and another example, of the unavailable subtitles seemingly meeting your criteria.](https://www.opensubtitles.com/en/subtitles/king-arthur-2004-extended-1080p-brrip-x264-yify)

I can also see, based on the info from that reddit thread, that you also limit the subtitles based on their number:

> We filter out subtitles that have `CD1` or `CD2` in their name also filter out subtitles that are not in `srt` format and we limit max subtitles to 500 and max subtitles per language to 25.

Maybe by mistake you filter the good srt ones as well...

Tested both on Linux desktop and Android TV including various versions of the same movies.

**Comment by TRtomasz** [comment]
There is no bug or issue this is different api not used by stremio

**Comment by jan-kleks** [comment]
@TRtomasz These exact subtitles linked above are available on [the older OpenSubtitles website](https://www.opensubtitles.org/en/subtitles/6536942/shaun-of-the-dead-pl) as well. Does the OpenSubtitles api not give you access to every srt subtitle for some reason?

I do not quite understand where is the difference...

**Comment by jan-kleks** [comment]
@TRtomasz There is also this unofficial OpenSubtitles "UFO" add-on, and it seems to download lots of subtitles for all the movies I mentioned in this thread, so there is definitely room of improvement when it comes to the official add-on.

Keep up the great work!
