### ISSUE TITLE
Stremio battery drain

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#791]
**Describe the bug**
Stremio drains too much battery

**To Reproduce**
Use the app

**Expected behavior**
For the battery to last longer

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit 
 - Browser Brave
 - Version 1.65.132

**Smartphone (please complete the following information):**
 - Device: Redmi 9 
 - OS: Android 12 MIUI 13 
 - Browser Brave
 - Version 1.65.132

**TV (please complete the following information):**
 - Device: FOX 32DLE188
 - OS: Android
 - Version 7

**Additional context**
/ 
![Screenshot_2024-05-14-12-36-57-982_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/6c1a046f-de5a-4544-b3fa-b124ed9235d1)
![Screenshot_2024-05-14-12-37-05-538_com android settings](https://github.com/Stremio/stremio-bugs/assets/18757054/1c016725-916d-449e-af16-b8fd2b3e5ce7)
![Screenshot_2024-05-14-12-36-21-999_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/e97c391a-33b0-4061-9820-66735f2868d0)

**Comment by TRtomasz** [comment]
There is no bug here to fix, watchin videos requires decoding which might use batttery faster then other applications. You might disable hardware acceleration in the settings, some videos might not work then.

**Comment by GKid94** [comment]
I watch videos on Tik Tok, Instagram and YouTube and they don't drain battery

**Comment by GKid94** [comment]
> These apps are not comparable. It is like comparing playing tetris to playing GTA.

All of them are video apps with same resolution videos
