### ISSUE TITLE
Unable to change audio track on WebOS 

### ISSUE THREAD

**Issue by Roirenardz** [Stremio/stremio-bugs#794]
**Describe the bug**
I cannot seem to find a way to change the audio track on WebOS, contrary to option available on Android version for example 

**To Reproduce**
Play a track with multiple Audio tracks. No option to changr audio track on WebOS. Same source has the option on Android. 

**Expected behavior**
Ability to change audio track. 

**TV (please complete the following information):**
 - Device: LG G3 
 - OS: Webos
 - Version 03.30.76

**Additional context**
Add any other context about the

**Comment by KetanM94** [comment]
@Roirenardz 
I faced the same issue and found a workaround.
This is how I do it:
Play the video and press back immediately. Then play the same video again. Now you'll see the option to change audio tracks.
I tested with 3 different videos and it worked as I described above.
It may or may not work for you. Please test this and see if it works for you.

**Comment by KetanM94** [comment]
Video shown here
https://github.com/Stremio/stremio-bugs/issues/792#issuecomment-2119183655

**Comment by jaruba** [comment]
closing in favor of: https://github.com/Stremio/stremio-bugs/issues/792
