### ISSUE TITLE
Stremio hangs on latest Ubuntu version

### ISSUE THREAD

**Issue by MrNull42** [Stremio/stremio-bugs#80]
When launching certain videos(movies/episodes) the app hangs.
It hangs after clicking on the Juan Carlos Torrents under Available streams.

Doing the same process on a windows computer working fine.

**Comment by rodrigoejcm** [comment]
Same issue on 16.04 LTS. Did you find any solution? @Manwelangelo @ZeevM3

**Comment by ZeevM3** [comment]
Installed windows. :+1:

**Comment by rodrigoejcm** [comment]
Really? 
Downloaded vlc for the proper codecs and libs.
Everything's working now.
You could mark this thread as DONE as this is not a stream.io issue

**Comment by ZeevM3** [comment]
@rodrigoejcm oh i disagree.
This is a stremio issue as there're no error messages or any available information for the users to try and solve the issue themselves.

App hangs - isn't an issue i'd close.

**Comment by jleonardolemos** [comment]
I just installed vlc: sudo apt-get install vlc
It is working now!!!
