### ISSUE TITLE
Stremio displays wrong subtitle track from media with internal subtitles (served from addon)

### ISSUE THREAD

**Issue by carlosvsilva** [Stremio/stremio-bugs#800]
**Describe the bug**
My AndroidTV stremio is configured for portuguese (Portugal) subtitles, and secondary english.
But when I watch a movie from Orion addon, with internal subtitles, or from any provider, featuring subtitles in many languages, including portuguese (portugal) and brazilian, Stremio displays the brazilian subtitle, and I'm forced to manually select the correct portuguese (Portugal) subtitle, for every media...Please look into this, so languages are correctly chosen, as a TV is not the most interactive device, used when people are tired and relaxing. Thanks.

**To Reproduce**
1. Set stremio global subtitle options to Primary: Portuguese Portugal , Secondary: English
2. Go to the library or home, select a movie, choose an Orion served file, and start watching.
3. Subtitles are displayed, in brazilian language.
4. I'm forced to pick up the remote and go mess around with subtitles to direct Stremio to the correct Portuguese subtitle track.

**Expected behavior**
See media in Portuguese language

**TV (please complete the following information):**
 - Device: Sagemcom DIW377
 - OS: Android TV 12
 - Version: latest

**Additional context**
Annoyance level

**Comment by TRtomasz** [comment]
This is outside our control. IF embedded subtitles are not correctly described within the video file(happens in a lot of cases with PT-BR subs) it is not possible to automatically pick them
