### ISSUE TITLE
Unable to select audio track on some (mostly large files) WebOS LG C2

### ISSUE THREAD

**Issue by py4747** [Stremio/stremio-bugs#801]
**Describe the bug**
Unable to select audio track on some (mostly large files) WebOS LG C2. A lot of very large 4K files just revert to a random language or the commentary track and the icon to select the audio track doesn't appear. I've tested these files on PC and Android and they have many audio track options, but WebOS just doesn't show me audio track button to select.

**To Reproduce**
1. Go to 'Stremio and play random very large files ( like ones that are 80gb).'
2. Click on 'the said file'
3. Scroll down to 'the place you usually see the audio track button'

**Expected behavior**
To see the audio track butto and be able to select the English audio track.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [LG C2]
 - OS: [WebOS]
 - Version [Latest]

**Additional context**
Thanks

**Comment by StreamScream** [comment]
Yes this is a must fix. Hopefully it's fixed soon.

**Comment by TRtomasz** [comment]
Should be fixed in the next release

**Comment by onfire-d** [comment]
> Should be fixed in the next release

Is there any ETA for next release?
