### ISSUE TITLE
Stremio crashes upon finishing loading the media

### ISSUE THREAD

**Issue by claudiodamache** [Stremio/stremio-bugs#803]
After I select the source, the media finishes loading as normal, but as the video is about to start, the app crashes.

I have the OS and the drivers fully updated and I've reinstalled Streamio, but the app still crashes at the same time as before.

**Desktop :**
- Asus Tuf gaming f15
 - OS: Windows 11
 - Version 23H2

**Comment by TRtomasz** [comment]
Try enabling hardware accelerated decoding in the settings and try again

**Comment by claudiodamache** [comment]
I have done that and tried reinstalling the addons but it still crashes upon finishing loading

**Comment by TRtomasz** [comment]
Try removing your GPU drivers using DDU and install them again after this.
