### ISSUE TITLE
Subtitle Improvements Needed

### ISSUE THREAD

**Issue by quincyp** [Stremio/stremio-bugs#804]
Android TV:
subtitle items (vertical offset, size, background color, etc) only accessible via home > settings > playback. Should be accessible from video playback subtitle menu (like Samsung TV stremio)

Samsung TV:
vertical offset is accessible via video playback subtitle menu, but only increments by 5% instead of 1% (like Android TV stremio)

Lastly for both I would suggest an option to select from a few default font options and potentially increase outline size.

**Comment by TRtomasz** [comment]
First of all this is not a bug report. Also please do not discard the bug report template when reating an issue. If you have improvmenets ideas you should create an issue in stremio-features repository. And use the template
