### ISSUE TITLE
Subtitle moving out of sync (android mobile / smart tv)

### ISSUE THREAD

**Issue by georgettica** [Stremio/stremio-bugs#805]
**Describe the bug**
After a few minutes of watching a video via a addon, the subtitles move out of sync (sometimes they return to sync too)

**To Reproduce**
1. Open any video
2. Add subtitles 
3. If needed, manually sync and start playing 
4. After a while the subtitles will go out of sync
5. Aka, see bug

**Expected behavior**
2 acceptable solutions with increasing complexity:
1. Don't allow the subtitles to get out of sync 
2. Add a "resync" button to attempt to auto sync the subtitles 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel (fairly new)
 - OS: Android 
 - Browser: stock browser
 - Version: 14

**TV (please complete the following information):**
 - Device: Samsung 50Q64B
 - OS: Android TV
 - Version [e.g. 2.0.0]

**Additional context**
Specific video / videos will be given per request (and not on the issue itself)

Willing to debug / extract as many data points needed to triage this issue better.

Mobile is my main driver, if TV data points are needed it will take me more time

**Comment by catalinp82** [comment]
This is a Stremio bug. Yes, Stremio is not responsible for subtitles quality or their synchronization, but the problem is that sometimes the desynchronization happens after manual synchronization.

**Comment by kelvincesar** [comment]
Yes, this happens with me too.

It gets out of sync after sometime watching...
