### ISSUE TITLE
Issue with Jeopardy on Catalogue 

### ISSUE THREAD

**Issue by kkerasounlis** [Stremio/stremio-bugs#807]
**Describe the bug**
Jeopardy episodes don't show up anymore in links after the change in seasons that happened today

**To Reproduce**
Go to Jeopardy, find an episode and see how the addons don't bring episodes today 

**Expected behavior**
See the associated episodes when clicking on Jeopardy episodes, as I did yesterday.
![Screenshot_2024-05-24-15-47-49-582_com stremio one](https://github.com/Stremio/stremio-bugs/assets/29676295/dca4e217-b954-4742-8c00-ac584a852097)

**Screenshots**
Screenshots added and all platforms (tv, pc, cell phone, mi box) show the same

**Comment by TRtomasz** [comment]
Stremio does not provide streams, they are provided by addons, so ther is no bug in stremio regarding missing streams

**Comment by kkerasounlis** [comment]
It's most probably an issue with Cinemeta which is associated with Stremio and is the default add on
