### ISSUE TITLE
Not able to type the letter "l" in the email field for logging in

### ISSUE THREAD

**Issue by rp1231** [Stremio/stremio-bugs#809]
**Describe the bug**
While trying to log in to stremio with your email account, I'm not able to type the letter "l" of @gmail.com in the input field

**To Reproduce**
1. Install stremio on windows 11
2. Try to type in your gmail address in the email input field

**Expected behavior**
You should be able to type in the letter "l"

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Stremio desktop app
 - Version: Stremio 4.4.168
                 WebUI 4.4.172
                 Server 4.20.8

**Comment by eyalkapon** [comment]
I tried to reproduce the error, but it didn't happen. Does this bug continue to occur?

**Comment by TRtomasz** [comment]
Perhaps check your keyboard
