### ISSUE TITLE
Continue watching,shows disappears without completion had to search again for the show

### ISSUE THREAD

**Issue by arrow00009** [Stremio/stremio-bugs#810]
**Describe the bug**
Not sure exactly when this happens,the show i was watching keeps disappear after episode ends even though it has episodes left and more seasons

**Expected behavior**
Usually it only should be happening after end of season and no more episodes left right 

 

 - Device: [fire stick 4k ]
 -
 -

**It kept happening to many shows i was watching suddenly the show removed from continue watching list

**Comment by arrow00009** [comment]
I noticed ite happening when i complete the episode and go back ,the show disappearing

**Comment by TRtomasz** [comment]
If you dont have 'auto play next episode' enabled in the settings new episodes will not be added to the continue watching.
