### ISSUE TITLE
Embedded subtitles showing as unknown in Samsung tv

### ISSUE THREAD

**Issue by lucasgrizante** [Stremio/stremio-bugs#811]
Hello

My tv is a Samsung qn90b, and when trying to watch some anime episodes (you can test it using Delicious in dungeon through torrentio), for embedded subtitles, they work but the name is "unknown", so it is pretty hard to find my language, as I have to test all subtitles (more than 25).

Also, it seems it doesn't load the open subtitles v3 to select there.

Thanks for the awesome app and for supporting the TV.

**Comment by TRtomasz** [comment]
This is not a stremio bug, some TVs are not able to recognize embedded subtitles. We are working on a workaround.
