### ISSUE TITLE
Subtitle black border too big 

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#812]
**Describe the bug**
The black border is too big and it's blocking the video

**To Reproduce**
1. Play video
2. Go to subtitle settings 
3. Enable black border 

**Expected behavior**
For the black border to be smaller like subtitle size or transparent, or add a outline on subtitles

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser Brave
 - Version 1.66.113

**Smartphone (please complete the following information):**
 - Device: Redmi 9 
 - OS: Android 12 MIUI 13 
 - Browser Brave
 - Version 1.66.113

**TV (please complete the following information):**
 - Device: FOX 32DLE188
 - OS: Android 
 - Version 7

**Additional context**
/ 
![Screenshot_2024-05-26-02-12-31-560_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/efca62d7-81d8-4aed-93fa-a5ec4f349499)
![Screenshot_2024-05-26-03-57-19-553_com miui securitycenter](https://github.com/Stremio/stremio-bugs/assets/18757054/101ca1ab-d121-4c7f-86fa-34cf3f0ec613)
![Screenshot_2024-05-26-03-57-52-394_com stremio one](https://github.com/Stremio/stremio-bugs/assets/18757054/bf9d2e78-3dab-4208-942d-4b3312d4d3cf)

**Comment by TRtomasz** [comment]
This not a border but background color. There is no option to configure border in android mobile app

**Comment by GKid94** [comment]
Can you add it?
