### ISSUE TITLE
Embebbed Subtitles issue on Lg WebOs 

### ISSUE THREAD

**Issue by Gonzas2000** [Stremio/stremio-bugs#813]
**Describe the bug**
The embebbed file subtitles are pixelated and almost impossible to read while any external subtitle work flawlessly 

**To Reproduce**
1. Just open any movie that as embebbed subtitles and option to select external ones
2. Select embebbed and check the problem 
3. Select external to compare the difference 

**Screenshots**
Embebbed ( Bigger and super pixelated almost without black border )
![IMG_0216](https://github.com/Stremio/stremio-bugs/assets/170902159/fd5d52aa-d7ed-4e2b-ba07-3cd694adccfa)

External ( Just Right and fully adjustable)
![IMG_0217](https://github.com/Stremio/stremio-bugs/assets/170902159/4f149411-8b1f-483a-83dc-1ff09d609cb9)

** TV LG OLED65G45LW 
 - OS: [Lg WebOs - 0.3.10.42]
 - Stremio Version [Theater 1.3.0]

**Additional context**
Please fix this issue because on the rest the app is just perfect

**Comment by Gonzas2000** [comment]
Update: Just found out that while changing the embebbed subtitle size, the subtitles have more resolution and then when set it drops back to pixelated

**Comment by TRtomasz** [comment]
Stremio does not render embedded subtitles, they are rendered by the internal webos player we do not controll how they look.
