### ISSUE TITLE
File selection persists

### ISSUE THREAD

**Issue by LJPLux** [Stremio/stremio-bugs#814]
**Describe the bug**
Browsing to an episode of a series displays multiple streams provided by the torrent provider.
Selecting any episode first however will persist the selected file, even after switching to another stream eg the first stream didn't have subtitles, while the subsequent selected stream did have subtitles.
This could be because the app redirects the file reference to match the title of the episode with the first played stream associated with it.

**To Reproduce**
1. Browse to any episode of a series with multiple streams available that differ (with and without subtitles)
2. Select the first or any stream without subtitles
3. Exit the playback
4. Select another stream with subtitles
5. Subtitles won't load, probably because it plays the first stream which had no subtitles

Navigating to another episode in another season and selecting an episode with subtitles as the first choice does load the subtitles.
Probably because the title is different and new file reference needs to be made.

**Expected behavior**
I expect that stream to be played which I selected last, not the one I selected previously which turns out to be not desired.

**TV**:
- Device: LG CX
- OS: WebOS 5
- Version 1.3.0

**Comment by TRtomasz** [comment]
How do you know first file does not have subtitles? How do you know next one has subtitles? Also what kind of subtitles do you mean? Addon subtitles or embedded subtitles
