### ISSUE TITLE
The Samsung TV app doesn't show "Brazilian Portuguese" as a language for subtitles anymore.

### ISSUE THREAD

**Issue by PauloDand** [Stremio/stremio-bugs#818]
Stremio separates Brazilian and European Portuguese subtitles as two different languages. It has always been this way.

The Samsung TV app doesn't show "Brazilian Portuguese" as a language for subtitles anymore, in any show or movie.
Only European Portuguese is available under the "Portuguese" label.
This only happens on the Samsung TV. The Android App, the Windows App and the Web version all work normally, therefore I believe this is not and problem with the OpenSubtitles addon.

I don't know if this was an attempt to clean the language selection list, with the intent of making both Brazilian and European available inside the "Portuguese" category. If that was the case, this implementation has deleted the Brazilian language.

**To Reproduce**
1. Open the Stremio App on the Samsung TV
2. Go to any movie or episode of any TV show
3. Play the content
4. Open the subtitle menu and look for "Brazilian Portuguese"
5. Only "Portuguese" is available. And it's entirely European Portuguese.

**Expected behavior**
"Brazilian Portuguese" should appear as a language right next to "Portuguese"

**Screenshots**
![img-2024-05-28-12-59-21](https://github.com/Stremio/stremio-bugs/assets/47481878/4b49dfbb-bef0-4ce2-8afa-afbb8b63437f)

**TV (please complete the following information):**
 - Device: Samsung TV - QN85A
 - OS: Tizen 2210 (Samsung)
 - Version [Theater v1.3.0]
 - Platform [Tizen 6]

**Additional context**
The term "Portuguese" is how Lusophonic speakers usually refer to "European Portuguese", spoke in Portugal. 
While "Brazilian Portuguese" refers to the Brazilian spoke in Brazil and most foreigners learning the Portuguese language, representing the majority of speakers of the whole Portuguese language.

**Comment by jaruba** [comment]
we know of this issue and we fixed it, it will be available in the next update
