### ISSUE TITLE
Hdr issues when frame rate matching is turned on

### ISSUE THREAD

**Issue by Blockr22** [Stremio/stremio-bugs#819]
**Describe the bug**
My setup includes shield tv 2017->Philips hue sync box->Tcl 55S535 tv’s hdmi port 1-> Tv’s Arc port to Lg LAC7 soundbar arc port for audio. Issue with stremio messing up audio/video when frame rate matching is turn on. Tv’s screen goes buzzerk, hdr logo flashing, black screen, star screen, video/audio flash for a sec & then black screen, over & over. Shield tv is unresponsive, roku os on my tv works. Only solution after this is to restart both shield & my tv. Only then it works. Also playing hdr video’s in stremio when frame rate matching is turned on, stremio lags a bit when playing video or after it’s stopped. Hdr movie/show might work once or twice without issues but after that shield signal to my tv glitches out.

It only happens with frame rates switched on. I hope frame rate matching gets fixed soon, until then i guess i will switch it off. 

I can add a video of the issue’s if needed. Thnx

**Comment by TRtomasz** [comment]
Framerate matching is not something stremio implements, we simply use the provided Android TV functionality. So it looks like issue is with you hardware configuration perhaps because Philips hue sync box is cauing this.

**Comment by Blockr22** [comment]
Kk, thnx. Will check with another sync box update
