### ISSUE TITLE
Chromecast not working

### ISSUE THREAD

**Issue by roydbt** [Stremio/stremio-bugs#82]
Streaming from latest version of stremio to newly purchased Chromecast.
It displays for 2 seconds like it's trying to play the show and then return to the blue icon and get stuck

**Comment by Ivshti** [comment]
a few questions:
1. Is it happening with all the content?
2. Can you try with official stremio add-ons, like the content you can find in Discover -> Channels or Discover -> Live TV
3. which operating system are you using?

**Comment by roydbt** [comment]
1. Tried it with Luke Cage 1x04 and The 100 1x02
2. I am using Juan Culters Torrents because "official stremio add-ons" aren't free.
3. Windows 10
