### ISSUE TITLE
Viewport bug in minimized mode in 14 inch or smaller display (PC)

### ISSUE THREAD

**Issue by fahim-42** [Stremio/stremio-bugs#820]
**Describe the bug**
PC with 14-inch or lower screens can't reduce stremio's window size since it is limited by default. Sometimes the default size is larger than the pc's viewport. Trying to minimizing stremio's window causes to slide the app away from the viewport and cannot be brought back into view, app's restart in compulsory to fix this problem. Can't use stremio unless it is in fullscreen mode.

**Expected behavior**
Stremio should be able to minimize at least 2/5 of the window's default viewport on all devices.

**Screenshots**
<img width="960" alt="Stremio-default-minimized-view-14inch-display" src="https://github.com/Stremio/stremio-bugs/assets/86187674/c799aa53-2edf-4b95-96c3-3e45c3775d02">

**Desktop (please complete the following information):**
 - OS: Windows 10 | Version 22H2; WIndows 11 | Version 23H2
 - Stremio Desktop App
 - Version 4.4.168 | Web UI 4.4.172 | Server 4.20.172

**Comment by TRtomasz** [comment]
minimum windows size is 1000/650 if you cant make window lower than this i guess you are using super old laptop with very small resolution and perhaps windows scaling set to very high value.
