### ISSUE TITLE
Stremio crashing when copying text by dragging

### ISSUE THREAD

**Issue by Teenam** [Stremio/stremio-bugs#822]
**Describe the bug**
Stremio crashing when copying text by dragging. If you highlight the text for example on the search bar and then click and drag the selection anywhere, Stremio will crash.

**To Reproduce**
1. Go to the search bar
2. Type some words 
3. Highlight the words 
4. click on it and just drag it in any direction

**Expected behavior**
After dragging the text, for my machine, the program will be unresponsive right away, and after about 3-7 seconds or so the windows pop up where it says the program is not working and would you like to close it or wait for it shows up.

**Screenshots**
You prolly can do it easily 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 10.0.22631 Build 22631
 - Stremio Ver 4.4.168
 - Web UI 4.4.172
 - Server 4.20.8

**Comment by TRtomasz** [comment]
It happens cause you try to drag and dropp text inside stremio again, if you try to move it outside stremio window nothing will happen
