### ISSUE TITLE
Can't Change Audio On LG TV

### ISSUE THREAD

**Issue by StreamScream** [Stremio/stremio-bugs#823]
The option to change the audio track is not available. 

1. Go to Stremio
2. Click on a movie or TV show to play
3. Click/play a stream

The expected behavior is to be able to click the icon to change the audio and be able to select any audio that stream provides.

TV
 - Device: [LG 86UQ7590PUD]
 - OS: [WebOS]
 - Version [WebOS TV Version - 7.4.0-1907 (mullet-meru)   Software Version - 04.40.94]

I really hope this gets fixed soon because it can make certain streams unwatchable. Then I have to go to a worse quality link that hopefully plays the correct audio.

**Comment by jaruba** [comment]
https://github.com/Stremio/stremio-bugs/issues/792
