### ISSUE TITLE
Windows desktop app slow to launch if a mapped network drive is offline.

### ISSUE THREAD

**Issue by Love-M** [Stremio/stremio-bugs#824]
**Describe the bug**:

If you have a mapped network drive in windows to a local file share and that share is offline Streamio will take a long time to launch.  Im assuming its waiting for windows to resolve the share that is offline?

If you disconnect the offline mapped drive in file explorer, steamio will launch instantly.

**To Reproduce
Steps to reproduce the behavior:**

Map a network drive in windows then make the share offline on your local server.

**Expected behavior:**

Launch quicker if mapped drives are offline.

**Desktop (please complete the following information):**
-OS Windows 10 Version	10.0.19045 Build 19045
-Streamio 4.4.168

**Comment by TRtomasz** [comment]
Go to the settings -> STreaming and disable settting "Enable the local files addon" it should resovle your issue.
