### ISSUE TITLE
Search / microphone not working

### ISSUE THREAD

**Issue by Paulie5000** [Stremio/stremio-bugs#825]
**I re-downloaded Stremio on my OLED Samsung TV. In the My Apps Stremio appears as a blank box.  I can stream but the search function does not work, and neither will the microphone . I use Stremio via my Sky NZ box. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**

**Comment by TRtomasz** [comment]
So this issue is about android app or samsung tv app?
