### ISSUE TITLE
Dragon ball release gone from Torrentio 

### ISSUE THREAD

**Issue by The2ndYamchaEnjoyer** [Stremio/stremio-bugs#826]
**Describe the bug**
A specific version of dragon ball that was available from Torrentio has now disappeared after using it for 3 days and i can't find it anywhere 

**To Reproduce**
1. Go to Search 
2. Click on Dragon ball on cinemeta
3. Scroll down to simply "torrentio"
4. And a version from nyaa uploaded by [ML04] is gone

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi]
 - OS: Don't know

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**

**Comment by jaruba** [comment]
https://www.reddit.com/r/Stremio/s/6eH6v2CMFd

**Comment by The2ndYamchaEnjoyer** [comment]
Who can i ask to solve my problem if you guys just solve alp problems?
