### ISSUE TITLE
Windows app crashes whenever I click on the app while loading

### ISSUE THREAD

**Issue by trlef19** [Stremio/stremio-bugs#829]
**Describe the bug**
Everytime I click on the window while the app is loading content, it would freeze and crash

**To Reproduce**
1. Go to a random movie
2. Click on a source to load
3.  Click anywhere while loading

**Expected behavior**
nothing should happen 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 -  App
 - Version  4.4.168

**Additional context**

**Comment by TRtomasz** [comment]
Please record and share a video so we can understan what exactly is happening and when

**Comment by trlef19** [comment]
https://github.com/Stremio/stremio-bugs/assets/82327147/4e76be79-0891-4828-aa30-1a862e34c511

I'm just clicking on the screen. (It also crashes if i try to full screen)

**Comment by TRtomasz** [comment]
I cant reproduce the issue and i didnt see any other user reporting the same issue so i guess it must be something related to your configration. Could be faulty GPU drivers you might consider reinstalling them. First remove them using DDU.

**Comment by trlef19** [comment]
Its not faulty drivers cause im using an nvidia gpu and it updates regularly. Maybe i can find the crash logs somewhere?
