### ISSUE TITLE
Not being able to broadcast to samsung smart TV KS8000

### ISSUE THREAD

**Issue by nando182** [Stremio/stremio-bugs#83]
Hi All, 
I am trying to broadcast movies from my notebook to my smart TV, Stremio detects the TV  but if i activate the subtitles the broadcast does not work, if I disable subtitles the broadcast happens but also fails some times.

log:
`Player using backend: [TV] Samsung
blob.js:1 Subtitles: loading subtitle file 6776769
blob.js:1 Subtitles: loaded from cache 23 subtitles
blob.js:1 Subtitles: loaded successfully subtitle file C:\Users\Fernando\AppData\Roaming\stremio\subtitles\6776769.srt
blob.js:1 Subtitles warning: no grouping found
blob.js:1 subtitles.get - calling to get subtitles
blob.js:1 subtitles.get returned per,hrv,ind,mac,kor,ita,hun,chi,may,pol,fre,dut,eng,rum,tur,cze,ell,heb,dan,ara,por,pob,spa sets of subtitles
blob.js:1 warning subtitles.get did not return grouping
blob.js:1 Subtitles: loading subtitle file 6776769
blob.js:1 Subtitles: loaded successfully subtitle file C:\Users\Fernando\AppData\Roaming\stremio\subtitles\6776769.srt
blob.js:1 Subtitles warning: no grouping found
blob.js:3 Reducing cache size to 5120MB from 0MB by deleting 0 files
C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\linvodb3\addon…:13 LinvoDB Sync: sync started for libraryItem
C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\linvodb3\addon…:149 Object {code: -32601, message: "Method not found"}(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\linvodb3\addon…:149(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\async\lib\asyn…:52(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\async\lib\asyn…:570(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\async\lib\asyn…:167(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\linvodb3\addon…:58(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\linvo-api4-cli…:85(anonymous function) @ jayson.jquery.js:53
blob.js:4 Error: connect ETIMEDOUT 192.168.0.18:9197(…)(anonymous function) @ blob.js:4(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\upnp-mediarend…:162(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\upnp-mediarend…:89(anonymous function) @ C:\Users\Fernando\AppData\Local\Programs\LNV\Stremio\resources\app.asar\node_modules\upnp-mediarend…:75emitOne @ events.js:77emit @ events.js:169socketErrorListener @ _http_client.js:259emitOne @ events.js:77emit @ events.js:169emitErrorNT @ net.js:1250doNTCallback2 @ node.js:441_tickCallback @ node.js:355`

 A timeout seems to be happening, some tips?
Thanks

**Comment by Ivshti** [comment]
Hello,

Thanks for reporting this

We are working to improve DLNA all the time, but our next major release is scheduled in 2-3 months, so this is the earliest point that there will be improvement :( sorry for that

Tip: you can test different addons (addons.strem.io) to see if some work better than others

**Comment by nando182** [comment]
Thank you for answering  @Ivshti  I glad to see that a improvement is being done, I have already set the option to get the lasted beta release but let m know if I can do some tests.

Thank you

**Comment by guiraldelli** [comment]
I have this bug with Stremio 4.4.10, but not with Stremio 3.6.5, on Ubuntu 18.04.

In the console, I repeatedly see the following message (Stremio 4.4.10):

```
Arguments -ss 5 -i http://127.0.0.1:11473/28b81d6db2f32d940be7ab812ddac592abb2fc35/0 -map 0:0 -map 0:1 -c copy -f matroska -threads 0 pipe:1                                                                                                    
-> GET /28b81d6db2f32d940be7ab812ddac592abb2fc35/0 bytes=0-                                                             
 ---> CLOSE premature close                                                                                             
-> GET /casting/transcode.mp4?video=http%3A%2F2F127.0.0.1%3A11473%2F28b81d6db2f32d940be7ab812ddac592abb2fc35%2F0&audioTrack=0%3A1&time=5.59&subtitles=&subtitlesDelay= bytes=86016-                                                            
URL /transcode.mp4?video=http%3A%2F2F127.0.0.1%3A11473%2F28b81d6db2f32d940be7ab812ddac592abb2fc35%2F0&audioTrack=0%3A1&time=5.59&subtitles=&subtitlesDelay=                                                                                    
GET HEADERS { range: 'bytes=86016-',                                                                                    
  'getcontentfeatures.dlna.org': '1',                                                                                   
  'transfermode.dlna.org': 'Streaming',                                                                                 
  host: '192.168.1.117:11473',                                                                                          
  connection: 'close' }                                                                                                 
-> HEAD /28b81d6db2f32d940be7ab812ddac592abb2fc35/0                                                                     
-> POST /casting/ec1d2fe9-c8fd-47f5-b82d-1f6ac56c9db5/player                                                            
-> GET /28b81d6db2f32d940be7ab812ddac592abb2fc35/0 bytes=0-                                                             
RESPONSE HEADERS HTTP/1.1 200 OK                                                                                        
content-type: video/x-mkv                                                                                               
transfer-coding: chunked                                                                                                
Accept-Ranges: none                                                                                                     
Connection: Close                                                                                                       
transferMode.dlna.org: Streaming                                                                                        
contentFeatures.dlna.org: DLNA.ORG_OP=01;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=01300000000000000000000000000000                  
Date: Sun, 07 Oct 2018 11:34:50 GMT                                                                                     
Transfer-Encoding: chunked   
```

There are no similar messages for Stremio 3.6.5. Just

```
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1                                                                          
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1 bytes=0-65535                                                            
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1 bytes=348570242-348635777                                                
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1                                                                          
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1                                                                          
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1                                                                          
-> /96ab8c5d20ff195ee9de26010adc024d69cecf53/1                            
```
