### ISSUE TITLE
Default audio language doesn't work on WebOS

### ISSUE THREAD

**Issue by peshh** [Stremio/stremio-bugs#830]
**Describe the bug**
When I choose Japanese for a default audio language in the WebOS app the streams which have a both a Japanese and another audio track default to the first one which may or may not be the Japanese one. 

**To Reproduce**
1. Go to Seettings/Playback/Audio/Default Language
2. Select any more obscure language.
3. Start a stream with multiple audio inputs and contains the selected language (if you selected Japanese, you can try with most animes).
4. The first audio track set in the video is played instead of the chosen default one.

**Expected behavior**
The chosen default language should be played in the stream if it is present in the audio tracks.

**TV (please complete the following information):**
 - Device: LG OLED65G2PUA
 - OS: WebOS 23
 - Version Theater v1.3.0

**Comment by TRtomasz** [comment]
If audio track name does not contain the language name it is not possible to pick it automatically, this is not  a bug.

**Comment by viralpandey** [comment]
I am getting the same error despite the audio track contains the language that is selected as default in the player. The error is on WebOS

**Comment by viralpandey** [comment]
@TRtomasz

**Comment by JasonBSteele** [comment]
Also raised here https://github.com/Stremio/stremio-bugs/issues/1096 and here https://github.com/Stremio/stremio-bugs/issues/917

**Comment by TRtomasz** [comment]
There is no need to have the same issue opened in multiple instances so that one will remain closed
