### ISSUE TITLE
Removed Lists on PC not syncing to Web or LG App

### ISSUE THREAD

**Issue by SaphuA** [Stremio/stremio-bugs#831]
I have tried a Trakt addon to add some lists to my Home screen (https://2ecbbd610840-trakt.baby-beamup.club/configure/). But removed it later because it didn't fit my use case.

The addon and its lists are indeed removed from the Windows App, but the removal of the lists does not sync well to either https://web.strem.io/ or to the LG App.

I am using the same account on all instances.
I have tried logging out / clearing cache where possible.

Screenshot of the app where the lists are removed:
![Qt5HhS5](https://github.com/Stremio/stremio-bugs/assets/4395292/c690ae63-d59c-44a0-8709-845a6e93169d)

Screenshot of the web where the lists are still visible:
![TvFS7Tj](https://github.com/Stremio/stremio-bugs/assets/4395292/a97a37cc-ee14-475c-8610-a3df320ac054)

**Comment by TRtomasz** [comment]
Try logging out and logging in, or perhaps check also addons list if it is still there and remove it again.

**Comment by SaphuA** [comment]
I have already tried logging in/out and clearing cache. 

The addon is not in the list as the web and LG versions only offer a sync option.

Please reopen the ticket

**Comment by TRtomasz** [comment]
Catalogs on your second screen are from the official trakt integration addon,
If you mean them, you should remove official trakt addon.

**Comment by SaphuA** [comment]
I'm fairly sure they are not, and are from the addon that I linked. 

In any case, these lists are not in the windows app and are in the web and LG apps, so that would still indicate a bug somewhere. 

I'll try removing/reinstalling the official trakt addon in a bit
