### ISSUE TITLE
Samsung tv not showing Portuguese Brazilian subtitles 

### ISSUE THREAD

**Issue by JCMFilho** [Stremio/stremio-bugs#832]
I bought a New samsung tv and It doesn't show Portuguese Brazilian as an option for subtitles. It doesn't even show on the menu where I choose my preference language for subtitles. I have stremio on other devices and Portuguese Brazilian works fine but on my new samsung TV it doesn't show up. I've googled it and I found other people with same pI bought a New samsung tv and It doesn't show Portuguese Brazilian as an option for subtitles. It doesn't even show on the menu where I choose my preference language for subtitles. I have stremio on other devices and Portuguese Brazilian works fine but on my new samsung TV it doesn't show up. I've googled it and I found other people with same problem with no answers.

**To Reproduce**
1. Open any movies/tv shows that has subtitles in Portuguese (Suits for example)

**TV (please complete the following information):**
 - Device: Samsung 55"
 - OS: Tizen Samsung
 - Version: Theater v1.3.0

**Comment by TRtomasz** [comment]
This will be fixed in the next release,
Please next time try using a search option before creating new issue - https://github.com/search?q=repo%3AStremio%2Fstremio-bugs+brazilian&type=issues
