### ISSUE TITLE
Mayday/Air Crash Investigation Season 24 inaccurate episode names

### ISSUE THREAD

**Issue by Hyderite** [Stremio/stremio-bugs#833]
**Describe the bug**

The names of the episodes in Season 24 of Mayday is inaccurate. For example, episode 1 is about United Airlines Flight 811, but the title indicates it's about Ethiopian Airlines Flight 302.

**To Reproduce**
1. Go to Mayday/Air Crash Investigation
2. Select Season 24

**Expected behavior**
Episode 1: Terror over the Pacific (United Airlines Flight 811)
Episode 2: Disaster at Dutch Harbor (PenAir Flight 3296)
Episode 3: Deadly Departure (Air Transport International Flight 782)
Episode 4: Without Warning (2019 Alaska mid-air collision)
Episode 5: ...
List of Season 24 episodes (for reference): https://en.wikipedia.org/wiki/List_of_Mayday_episodes#Season_24_(2024)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iPadOS
 - Browser: Safari
 - Version: 17.5.1

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 14
 - Browser: N/A (I'm using the app)
 - Version: 1.6.12

**Comment by TRtomasz** [comment]
Hello, this should be fixed soon once cache expires.
