### ISSUE TITLE
Subtitles doesn't work well in Samsung TV

### ISSUE THREAD

**Issue by cortezothiago** [Stremio/stremio-bugs#834]
**Describe the bug**
When I want to use subtitles from an external source it always gives an error, also the embedded subs have disappeared, this has happened since the last update on Samsung TV. On the other devices (computer, cell phone) they work correctly, so I know that the problem is not with the addon itself.

**Expected behavior**
 I would like that the subtitles from external addons load correctly, and the embedded subs would work (appear) again. And, if possible, name the embedded languages.

**TV (please complete the following information):**
 - Device: Samsung 50AU7700
 - OS: Tizen (Samsung)
 - Version: Tizen 2210

**Comment by bartolo112** [comment]
I've got same problem on samsung tv. How I can fiz it?

![20240715_135944](https://github.com/user-attachments/assets/d268152f-703c-4c85-b617-dc64784ad1f3)
