### ISSUE TITLE
No access to other sources after a torrent is added

### ISSUE THREAD

**Issue by xjunior** [Stremio/stremio-bugs#84]
Once you add a torrent for a movie, you cannot see other sources anymore. In my case, I tried a torrent which turned out to have really bad quality. Now I can't check if it's available on Juan Carlos Torrents or other sources.

**Comment by Ivshti** [comment]
can you please enable guidebox/other add-ons which would have sources for this movie and see if they appear

it's possible that your local source is simply the same as the one from the third-party add-on, as stremio de-duplicates sources

**Comment by xjunior** [comment]
@Ivshti I removed the entire `Library/Application Support/stremio` and the movie has no other source yet.
