### ISSUE TITLE
Stremio Android mobile app crashes while addons subtitles are loading.

### ISSUE THREAD

**Issue by batuhankrmn** [Stremio/stremio-bugs#842]
**Describe the bug**
I've been struggling with this issue while addons subtitles are loading. I uninstalled all the other subtitles addons to make sure and just installed official Opensubtitles v3 addon. When I clicked on subtitles button, I see "Loading subtitles..." on addons subtitles section. Subtitles never comes and app crashes after waiting approximately 30 seconds. 

**To Reproduce**
1. Open the Stremio app
2. Make sure you have only official Opensubtitles v3 addon.
3. Open any video stream as you want.
4. Click on the subtitles icon to see addons subtitles
5. Wait for addons subtitles to finish loading.

**Expected behavior**
Its is expected that addons subtitles should be loaded successfully when clicked on subtitles icon on the player.

**Screenshots**

https://github.com/Stremio/stremio-bugs/assets/57859656/ddf20717-31fa-4fef-b7fb-44ae1229da66

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Plus and Galaxy Tab S9 Ultra (same issue for both)
 - OS: Android 14 OneUI 6.1
 - Browser Stremio Android App
 - Version 1.6.12

**Additional context**
This is valid issue for my both devices; Galaxy s22 plus and Galaxy Tab s9 ultra but I can get subtitles with same account and same addons on the PC app. I've force stopped the app, cleared cache/data, uninstalled and reinstalled the app, restarted the phone/table. These didn't worked unfortunately. I even created new account but same issue occurred with that account also. I wonder If there is any other way to clear cache/data of the app, maybe this issue caused by cache but I cleared them from applications settings as I said. I'm open to any suggestion and investigation to get rid of this issue. Thanks in advance.

**Comment by TRtomasz** [comment]
cant reproduce on galaxy s23

**Comment by amirshahab89** [comment]
I followed your instructions. It works for me with Samsung A55. The add-on Opensubtitles v3 is fetching correct files for the video. 
Have you tried to uninstall it? Shut down, then install again? Must be some hidden glitch somewhere for you.
