### ISSUE TITLE
Stremio on WebOS

### ISSUE THREAD

**Issue by Adorald** [Stremio/stremio-bugs#843]
**Describe the bug**

When they are going to update the app cause subtitles are getting on my nerve lol. When u play content it won't play subs automatically u have to press on it to make it appear also Embedded subs are too big, Open-Subs are too small with no features like fonts or transparency of background black bar other than that content is playing marvellous with no stutter or buffering just need to fix subtitles thats all.

**Comment by TRtomasz** [comment]
Please update your issue wit the new issue template.
