### ISSUE TITLE
Getting error on desktop "QProcess::ProcessError code: 1"

### ISSUE THREAD

**Issue by traviss64** [Stremio/stremio-bugs#845]
**Describe the bug**
Whenever I start the streaming on my desktop in stremio player I get this error:-

```
    Stremio streaming server has thrown an error

    QProcess::ProcessError code: 1

    (node:12660) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

    (Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)

    #

    # Fatal error in , line 0

    # Fatal process out of memory: Zone

    #

    #

    #

    #FailureMessage Object: 0683CD04

    <--- Last few GCs --->
```

**To Reproduce**
1. Go to 'stremio'
2. Click on 'any stream'
3. Scroll down to 'It will show error'

**Expected behavior**
There should not be this error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox/Chrome
 - Version: Stremio 4.4.168, WebU14.4.172, Server 4.20.8

**Comment by TRtomasz** [comment]
Looks like something on your desktop is affecting stremio NodeJS server
