### ISSUE TITLE
Exoplayer audio out of sync 

### ISSUE THREAD

**Issue by Atreus93** [Stremio/stremio-bugs#846]
Audio when i play a video with Exoplayer is earlier than image around 0.25 - 0.5 second.

Devices: mi stick, mi box s2.
This issue does not occur with libVLC player or external player.

If you guys consider adding Audio Sync Adjustment feature on Exoplayer that would be great. 

Thanks

**Comment by TRtomasz** [comment]
Exoplayer does not provide such feature it is not possible.
