### ISSUE TITLE
Next episode

### ISSUE THREAD

**Issue by Maxxx233** [Stremio/stremio-bugs#847]
No Next Episode after watching an episode

**Expected behavior**
After watching like 98% of the show it doesn't get marked as watched and after watching the 100% the next episode doesnt show up in continue watching

Smartphone:
 - Device: Samsung galaxy a53 
 - OS: Android 14

**Comment by TRtomasz** [comment]
if you watched majority of the episode on different device or used seek a lot it will not get marked as watched
