### ISSUE TITLE
high cpu usage from stremio when external player is used

### ISSUE THREAD

**Issue by craigyhay** [Stremio/stremio-bugs#850]
When desktop version of stremio is used with an external player such as mpc-be cpu usage behaviour is:
external player used option: mpc-be<2% cpu usage **stremio application 14-23% cpu usage** depends on bitrate of file
link from stremio manually moved from stremio to mpc: mpc-be 2% total cpu usage
stremio internal player used: upto 2% cpu usage

system used i5 12400f windows 11 32gb ddr4 rx 6800 16gb.

stremio is unecessarily eating cpu for no purpose, suspect software decoding on video or similar may be ocurring despite stremio internal player not being shown and external player in use.

**Comment by TRtomasz** [comment]
Stremio has no info to what it is casting so casting endpoint requires transcoding and stremio is performing it.
