### ISSUE TITLE
[LG] Application not installed, please try again

### ISSUE THREAD

**Issue by ItsDeidara** [Stremio/stremio-bugs#851]
**Describe the bug**
App downloads from the LG app store, but fails to install. 

**To Reproduce**
1. Go to LG App store
2. Click on Install Stremio
3. Wait for download

**Expected behavior**
App should download and install succesfully. 

**Screenshots**
[Short video of the issue](https://github.com/Stremio/stremio-bugs/assets/16449821/9c066095-2de4-4f15-be23-fa92d6789b0b)

**TV (please complete the following information):**
 - Device: LG OLED65B2PUA
 - OS: [WebOS)]
 - Version [8.3.0-2401]

**Additional context**
My TV is rooted, using [dejavuln](https://github.com/throwaway96/dejavuln-autoroot) if that matters. So if needed I could try and grab system logs. 

Even with 1800mb of free space left on my TV. The application still fails to install. I've also attempted to change DNS servers to 1.0.0.1 and keep the TV unplugged for an hour.

**Comment by jaruba** [comment]
the error on the screen gives no relevant hint, so yeah, logs would be nice, but i have a feeling that ur environment / device is causing this somehow, what country are you from?

**Comment by ItsDeidara** [comment]
I'm in the US.

Here is the log file. If it matters these are the steps I took to generate it. 

[streamio.json](https://github.com/user-attachments/files/16101865/streamio.json)

1. SSH into the TV as root 
2. use command ls-monitor -j -f com.webos.appInstallService > streamio.jsonl 
3. press enter. 
4. Install Stremio on your TV
5. After it fails, go back to the terminal 
6. press Ctrl+C
7. Pull the file from /home/root

Please note the extension of the log file was initially .jsonl instead of .json. I had to change it in order to upload it
