### ISSUE TITLE
[AndroidTV] Exoplayer not working on 1.6.10

### ISSUE THREAD

**Issue by dineshalphaque** [Stremio/stremio-bugs#852]
**Describe the bug**
Am facing a bug with the new 1.6.10 version for AndroidTV 10. Playing H265 content (Real-debrid stream) takes an inordinately long time to load before throwing an error "switching to libVLC playback error" when the default player is set to Exoplayer. 

The same file played well without issue in Stremio 1.6.9 on the same TV. 

Setting default player to libVLC helps somewhat, but it's clear Exoplayer is broken in this release. Hoping for a fix for this soon.

**To Reproduce**
1. Play HEVC/H.265 encoded stream. 

**Expected behavior**
Stream should play in Exoplayer.

**TV (please complete the following information):**
 - Device: Prism+ Q65-QE
 - OS: AndroidTV
 - Version: 10

**Comment by max1c** [comment]
Having the same issue on Android TV 11.

**Comment by TRtomasz** [comment]
@max1c  https://drive.google.com/file/d/1iG9LeCbDBkzLwpZ3qRjaunHl0cLHHBa5/view?usp=sharing try this version

**Comment by dineshalphaque** [comment]
> @dineshalphaque you could try this version if it helps with your issues https://drive.google.com/file/d/1iG9LeCbDBkzLwpZ3qRjaunHl0cLHHBa5/view?usp=sharing

This does seem to work playing the same file, without the switching to libVLC playback error mentioned above.

Will continue testing with other files over the next 24 hours and report back here.

Thanks for the quick response, @TRtomasz!

**Comment by max1c** [comment]
> @max1c https://drive.google.com/file/d/1iG9LeCbDBkzLwpZ3qRjaunHl0cLHHBa5/view?usp=sharing try this version

Yes, I also tested on several different ones that did not work and this version is working as expected. Since this was sideloaded will it be able to update via PlayStore in the future or will I need to re-install when the next update comes out?

**Comment by TRtomasz** [comment]
@max1c  i'm think if you have play store, it will get automatically updated even though you sideloaded it now

**Comment by GStrategos** [comment]
Same here. 
I'm using Google for Android TV.
App got updated automatically and since then EXO player doesn't work.

**Comment by GStrategos** [comment]
> @dineshalphaque you could try this version if it helps with your issues https://drive.google.com/file/d/1iG9LeCbDBkzLwpZ3qRjaunHl0cLHHBa5/view?usp=sharing

Hi,
I'm Facing the same issue here. 
I'm using Google for Android TV.
I grabbed your updated file but now add-on subtitles 
aren't working, only the embedded. So could you please give us the previous 1.5.9 version so we could downgrade till it's fixed? 

Thank you very much!

**Comment by GStrategos** [comment]
@TRtomasz 
Hi,
I was having the same issue with the libvlc switching  error (using chromecast for Google tv) and I grabbed your updated 1.6.11 version from here, but after that all my add-on subtitles stopped working and only the embedded ones are showing. I have found and downgraded to bit 1.6.9 and 1.6.7 versions with no luck. I really can't figure this out. 

Could you please help me? I really appreciate your overall Stremio work! 

Thank you very much!

**Comment by dineshalphaque** [comment]
With 1.6.11 already avaliable for apk download on the stremio site, am closing this issue as fixed. Thanks to all involved!
