### ISSUE TITLE
Open subtitlesv3 official add-on suddenly stopped working with latest or previous versions. 

### ISSUE THREAD

**Issue by GStrategos** [Stremio/stremio-bugs#854]
**Describe the bug**
After updating to 1.6.10 later or previous versions the official Open subtitlesv3 add-on doesn't work no matter the player or language used. 

**To Reproduce**
1. Go to any movie or series. 
2. Click on any subtitles. 
3. Scroll down to available subtiles.
4. The subtitles are visible in the subtitles menu but not playing during the movie or series. Only the embedded ones are working. 

**Expected behavior**
Till yesterday the Open subtitlesv3 add-on was working perfectly in both Chromecast and android phone as expected. 

**Smartphone (please complete the following information):**
 - Device: Poko X3 Pro
 - OS: Android 12

**TV (please complete the following information):**
 - Device: Chromecast for Google TV.

**Additional context**
I was having the (now closed) issue with the libvlc switching  error (using chromecast for Google tv) after updating to 1.6.10 and I grabbed the updated 1.6.11 version provided, but right after that my add-on subtitles stopped working (using 
the official Open subtitlesv3) and only the embedded ones are showing. I went back to 1.6.10 and I also found and tested both 1.6.9 and 1.6.7 versions with no luck and sadly there's no other subtitle add-on active or working correctly.
Btw today my smartphone's stremio app is also NOT playing the add-on subtitlesv3.

I really can't figure this out and I'm reporting this here because **I think that last time the official Open subtitlesv3 add on wasn't working you guys update it and solved the issue.** 

Could you please check this issue? I really appreciate your overall Stremio work!

Thank you very much!

Edit: I was writing this report and I just found out that another one was posted a few minutes earlier. Anyhow this one is much more detailed, so I hope you can use it better.

**Comment by tomer1983** [comment]
Im having the same issue reported

**Comment by braleopard** [comment]
I have the same problem.  Mainly in HDR and Atmos videos.  I'm on version 1.6.11 and Android tv 11.
