### ISSUE TITLE
Samsung TV: “Dismiss” button/option name in Hebrew is incorrect.

### ISSUE THREAD

**Issue by SubEdict** [Stremio/stremio-bugs#855]
**Describe the bug**
Wrong menu translation to the word Dismiss in Hebrew.

**To Reproduce**
1. Go to 'any media'
2. Click on 'play'
3. On the right menu option, Scroll down to 'Dismiss' x. 
4. See error: In Hebrew, it translates to “Continue”.

**Expected behavior**
Change the Hebrew world "המשך" (Continue) to "הסר" (Dismiss / Remove).

Samsung TV, Tizen.

**Comment by TRtomasz** [comment]
We do not controll translations
