### ISSUE TITLE
Download subtitles error

### ISSUE THREAD

**Issue by GKid94** [Stremio/stremio-bugs#856]
**Describe the bug**
Subtitle download shows error page

**To Reproduce**
1. Play movie
2. Press more options in the bottom right
3. Select download subtitles

**Expected behavior**
To download subtitles

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Brave
 - Version 1.67.123 

**Smartphone (please complete the following information):**
 - Device: Redmi 9
 - OS: Android 12 MIUI 13
 - Browser Brave
 - Version 1.67.123

**TV (please complete the following information):**
 - Device: FOX 32DLE188
 - OS: Android
 - Version 7

**Additional context**
/ 
![Screenshot 2024-07-06 195233](https://github.com/Stremio/stremio-bugs/assets/18757054/f69fc3bf-fd6c-4419-9934-ae83238217c8)
![Screenshot 2024-07-06 195246](https://github.com/Stremio/stremio-bugs/assets/18757054/af2066b7-1808-42ca-a2e7-d886cfa40e49)

**Comment by Gupacode** [comment]
I'm having the same issue.
Installed Flatpak version of Stremio from Flathub (v4.4.168) on Linux Mint 21.3 Cinnamon. Subtitles are not working/loading when selected from the list and when try to do the step you described the same page is shown.
Ran Stremio on terminal using `flatpak run com.stremio.Stremio` to see what is showing when trying to use subtitles. It is showing this error:

```
js: Access to fetch at 'https://subs5.strem.io/en/download/subencoding-stremio-utf8/src-api/file/1951639077' from origin 'https://app.strem.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
-> GET /subtitlesTracks?subsUrl=https%3A%2F%2Fsubs5.strem.io%2Fen%2Fdownload%2Fsubencoding-stremio-utf8%2Fsrc-api%2Ffile%2F1951639077 
```

It seems to be a Stremio problem when it requests access to addons subtitles...
