### ISSUE TITLE
Deleting existing user sessions failes with database error (541)

### ISSUE THREAD

**Issue by ItsDrike** [Stremio/stremio-bugs#859]
**Describe the bug**
When attempting to delete my logged in sessions from the stremio website, nothing seems to happen. Upon further inspection using the developer tools, it turns out that the deletion requests are giving back HTTP 541 status code, with the JSON response body of: `{"error":{"message":"Database error #2"}}`

**To Reproduce**
1. Navigate to https://www.stremio.com/acc-settings using your browser.
2. Scroll down to user sessions
3. Open developer tools
4. Click on delete all sessions (or delete on any individual session)
5. See the newly made request to delete this session fail with HTTP 541

**Expected behavior**
The session(s) should be deleted.

**Screenshots**
![image](https://github.com/Stremio/stremio-bugs/assets/20902250/9834310b-d6c6-4afb-9829-e0926df119d6)

**Desktop (please complete the following information):**
 - OS: NixOS (nixpkgs rev: 9f4128e00b0ae8ec65918efeba59db998750ead6)
 - Browser Firefox
 
 **Additional Information**
 Below is a curl command to produce the HTTP request to replicate the failure shown in the browser. Note that I have redacted the authKey from body.
 ```
 curl 'https://api.strem.io/api/logout' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://www.stremio.com/' -H 'content-type: application/json' -H 'Origin: https://www.stremio.com' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'Priority: u=1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw '{"authKey":"[MY AUTH TOKEN FOR THIS SESSION]"}'
```

**Comment by GStrategos** [comment]
I'm in the same boat. For the last few days I'm having constant 541 errors and I can't even uninstall add-ons because of this. Using Chromecast.

**Comment by GStrategos** [comment]
I'm using Chromecast and having 541 API errors all the time. I can't even uninstall or install any add-ons because of that error. Everything started acting weird after 1.6.10 and 1.6.11 updates tbh.

**Comment by jaruba** [comment]
@GStrategos it's unrelated to the android tv updates

**Comment by GStrategos** [comment]
> @GStrategos it's unrelated to the android tv updates

Ok thanks! Do we know what's causing it then?

Cheers!

**Comment by TRtomasz** [comment]
Is this still happening @GStrategos ?

**Comment by ItsDrike** [comment]
I was able to get my user sessions deleted today, so it seems that the issue is resolved
