### ISSUE TITLE
Subtitles encoding on smart tv streaming

### ISSUE THREAD

**Issue by advicente** [Stremio/stremio-bugs#86]
I'm facing problems while streaming any strem.io content to my LG Smart TV 32LH570B.
Some characters like the following: "ã ç é â" don't appear correctly.

Maybe I can upload a photo or if more info is needed please let me know.
Thanks,

**Comment by honlino** [comment]
I have exactly the same issue.

**Comment by advicente** [comment]
Can anyone tell me if this is somewhat a plugin problem or a bug in Stremio source?

Thanks,

**Comment by DaniCastilho** [comment]
i have the same problem...

**Comment by johnnyghost** [comment]
+1

**Comment by rodrigotm** [comment]
+1

**Comment by dfvg** [comment]
+1

**Comment by honlino** [comment]
Why nobody answers this neither tries to fix it, it might be something really simple like changing the encoding...

**Comment by advicente** [comment]
Bump

**Comment by kl0ck** [comment]
+1
