### ISSUE TITLE
Large Files Buffer on Android TV and Android Apps only

### ISSUE THREAD

**Issue by amintb7** [Stremio/stremio-bugs#860]
Large Files 21GB and above constantly stutter on android TV Chromecast and Android Apps across the board, No issues exists in Desktop

Rigorous testing done using Torrentio+RD+All Debrid with 1GB connection

Used all Players with changing all settings including tunneled playback

**Comment by TRtomasz** [comment]
i'v just tried and have no issue playing bigger files, looks like issue is somewhere on your side. Especially considering large stremio user base it is almost impossible that we have a global issue and receieved only one report.
