### ISSUE TITLE
Low volume on ExoPlayer

### ISSUE THREAD

**Issue by asaddon** [Stremio/stremio-bugs#863]
**Describe the bug**
Hello, After the last Android TV app update version 1.6.11, the audio volume on videos playing using ExoPlayer is considerablly lower as compared to when played via libVLC player, before that update it was all okay. Not sure if its just my device or an overall issue.

**To Reproduce**
1. Play Video using ExoPlayer and monitor audio.
2. Play Video using libVLC player and monitor audio.
3. Compare the two.

**Expected behavior**
Audio volume should be consistant and loud on both players.

**TV (please complete the following information):**
 - Device: Sony X950H
 - OS: Android TV
 - Version: 10

**Comment by TRtomasz** [comment]
This is not a bug but simply wrong configuration of your hardware. I was having the same issue where libvlc was playing video with louder audio track but after changing my tv configuration there was no difference. Cant advice what exactly you have to change but for sure it is configurable.

**Comment by asaddon** [comment]
> This is not a bug but simply wrong configuration of your hardware. I was having the same issue where libvlc was playing video with louder audio track but after changing my tv configuration there was no difference. Cant advice what exactly you have to change but for sure it is configurable.

Any chance you remember what exactly you changed? It'll help me point in the right direction.
