### ISSUE TITLE
subtitles do not load

### ISSUE THREAD

**Issue by f0nchi** [Stremio/stremio-bugs#864]
**Describe the bug**
In the subtitles option of any media that I want to play, it appears empty.

**To Reproduce**
1. Play media
2. Select subtitles
3. Only None option appears to select

**Expected behavior**
All available language options used to appear, usually with Spanish (my language) preselected

**TV (please complete the following information):**
 - Device: BeyondTV
 - OS: Android TV
 - Version 11

**Additional context**
It continues to happen even after the fix that was mentioned in the blog

**Comment by jaruba** [comment]
what country are you in and what interner provider do you use?

**Comment by f0nchi** [comment]
> what country are you in and what internet provider do you use?

Hi there! 
Argentina with Personal (used to be called Fibertel) as Internet Provider.
Thank you :)

**Comment by Kresbok** [comment]
Hello, it has been reported that other ISP blocking certain access, to fix this you need to change your DNS resolution 

Follow this video:

https://youtu.be/1VeeJE5RUyE?si=9ZCRn9a49qoYDJ_V

Hopefully this would help.

**Comment by Kresbok** [comment]
Hello, there's been reports from certain ISP blocking something on their end, try changing the DNS resolution on your device or modem/router

https://youtu.be/1VeeJE5RUyE?si=9ZCRn9a49qoYDJ_V

Hopefully this can help.

**Comment by Kresbok** [comment]
> Argentina with Personal (used to be called Fibertel) as Internet Provider.
> Thank you :)

Soy de Argentina, al parecer Movistar está haciendo el bloqueo de ciertos accesos, probá cambiando el DNS, podría ayudar.

**Comment by f0nchi** [comment]
Resolved! Muchas gracias!

🙌

**Comment by f0nchi** [comment]
Resolved! Muchas gracias!

🙌

**Comment by Kresbok** [comment]
Resolved! Muchas gracias!
> 
> 🙌

De nada! Saludos!
