### ISSUE TITLE
Foreign Titles for Foreign Shows are incorrect or even missing on search

### ISSUE THREAD

**Issue by rababR1** [Stremio/stremio-bugs#866]
**Describe the bug**
When searching for foreign shows, especially Turkish shows for example, it may show the title card  either in the show's original language, or a foregin language outside of Turkish, or no logo at all.

**To Reproduce**
1. Go to Stremio Web or open Stremio Desktop, then type in 'saladin the conqueror of jerusalem' (for example)
2. Click on 'Popular- Series'(for Stremio Web) or 'Series - Cinemeta: Popular' if on Stremio Desktop
3. Scroll down to '....' (No need to scroll, but the error's right in front of you)

**Expected behavior**
The show logo will be displayed either in Turkish or the English translation of that same show.

**Screenshots**
An example will be Kudüs Fatihi Selahaddin Eyyubi (Saladin: The Conqueror of Jersulamen).
Here, it displays the show's name in Arabic, whereas it should be Turkish:
![image](https://github.com/Stremio/stremio-bugs/assets/65360255/8ff0f3ab-ab0d-4756-a41b-c45fd86a3519)
![images](https://github.com/Stremio/stremio-bugs/assets/65360255/7f401fec-adca-4b33-bfe9-cada75ff6a12)
I think its impossible to get the logo for the Turkish version, but here's the English logo, extracted from HilalPlay:

![saladin-the-conqueror-of-jerusalem_1701082232841_AzRdVRNsnDCZ7UvVRqrv](https://github.com/Stremio/stremio-bugs/assets/65360255/d316ab52-ef70-4261-b109-cfdb6194a878)

Not only that but even for this show, the logo doesnt even show up:
![image](https://github.com/Stremio/stremio-bugs/assets/65360255/afa1669e-21ec-4262-89d6-ad46f0f55910)
Once again, here's the image link from HilalPlay:
![the-great-seljuks-alparslan_1648640851381_BKTKL7wkkBdCAXvBjQBB](https://github.com/Stremio/stremio-bugs/assets/65360255/44295063-71ca-4cb6-9b53-464724e97c1c)

Unlike the previous show (Alparslan is a direct prequel to this), the logo does show up:
![image](https://github.com/Stremio/stremio-bugs/assets/65360255/ac897f98-2ff3-474f-aac0-cf4d4099021f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 4.4.168

**Comment by rababR1** [comment]
@jaruba , apologies for the ping. I believe this issue could be a bug

**Comment by TRtomasz** [comment]
If we dont have logo we will not show it. I dont understand how is this a bug?

**Comment by jaruba** [comment]
@rababR1 the issue with Kudüs Fatihi Selahaddin Eyyubi (Saladin: The Conqueror of Jersulamen) comes from here: https://www.themoviedb.org/tv/232132-selahaddin-eyyubi/images/logos

TMDB has only 2 logos, and none of them have a language set, when chosing a logo, we prefer:
- english logo if available
- logo in original language if available
- most popular logo

in this case there are 2 logos, none have any votes and none have a language set, so it chooses the first one, which u say is the wrong one.

you should either vote on the logo you want to make it more popular, or upload the correct logo to TMDB and set the correct language name when uploading it

for Alparslan: Büyük Selçuklu, there are no logos at all on TMDB: https://www.themoviedb.org/tv/138171-alparslan-buyuk-selcuklu/images/logos

so you should upload a logo to TMDB for it if you want it to show in Stremio
