### ISSUE TITLE
Android TV: Changing language to Hebrew changes the UI to RTL but doesn't translate anything

### ISSUE THREAD

**Issue by yortem** [Stremio/stremio-bugs#867]
**The bug:** 
 Changing language to Hebrew changes the UI to RTL but doesn't translate anything to Hebrew, it's still in English

**What I'm doing:** 

- I'm going to Settings > Interface > Language 
- I change from English to Hebrew
- Then the whole UI turn into RTL interface, which is good, but it's still 100% in English. 

**What I tried:** 

- I tried Arabic and it's working well, and then Hebrew again and it's still going back to English
- I tried on the PC app and Hebrew works fine (but without RTL, I assume it's a different issue or not an issue at all)

**Screenshots:** 
Screenshot that show that the interface is changed to Hebrew 
![issue1](https://github.com/Stremio/stremio-bugs/assets/45399403/24c91926-08af-4db7-83f1-5efb357a126e)

Screenshot of the app still in RTL but no Hebrew in sight, only English
![issue2](https://github.com/Stremio/stremio-bugs/assets/45399403/b1195656-16c1-4a49-a692-17c27e4e9de6)

**Info:** 
Stremio version: 1.6.9
It's a Samsung TV but not a smart TV so I'm using Xiaomi Box S with Android TV.

**Comment by TRtomasz** [comment]
thanks for reporting will be fixed in the next release!

**Comment by yortem** [comment]
Thank you!

**Comment by roy9982-cmd** [comment]
You didn't fix it

**Comment by yortem** [comment]
> You didn't fix it

@roy9982-cmd 

It was fixed for me a few weeks ago. Make sure you have the latest version. (Android TV is not the same app as Samsung or LG version). The menu is translated but not the movies themselves and it's normal.
