### ISSUE TITLE
Board is empty, content disappears

### ISSUE THREAD

**Issue by SOstrouhov** [Stremio/stremio-bugs#87]
After couple of days of using app 'board' became empty. After launching app, I can see content just a second and then it's all disappears, remains just a blank page. I reinstalled the app, it didn't make any changes. This  issue exist both an my pc and laptop

**Comment by Ivshti** [comment]
Can you upload some screenshots? are you talking about the desktop app? What operating system?

**Comment by SOstrouhov** [comment]
![desctop screenshot](https://cloud.githubusercontent.com/assets/16515570/21476181/2d3d20b8-cb68-11e6-9e5a-376a0cc93c59.png)
Yes, it's Windows 10 with latest updates on both my PC and laptop. I have tried to delete all the items in the library, it didn't make any differences. I've created a new account. In the new account, I unmarked add-ons YouTube, GuideBox, Filmon.TV and added Subtitles, Juan Carlos, Popcorn Time and connected Trakt.tv. Then go to the board, add Vikings series to the library. At this point, the board worked. Then board changes and appeared helping messages about new episodes and new channels with The Big Bang Theory as an example. I opened it, add to library and after it, content on board disappeared.

**Comment by SOstrouhov** [comment]
Video from my PC https://drive.google.com/file/d/0B9_05DMtc9B5T1UtMVl3UkJaUTg/view

It seems that it has something to do with New episodes' alert. Because in 'guest login' board works. 
Also, I have a problem with notifications. First, I can't disable it in the tray. After restarting the program it enabled again. In the second, every time I start the Stremio I get popup notifications about available new videos. I continue to get them even after I deleted all the items in series and channels libraries and reinstalling Stremio. I have only a few films in the library, where these available new videos may come from. I don't get these notifications on my PC.

Here is the video from my laptop and my first account https://drive.google.com/open?id=0B9_05DMtc9B5SlNCSG11a2VrMGc

**Comment by SOstrouhov** [comment]
It works now, but android app started crashes after start

**Comment by pateldhruv1993** [comment]
I'm having the same issue. I've tried restarting the program multiple time (even checked system tray and task manager to make sure the process isn't lingering) but it still won't fix itself. I think there is a bug in clearing the board of all the default shows and stuff and filling it with my latest shows.

**Comment by asolvang** [comment]
Same problem here. Windows 10 system. Tried reinstalling but not effective. I get new episode notification in the library, but when clicking into the show, the episodes do not show up. If I open any episode, and click the right bar with the list of all episodes, new episodes are shown with the yellow unseen mark. Everything works perfectly on the andorid app for me.

**Comment by Harith163** [comment]
Me too. It seemed to start after using the mobile app
