### ISSUE TITLE
[TizenOS] Playback Speed Issue

### ISSUE THREAD

**Issue by aadnan181** [Stremio/stremio-bugs#870]
**Describe the bug:**
I've noticed the playback speed option offers variable speeds but only 2x and 1x(normal) works. Rest of the speed options are just for show, they don't work when selected.

**To Reproduce:**
For any content from Real-Debrid, I have faced this issue. I haven't used any other add-ons so I cannot tell. For example, let's say I'm on 1x speed, when I change it to 1.5x or 1.25x, nothing happens, the stream continues to play on 1x speed. But the speed is only changed when I select 2x from 1x or vice-e-versa.

**TV Details:**
 - Device: [Samsung QN85C]
 - OS: [Tizen (Samsung)]
 - Version [7]

**Comment by TRtomasz** [comment]
should be fixed in the next release

**Comment by aadnan181** [comment]
Thanks a lot! Do you have an estimated timeline for the next release?

**Comment by TRtomasz** [comment]
@aadnan181  out of our hands, waiting for the update to be approved in the store
