### ISSUE TITLE
[DL+] Content - 100mb buffer is under-run with fast on-screen action with wifi connected devices. 

### ISSUE THREAD

**Issue by I3ordo** [Stremio/stremio-bugs#871]
For the usual content where stremio client connects to multiple sources , there is a way to set a cache size for the content to allow a larger cache size that help with slower connections.

However, once you use an add-on that allows you to access previously cached sources, the cache size is preset to 100mb to allow much responsive video progress seeking. (Fastforwarding or rooling back to previous timelines happen much faster due to smaller streaming cache size.) But this also cause prefectly capable wirelessly connected devices to run out of video cache as this 100mb cache is definetely not enough where the action on screen is too frequent like intros where the scenery changes every other second.

**To Reproduce**
1. add a torrentio add on with debrid account.
2. Select a content that has ~5gb size with a duration of ~60 minutes.
3. Click on "DL+" prefixed source so that, a previously cached file is delivered by the debrid enabled content.
4. See the endless buffering due to 100mb clearly not being enough. Especially true with content that has an intro sequence where screen is very dynamic.

**Expected behavior**
Similar to cache size setting for the usual p2p content, i wish stremio app had a similar cache size setting for the cached content(debrid) as well.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 x64 22h2

**Comment by TRtomasz** [comment]
This is almost not possible to understand what is your issue. Cache setting is only for torrents streams. There is no cache for other kind of streams like https streams(debrid). This is not a bug
