### ISSUE TITLE
few bugs for latest stremio android version.

### ISSUE THREAD

**Issue by spidy2356** [Stremio/stremio-bugs#872]
**Describe the bug**
1. if I go to next video from the player, the back button ( for me gesture) didn't work anymore.

2. if I pause stream, minimize the app, and play again after a few seconds, only black screen appears with sound. get fixed if I tap on backward button/ forward button or sometimes gets fixed automatically after a few seconds

**To Reproduce**
for bug no. 1, steps-
1. play a movie/series.
2. then from select second episode from the player, the option giver below right corner.
3. play second episode. and back button/ gesture stop working.

for bug no.2, steps
1. play any video
2. pause the video and minimize the app.
3. open the app again after few seconds and play video again. only black screen appears, only sound comes out.
I tried with external player, no issue there. so not the source issue.

**Expected behavior**
1. back button should work.

2. properly play the video without any black out.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: poco x2
 - OS: android 13

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**

**Comment by TRtomasz** [comment]
closing as duplicate for the first one - we track it in the different issue, second one isnt the bug we can fix as this is how vlc player behaves. Please in the future open one issue for one bug.
