### ISSUE TITLE
[Samsung App] App don't show the addons

### ISSUE THREAD

**Issue by mayracleal** [Stremio/stremio-bugs#873]
**Describe the bug**

I'm installed stremio app on my samsung tv but the addons don't show and don't permission to sync with app on my iphone or laptop. I don't know how I resolve this to watch on my tv, please help me.

I'm already reinstalled app on tv, iphone and laptop, but it's the same.

**To Reproduce**
I'm installed app on my tv, doing a login with QR code and ok. But when I click in someting to watch don't show any link to doing this and I go to the Addons tab and didn't have any addons install, just the screen write 'SYNC' and I press the button to do and nothing doing. I go to my iphone and all is there, installed, but don't show on my tv.

I put some images to show how appear on all the devices.

**Expected behavior**
Looks like my app on laptop: click on movie/series and show the links available to watch.

**Screenshots**
add files to show my library on tv and app and my addons on my app and tv too.
![IMG_3786](https://github.com/user-attachments/assets/8fb13611-fbff-4f75-8c37-064f1c06f581)
![IMG_3787](https://github.com/user-attachments/assets/1845c5d0-6f82-4fd1-ae75-dcda4f7dbfb3)
![IMG_3788](https://github.com/user-attachments/assets/16f5920f-c44a-421d-9bed-fb9e5f1acacd)
![IMG_3877](https://github.com/user-attachments/assets/de8e6f66-c506-4df8-9c5d-20caea4e983c)
![IMG_3876](https://github.com/user-attachments/assets/9f47378d-8dff-4fe1-8400-57c30099ecc6)
![IMG_3784](https://github.com/user-attachments/assets/44e1b000-1a7f-4626-8326-96e6ec4c9342)
![IMG_3874](https://github.com/user-attachments/assets/a62e5d5f-d5e6-40cc-9cc9-aea98f6fa520)

**Desktop:**
 - OS:  Windows 10
 - Browser: APP for windows
 - Version: 4.4.160

**Smartphone:**
 - Device: iPhone 14
 - OS: iOS 17.5.1
 - Browser: app to iOS
 - Version: Stremio Organizer 3.0.1

**TV:**
 - Device: TV Samsung AU7700 50"
 - OS: Tizen Samsung
 - Version: Stremio for Samsung TV 1.3.0

**Additional context**
 My library don't show on my tv too, but shows on my iphone and laptop, I put images here.

**Comment by TRtomasz** [comment]
If your library does not show you clearly logged on your TV using different account that you used to log in on your Laptop.

**Comment by mayracleal** [comment]
Hi Tomas, no, I didn't using different account to log in all advices, is the same.
