### ISSUE TITLE
Continue Watching no longer displaying Series when I'm up to the next episode

### ISSUE THREAD

**Issue by adrian-vapor** [Stremio/stremio-bugs#874]
**Describe the bug**
Before the last Android TV update (1.6.11) the Continue Watching section within the Stremio App (and version on the Home screen of my TV) used to display all Series that I was currently watching, whether I was in the middle of an episode or if the episode finished and I am up to the next episode.

After the update, it only lists the episodes which I am in the middle of. To access the next episode for seasons of TV shows I am watching, I now have to continually go to Library - Series and select the show from there.

**To Reproduce**
1. Go to 'Home - Continue Watching'
2. Only Series whose episodes have been started are listed here

**Expected behavior**
Would like it to again display all Series here which have a next available episode (i.e. not a completed series) as well as episodes which have been started.

**Screenshots**

**TV (please complete the following information):**
 - Device: Sony BRAVIA 4K UR3 (A8H)
 - OS: Android TV v14
 - Stremio: v1.6.11

**Comment by TRtomasz** [comment]
i'v just checked and they are displaying perfectly fine, if you play any episode after new one is released notifications are removed.

**Comment by adrian-vapor** [comment]
Thanks for your response, but I think you have misunderstood my issue. I've been using Stremio for at least two years, and even when watching old series which have no new episodes (e.g. Seinfeld), the series would remain in the Continue Watching section after I watched each episode, until I would complete the whole series, when it would then be removed.

Has this behaviour changed since the latest software release? Is this how it is supposed to work, or was a bug introduced in the latest software release?

It is much more convenient to keep watching series from the Continue Watching section, rather than having to go to your Library each time to continue watching the next episode.

**Comment by TRtomasz** [comment]
Nothing like this has been changed in latest version and i have checked myslef again and it is working just fine but you must have auto play next episode enabled in the settings. 
Stremio have many millions of users everyday i dont think there was any bug introduced considering you are the only one reporting that something is wrong.

**Comment by adrian-vapor** [comment]
OK NP. Any suggestions then? I've logged out and back in, then I uninstalled and re-installed. Anything else you can think of (I do already have auto play next episode turned ON)? Do you think a hard resetting of the Sony TV would help at all (just reticent to do this since it takes a while to set everything up again)? Cheers!

**Comment by adrian-vapor** [comment]
@TRtomasz I've figured out what is happening. The issue only occurs if you use the Skip button either using your TV's remote or via the on-screen menu. If you instead use the Seek (Fast Forward) button on your TV remote, or click on the "Skip CREDITS" button (which appears on-screen near the end of an episode) to navigate to the end of the episode, you can back out of that series without having to watch a few seconds of the next episode, and the series remains in the Continue Watching section.

This issue only started after the latest software update (https://blog.stremio.com/stremio-tech-update-31-stremio-android-tv-updated/), as I've been using the Skip button for months to get to the next episode quickly, and it would always load the next episode on my Continue Watching list.

Are you able to re-open this issue and see if you can replicate it? Or, would you prefer I opened a new issue?

P.S. this solution also works for the other issue I raised https://github.com/Stremio/stremio-bugs/issues/875
