### ISSUE TITLE
Attempt to watch next episode of a Series, you are taken to episode list with the previous episode selected

### ISSUE THREAD

**Issue by adrian-vapor** [Stremio/stremio-bugs#875]
**Describe the bug**
After you finish an episode of a Series you are watching, when you leave the session, then go back to watch the next episode from Libraray, it instead takes you to the list of episodes, with the previous episode selected. Before the last Android TV update (1.6.11), this behaviour used to result in the next episode being played (bypassing the episode list).

**To Reproduce**
1. Go to 'Library'
2. Click on 'a show you would like to watch'
3. The episode list is displayed, with the previously watched episode highlighted.

**Expected behavior**
When you click on any Series which has remaining epsiodes in the season/show, it should play the next episode, bypassing the episode list (obviously only if the source that was previously selected has the next episode).

**TV (please complete the following information):**
 - Device: Sony BRAVIA 4K UR3 (A8H)
 - OS: Android TV v14
 - Stremio: v1.6.11

**Comment by TRtomasz** [comment]
please check if you have auto play next episode enabled in the settings.

**Comment by adrian-vapor** [comment]
Again, thanks for your comment. I do have auto play next episode ON, and have always had this on and not changed any settings since I set Stremio up around two years ago.

As per issue https://github.com/Stremio/stremio-bugs/issues/874, this behaviour has only changed since the latest software release.

Is there any way to download previous software versions?
