### ISSUE TITLE
No persistence of subtitle delay - Chromecast with Google TV

### ISSUE THREAD

**Issue by n-katti** [Stremio/stremio-bugs#878]
**Describe the bug**
I have to delay all subtitles by 0.5 seconds usually. When I use the Next Episode button, either at the end of an episode or within the player controls, this 0.5 second delay does NOT carry over into the next episode - this is confirmed even if I am using the same exact subtitles. However, at the end of an episode, if I exit out of the player/stream and manually go click on the next episode, the 0.5 second delay will carry over. The fact that this method works proves that it does not have to do with the subtitles being different from episode to episode. Thanks!

**To Reproduce**
1. Start streaming an episode of any TV show
2. Set a delay for the subtitles
3. Click on the next episode button - either at the end of the stream, or within the controls/UI
4. When you get to the next episode, the subtitle delay will be gone 
5. However, if you set a delay and then exit out of the current episode stream, use the show details page to navigate to the next episode, and open a stream, the delay will persist 

**Expected behavior**
The subtitle delay should persist using both methods of going to the next episode. This issue occurs even despite using the same exact stream source (for a different episode) and same subtitle source. 

**Screenshots**
N/A

**TV (please complete the following information):**
 - Device: Chromecast with Google TV
 - OS: Android/Google TV
 - Version 1.6.11

**Comment by TRtomasz** [comment]
There is a bug here but it is not what you think, bug is to carry subtitles delay to next episode this does not make any sense
