### ISSUE TITLE
ADDON_PUSH_FAILED error

### ISSUE THREAD

**Issue by brunnovfc** [Stremio/stremio-bugs#879]
**Describe the bug**

**Screenshots**
<img width="365" alt="Captura de Tela 2024-07-24 às 17 03 55" src="https://github.com/user-attachments/assets/c80a937d-e054-498e-a8b1-b975f2acd2cf">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1 

**Additional context**

This error started today in my Stremio app (Mac Sonoma), and I simply cannot watch anything as it doesn't show any watch options for any film or series. I tried searching and found out that I should uninstall and reinstall the add-ons, and Stremio should work properly. I have already done that, and the error persisted. I tried uninstalling and then reinstalling Stremio, and the error remained. Now I have only two add-ons installed (Cinemeta and Local Files), which cannot be uninstalled (Protected add-on). When I try to install any add-on, the error "ADDON_PUSH_FAILED" appears. What can I do?

**Comment by TRtomasz** [comment]
For some reason looks like you are using outaded stremio app please update it to the latest version
