### ISSUE TITLE
Android TV 1.6.11 Exoplayer issues

### ISSUE THREAD

**Issue by virmele** [Stremio/stremio-bugs#880]
Exoplayer on Android TV 1.6.11 is buggy and performing very badly. I tested this on 3 different devices, and all showed same behaviour. Also, there is a thread on reddit with other people having same issue. Ever since 1.6.10 exoplayer keeps crashing on higher bitrate files. I used to be able to playback 80gb size movies without issues on both nvidia shield pro, and sony android tv. With newest version, even 20gb movies crash sometimes. Something like 40gb will instantly crash. If I install older version of stremio, which I suspect has older version of Exo player(1.5.7), all issues disappear and I'm able to play even the biggest 80gb rips with no problem.

**To Reproduce**
1. Play 30+ gb size movie and exo player will crash evetually

**Expected behavior**
On older versions like 1.5.7, I can play even the biggest bitrate content without issues, and I confirmed this with 3 different Android TV devices.

**TV (please complete the following information):**
 - Device: Nvidia Shield Pro, Sony Android TV 10, TCL Android TV 11.

**Comment by TRtomasz** [comment]
We cant fix exoplayer issues, as we do not develop exoplayer, we could only wait for next stable release and update it in our app.

**Comment by virmele** [comment]
I understand that, but would it not be smart to release update with the older version of Exo that nobody had issues with?

**Comment by dineshalphaque** [comment]
1.6.11 on Android TV 12 CCwGTV keeps buffering on large files as well, 25GB and above whole streaming from real-debrid. The buffering happens every 4-5 minutes and lasts about 15 seconds.

Have similar experience on Andros TV 10 as well with buffering for 1.6.11.

The test versions of 1.6.12 posted in the Stremio subreddit face the same problem.
