### ISSUE TITLE
Continue watching catalog has different state across platforms

### ISSUE THREAD

**Issue by mattokar** [Stremio/stremio-bugs#882]
**Describe the bug**
I just did full setup of stremio and also imported my trakt watched history on https://www.stremio.com/acc-settings

Now Continue watching on web player shows only one show where I am missing latest episode. This is correct state, same as on my Kodi setup. Android and Lg webOS app are not showing this. Continue Watching catalog is missing or empty. Does anybody know why? (I did sync addons on Lg)

Thank you

**To Reproduce**
1. Import trakt history
2. Check Continue catalog on different platforms

**Expected behavior**
Continue catalog contains in progress episodes, movies and also started shows with not watched episodes. And has same behaviour on all platforms.

**Screenshots**
<img width="514" alt="image" src="https://github.com/user-attachments/assets/28d14971-6d7c-4805-8fd1-86cc34738293">
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/ad1459e0-450e-4eeb-8f9a-ed780d5f7f7f">

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Browser chrome 127.0.6533.73

**Smartphone (please complete the following information):**
 - Device: Galaxy S24
 - OS: Android 14
 - Stremio Version 1.6.12

**TV (please complete the following information):**
 - Device: LG OLED65C11LB
 - OS: webOS 6.3.2, firmware 03.34.95

**Comment by TRtomasz** [comment]
lg webos app does not have implemented notifications
