### ISSUE TITLE
TV channels cannot be filtered by genre on Android TV and Web client

### ISSUE THREAD

**Issue by DryKillLogic** [Stremio/stremio-bugs#885]
**Describe the bug**
On discovery, TV channels cannot be filtered by genre on Android TV and Web client.  In other platforms work as expected. I'm unsure whether this is a bug or hasn't been implemented yet. Thanks! 

**To Reproduce**
1. Go to the Discovery page on Android TV or the Web client
2. Select TV channels 
3. Try to filter by genre 
4. No genres are shown in the dropdown

**Expected behavior**
The list of genres should be displayed

**Additional**
This might be the case for other platforms which I don't have access to.

**Comment by TRtomasz** [comment]
Which addon are you using?

**Comment by DryKillLogic** [comment]
@TRtomasz https://stremio-addons.netlify.app/usa-tv

**Comment by TRtomasz** [comment]
@DryKillLogic  this is not stremio issue, this addon does not adhere to the new stremio addon sdk thats why it is not possible to select genres in new apps
![image](https://github.com/user-attachments/assets/bfa8746e-00ef-4b04-97ef-931f54de5cff)

**Comment by dexter21767-dev** [comment]
@DryKillLogic a follow-up on what @TRtomasz said, 

here's what the fixed version should look like 

```json
{
  "id": "community.usatv",
  "version": "1.1.0",
  "catalogs": [
    {
      "name": "USA TV",
      "type": "tv",
      "id": "all",
      "extra": [
        {
          "name": "genre",
          "isRequired": false,
          "options": [
            "Local",
            "News",
            "Sports",
            "Entertainment",
            "Lifestyle",
            "Kids",
            "Spanish",
            "Documentaries"
          ]
        }
      ]
    }
  ],
  "resources": [
    "catalog",
    "stream",
    "meta"
  ],
  "types": [
    "tv"
  ],
  "name": "USA TV",
  "description": "USA TV provides access to channels across various categories including local channels, news, sports, entertainment, lifestyle, kids' shows, Spanish-language programming, documentaries, and much more.",
  "logo": "https://848b3516657c-usatv.baby-beamup.club/public/logo.png",
  "background": "https://848b3516657c-usatv.baby-beamup.club/public/background.jpg"
}
```

also i would highly suggest using the [idPrefixes property](https://github.com/Stremio/stremio-addon-sdk/blob/fd80858284eb11c9d4206d4697b41f5defee0562/docs/api/responses/manifest.md#filtering-properties) 
cuz as it's now, a user that has the addon installed, will send a request to your addon whenever he's trying to watch anything with the type "tv", which can overload your addon with unnecessary requests.

**Comment by DryKillLogic** [comment]
@dexter21767-dev  @TRtomasz Thanks guys for the help, I will implement those changes.
