### ISSUE TITLE
Subtitle no tracks error when loading locally

### ISSUE THREAD

**Issue by AdivonSlav** [Stremio/stremio-bugs#887]
**Describe the bug**
Whenever I attempt to locally drag a subtitle to Stremio (flatpak version), I get `Error: no tracks`. On closer inspection when running Stremio through the terminal, I can see this:
```bash
-> GET /subtitles.vtt?from=/home/adi/Downloads/79766-The_Dark_Knight_1Cd_Eng_2008.Srt/The.Dark.Knight%255B2008%255DDvDrip-aXXo.srt 
[Error: ENOENT: no such file or directory, open '/home/adi/Downloads/79766-The_Dark_Knight_1Cd_Eng_2008.Srt/The.Dark.Knight%5B2008%5DDvDrip-aXXo.srt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/adi/Downloads/79766-The_Dark_Knight_1Cd_Eng_2008.Srt/The.Dark.Knight%5B2008%5DDvDrip-aXXo.srt'
}
```

I'm also building a Stremio subtitle addon and encounter this same issue, whenever I respond to Stremio's requests for subtitles, they never load with the same "No tracks" error.

**To Reproduce**
1. Open any stream
2. Drag a SRT subtitle to the player
3. See error

**Expected behavior**
Subtitles actually loading

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04
- App: Stremio Flatpak 4.4.168

**Comment by TRtomasz** [comment]
Subtitles has to be in utf8 encoding to work properly

**Comment by pratik-ac** [comment]
Flatpak apps runs in sandbox for security purposes so you have to grant file system access 

sudo flatpak override com.stremio.Stremio --filesystem=home

restart after this and it should work
