### ISSUE TITLE
Stremio server error at start

### ISSUE THREAD

**Issue by m4n0v31** [Stremio/stremio-bugs#897]
Stremio server crashes shortly after start. See error below.

Stremio server v4.20.8, run in Docker container using:
https://github.com/tsaridas/stremio-docker

Error:

/srv/stremio-server/server.js:33726
                return parseFloat(value.replace(/([\d.]+)(\w?)/, (function(_, val, unit) {
                                        ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at parseValue (/srv/stremio-server/server.js:33726:41)
    at /srv/stremio-server/server.js:33741:31
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:350:12)

Node.js v18.20.3

**Comment by TRtomasz** [comment]
We are not able to help with 3rd party components use stremio server-docker github repo for official package

**Comment by jaruba** [comment]
or create an issue at: https://github.com/tsaridas/stremio-docker instead?

**Comment by m4n0v31** [comment]
The Docker just download the server from:
https://dl.strem.io/server/v4.20.8/desktop/server.js

And then starts it with node:
node server.js

**Comment by tsaridas** [comment]
maybe check the content of server.js in the image to verify that it downloaded it correctly. I guess I might need to make some changes on the download to validate a 200 response and fail if not.

**Comment by m4n0v31** [comment]
Thx for the feedback. The server.js files is correctly downloaded, you can see the line in which the error is thrown (number and also content) in the first post.
Additionally, if I modify the line where the error is happening to return always 10 to the parseFloat, the server runs correctly.

**Comment by jaruba** [comment]
@m4n0v31 it is not correctly downloaded, that line doesn't exist in the server.js code, it downloaded an error xml file
here is an example:
- correct server url with correct version: https://dl.strem.io/server/v4.20.9/desktop/server.js
- incorrect server url, using incorrect server version:https://dl.strem.io/server/v4.20.10/desktop/server.js

do you see how an incorrect url leads to a xml page with an error? and do u see how the line from ur logs is a xml file header instead of JS code?

**Comment by jaruba** [comment]
i removed my comment because i confused the issues, there are 2 similar issues that were created today

**Comment by jaruba** [comment]
to answer properly: there are only a few things that can break the server on startup:
- a network error
- a fs access error
- invalid settings json file
- incompatible nodejs version

if the server was downloaded properly, then the environment in which it is running is the issue, in this case the docker container, as we did not build the docker container, then the factors that generate this error are outside of the Stremio Team's control

**Comment by tsaridas** [comment]
@m4n0v31 it has something to do with the disk. as you might have seen the function being called there is getDiskSpace. I'm guessing disk is full or readonly ? You can continue the topic on : https://github.com/tsaridas/stremio-docker/issues/40

**Comment by m4n0v31** [comment]
The issue was correctly given by the environment in which server.js was running.
The output of the "df -k" command used in the server is not standardized, some system write the output differently and the parsing made fails. 
If the flag -P is added to the command, then the output is POSIX confirm and the parsing works

See below:
df -k /tmp
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/cachedev_1
                     5621459192 1052306704 4569152488  19% /

df -Pk /tmp
Filesystem           1024-blocks    Used Available Capacity Mounted on
/dev/mapper/cachedev_1   5621459192 1052306824 4569152368  19% /
