### ISSUE TITLE
Can't play some videos, because "Codec not supported"

### ISSUE THREAD

**Issue by lovromazgon** [Stremio/stremio-bugs#9]
I'm running Stremio 3.3.1 on Ubuntu 15.10 and some videos are not playing. If I run Stremio from the terminal I get these messages:

```
[00003f6c32772e58] core demux error: corrupt module: /opt/stremio/WCjs/vlc/lib/vlc/plugins/demux/libmkv_plugin.so
[00003f6c342fa298] core decoder error: Codec `h264' (H264 - MPEG-4 AVC (part 10)) is not supported.
[00003f6c342fa298] core decoder error: Codec not supported
[00003f6c342fa298] core decoder error: VLC could not decode the format "h264" (H264 - MPEG-4 AVC (part 10))
```

or this:

```
[00003f6c328c3b98] core decoder error: Codec `mp4v' (MPEG-4 Video) is not supported.
[00003f6c328c3b98] core decoder error: Codec not supported
[00003f6c328c3b98] core decoder error: VLC could not decode the format "mp4v" (MPEG-4 Video)
[00003f6c33d53c98] mpgatofixed32 audio converter error: libmad error: bad main_data_begin pointer
```

I've got VLC and ubuntu-restricted-extras, so VLC normally plays everything.

**Comment by Ivshti** [comment]
This is a Linux-specific issue, where it happens if libs like libav aren't installed. Safe bet would be to install the whole VLC and it would also install all it's deps with it.

**Comment by lovromazgon** [comment]
I have the whole VLC installed (even before stremio). The problem is only present on a few videos, for example series "The Last Man on Earth" season 1 episodes 6-10. All others work fine.

Anyway, still a great app, kudos! :+1:

**Comment by ed0c** [comment]
Hi!
I've got the same issue for some vids
"VLC could not decode the format "hevc" (MPEG-H Part2/HEVC (H.265))"
I'm on Archlinux, and the latest VLC is installed. Also, I tried to play some vids encoded in H265 with VLC, and it worked, so it doesn't seem to be a problem related to vlc..
I don't have a clue to solve the problem!

**Comment by Ivshti** [comment]
@ed0c can do you do the following: in the dir you installed Stremio, there is a WCJs dir, and inside there's something like lib/ or vlc/lib, where all the .so files are located. Try to run ldd on them and see which are the missing .so files

**Comment by ed0c** [comment]
I'm sorry but i don't know the tool "ldd". How can i use it ? It doesn't work if i try directly "ldd libvlc.so"
And here is the content of the vlc/lib folder which i found in the WCJs dir:

```
ls -la
total 1192
drwxr-xr-x 4 root root    4096 25 nov.  16:37 .
drwxr-xr-x 3 root root    4096 25 nov.  16:37 ..
-rw-r--r-- 1 root root    6148 23 août  14:40 .DS_Store
-rwxr-xr-x 1 root root      15 23 août  14:40 libvlc.so
-rwxr-xr-x 1 root root      15 23 août  14:40 libvlc.so.5
-rwxr-xr-x 1 root root  130440 25 nov.  16:31 libvlc.so.5.5.0
-rwxr-xr-x 1 root root      19 23 août  14:40 libvlccore.so
-rwxr-xr-x 1 root root      19 23 août  14:40 libvlccore.so.8
-rwxr-xr-x 1 root root 1048176 25 nov.  16:31 libvlccore.so.8.0.0
drwxr-xr-x 2 root root    4096 25 nov.  16:37 pkgconfig
drwxr-xr-x 4 root root    4096 25 nov.  16:37 vlc
```

**Comment by lovromazgon** [comment]
I've got the same structure, and the command `ldd *` outputs:

    libvlccore.la:
        not a dynamic executable
    libvlccore.so:
        not a dynamic executable
    libvlccore.so.8:
        not a dynamic executable
    libvlccore.so.8.0.0:
        linux-vdso.so.1 =>  (0x00007ffd95bec000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2443336000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f2443103000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2442ee4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2442ce0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f24429d8000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f244278b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f24423c1000)
        /lib64/ld-linux-x86-64.so.2 (0x0000561bda7c8000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f2442340000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f244211d000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f2441e3b000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2441c28000)
    libvlc.la:
        not a dynamic executable
    libvlc.so:
        not a dynamic executable
    libvlc.so.5:
        not a dynamic executable
    libvlc.so.5.5.0:
        linux-vdso.so.1 =>  (0x00007ffd51523000)
        libvlccore.so.8 => /usr/lib/libvlccore.so.8 (0x00007faacf379000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faacf15b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faacee52000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faacea88000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007faace880000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007faace64c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faace448000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007faace1fc000)
        /lib64/ld-linux-x86-64.so.2 (0x0000558d07340000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007faace17a000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007faacdf58000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007faacdc76000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007faacda62000)

**Comment by ed0c** [comment]
Ok. So i have this result :
```
./libvlc.so:
	n'est pas un exécutable dynamique
./libvlc.so.5:
	n'est pas un exécutable dynamique
./libvlc.so.5.5.0:
	linux-vdso.so.1 (0x00007fffcddf3000)
	libvlccore.so.8 => /usr/lib/libvlccore.so.8 (0x00007f8b34821000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8b34604000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f8b34306000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8b33f61000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f8b33d59000)
	libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f8b33b25000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f8b33920000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f8b336cf000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x0000563fb0444000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f8b3364a000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f8b33433000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f8b3320d000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f8b32ffb000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f8b32d18000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f8b32b05000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f8b32901000)
	libattr.so.1 => /usr/lib/libattr.so.1 (0x00007f8b326fb000)
./libvlccore.so:
	n'est pas un exécutable dynamique
./libvlccore.so.8:
	n'est pas un exécutable dynamique
./libvlccore.so.8.0.0:
	linux-vdso.so.1 (0x00007ffcdf1d9000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f8d025e3000)
	libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f8d023af000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f8d02192000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f8d01f8d000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f8d01c8f000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f8d01a3e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f8d01699000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00005651cbb4f000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f8d01615000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f8d013fe000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f8d011d7000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f8d00fc5000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f8d00ce3000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f8d00acf000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f8d008cb000)
	libattr.so.1 => /usr/lib/libattr.so.1 (0x00007f8d006c5000)
```

**Comment by Ivshti** [comment]
@ed0c @lovromazgon try ldd on vlc/plugins/* - i.e. all the vlc plug-ins. Since that will output a huge lot of results, grep-ing for not founds somehow would be great. I'm not sure what's the string ldd will use when something's not found though

**Comment by lovromazgon** [comment]
the command `find . -type f | xargs ldd | grep "not found"` inside the `vlc/plugins` folder outputs:

    libdvbpsi.so.8 => not found
    libavformat.so.54 => not found
    libavcodec.so.54 => not found
    libavutil.so.52 => not found
    libdvbpsi.so.8 => not found
    libtar.so.0 => not found
    libgcrypt.so.11 => not found
    libgcrypt.so.11 => not found
    libswscale.so.2 => not found
    libgcrypt.so.11 => not found
    libgcrypt.so.11 => not found
    libpostproc.so.52 => not found
    libavutil.so.52 => not found
    libgnutls.so.28 => not found
    libass.so.4 => not found
    libavcodec.so.54 => not found
    libavutil.so.52 => not found
    libx264.so.142 => not found
    libdvbpsi.so.8 => not found
    libavformat.so.54 => not found
    libavutil.so.52 => not found
    libgcrypt.so.11 => not found
    libfreerdp-core.so.1.0 => not found
    libfreerdp-gdi.so.1.0 => not found
    libdvbpsi.so.8 => not found
    libavcodec.so.54 => not found
    libavutil.so.52 => not found
    libgcrypt.so.11 => not found

now we're getting somewhere :)

**Comment by Ivshti** [comment]
definitely! it appears to me like you have a newer or older version of VLC installed, which depends on, for example, libx264.so.141 instead of .142

Stremio uses VLC 2.2

Anyway, since you do have VLC installed, and the WebChimera.js player we're using is compatible with multiple VLC versions, consider doing this:

Open Stremio.sh and replace
```
LD_PRELOAD="./WCjs/vlc/lib/libvlc.so.5.5.0 ./WCjs/vlc/lib/libvlccore.so.8.0.0" ./Stremio-runtime . $@
```
with just
```
./Stremio-runtime . $@
```

**Comment by lovromazgon** [comment]
Works like a charm! :+1: Thanks for your support!

**Comment by Ivshti** [comment]
@lovromazgon keeping this open cause other users might run into it, and we can't expect them to fix it by themselves.

I'm thinking of disabling the VLC player from the Linux version. In that case Stremio will be only able to play mp4/webm, but users will be able to install vlc to enable support of other formats inside Stremio

**Comment by ed0c** [comment]
I agree with @Ivshti .
And i've got the latest version of vlc:
VLC media player 2.2.1 Terry Pratchett (Weatherwax) (revision 2.2.1-0-ga425c42)

So it's a bit weird

**Comment by Ivshti** [comment]
So here's my solution.

This is Stremio.sh
```
#!/usr/bin/env bash
cd $(dirname $0)
if [ `which vlc` ]; then
	./Stremio-runtime . $@
else
	# WARNING: this doesn't guarantee anything since we still need the deps of all the vlc plugins
	# so maybe consider removing the bundled vlc from stremio entirely
	LD_PRELOAD="./WCjs/vlc/lib/libvlc.so.5.5.0 ./WCjs/vlc/lib/libvlccore.so.8.0.0" ./Stremio-runtime . $@
fi
```

If the user has an installed VLC, it will use it, otherwise fallback to our bundled version.

As I said, maybe in near future we'd have the bundled vlc removed entirely, first for Linux and then for the other operating systems.

We can fallback on our transcoding tech, which is pretty low-overhead for most files - avi are usually low quality and most mkv's only require audio transcoding.

**Comment by lovromazgon** [comment]
Sorry for closing the issue. I would just suggest that you improve the if statement, because of [this answer](http://stackoverflow.com/a/677212/1212463). Maybe I'm nitpicking, but according to the answer you should use:

    if hash vlc 2>/dev/null; then
    ...

Anyway, thanks for looking into this issue.

**Comment by Ivshti** [comment]
@lovromazgon point taken, I now remembered that which indeed does package manager things, we don't want that in the start script.
Changed it to hash

With this script this issue will be partially fixed, I'm probably going to close it then

In the future, via avoiding bundled vlc entirely, the issue will be 100% solved

**Comment by gadelat** [comment]
I run this issue on Ubuntu 16.04 and solved it with installing ffmpeg

**Comment by TRtomasz** [comment]
Closing. Stremio 3.x is no longer mantained
