### ISSUE TITLE
No `webm` support?

### ISSUE THREAD

**Issue by dessalines** [Stremio/stremio-bugs#900]
**Describe the bug**

I created a torrent for a locally created video in the `.webm` format. After adding the magnet link to stremio, it shows empty text, and you cannot even click the video to begin streaming.

I tried encoding the same video to `mkv`, and recreating the torrent, and that works perfectly.

**To Reproduce**
1. Add a torrent to stremio that contains a webm file.
2. An empty, unclickable block is shown, that is unable to stream

**Expected behavior**

It should be able to stream the video like a `mkv`, which seems to work fine.

**Smartphone (please complete the following information):**
 - Device: Android Oneplus
 - OS: Android 13
 - Version : 1.6.12

**Comment by jaruba** [comment]
`stremio-bugs` was created 9 years ago, this is the very first request for webm support, unless we see more user interest, we cannot dedicate time to this.. it is simply not a common enough video container

**Comment by dessalines** [comment]
Alright then, thank you.
