### ISSUE TITLE
Brazillian Portuguese not Available on Subtitles OpenSubtitlesV3 official add-on

### ISSUE THREAD

**Issue by ebellumat** [Stremio/stremio-bugs#908]
**Describe the Bug**
The Subtitles language options include Portuguese, but it is Portuguese from Portugal, not Brazilian Portuguese. To get Brazilian Portuguese subtitles, I had to use additional Subtitle Add-Ons.

Brazilian Portuguese differs significantly from European Portuguese, making it difficult to read and, in some cases, it's more comfortable to use English subtitles instead.

**To Reproduce**
Steps to reproduce the issue:
1. Open the Subtitles Menu.
2. Click on Languages.
3. Scroll down to Portuguese.
4. Notice that Brazilian Portuguese is not available.

**Expected Behavior**
The Subtitles menu should differentiate between Portuguese (Portugal) and Brazilian Portuguese, allowing users to select the correct version.

**Screenshots**
![IMG_4228](https://github.com/user-attachments/assets/d3d90c07-0930-4094-9d22-4ebb1f0ab86a)

**TV (please complete the following information):**
- Device: LG OLED C1
- OS: Web OS
- Version: 03.40.87

**Additional Context**
It would be helpful to add distinct options for both language variants to improve user experience.

**Comment by TRtomasz** [comment]
this is duplicate, well known issue will be fixed in the next update https://github.com/Stremio/stremio-bugs/issues/767
