### ISSUE TITLE
Stremio crashing immediately after streaming content 

### ISSUE THREAD

**Issue by arrow00009** [Stremio/stremio-bugs#914]
**Describe the bug**
Crashing after 4-5 secs into any show on both lg G2 and firestick 4k
**TV (LG G2 ):**
 - Device: [firestick ]
 - OS: [fire tv os and lg webos ]

**Additional context**
Tried changing settings like playback toggle on and.off.and stuff ,still crashing.
On LG webos tv  stremio app it gets stuck like 30secs and then closes the app then tv itself turns off

**Comment by TRtomasz** [comment]
Please update the issue with details we can use to reproduce the issue(which stream you are trying to play), from your brief description looks like you are trying to play content your devices cant handle.
