### ISSUE TITLE
Cannot continue progress of show/movie

### ISSUE THREAD

**Issue by koukos93** [Stremio/stremio-bugs#916]
**Describe the bug**
If i have an episode or movie that i stopped watching halfway, when i return to continue watching, it gets stuck at flashing the show name(buffering) and after a while the app crashes(not everytime, sometimes it stays like that until i press back).Not speed related(300mbps line) as i found that if i hold 
select->clear progress and restart the stream from the beginning it starts normally and i have to fast forward to where i left off.

**To Reproduce**
1. Go to a show that you watched and left before ending.
2. Click on the show to continue playing.
3. Name of show keeps flashing even if i pick a different stream than the one i picked previously.

**Expected behavior**
Expected the stream to continue from the point i stopped watching.

**Screenshots**

**TV (please complete the following information):**
 - Device: [Nvidia shield tv pro 2019]
 - OS: [Android TV]
 - Version [9.1.1]
 - Stremio Version [1.6.09] also tried with [1.6.11]
**Additional context**
tried different streams, qualities, DV, non DV streams, hdr or atmos same behavior.

**Comment by TRtomasz** [comment]
There is no bug, connection timeouts if you leave it paused for a long time and you should exit player and open it again.

**Comment by koukos93** [comment]
After some testing on my pc, i tried the same scenario. While show name flashed i went to task manager to see if ethernet was being used and i saw that it was pulling all of my 330 mbps line. My understanding is that since i was left halfway it has to re-download or re-stream the whole file again till it reaches the point i stopped watching to resume playback. Tested it on my shield and sure enough after some time it resumed. Still sometimes the app crashes while buffering. I remember maybe a month before i just resumed the episode and it started instantly. Maybe it was cached on device and i coincidentally had stopped the episode/movie very early on. I am gonna go ahead and close the issue.
