### ISSUE TITLE
Player 

### ISSUE THREAD

**Issue by tomtomclub** [Stremio/stremio-bugs#919]
**Describe the bug**
Found the problem i think its player in stremio way? Because stremio doesn't play anything when I turn on the subs in my Android phone and when it's off? I'm stuck
Probleem 2 Android tv box Several types of subs addons no longer work with series not being displayed no matter what you do

**To Reproduce**
1. Serie'
2. For example Evil so4E013. And many more
3. Scroll down to '. Pick subs ...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 
 - Browser tv box and Android phone 
 - Version [

**Smartphone (please complete the following information):**
 - Device: Oppo 
 - OS: 11

**TV (please complete the following information):**
 - Device: [Nvidia shild

**Additional context**

**Comment by TRtomasz** [comment]
It is not possible to understand what is your issue please create it once again with a description and screenshots that will help us understand what is going on for you.

**Comment by tomtomclub** [comment]
What I actually want to say is that as an example the subtitle add-ons for series no longer appear, this is difficult ; You increasingly see that series are no longer shown on screen Hey it seems that code is no longer found for translations
