### ISSUE TITLE
Stremio does not close when X icon is clicked

### ISSUE THREAD

**Issue by mikegoodstadt** [Stremio/stremio-bugs#92]
Hi - Firstly thanks for developing such a great app! :)
Now the bug:
Version: Stremio 3.6.5
OS: macOS 10.12.2 (and before on OSX 10.10.5)
Bug: Fails to close when clicking the X on the interface.
Workaround: Rick click on Dock icon and select Close.

**Comment by Ivshti** [comment]
This is intended behaviour, as Stremio sends you notifications for the episodes that come out for the series you follow.

Maybe we will add an option to disable it if there's enough demand
