### ISSUE TITLE
Overlapping Text and Shortcut Labels in Search Box Context Menu

### ISSUE THREAD

**Issue by metha1** [Stremio/stremio-bugs#922]
**Bug Description:**
When a user right-clicks within the search box in Stremio, the context menu appears, displaying actions such as "Undo," "Redo," "Cut," "Copy," "Paste," and "Select all." However, the text labels and their corresponding shortcut labels (e.g., "Ctrl+Z," "Ctrl+Y," etc.) are overlapping, making them difficult to read and understand.

**Expected Behavior:**
The text labels and shortcut labels should be displayed clearly and without overlap.
The context menu should be designed to accommodate the full length of the labels and shortcuts.

**Steps to Reproduce:**
- Launch Stremio.
- Navigate to the search bar.
- Right-click within the search bar.
- Observe the overlapping text and shortcut labels in the context menu.

**Impact:**
User experience is negatively affected due to the difficulty in reading and understanding the available actions.
The functionality of the context menu may be hindered if users cannot accurately identify and select the desired actions

**Device Information:**
- Device Model: HP Zbook 15 g2
- Operating System: Fedora Linux 40
- Graphics Card Model: ‎Nvidia Quadro K100M
- CPU Model: 8 × Intel® Core™ i7-4810MQ CPU @ 2.80GHz

**Screenshot:**
![2024-09-13_10-58](https://github.com/user-attachments/assets/993d34f5-ac59-4664-a442-625d22b7301a)

**Comment by TRtomasz** [comment]
We do not modify this context menu moste likely issue is coming from your OS or desktop environment
