### ISSUE TITLE
Error_Code_Failed_Runtime_Check

### ISSUE THREAD

**Issue by BaconRollz14** [Stremio/stremio-bugs#923]
**Describe the bug**
RD+ file plays on ExoPlayer for 15-20 seconds and then crashes and get the message "Error_Code_Failed_Runtime_Check" and then drops to libvlc. This seems to only happen on Dolby Vision Content.

**To Reproduce**
1. Play DV file using Exoplayer on shield using torrentino link. 

**Expected behavior**
File plays DV content without issue.

**Screenshots**

**TV (please complete the following information):**
 - Device: Shield Pro 4k
 - OS: Android TV
 - Version 4.4

**Additional context**
LG G3 Tv, Gigabit internet hardwired. No issues playing same content on Plex, issue limited to Streamio.

**Comment by TRtomasz** [comment]
We cant help with media3(Exo player issues like this) you can try changing your settings like tunneled playback setting
