### ISSUE TITLE
Can’t disable Samsung TV subtitles

### ISSUE THREAD

**Issue by Johnboy90** [Stremio/stremio-bugs#924]
**Describe the bug**
You cannot permanently disable subtitles on Samsung TV. You can turn them of in an episode but they will turn back on for the next one. 

**To Reproduce**
Try to disable subtitles. 

**Expected behavior**

Subtitles stay off.

**Screenshots**

**TV (please complete the following information):**
 
 All models of Samsung TV. 
 

**Additional context**

Problem since launch

**Comment by BehaDev** [comment]
it doesn't save subtitles preferences somehow i don't know why , i hope it gets fixed asap stremio on samsung TVS has lot lots of problems tho...

**Comment by TRtomasz** [comment]
This is a known issue will be fixed in the ucpoming release
