### ISSUE TITLE
4K H.265 content showing black screen on Fire Stick 4K Stremio Stremio 1.6.12 ARM APK

### ISSUE THREAD

**Issue by TheMaje1992** [Stremio/stremio-bugs#926]
Whenever I try to play a 4K H.265 video file, I get a black screen, audio is working fine, ATMOS data is being picked up by my soundbar, and subtitles are being displayed.

**To Reproduce**

1. Go to 'Stremio from FireStick apps menu'
2. Select your desired 4K content
3. Select a 4K file with a H.265 tag in the file name (using torrentio scraper)
4. Video will play with no visual data (black screen) audio is working fine, ATMOS data is being picked up by my soundbar, and subtitles are being displayed.

**Expected behavior**
i would expect there to be a visual accompanying the audio and subtitles, but the playback displays a black screen.

 - Device: [Firestick 4K]
 - OS: [Fire OS]
 - Version [6.7.0.5]

**Additional Information**
H.264 content seems to work, and when available we are using this file format to get around the issue.

Also had to use "Tunneled Playback" and "Hardware Accelerated decoding" to get the sound bar to recognise Atmos audio; toggling either of these settings independently or together did not resolve the H.265 playback issue.

**Comment by TRtomasz** [comment]
this nos not something we can fix https://www.reddit.com/r/PleX/comments/124vdg2/dolby_vision_on_firestick_tv_just_a_black_screen/
