### ISSUE TITLE
[MacOS] Audio lag when streaming audio through system Airplay

### ISSUE THREAD

**Issue by lothar-cell** [Stremio/stremio-bugs#928]
**Describe the bug**
When using Airplay from the OS menu bar/sound icon to stream audio to external speakers, it has a constant lag (like 1-2 seconds).

**To Reproduce**
1. Start Stremio playback
2. Go to the sound icon in MacOS Menu Bar
3. Click on the Airplay device you want to stream audio to
4. See audio lag

**Expected behavior**
A perfectly synced audio.

**Screenshots**
<img width="303" alt="Screenshot 2024-09-25 at 08 08 07" src="https://github.com/user-attachments/assets/58082909-e4e1-4600-ba01-f934063e4f05">

**Desktop (please complete the following information):**
 - OS: MacOS 14.7
 - Stremio Version 4.4.168

**Additional context**
I assume Airplay problem never got resolved, hence deprecated from Stremio: https://github.com/Stremio/stremio-bugs/issues/78#issuecomment-252003814
However now Airplay is an essential feature of the OS.

**Comment by TRtomasz** [comment]
there is no bug here, it is normal for airplay to cause sound delay since it is casted

**Comment by lothar-cell** [comment]
It is a bug TRtomasz, Airplay DOES NOT have delay by default, only in Stremio.
I'm going to make a complaint to Stemio team that you close every issue without actually considering it.

**Comment by TRtomasz** [comment]
You can find it in multuple places over the internet https://github.com/iina/iina/issues/4540 
ps i'm part of Stremio team, thank you for your complain.
