### ISSUE TITLE
Issue with Cyberflix Addon

### ISSUE THREAD

**Issue by fabioodebiase** [Stremio/stremio-bugs#929]
Hi Guys, these days I'm having this problem with metadata ONLY for TV series, while for movies it works like a charm. From my smartphone I get an error message about information retrieval, and I'm able to watch the content, while for smart TVs and computers, I can't do anything. This happens when I search for content from the Cyberflix addon, while with Tmdb this doesn't happen.

![Screenshot_1](https://github.com/user-attachments/assets/d3a55c54-98a4-4700-a06e-a7ab8e6713d8)
![Screenshot_2](https://github.com/user-attachments/assets/46d27c2b-9ede-4c7b-89d9-0ea85c12e49f)

**Comment by TRtomasz** [comment]
We cant help with issues caused by 3rd party addons i checked and everything is fine on my side
