### ISSUE TITLE
Lately strem.io is showing wrong subtitles very often

### ISSUE THREAD

**Issue by Cris70** [Stremio/stremio-bugs#93]
Like the subjects says. This happens mainly with TV series episodes, where the subtitles belong to another episode in the same series.
Sometimes I am able to correct the situation by stopping the video, exiting back to the menu, then resuming. Sometimes it takes more than a try, and sometimes there's nothing to do: it just keeps showing the wrong subtitles.
I have tried perusing the "Wrong subtitles?" link but it usually just keeps showing the same subtitles.

**Comment by Ivshti** [comment]
thanks for reporting this. is this happening for the desktop app or the android app?

Also, you can try the windows alpha: http://dl.strem.io/Stremio%204.0.0-alpha.22.exe

**Comment by Cris70** [comment]
Hi Ivo,
this is happening for the desktop app.
However, I am a Linux user so I cannot try the Windows alpha.
If you have an equivalent Linux alpha I'll gladly try it.

Regards
Cris




  <https://mailtrack.io/>

Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=criguada@gmail.com&idSignature=22>

**Comment by 22tooty2** [comment]
Also have this problem.

Same series but wrong episode, open subtitles have the correct results
