### ISSUE TITLE
PT-BR subtitles do not appear on my Samsung TV

### ISSUE THREAD

**Issue by felipefigueiredo1** [Stremio/stremio-bugs#930]
- Device: Samsung 55Q60B
 - OS:  Tizen (Samsung)
 - Version : latest

PT-BR subtitles do not appear on my Samsung TV

I even tried to find the project here and make a PR but I couldn't find it. I would like to contribute and add this feature if possible.

**Comment by TRtomasz** [comment]
It is a known issue will be fixed in the next release
