### ISSUE TITLE
If there is no season 1 the app will stop responding on Samsung tv all models

### ISSUE THREAD

**Issue by Krishnakant010** [Stremio/stremio-bugs#933]
**Describe the bug**
In the forumulio addon there is no season 1 for some series of races so when we click on the series the app will crash

**To Reproduce**
1. Go to series of formulio races
2. Click on the race series
3. app will stop responding 

**Expected behavior**
App should not bug out and should render the data instead of freezing 

**Screenshots**

**TV (please complete the following information):**
 - samsung all tizen TVs 

**Additional context**

**Comment by BehaDev** [comment]
i hope it gets fixed asap stremio on samsung TVS has lot lots of problems tho...

**Comment by TRtomasz** [comment]
this will be fixed in the next release
