### ISSUE TITLE
Android App Refreshes When Bluetooth Device is Sleeps/Disconnected 

### ISSUE THREAD

**Issue by ryecoder** [Stremio/stremio-bugs#935]
**Describe the bug**
Android App refreshes when a bluetooth device is disconnected or connected. This then closes the current video that is playing. A wireless keyboard, for example, has a 15 mins sleep function to save battery, so the app would refresh every 15 mins.

**To Reproduce**
1. Play a video
2. Connect a bluetooth device (in my case a bluetooth keyboard)
3. The app refreshes and goes back to main screen.

**Expected behavior**
App should not refresh or go to main when a bluetooth device's connection updates. This can be a settings if other people find the app automatic refresh a feature.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 11
 - Browser: NA
 - Version: 1.6.12

**Comment by TRtomasz** [comment]
closing as duplicate https://github.com/Stremio/stremio-bugs/issues/913
