### ISSUE TITLE
No icon on Ubuntu Unity launcher

### ISSUE THREAD

**Issue by pabloab** [Stremio/stremio-bugs#94]
Trivial bug: No icon defined on Ubuntu Unity launcher. At least 16.04 LTS:
![image](https://cloud.githubusercontent.com/assets/657836/22855130/677f8af2-f059-11e6-9469-03fed659e2a3.png)
[Useful related link](https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles).

**Comment by Ivshti** [comment]
did you use the .deb which is on the website (www.strem.io) ?

**Comment by pabloab** [comment]
Right now I'm using the stand-alone binary (unpacked tar), either way
shouldn't display the icon on Launcher? I'm pretty sure with deb
installation the icon was also missing.
