### ISSUE TITLE
Multi audio shows on LG's Stremio app

### ISSUE THREAD

**Issue by soulinfinity96** [Stremio/stremio-bugs#940]
**There isn’t a button to change the audio in multi audio shows in the Stremio app for the LG Smart TV**

**To Reproduce**
1. Go to Stremio app on LG Smart TV
2. Click on a show that has multi audio (eg. Maxton Hall)
3. Scroll down to the icons
4. See error that there no button to change the audio

**Expected behavior**
I expected to have a button to choose the audio of the show/movie

**Screenshots**

**TV (please complete the following information):**
 - Device: LG Smart TV
 - OS: NA
 - Version [e.g. 2.0.0]

**Additional context**

**Comment by TRtomasz** [comment]
This feature will be added in the next release of stremio app
