### ISSUE TITLE
Addon system on Stremio Web is broken

### ISSUE THREAD

**Issue by Viren070** [Stremio/stremio-bugs#942]
**Describe the bug**
Attempting to install or uninstall an addon on [Stremio Web](https://web.stremio.com) will result in a blank screen, and the addon not installing/uninstalling. The blank screen remains even if you press the back arrow. You must refresh the page to fix the blank screen. 

**To Reproduce**

1. Go to [Stremio Web](https://web.stremio.com) or [the development branch](https://stremio.github.io/stremio-web/development)
2. Go to the Addons page
3. Click `Install` or `Uninstall` on any addon

or 

1. Go to [Stremio Web](https://web.stremio.com) or [the development branch](https://stremio.github.io/stremio-web/development)
2. Go to the Addons page
3. Click on '+ Add Addon'
4. Enter an addon Manifest URL (e.g. https://opensubtitles-v3.strem.io/manifest.json)

or 

1. Go to https://web.stremio.com/#/addons?addon or https://stremio.github.io/stremio-web/development/#/addons?addon=

**Expected behaviour**
The addon should be installed, and the addons menu should be visible

**Actual behaviour**

I see a blank purple screen and I am forced to refresh the page (on a different url path) to resolve the issue.

**Screenshots**

After pressing add
![image](https://github.com/user-attachments/assets/27d945fb-c1bd-4005-b1f8-4641e363d127)

Page must be refreshed to resolve the issue. 

Errors in console: 

![image](https://github.com/user-attachments/assets/bec8dfc9-9ba5-45be-8294-95f0454184cb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: Version 1.70.123 Chromium: 129.0.6668.89

**Smartphone (please complete the following information):**
 - Device: Samsung S24
 - OS: One UI 6.1.1 / Android 14
 - Browser: Firefox Nightly
 - Version: 

**Additional context**

Problem seems to have occurred after this commit: https://github.com/Stremio/stremio-web/commit/443e86a1adf57a3f13e84187eb935cbfdbb51c4f

**Comment by kKaskak** [comment]
https://github.com/Stremio/stremio-web/releases/tag/v5.0.0-beta.11
Changes should be live in the next 24 hours

**Comment by kmjsmith** [comment]
hi i cant get any addons to load such as comet or torento when i use the web version but  when i use the app version the apps load fine does someone have an explination as to why this is.
