### ISSUE TITLE
Stremio Web external player issue

### ISSUE THREAD

**Issue by hsnsdhdh** [Stremio/stremio-bugs#944]
I am using Stremio Web and have been using IINA as an external media player.
Today, suddenly I was unable to play with IINA and it now downloads an M3U Playlist file instead of opening IINA.
I went to see my settings and now I am unable to find IINA as an external player.
I have uninstalled and reinstalled the Stremio desktop application, tried different browsers (Microsoft Edge and Safari), and still, I cannot find IINA as an option for external player.
I have also downgraded my IINA application to version 1.3.4 from 1.3.5.

I tried looking for solutions online and came across this thread:
https://github.com/Stremio/stremio-shell/issues/193
I did try the fix mentioned and still could not see IINA as an external player.

I have also uninstalled IINA and installed VLC, but when I have VLC selected as an external player, nothing happens when I play a file. 

 - OS: macOS Sequoia 15.0.1
 - Browser: Microsoft Edge
 - Version: 129.0.2792.79
 
![IINA not found](https://github.com/user-attachments/assets/da8d9c87-107f-47cf-ba65-68af3bb802d1)

**Comment by addisonxx** [comment]
I have this same issue right now. Did you find a fix for it?

**Comment by tymmesyde** [comment]
> I have this same issue right now. Did you find a fix for it?

Yes, it has been merged to the development branch of stremio-web
https://stremio.github.io/stremio-web/development/
