### ISSUE TITLE
Samsung TV, everything show subtitles even after removing the addon

### ISSUE THREAD

**Issue by mrreedo90** [Stremio/stremio-bugs#946]
**Describe the bug**
subtitles appear for every single thing I watch. Have tried changing the language, setting to ‘none’ and uninstalling the addons completely. But subtitles still appear and have to turn them off each time

**To Reproduce**
1. Go to any show
2. Subtitles appear even after removing the addons completely. 

**Expected behavior**
no subtitles to appear as I have removed them. 

**TV (please complete the following information):**
 Device: Samsung QA75Q60RAWXXY
OS: Tizen 5
Stremio Version: Theater v1.3.0

**Comment by TRtomasz** [comment]
closing as a duplicate
