### ISSUE TITLE
 UPnP/DLNA on mac devices 

### ISSUE THREAD

**Issue by krapgras** [Stremio/stremio-bugs#95]
When i try to stream from my mac device to my smart TV (LG) my TV doesn't react, but the moment i do the same from a windows machine it starts playing the content. I have friends that come up with the exact same problem.

My knowledge on UPnP/DLNA is limited to a general idea of how it works, not how to implement it, but i do know Apple like to be a pain in the ass when it comes to not using there "standard". 

Is there anyway to get this fixed? Is this a OS problem or can this be fixed inside the app?

**Comment by Ivshti** [comment]
Technically the code should be platform-independent, but there's apparently some nuance that we're missing. We are re-implementing DLNA support from scratch for our next version (4.0), which will be in Beta by the end of the month, but probably won't have DLNA support initially at all until we re-implement it up until some level at least.

Is this issue consistent? Also, to confirm - Stremio discovers the TV both on windows and mac, right?

**Comment by krapgras** [comment]
Well yes this was till the last version, same tv, same content. I do have to check if it detects tv. But i also keep getting firewall alerts at startup. So maybe this is a connection problem. i will check this but my firewall allows the app tho... But ill do some more checks this week.

**Comment by krapgras** [comment]
If i hover over the TV button it shows my tv name.
http://prntscr.com/e95wr6
And i keep getting Firewall accept incoming connection for Stremio.app as well as  Stremio Helper.app
http://prntscr.com/e95y19
http://prntscr.com/e95yth
And in my setting i do allow incoming connections.
http://prntscr.com/e95z40
It keeps asking for it tho....

**Comment by lesoisaeu** [comment]
Well I use ArkMC app for Mac to stream my media to smart tv, xbox, and other devices. The main thing is that the app screams without any bugs and easy in use.
