### ISSUE TITLE
hotkeys not working with 'Launch player in a separate window (advanced)' player

### ISSUE THREAD

**Issue by onimoschta** [Stremio/stremio-bugs#951]
**Describe the bug**
built-in 'seperate window' player has no hotkey functions like space for pause or arrow keys for skipping back/ahead.

**To Reproduce**
1. Go to 'settings'
2. Click on 'Player'
3. Scroll down to 'Advanced'
4. enable 'Launch player in a separate window (advanced)'

**Additional context**
i suppose the 'seperate window player' is some kind of internal player based on MPV.
It has the best performance on my N100 mini-pc in combination with enabled hardware acceleration.
Using the stremio standard player has negative impact on my performance and VLC is not as good as the seperate window player.
The problem is, i can't use any hotkeys like pause and stuff.

**Comment by TRtomasz** [comment]
thats not a bug, you launch totally separate new app in new window.
