### ISSUE TITLE
No atmos using Exoplayer

### ISSUE THREAD

**Issue by designbysousa** [Stremio/stremio-bugs#952]
**Describe the bug**
If I use the Exoplayer, instead of the VLC, in android TV, nvidia shield pro, I only get multichannel audio and no atmos.

If I use VLC I get atmos.

I have Sonos soundbar with surround setup.

I dont use VLC because the subtitles have a bug, they dont resize and they are hidden behind the movie black bar.

**To Reproduce**
1. Go to settings and change to Exoplayer
2. Choose a movie with atmos.
3. You will get multichannel and not atmos.

**Expected behavior**

**TV (please complete the following information):**
 - Device: [Nvidia Shield Pro, Sony A80L]

I am using last stremio version.

**Comment by TRtomasz** [comment]
have you tried enabling tunneled playback in the settings?

**Comment by designbysousa** [comment]
> have you tried enabling tunneled playback in the settings?

Yes, tried with and without, the nvidia and tv settings is all  the same, nothing change, the only thing that change was the update on the stremio.

I use to use VLC, but vlc have a problem with subtitle, and I change to exoplayer and was when I notice that.

**Comment by designbysousa** [comment]
Found a work arround, if I turn on hardware transcoding, atmos works again.

**Comment by TRtomasz** [comment]
thats not a work around, now you set how it is configured by default, @designbysousa hardware accelerated decoding is turned on by default.
