### ISSUE TITLE
VLC subtitle are getting behind the black movie bar

### ISSUE THREAD

**Issue by designbysousa** [Stremio/stremio-bugs#953]
**Describe the bug**
When I load a subtitle using VLC, the subtitle dont get resize and they are hidden in the black bar of the movie, impossible to see part of it.

**To Reproduce**
1. Choose a movie.
2. Load subtitle
3. Subtitle will be half hidden in the black bar and it doenst resize.
4. If I change to exoplayer, everything is good.

**Expected behavior**

**TV (please complete the following information):**
 - Device: [Nvidia Shield Pro]]

I am using last stremio version.

**Comment by TRtomasz** [comment]
not a stremio bug
