### ISSUE TITLE
Subtitles cut off due to scaling

### ISSUE THREAD

**Issue by hugo9655** [Stremio/stremio-bugs#955]
**Describe the bug**
On mobile when scaling the video stream, the subtitles move with it, causing them to cut off from the screen.

**To Reproduce**
1. Open a video source that requires scaling.
2. Scale it to fit the screen.
3. See the subtitles cut off at the bottom.

**Expected behavior**
The subtitles should be unaffected.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Browser: Firefox
 - Version: Stremio latest version

**Comment by TRtomasz** [comment]
Thats not a bug, if subtitles are embedded into the video it is normal that when you change scaling that requires some zooming the video they will be out of the visible area same as the rest of the video
