### ISSUE TITLE
Can't search for series or movies and the favorite series and movies are all gone

### ISSUE THREAD

**Issue by fabioDdias** [Stremio/stremio-bugs#96]
Hi,
I'm running stremio on macbook pro but when I login with my personal email in my account all my series are gone and I can't search for series or movies, but when I login with my facebook account it works and I can add series to library, and use search box in the right corner.
Is there something wrong with my account?
I already uninstall and install stremio again, I don't know if the problem is from the update that I made.
Help me please.

Thanks, 
Fábio Dias.

**Comment by Ivshti** [comment]
@fabioDdias how does it work now?
