### ISSUE TITLE
Playback error on MacOS app

### ISSUE THREAD

**Issue by Golonchy** [Stremio/stremio-bugs#960]
**Describe the bug**

whenever i tried loading a video/movie i get the placyback error, please try again. i tried using wirewguard and openVPN but nothing helped. i also tried it on a virtual machine which it worked but loading a vm everytime to watch smth is annyoying. i also tried this on my browser and it didnt work.
**To Reproduce**
1. Go to any video
2. Click on the play buttn
3. Scroll down to i dont have 3 and 4
5. See error

**Expected behavior**

the video will show its preview with the playback error

**Screenshots**

<img width="987" alt="Screenshot 2024-10-20 at 11 35 11" src="https://github.com/user-attachments/assets/c2108cb7-733e-492e-8831-22be706f0eb6">

**Desktop (please complete the following information):**
<img width="176" alt="Screenshot 2024-10-20 at 11 35 32" src="https://github.com/user-attachments/assets/245ae095-ad89-49bb-bc82-e0a40a70d652">

this is the browser i tried it on
<img width="739" alt="Screenshot 2024-10-20 at 11 37 31" src="https://github.com/user-attachments/assets/b29a8732-5706-4583-b021-65e218d7aed6">

<img width="107" alt="Screenshot 2024-10-20 at 11 36 11" src="https://github.com/user-attachments/assets/60398300-6c86-4b5f-b624-568d96f622fd">

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**
thank you fr making stremio and the for the help

**Comment by TRtomasz** [comment]
Use https://web.stremio.com/ if you want to use web app version
