### ISSUE TITLE
When video buffers, statistics page doesn't show correct information.

### ISSUE THREAD

**Issue by Shockshwat** [Stremio/stremio-bugs#961]
**Describe the bug**
When a stream is buffering (normally playing first but then stopping), if you try to go to statistics page it will show speed 0kb/s and buffered : 100mb.

**To Reproduce**
1. Go to a random stream with preferably low seeder count or big file size 
2. Wait for it to buffer, if it doesn't then choose another stream.
3. Click on statistics button

**Expected behavior**
The real data shown 

**Screenshots**
![image](https://github.com/user-attachments/assets/192e7ac5-48f2-4914-b397-a89041a20923)

**Desktop:**
 - OS: Windows 11
 - Version 24H2 (Problem also occurred with 22H2)

**Additional context**
Sometimes, let's say the video is 50% loaded and it lags at around 4% mark and then when i thought oh lets check statistics if peers went missing or what since i already downloaded 50% of the movie i think and i see the placeholder data.

**Comment by TRtomasz** [comment]
This will not show any data for RD streams, just starting value which is 100MB. 
Also will not show 100% accurate data if you exit stream and start again
other than this it shows stats just fine when buffering(After initiall buffering)
![image](https://github.com/user-attachments/assets/c968eb3b-d611-4bd1-8dbc-da49aec33aa1)

**Comment by Shockshwat** [comment]
@TRtomasz I do not use RD. Also this problems occurs after the initial buffering lets say at half point when torrent randomly decides to not give me bandwidth at all for some reason.
