### ISSUE TITLE
Stremio crashing in Meta Quest 3

### ISSUE THREAD

**Issue by Danieljflopes** [Stremio/stremio-bugs#964]
- When watching movies or series through torrents it sometimes closes the app. Doesn’t happen in all torrents but in the ones it does you can replicate the issue always.

**To Reproduce**
1. In my case I can reproduce this with the same torrent. I’m using real debrid and if I open a the first stream that appears in order of the 4k streams in mad max furiosa it always crashes. 
I’ve opened the same stream on my xiaomi android box with your app and have no issues. 

**Expected behavior**
With some torrents it plays for the first seconds and then force closes the app. 

Device: Meta Quest 3
OS: V. 69 
Android mobile version: 1.6.12ARM64 APK

Th installation procedure was done following your guide on the web page (stremio.com)

**Comment by TRtomasz** [comment]
We will not fix issues that occuring on a not officialy supported device
