### ISSUE TITLE
Videos lagging/not smooth since last Android TV update 

### ISSUE THREAD

**Issue by onfire-d** [Stremio/stremio-bugs#965]
**Describe the bug**
Since last Android TV version videos dont go smooth, there are like “cuts”. Happens with all videos. They work fine if I open with VLC. Other streaming services work fine too.

**To Reproduce**
Watch any content

**Expected behavior**
Work smooth

**TV (please complete the following information):**
 - Device: Xiaomi TV Stick
 - OS: Android TV 
 - Version : 1.6.11
**Additional context**

**Comment by TRtomasz** [comment]
Please provide more details for us to be able to reproduce the issue
