### ISSUE TITLE
some all debrid files are not playing

### ISSUE THREAD

**Issue by patercakepat74** [Stremio/stremio-bugs#966]
hi,

i have stremio on all my devices, pc phone and firestick v 1.6.12, i also have a premium account on all debrid,

i use torrentio for the addon and have it set to 4k size first so i get the best quality.

recently a lot of files that are mkv are failing to load and im getting a playback error on all devices.

transformer one, the first 6 links dont work but number 7 does play but at a lower quality than the first link as its only 10gb not 18gb like the first

also deadpool vs wolverine the biggest size is 69gb then 50 gb and so on, all these wont play, but the 25gb file does play, but i want to watch better quality

ive tried other films like mad max and a couple also fail but some of the 70 gb files do play fine.

i spoke to all debrid and they say its not them as playback error is not one of their error codes.

please find attached some screenshots

![7th link working](https://github.com/user-attachments/assets/915a92d5-a468-4848-bbf9-0fec4a99c8b3)
![playback error 1st link](https://github.com/user-attachments/assets/f02d089e-571a-4c8f-852d-3655af71d120)
![playback error 4th link ](https://github.com/user-attachments/assets/b362bcf6-ac63-4cd5-8e4d-1a1bf2504832)
![playback error 6th link ](https://github.com/user-attachments/assets/28a2f4de-3eff-48d7-a6c8-534c8f430eaa)
![transformers links](https://github.com/user-attachments/assets/f9d0fb24-9995-4140-a345-08164cb0b4a3)

**Comment by TRtomasz** [comment]
I tried the same from the RD as i dont have access to all debrid and it is working just fine, so perhaps issue is on their site

**Comment by patercakepat74** [comment]
ive spoken to all debrid again and they say their links work fine, i did try transformers one again and got same error, but when i geberated link on their website i was able to download file directly to my pc, so link does work, just not through stremio, here is what they said in reply.

Copy paste our link there, hit the green button and download the new generated link. It's working.

Any issue related to any third party app, like "stremio", can't be resolved by us.

If "stremio" has an issue with our API, they can contact us.

sounds like an API problem, please fix stremio, thanks

**Comment by TRtomasz** [comment]
we do not controll the addon you should try ask question in the addon community
