### ISSUE TITLE
Casting does not work

### ISSUE THREAD

**Issue by Maurits12** [Stremio/stremio-bugs#967]
When casting to chrome cast, my stream starts, but on my Mac it still says it Is loading. then after a while the cast stops.
the same problem occurs on my windows laptop
Using a chrome cast 3
Mac OS 15.0.1
Windows 11

https://github.com/user-attachments/assets/29b1dd17-b1fa-4bc9-af7b-a66ba752a5e8

**Comment by TRtomasz** [comment]
DLNA casting is no longer being maintained

**Comment by Maurits12** [comment]
what so casting is no more?

**Comment by TRtomasz** [comment]
You should use chromecasting if you want to maintain stable casting experience

**Comment by Maurits12** [comment]
that is what im using
