### ISSUE TITLE
No controls when casting on TV

### ISSUE THREAD

**Issue by gabro** [Stremio/stremio-bugs#97]
I'm (successfully) casting to a Hisense TV, but when I hit the TV button I have no way of controlling the playback (pause/play, fast-forward, ...). The stream works correctly but I simply have no control over it, it gets detached completely from the app.

Is this a known issue?

**Comment by Ivshti** [comment]
Yes, it is not implemented at the moment

We plan to bring DLNA control in our upcoming 4.0 version, but keep in mind not all TVs support that
