### ISSUE TITLE
Samsung TV App - Does not mark episodes as watched

### ISSUE THREAD

**Issue by XDeadHackerX** [Stremio/stremio-bugs#971]
**Describe the bug**
I have been using Stremio for several months on my Samsung TVs and I have found that it does not mark the episodes of a Tv Show as seen, even if you wait for the end of the chapter and jump to the next episode it still does not mark it as seen (Unlike Windows, Android Tv and Android).

**To Reproduce**
1. Plays the episode of a Tv Show.
2. Wait until the end of the episode.
3. Go back and check that the episode does not have the watched check box.

**Expected behavior**
When you finish watching a chapter of a series it is marked as watched just like Stremio does on Windows, Android Tv and Android.

**TV (please complete the following information):**
 - Device: Samsung TV (Samsung QLED 65Q60D (2024))
 - OS: Tizen

**Comment by TRtomasz** [comment]
Closing as duplicate, it will be fixed in the next update
