### ISSUE TITLE
In Win11 under Caching Drive, Stremio-Server & Stremio-Cache are labelled as “Unavailable”.

### ISSUE THREAD

**Issue by EurosE77** [Stremio/stremio-bugs#975]
**Describe the bug**
On my laptop in Windows 11, under Caching Drive, the default caching folder (Stremio-cache found in Stremio-server) is labelled as (Unavailable). When I find the stremio-server and stremio-cache in my files nothing is inside. It doesn’t allow me to choose any other folder to store cache. Due to cache not working, movies end up crashing the app after 20 minutes. Heavy GB torrents don’t load at all even with Real Debrid.

**To Reproduce**
1. Go to Settings
2. Click on Cache Drive
3. Scroll down to Cache Folder under C:\Users\''Your user''\AppData\Roaming\stremio\stremio-server\
4. Labelled as (unavailable) Stremio-cache seemingly not accessible.

**Expected behavior**
Default cache folder Stremio-server/stremio-cache to be available, accessible, and working. 

**Screenshots**

![IMG_1291](https://github.com/user-attachments/assets/4529ac1d-1795-47a0-bdab-e7586ed6f2f6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Firefox
 - Stremio 4.4.168
 - Web UI 4.4.172
 - Server 4.20.8

**Additional context**
Everything is updated to the latest version. No Windows firewall is blocking Stremio on public and private networks. I believe no permissions are blocked for Stremio. Hidden files are shown in file explorer so I can see App Data, Roaming, Stremio files. I can see Stremio-server file and inside then Stremio-cache file but nothing is inside the latter.

**Comment by TRtomasz** [comment]
Reported issue has nothing to do with crashes, you can just ignore Unavailable message, it is default cache location. If you select `C` as cache location it will then create there stremio cache folder.
It is not possible to set custom cache patch you can only change partition and you have just one.
Additionaly cache is only for torrent based streams, nothing will be stored in these folders if you use real debrid.
Regarding crashing ensure you have enabled hardware accelerated decoding in the settings

**Comment by EurosE77** [comment]
Thank you for the hasty reply! Hardware accelerated decoding is enabled. I wonder if the crashing is something to do with the AMD drivers then? I’m totally lost now
