### ISSUE TITLE
[UX] Installer installs the program to C: drive without asking

### ISSUE THREAD

**Issue by bradenbest** [Stremio/stremio-bugs#978]
**Describe the bug**
The installer immediately installs the program to the user's C: drive without any configuration options. If my only option is an installer, I prefer to install to my D: drive instead. This is a UX error.

**To Reproduce**
1. Run the installer

**Expected behavior**
Wizard opens up asking where the user wants to install it, then installs.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A (desktop app)
 - Version 4.4.168

**Smartphone (please complete the following information):**
N/A

**TV (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TRtomasz** [comment]
Installers install apps in the dedicated catalogs(by windows), it will not be changed
