### ISSUE TITLE
[Bug] Stremio ignores cache limit setting

### ISSUE THREAD

**Issue by bradenbest** [Stremio/stremio-bugs#979]
**Describe the bug**
I set the cache limit to 2GB and later noticed Stremio's cache folder had consumed 3.5GB of my 12GB of available hard disk space. In response to this, I deleted the cache folder and set the limit to zero. Unless I'm missing something (in which case the option needs rewording), this is a bug.

**To Reproduce**
1. Set a cache limit
2. Monitor the cache folder until it exceeds the cache limit

**Expected behavior**
The program should not exceed the limit set by the user.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A (desktop app)
 - Version 4.4.168

**Smartphone (please complete the following information):**
N/A

**TV (please complete the following information):**
N/A

**Additional context**
Before I set the limit to 2GB, I deleted the cache folder as I saw that it was multiple gigabytes in size. It's also possible that 2GB was the default setting. In which case I didn't even change it and it exceeded it.

**Comment by TRtomasz** [comment]
This is not a bug and has been explained multiple times. Stremio will use as much space as file you are trying to play takes. Cache will be cleared on the next streaming start if you reached caching limit.
