### ISSUE TITLE
[BUG] Metadata incomplete in discover on Stremio for Windows

### ISSUE THREAD

**Issue by oleglucic** [Stremio/stremio-bugs#983]
**Describe the bug**
When you open discover and open catalogues from addons that aren't Cinemeta (TMDB this time), info such as cast and media lenght, as well as media title logo aren't shown.

**To Reproduce**
1. Go to Discover on Windows app and choose TMDB catalogues
2. Click on any media

**Expected behavior**
Your results will be similar to the screenshots.

**Screenshots**
![image](https://github.com/user-attachments/assets/08ff50f4-c2dd-4956-b53f-504e7e6f43e7)
Metadata from discover snapshot

![image](https://github.com/user-attachments/assets/b9a4ec59-8337-4dd3-85b2-0be98192471e)
Metadata is complete when the media page is opened

**Desktop:**
 - OS: Windows 11 23H2
 - Version 4.4.168

**Additional context**
Hope this will be resolved in one of the next updates :)

**Comment by TRtomasz** [comment]
We do not controll what metadata imdb addon provides so this is not a stremio bug

**Comment by oleglucic** [comment]
It is a bug because you can see that the same addon provides complete metadata in the second picture. That is the reason why I've attached the other picture.

**Comment by TRtomasz** [comment]
It's not because data you see after opening the details is different tha one provided befor you open the details and both are controlled by imdb

**Comment by oleglucic** [comment]
These catalogues use TMDB API and images. They have nothing to do with IMDb.

**Comment by mrcanelas** [comment]
@oleglucic  I think you ended up confusing things, what you reported is not a client bug, @TRtomasz  is right, this is a limitation of the TMDB Addon, the discovery part of the TMDB API does not bring all the data, to bring all the data such as logo, trailers and etc, several other requests would need to be made behind the scenes, which would make the addon very slow in this discovery part, which is unfeasible, what could be done is to generate this and then save it in a database, but database hosting is expensive and the addon does not receive any resources for this.

**Comment by oleglucic** [comment]
Thank you : )
