### ISSUE TITLE
Android tv and Windows crashing

### ISSUE THREAD

**Issue by sinbad1722** [Stremio/stremio-bugs#984]
experiencing crashing on android tv with two addons. Easynews+ and Shuvam GDrive addon

**To Reproduce**
1. Go to "From" S03E04 5gb file size, it will stop around 8min 50sec

**Desktop (please complete the following information):**
 - OS: Windows 10 , windows 11

**TV:**
 - Device: pretty much in every tv box I tried

 its a problem with the app having a memory leak writing the cache to memory it falls over due to the heap size being too small

**Comment by TRtomasz** [comment]
after checking the addon, looks like addon decides at 8:50 to just send info about end of file and this is the source of this issue

**Comment by sinbad1722** [comment]
sure about this mate? Cause it happens with multiple http addons and all of them fail at some point mostly on windows and and android tv clients. I'm not the only one facing this issue , and I made a patch file for increasing the heap size in windows and it worked. It is an issue with the app not the addon.

**Comment by Camzilla78** [comment]
Agreed have the issue with both addons with android tv, addons work perfectly fine on mobile so seems it's an android tv app and windows bug.

**Comment by TRtomasz** [comment]
what patch @sinbad1722  ?

**Comment by mikmc55** [comment]
> sure about this mate? Cause it happens with multiple http addons and all of them fail at some point mostly on windows and and android tv clients. I'm not the only one facing this issue , and I made a patch file for increasing the heap size in windows and it worked. It is an issue with the app not the addon.

YOU did? you need to edit that to keep things factual here. A wrapper to increase the heap size does let the windows client run as it should but it is not your work
I'm reluctant to post that code it is not a patch and i don't want to deal with the support that comes with releasing it

**Comment by mikmc55** [comment]
a link for the file

https://file.io/kb0lCuwpd4v2
