### ISSUE TITLE
[Bug] [Samsung TV 2022] App Freezes when selecting plugin that returns no streams

### ISSUE THREAD

**Issue by shadyabdou** [Stremio/stremio-bugs#985]
1- Open Stremio on Samsung TV 2022
2- Select a show like "Clebrity squares" 
3- Select a provider like "Jackettio RD", no results are founds
4- App Freezes and have to restart app to work
![tempImageHaQ2wa](https://github.com/user-attachments/assets/2e04cd64-0a63-48c5-9998-0e6939a4039c)

**Comment by TRtomasz** [comment]
Closing as duplicate, it will be fixed in the next update
