### ISSUE TITLE
Windows application - Cannot play Trailers

### ISSUE THREAD

**Issue by XDeadHackerX** [Stremio/stremio-bugs#986]
**Describe the bug**
When you want to watch the trailer of a movie in Windows you can't, an error box appears.

**To Reproduce**
1. Open any movie.
2. Click on Preview/Trailer.
3. Check the error displayed on the screen.

**Expected behavior**
The trailer is played as on all other devices.

**Screenshots**
![imagen](https://github.com/user-attachments/assets/7bd3ec36-4691-4d14-b2a6-2e49cd87b7bd)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I don't know if it has something to do, but I only use the TMDB Addon configured in Spanish, I have not put great importance because in the rest of devices it works, but in Windows it failed me from the first day.

**Comment by TRtomasz** [comment]
If trailer is not playable outside youtube, or not playable in your region you might see such error
