### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by krisdebock** [Stremio/stremio-bugs#987]
if I change the language to Dutch in settings on my smartphone in version 1.6.12, I always have to change back to Dutch with standard subtitles, also with my version v1.3.0 on my Samsung TV I always have to enter Dutch when I see a movie. How come you change this in settings, this still has to be changed manually every time you watch a movie, so it doesn't happen automatically. I hope you understand my problem ,thank you. Normally it should happen automatically because you have set this, but afterwards I have to change it again in the settings,both on my smartphone version and my tv version on samsung

**Comment by TRtomasz** [comment]
Sorry it is not possible to understand about what is your issue, if you have an issue with TV app or mobile app. Please create new issue, following the new issue template with detailed steps how to reproduce it.
