### ISSUE TITLE
standard subtitles

### ISSUE THREAD

**Issue by krisdebock** [Stremio/stremio-bugs#989]
if I enter standard Dutch in settings, then when I start a movie, I still have to manually replace the subtitles to Dutch, even though I have entered this as standard. on my version 1.6. 12 on smartphone, now I have just seen that there has apparently been an update today because it says version 1.6. 13
Also in language settings: interface, standard subtitles and standard audio track; I have to change standard subtitles and standard audio track back because this does not remain in Dutch language when I have entered this, how come?

**Comment by TRtomasz** [comment]
There is no Dutch option there is netherlands, if embedded subtitles will be named Netherlands they will not be automatically selected
