### ISSUE TITLE
Cast to chromecast button not available after disconnect

### ISSUE THREAD

**Issue by pct00** [Stremio/stremio-bugs#99]
play a movie, and cast it to chromecast.
paused and after 5 or 10 minutes chromecast disconnects the stream for idling
when tried to resume playback the button to cast is disabled

Happened in version 3
now testing in alpha 4.00.0 alpha 34 and still the same

the button is disabled, greyed out.
tried restarting dlna/upnp services but no result

can still cast to chromecast from other apps

**Comment by TRtomasz** [comment]
Perhaps it is fixed now. As no one else have reproted such issue.
