### ISSUE TITLE
buffers need to refresh more frequently or even reset the entire torrent download because of many issues occuring while pausing and replaying with relative big time intervals.

### ISSUE THREAD

**Issue by papajo-r** [Stremio/stremio-bugs#991]
**Describe the bug**
buffers need to refresh more frequently or even reset the entire torrent download because of many issues occuring while pausing and replaying with relative big time intervals.

e.g E-V-E-R-Y single time no matter the torrent/movie/show if I pause it and leave it paused on the background for a considerable time (hours or even just a few minutes, didnt count but ballparking it I would say starting about above 15 or so )  I get one of the following issues:

1) it just buffers and never plays no matter how much time you wait  (<--- here is a "side issue there is no way to completely reset/close stremio other than opening task manager and ending the server process which is bothersome e.g just alt+f4 or clicking on "X" on the window will close it but when double clicking it again it essentially loads its buggy state so buffering forever which gets fixed only by manually terminating the process via task manager) 

2) it buffers but plays again but with issues (color artifacts, audio distortion or delay, black screen with audio or without and fast frame passing -everything moves very fast -while audio is normal just because the video started later than the audio playback and tries to catch up)  mostly color artifacts and fast frame passing and buffering. 

I think that's because for some reason data on RAM gets distorted hence having a button (on the timeline bar) to reset the torrent download or refresh the buffer would solve this. 

**To Reproduce**
1. play a video
2. pause it
3. have it on the background while doing other stuff with your PC(preferably memory intensive e.g open a browser with many tabs and stream other videos etc) 
4. bring it back on the foreground and/or full screen and click on play... 

**Expected behavior**
I expect from video to play instead it does cases  "1" or "2"  mentioned above. 

**Desktop (please complete the following information):**
 - OS: Windows 11 24h2
 - Browser Windows  stremio app (browser usually open in the background is chrome) 
 - Version latest
 - 

**Additional context**
I have 1TB nvme SSD and 32 GB (2*16GB, 2/2 slots on motherboard filled)  2928 Mhz cl 17 RAM and 6c/12th intel i7 8750h CPU with nvidia GTX 1060 6GB GPU my internet connections is VDSL 50 down 30 up tested via speedtest and fast.com and also 0 or minimal packet loss orjitter over wifi, the laptop usually streams from the same place and I have 2x2 MIMO for each band (4 antennas total) wifi 6 router with OFDMA and beamforming and laptop also supports MU MIMO it certainly isnt my connections (movies/films watched with debrid account and torrentio of 1080p less than 4GB usually and with 3 digit number of seeds most of the time) 

An other indicator that its not the connection is that by shutting down stremio (via task manager) and opening it again the movie or shor plays instantly after clicking it from the "continue watching" option on the main menu

**Comment by papajo-r** [comment]
Forgot to mention that a manual remedy for this is to set the timeline to a different point in the past (or outside the buffer zone) e.g -10 seconds before hitting the play button that way it buffers on its own again and when you hit play it wont stuck or show corrupted video frames.

**Comment by TRtomasz** [comment]
You didnt mention what kind of streams you are trying to play but if they are HTTP streams specifically debrid streams it is expected and there is nothing we can do about this.
