### ISSUE TITLE
[REQUEST] Background service should be killed when the app is closed

### ISSUE THREAD

**Issue by oleglucic** [Stremio/stremio-bugs#992]
When finished using stremio and exiting the app, service still runs in the background (as you can see in systray). When the app is being exited, all it's services should be killed, in order to preserve machine's resources.

Windows 11 23H2
Stremio Windows 4.4.68

**Comment by TRtomasz** [comment]
Go to the settings - enable option close app when closing window from now X buttom will close the app too

**Comment by oleglucic** [comment]
Is there such an option on v5?

**Comment by oleglucic** [comment]
Looking forward to it : )
