### ISSUE TITLE
Cinemeta images won't load.

### ISSUE THREAD

**Issue by null-p01ntr** [Stremio/stremio-bugs#994]
**Describe the bug**
Images provided my Cinemeta doesn't load. Other catalogs load fine (TMDB, RPDB), the movie title and details load fine. But; Posters, episode thumbnails for series, backgrounds, title logo at the beginning of the content, nothing image related loads.
The same happens when I use [Stremio Web](https://web.stremio.com/) on the same android device.

**To Reproduce**
I couldn't reproduce the error on a different device.
They work fine on the same network with the same account

**Expected behavior**
All the posters and other images were loading fine a couple of months ago.

**Screenshots**
Home Page (below there are images of TMDB catalogs)
![20241106_150158](https://github.com/user-attachments/assets/ea5a11c4-fff4-492a-aafe-7a16fb333420)

Discover (Cinemeta)
![20241106_150256](https://github.com/user-attachments/assets/eb96df4b-fd39-4b5f-82e9-cd484a3a7b24)

Discover (TMDB)
![20241106_150224](https://github.com/user-attachments/assets/c76058c7-104a-47cc-a000-260489ca71b3)

Series Page 
![20241106_151020](https://github.com/user-attachments/assets/0feafcc9-85ec-4ec9-b070-aa642ddf75d0)

**Tv Box (acting as a Tablet):**
 - Device: HiMedia A5 Android TV Box (tablet Android OS **_not_** Android TV OS)
 - OS: Android
 - Browser: Safari
 - Version 6.0.1

**Additional context**
This happens only on a single device, every other device with the same account works fine.
I've cleared data/cache, even reinstalled.
Tried opening with VPN, disabled Pi-Hole (using for ad-block), nothing helped. I couldn't find a similar problem online.

**Comment by jaruba** [comment]
you are using Stremio for android mobile on an android tv device, install Stremio for android tv instead

**Comment by null-p01ntr** [comment]
> you are using Stremio for android mobile on an android tv device, install Stremio for android tv instead

I especially explained and detailed the this in this part
"Tv Box (acting as a Tablet):
Device: HiMedia A5 Android TV Box (tablet Android OS not Android TV OS)
OS: Android
Browser: Safari
Version 6.0.1"

The OS is standart Android, **NOT** Android TV. Thus, Android TV apps don't work.
Think it like a android tablet with an hdmi output.


> to further clarify the issue comes from expired root CA for SSL encryption, ur device is old and is not receiving updates anymore which causes it to fail ssl certificate validation

Every other add-on's catalog and images appears up.
Can different add-ons require different SSL certificates?
