### ISSUE TITLE
Open in external player not working with m3u8 files in Outplayer

### ISSUE THREAD

**Issue by thelastblt** [Stremio/stremio-bugs#997]
**Describe the bug**
When open in external player- Outplayer is selected opening a stream from Stremio does not load in the Outplayer app. The app freezes up. 

**To Reproduce**
1. Go to a m3u8 stream link 
2. Click on play to open in external player
3. See error

**Expected behavior**
The stream link opens and begins playing. The expected behavior happens if you use VLC as an external player. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 18.0.1
 - Browser: PWA - Safari

**Additional context**
When using VLC, the links open appropriately. When copying the stream link in Stremio and pasting into Outplayer, the links open appropriately. Other links from WebDav open in Outplayer as intended.

**Comment by TRtomasz** [comment]
We are not able to control third party apps issues you should contact with their support
